import * as monaco from 'monaco-editor';

export default {
  base: 'vs',
  inherit: false,
  colors: {
    'activityBar.activeBorder': '#1c6b48',
    'activityBar.background': '#ffffff',
    'activityBar.border': '#f0f0f0',
    'activityBar.foreground': '#393a34',
    'activityBar.inactiveForeground': '#393a3450',
    'activityBarBadge.background': '#4e4f47',
    'activityBarBadge.foreground': '#ffffff',
    'badge.background': '#393a3490',
    'badge.foreground': '#ffffff',
    'breadcrumb.activeSelectionForeground': '#22222218',
    'breadcrumb.background': '#f7f7f7',
    'breadcrumb.focusForeground': '#393a34',
    'breadcrumb.foreground': '#6a737d',
    'breadcrumbPicker.background': '#ffffff',
    'button.background': '#1c6b48',
    'button.foreground': '#ffffff',
    'button.hoverBackground': '#1c6b48',
    'checkbox.background': '#f7f7f7',
    'checkbox.border': '#d1d5da',
    'debugToolBar.background': '#ffffff',
    descriptionForeground: '#393a3490',
    'diffEditor.insertedTextBackground': '#1c6b4830',
    'diffEditor.removedTextBackground': '#ab595940',
    'dropdown.background': '#ffffff',
    'dropdown.border': '#f0f0f0',
    'dropdown.foreground': '#393a34',
    'dropdown.listBackground': '#f7f7f7',
    'editor.background': '#ffffff',
    'editor.findMatchBackground': '#e6cc7744',
    'editor.findMatchHighlightBackground': '#e6cc7766',
    'editor.focusedStackFrameHighlightBackground': '#fff5b1',
    'editor.foldBackground': '#22222210',
    'editor.foreground': '#393a34',
    'editor.inactiveSelectionBackground': '#22222210',
    'editor.lineHighlightBackground': '#f7f7f7',
    'editor.selectionBackground': '#22222218',
    'editor.selectionHighlightBackground': '#22222210',
    'editor.stackFrameHighlightBackground': '#fffbdd',
    'editor.wordHighlightBackground': '#1c6b4805',
    'editor.wordHighlightStrongBackground': '#1c6b4810',
    'editorBracketHighlight.foreground1': '#2993a3',
    'editorBracketHighlight.foreground2': '#1e754f',
    'editorBracketHighlight.foreground3': '#a65e2b',
    'editorBracketHighlight.foreground4': '#a13865',
    'editorBracketHighlight.foreground5': '#bda437',
    'editorBracketHighlight.foreground6': '#296aa3',
    'editorBracketMatch.background': '#1c6b4820',
    'editorError.foreground': '#ab5959',
    'editorGroup.border': '#f0f0f0',
    'editorGroupHeader.tabsBackground': '#ffffff',
    'editorGroupHeader.tabsBorder': '#f0f0f0',
    'editorGutter.addedBackground': '#1e754f',
    'editorGutter.commentRangeForeground': '#393a3450',
    'editorGutter.deletedBackground': '#ab5959',
    'editorGutter.foldingControlForeground': '#393a3490',
    'editorGutter.modifiedBackground': '#296aa3',
    'editorHint.foreground': '#1e754f',
    'editorIndentGuide.activeBackground': '#00000030',
    'editorIndentGuide.background': '#00000015',
    'editorInfo.foreground': '#296aa3',
    'editorInlayHint.background': '#00000000',
    'editorInlayHint.foreground': '#999999',
    'editorLineNumber.activeForeground': '#4e4f47',
    'editorLineNumber.foreground': '#393a3450',
    'editorOverviewRuler.border': '#ffffff',
    'editorStickyScroll.background': '#f7f7f7',
    'editorStickyScrollHover.background': '#f7f7f7',
    'editorWarning.foreground': '#a65e2b',
    'editorWhitespace.foreground': '#00000015',
    'editorWidget.background': '#ffffff',
    errorForeground: '#ab5959',
    focusBorder: '#00000000',
    foreground: '#393a34',
    'gitDecoration.addedResourceForeground': '#1e754f',
    'gitDecoration.conflictingResourceForeground': '#a65e2b',
    'gitDecoration.deletedResourceForeground': '#ab5959',
    'gitDecoration.ignoredResourceForeground': '#393a3450',
    'gitDecoration.modifiedResourceForeground': '#296aa3',
    'gitDecoration.submoduleResourceForeground': '#393a3490',
    'gitDecoration.untrackedResourceForeground': '#2993a3',
    'input.background': '#f7f7f7',
    'input.border': '#f0f0f0',
    'input.foreground': '#393a34',
    'input.placeholderForeground': '#393a3490',
    'inputOption.activeBackground': '#393a3450',
    'list.activeSelectionBackground': '#f7f7f7',
    'list.activeSelectionForeground': '#393a34',
    'list.focusBackground': '#f7f7f7',
    'list.highlightForeground': '#1c6b48',
    'list.hoverBackground': '#f7f7f7',
    'list.hoverForeground': '#393a34',
    'list.inactiveFocusBackground': '#ffffff',
    'list.inactiveSelectionBackground': '#f7f7f7',
    'list.inactiveSelectionForeground': '#393a34',
    'menu.separatorBackground': '#f0f0f0',
    'notificationCenterHeader.background': '#ffffff',
    'notificationCenterHeader.foreground': '#6a737d',
    'notifications.background': '#ffffff',
    'notifications.border': '#f0f0f0',
    'notifications.foreground': '#393a34',
    'notificationsErrorIcon.foreground': '#ab5959',
    'notificationsInfoIcon.foreground': '#296aa3',
    'notificationsWarningIcon.foreground': '#a65e2b',
    'panel.background': '#ffffff',
    'panel.border': '#f0f0f0',
    'panelInput.border': '#e1e4e8',
    'panelTitle.activeBorder': '#1c6b48',
    'panelTitle.activeForeground': '#393a34',
    'panelTitle.inactiveForeground': '#6a737d',
    'peekViewEditor.background': '#ffffff',
    'peekViewResult.background': '#ffffff',
    'pickerGroup.border': '#f0f0f0',
    'pickerGroup.foreground': '#393a34',
    'problemsErrorIcon.foreground': '#ab5959',
    'problemsInfoIcon.foreground': '#296aa3',
    'problemsWarningIcon.foreground': '#a65e2b',
    'progressBar.background': '#1c6b48',
    'quickInput.background': '#ffffff',
    'quickInput.foreground': '#393a34',
    'quickInputList.focusBackground': '#f7f7f7',
    'scrollbar.shadow': '#6a737d33',
    'scrollbarSlider.activeBackground': '#393a3450',
    'scrollbarSlider.background': '#393a3410',
    'scrollbarSlider.hoverBackground': '#393a3450',
    'settings.headerForeground': '#393a34',
    'settings.modifiedItemIndicator': '#1c6b48',
    'sideBar.background': '#ffffff',
    'sideBar.border': '#f0f0f0',
    'sideBar.foreground': '#4e4f47',
    'sideBarSectionHeader.background': '#ffffff',
    'sideBarSectionHeader.border': '#f0f0f0',
    'sideBarSectionHeader.foreground': '#393a34',
    'sideBarTitle.foreground': '#393a34',
    'statusBar.background': '#ffffff',
    'statusBar.border': '#f0f0f0',
    'statusBar.debuggingBackground': '#f7f7f7',
    'statusBar.debuggingForeground': '#4e4f47',
    'statusBar.foreground': '#4e4f47',
    'statusBar.noFolderBackground': '#ffffff',
    'statusBarItem.prominentBackground': '#f7f7f7',
    'tab.activeBackground': '#ffffff',
    'tab.activeBorder': '#f0f0f0',
    'tab.activeBorderTop': '#393a3490',
    'tab.activeForeground': '#393a34',
    'tab.border': '#f0f0f0',
    'tab.hoverBackground': '#f7f7f7',
    'tab.inactiveBackground': '#ffffff',
    'tab.inactiveForeground': '#6a737d',
    'tab.unfocusedActiveBorder': '#f0f0f0',
    'tab.unfocusedActiveBorderTop': '#f0f0f0',
    'tab.unfocusedHoverBackground': '#ffffff',
    'terminal.ansiBlack': '#121212',
    'terminal.ansiBlue': '#296aa3',
    'terminal.ansiBrightBlack': '#aaaaaa',
    'terminal.ansiBrightBlue': '#296aa3',
    'terminal.ansiBrightCyan': '#2993a3',
    'terminal.ansiBrightGreen': '#1e754f',
    'terminal.ansiBrightMagenta': '#a13865',
    'terminal.ansiBrightRed': '#ab5959',
    'terminal.ansiBrightWhite': '#dddddd',
    'terminal.ansiBrightYellow': '#bda437',
    'terminal.ansiCyan': '#2993a3',
    'terminal.ansiGreen': '#1e754f',
    'terminal.ansiMagenta': '#a13865',
    'terminal.ansiRed': '#ab5959',
    'terminal.ansiWhite': '#dbd7ca',
    'terminal.ansiYellow': '#bda437',
    'terminal.foreground': '#393a34',
    'terminal.selectionBackground': '#22222218',
    'textBlockQuote.background': '#ffffff',
    'textBlockQuote.border': '#f0f0f0',
    'textCodeBlock.background': '#ffffff',
    'textLink.activeForeground': '#1c6b48',
    'textLink.foreground': '#1c6b48',
    'textPreformat.foreground': '#586069',
    'textSeparator.foreground': '#d1d5da',
    'titleBar.activeBackground': '#ffffff',
    'titleBar.activeForeground': '#4e4f47',
    'titleBar.border': '#f7f7f7',
    'titleBar.inactiveBackground': '#ffffff',
    'titleBar.inactiveForeground': '#6a737d',
    'tree.indentGuidesStroke': '#e1e4e8',
    'welcomePage.buttonBackground': '#f6f8fa',
    'welcomePage.buttonHoverBackground': '#e1e4e8',
  },
  rules: [
    {
      token: 'comment',
      foreground: 'a0ada0',
    },
    {
      token: 'punctuation.definition.comment',
      foreground: 'a0ada0',
    },
    {
      token: 'string.comment',
      foreground: 'a0ada0',
    },
    {
      token: 'delimiter.bracket',
      foreground: '999999',
    },
    {
      token: 'delimiter',
      foreground: '999999',
    },
    {
      token: 'invalid.illegal.character-not-allowed-here.html',
      foreground: '999999',
    },
    {
      token: 'keyword.operator.rest',
      foreground: '999999',
    },
    {
      token: 'keyword.operator.spread',
      foreground: '999999',
    },
    {
      token: 'keyword.operator.type.annotation',
      foreground: '999999',
    },
    {
      token: 'keyword.operator.relational',
      foreground: '999999',
    },
    {
      token: 'keyword.operator.assignment',
      foreground: '999999',
    },
    {
      token: 'keyword.operator.type',
      foreground: '999999',
    },
    {
      token: 'meta.brace',
      foreground: '999999',
    },
    {
      token: 'meta.tag.block.any.html',
      foreground: '999999',
    },
    {
      token: 'meta.tag.inline.any.html',
      foreground: '999999',
    },
    {
      token: 'meta.tag.structure.input.void.html',
      foreground: '999999',
    },
    {
      token: 'meta.type.annotation',
      foreground: '999999',
    },
    {
      token: 'meta.embedded.block.github-actions-expression',
      foreground: '999999',
    },
    {
      token: 'storage.type.function.arrow',
      foreground: '999999',
    },
    {
      token: 'meta.objectliteral.ts',
      foreground: '999999',
    },
    {
      token: 'punctuation',
      foreground: '999999',
    },
    {
      token: 'constant',
      foreground: 'a65e2b',
    },
    {
      token: 'entity.name.constant',
      foreground: 'a65e2b',
    },
    {
      token: 'variable.language',
      foreground: 'a65e2b',
    },
    {
      token: 'meta.definition.variable',
      foreground: 'a65e2b',
    },
    {
      token: 'entity',
      foreground: '59873a',
    },
    {
      token: 'entity.name',
      foreground: '59873a',
    },
    {
      token: 'variable.parameter.function',
      foreground: '393a34',
    },
    {
      token: 'entity.name.tag',
      foreground: '1e754f',
    },
    {
      token: 'tag.html',
      foreground: '1e754f',
    },
    {
      token: 'entity.name.function',
      foreground: '59873a',
    },
    {
      token: 'keyword',
      foreground: '1e754f',
    },
    {
      token: 'storage.type.class.jsdoc',
      foreground: '1e754f',
    },
    {
      token: 'storage',
      foreground: 'ab5959',
    },
    {
      token: 'storage.type',
      foreground: 'ab5959',
    },
    {
      token: 'support.type.builtin',
      foreground: 'ab5959',
    },
    {
      token: 'constant.language.undefined',
      foreground: 'ab5959',
    },
    {
      token: 'constant.language.null',
      foreground: 'ab5959',
    },
    {
      token: 'text.html.derivative',
      foreground: '393a34',
    },
    {
      token: 'storage.modifier.package',
      foreground: '393a34',
    },
    {
      token: 'storage.modifier.import',
      foreground: '393a34',
    },
    {
      token: 'storage.type.java',
      foreground: '393a34',
    },
    {
      token: 'string',
      foreground: 'b56959',
    },
    {
      token: 'string punctuation.section.embedded source',
      foreground: 'b56959',
    },
    {
      token: 'attribute.value',
      foreground: 'b56959',
    },
    {
      token: 'punctuation.definition.string',
      foreground: 'b5695999',
    },
    {
      token: 'punctuation.support.type.property-name',
      foreground: 'b5695999',
    },
    {
      token: 'support',
      foreground: '998418',
    },
    {
      token: 'property',
      foreground: '998418',
    },
    {
      token: 'meta.property-name',
      foreground: '998418',
    },
    {
      token: 'meta.object-literal.key',
      foreground: '998418',
    },
    {
      token: 'entity.name.tag.yaml',
      foreground: '998418',
    },
    {
      token: 'attribute.name',
      foreground: '998418',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: 'b07d48',
    },
    {
      token: 'invalid.deprecated.entity.other.attribute-name.html',
      foreground: 'b07d48',
    },
    {
      token: 'variable',
      foreground: 'b07d48',
    },
    {
      token: 'identifier',
      foreground: 'b07d48',
    },
    {
      token: 'support.type.primitive',
      foreground: '2e8f82',
    },
    {
      token: 'entity.name.type',
      foreground: '2e8f82',
    },
    {
      token: 'namespace',
      foreground: 'b05a78',
    },
    {
      token: 'keyword.operator',
      foreground: 'ab5959',
    },
    {
      token: 'keyword.operator.assignment.compound',
      foreground: 'ab5959',
    },
    {
      token: 'meta.var.expr.ts',
      foreground: 'ab5959',
    },
    {
      token: 'invalid.broken',
      foreground: 'b31d28',
    },
    {
      token: 'invalid.deprecated',
      foreground: 'b31d28',
    },
    {
      token: 'invalid.illegal',
      foreground: 'b31d28',
    },
    {
      token: 'invalid.unimplemented',
      foreground: 'b31d28',
    },
    {
      token: 'carriage-return',
      foreground: 'fafbfc',
    },
    {
      token: 'message.error',
      foreground: 'b31d28',
    },
    {
      token: 'string variable',
      foreground: 'b56959',
    },
    {
      token: 'source.regexp',
      foreground: 'ab5e3f',
    },
    {
      token: 'string.regexp',
      foreground: 'ab5e3f',
    },
    {
      token: 'string.regexp.character-class',
      foreground: 'b56959',
    },
    {
      token: 'string.regexp constant.character.escape',
      foreground: 'b56959',
    },
    {
      token: 'string.regexp source.ruby.embedded',
      foreground: 'b56959',
    },
    {
      token: 'string.regexp string.regexp.arbitrary-repitition',
      foreground: 'b56959',
    },
    {
      token: 'string.regexp constant.character.escape',
      foreground: 'bda437',
    },
    {
      token: 'support.constant',
      foreground: 'a65e2b',
    },
    {
      token: 'keyword.operator.quantifier.regexp',
      foreground: '2f798a',
    },
    {
      token: 'constant.numeric',
      foreground: '2f798a',
    },
    {
      token: 'number',
      foreground: '2f798a',
    },
    {
      token: 'keyword.other.unit',
      foreground: 'ab5959',
    },
    {
      token: 'constant.language.boolean',
      foreground: '1e754f',
    },
    {
      token: 'constant.language',
      foreground: '1e754f',
    },
    {
      token: 'meta.module-reference',
      foreground: '1c6b48',
    },
    {
      token: 'punctuation.definition.list.begin.markdown',
      foreground: 'a65e2b',
    },
    {
      token: 'markup.heading',
      foreground: '1c6b48',
    },
    {
      token: 'markup.heading entity.name',
      foreground: '1c6b48',
    },
    {
      token: 'markup.quote',
      foreground: '2e808f',
    },
    {
      token: 'markup.italic',
      foreground: '393a34',
    },
    {
      token: 'markup.bold',
      foreground: '393a34',
    },
    {
      token: 'markup.raw',
      foreground: '1c6b48',
    },
    {
      token: 'markup.deleted',
      foreground: 'b31d28',
    },
    {
      token: 'meta.diff.header.from-file',
      foreground: 'b31d28',
    },
    {
      token: 'punctuation.definition.deleted',
      foreground: 'b31d28',
    },
    {
      token: 'markup.inserted',
      foreground: '22863a',
    },
    {
      token: 'meta.diff.header.to-file',
      foreground: '22863a',
    },
    {
      token: 'punctuation.definition.inserted',
      foreground: '22863a',
    },
    {
      token: 'markup.changed',
      foreground: 'e36209',
    },
    {
      token: 'punctuation.definition.changed',
      foreground: 'e36209',
    },
    {
      token: 'markup.ignored',
      foreground: 'f6f8fa',
    },
    {
      token: 'markup.untracked',
      foreground: 'f6f8fa',
    },
    {
      token: 'meta.diff.range',
      foreground: '6f42c1',
    },
    {
      token: 'meta.diff.header',
      foreground: '005cc5',
    },
    {
      token: 'meta.separator',
      foreground: '005cc5',
    },
    {
      token: 'meta.output',
      foreground: '005cc5',
    },
    {
      token: 'brackethighlighter.tag',
      foreground: '586069',
    },
    {
      token: 'brackethighlighter.curly',
      foreground: '586069',
    },
    {
      token: 'brackethighlighter.round',
      foreground: '586069',
    },
    {
      token: 'brackethighlighter.square',
      foreground: '586069',
    },
    {
      token: 'brackethighlighter.angle',
      foreground: '586069',
    },
    {
      token: 'brackethighlighter.quote',
      foreground: '586069',
    },
    {
      token: 'brackethighlighter.unmatched',
      foreground: 'b31d28',
    },
    {
      token: 'constant.other.reference.link',
      foreground: 'b56959',
    },
    {
      token: 'string.other.link',
      foreground: 'b56959',
    },
    {
      token: 'punctuation.definition.string.begin.markdown',
      foreground: 'b56959',
    },
    {
      token: 'punctuation.definition.string.end.markdown',
      foreground: 'b56959',
    },
    {
      token: 'markup.underline.link.markdown',
      foreground: '393a3490',
    },
    {
      token: 'markup.underline.link.image.markdown',
      foreground: '393a3490',
    },
    {
      token: 'type.identifier',
      foreground: '5a6aa6',
    },
    {
      token: 'constant.other.character-class.regexp',
      foreground: '5a6aa6',
    },
    {
      token: 'entity.other.attribute-name.html.vue',
      foreground: '59873a',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
