import * as monaco from 'monaco-editor';

export default {
  base: 'vs-dark',
  inherit: false,
  colors: {
    'activityBar.activeBackground': '#00000000',
    'activityBar.activeBorder': '#00000000',
    'activityBar.activeFocusBorder': '#00000000',
    'activityBar.background': '#181926',
    'activityBar.border': '#00000000',
    'activityBar.dropBorder': '#c6a0f633',
    'activityBar.foreground': '#c6a0f6',
    'activityBar.inactiveForeground': '#6e738d',
    'activityBarBadge.background': '#c6a0f6',
    'activityBarBadge.foreground': '#181926',
    'activityBarTop.activeBorder': '#00000000',
    'activityBarTop.dropBorder': '#c6a0f633',
    'activityBarTop.foreground': '#c6a0f6',
    'activityBarTop.inactiveForeground': '#6e738d',
    'badge.background': '#494d64',
    'badge.foreground': '#cad3f5',
    'banner.background': '#494d64',
    'banner.foreground': '#cad3f5',
    'banner.iconForeground': '#cad3f5',
    'breadcrumb.activeSelectionForeground': '#c6a0f6',
    'breadcrumb.background': '#24273a',
    'breadcrumb.focusForeground': '#c6a0f6',
    'breadcrumb.foreground': '#cad3f5cc',
    'breadcrumbPicker.background': '#1e2030',
    'button.background': '#c6a0f6',
    'button.border': '#00000000',
    'button.foreground': '#181926',
    'button.hoverBackground': '#dac1f9',
    'button.secondaryBackground': '#5b6078',
    'button.secondaryBorder': '#c6a0f6',
    'button.secondaryForeground': '#cad3f5',
    'button.secondaryHoverBackground': '#6a708c',
    'button.separator': '#00000000',
    'charts.blue': '#8aadf4',
    'charts.foreground': '#cad3f5',
    'charts.green': '#a6da95',
    'charts.lines': '#b8c0e0',
    'charts.orange': '#f5a97f',
    'charts.purple': '#c6a0f6',
    'charts.red': '#ed8796',
    'charts.yellow': '#eed49f',
    'checkbox.background': '#494d64',
    'checkbox.border': '#00000000',
    'checkbox.foreground': '#c6a0f6',
    'commandCenter.activeBackground': '#5b607833',
    'commandCenter.activeBorder': '#c6a0f6',
    'commandCenter.activeForeground': '#c6a0f6',
    'commandCenter.background': '#1e2030',
    'commandCenter.border': '#00000000',
    'commandCenter.foreground': '#b8c0e0',
    'commandCenter.inactiveBorder': '#00000000',
    'commandCenter.inactiveForeground': '#b8c0e0',
    'debugConsole.errorForeground': '#ed8796',
    'debugConsole.infoForeground': '#8aadf4',
    'debugConsole.sourceForeground': '#f4dbd6',
    'debugConsole.warningForeground': '#f5a97f',
    'debugConsoleInputIcon.foreground': '#cad3f5',
    'debugExceptionWidget.background': '#181926',
    'debugExceptionWidget.border': '#c6a0f6',
    'debugIcon.breakpointCurrentStackframeForeground': '#5b6078',
    'debugIcon.breakpointDisabledForeground': '#ed879699',
    'debugIcon.breakpointForeground': '#ed8796',
    'debugIcon.breakpointStackframeForeground': '#5b6078',
    'debugIcon.breakpointUnverifiedForeground': '#a47487',
    'debugIcon.continueForeground': '#a6da95',
    'debugIcon.disconnectForeground': '#5b6078',
    'debugIcon.pauseForeground': '#8aadf4',
    'debugIcon.restartForeground': '#8bd5ca',
    'debugIcon.startForeground': '#a6da95',
    'debugIcon.stepBackForeground': '#5b6078',
    'debugIcon.stepIntoForeground': '#cad3f5',
    'debugIcon.stepOutForeground': '#cad3f5',
    'debugIcon.stepOverForeground': '#c6a0f6',
    'debugIcon.stopForeground': '#ed8796',
    'debugTokenExpression.boolean': '#c6a0f6',
    'debugTokenExpression.error': '#ed8796',
    'debugTokenExpression.number': '#f5a97f',
    'debugTokenExpression.string': '#a6da95',
    'debugToolBar.background': '#181926',
    'debugToolBar.border': '#00000000',
    descriptionForeground: '#cad3f5',
    'diffEditor.border': '#5b6078',
    'diffEditor.diagonalFill': '#5b607899',
    'diffEditor.insertedLineBackground': '#a6da9526',
    'diffEditor.insertedTextBackground': '#a6da951a',
    'diffEditor.removedLineBackground': '#ed879626',
    'diffEditor.removedTextBackground': '#ed87961a',
    'diffEditorOverview.insertedForeground': '#a6da95cc',
    'diffEditorOverview.removedForeground': '#ed8796cc',
    disabledForeground: '#a5adcb',
    'dropdown.background': '#1e2030',
    'dropdown.border': '#c6a0f6',
    'dropdown.foreground': '#cad3f5',
    'dropdown.listBackground': '#5b6078',
    'editor.background': '#24273a',
    'editor.findMatchBackground': '#604456',
    'editor.findMatchBorder': '#ed879633',
    'editor.findMatchHighlightBackground': '#455c6d',
    'editor.findMatchHighlightBorder': '#91d7e333',
    'editor.findRangeHighlightBackground': '#455c6d',
    'editor.findRangeHighlightBorder': '#91d7e333',
    'editor.focusedStackFrameHighlightBackground': '#a6da9526',
    'editor.foldBackground': '#91d7e340',
    'editor.foreground': '#cad3f5',
    'editor.hoverHighlightBackground': '#91d7e340',
    'editor.lineHighlightBackground': '#cad3f512',
    'editor.lineHighlightBorder': '#00000000',
    'editor.rangeHighlightBackground': '#91d7e340',
    'editor.rangeHighlightBorder': '#00000000',
    'editor.selectionBackground': '#939ab740',
    'editor.selectionHighlightBackground': '#939ab733',
    'editor.selectionHighlightBorder': '#939ab733',
    'editor.stackFrameHighlightBackground': '#eed49f26',
    'editor.wordHighlightBackground': '#939ab733',
    'editorBracketHighlight.foreground1': '#ed8796',
    'editorBracketHighlight.foreground2': '#f5a97f',
    'editorBracketHighlight.foreground3': '#eed49f',
    'editorBracketHighlight.foreground4': '#a6da95',
    'editorBracketHighlight.foreground5': '#7dc4e4',
    'editorBracketHighlight.foreground6': '#c6a0f6',
    'editorBracketHighlight.unexpectedBracket.foreground': '#ee99a0',
    'editorBracketMatch.background': '#939ab71a',
    'editorBracketMatch.border': '#939ab7',
    'editorCodeLens.foreground': '#8087a2',
    'editorCursor.background': '#24273a',
    'editorCursor.foreground': '#f4dbd6',
    'editorError.background': '#00000000',
    'editorError.border': '#00000000',
    'editorError.foreground': '#ed8796',
    'editorGroup.border': '#5b6078',
    'editorGroup.dropBackground': '#c6a0f633',
    'editorGroup.emptyBackground': '#24273a',
    'editorGroupHeader.tabsBackground': '#181926',
    'editorGutter.addedBackground': '#a6da95',
    'editorGutter.background': '#24273a',
    'editorGutter.commentRangeForeground': '#939ab7',
    'editorGutter.deletedBackground': '#ed8796',
    'editorGutter.foldingControlForeground': '#939ab7',
    'editorGutter.modifiedBackground': '#eed49f',
    'editorHoverWidget.background': '#1e2030',
    'editorHoverWidget.border': '#5b6078',
    'editorHoverWidget.foreground': '#cad3f5',
    'editorIndentGuide.activeBackground': '#5b6078',
    'editorIndentGuide.background': '#494d64',
    'editorInfo.background': '#00000000',
    'editorInfo.border': '#00000000',
    'editorInfo.foreground': '#8aadf4',
    'editorInlayHint.background': '#1e2030bf',
    'editorInlayHint.foreground': '#5b6078',
    'editorInlayHint.parameterBackground': '#1e2030bf',
    'editorInlayHint.parameterForeground': '#a5adcb',
    'editorInlayHint.typeBackground': '#1e2030bf',
    'editorInlayHint.typeForeground': '#b8c0e0',
    'editorLightBulb.foreground': '#eed49f',
    'editorLineNumber.activeForeground': '#c6a0f6',
    'editorLineNumber.foreground': '#8087a2',
    'editorLink.activeForeground': '#c6a0f6',
    'editorMarkerNavigation.background': '#1e2030',
    'editorMarkerNavigationError.background': '#ed8796',
    'editorMarkerNavigationInfo.background': '#8aadf4',
    'editorMarkerNavigationWarning.background': '#f5a97f',
    'editorOverviewRuler.background': '#1e2030',
    'editorOverviewRuler.border': '#cad3f512',
    'editorOverviewRuler.modifiedForeground': '#eed49f',
    'editorRuler.foreground': '#5b6078',
    'editorStickyScrollHover.background': '#363a4f',
    'editorSuggestWidget.background': '#1e2030',
    'editorSuggestWidget.border': '#5b6078',
    'editorSuggestWidget.foreground': '#cad3f5',
    'editorSuggestWidget.highlightForeground': '#c6a0f6',
    'editorSuggestWidget.selectedBackground': '#363a4f',
    'editorWarning.background': '#00000000',
    'editorWarning.border': '#00000000',
    'editorWarning.foreground': '#f5a97f',
    'editorWhitespace.foreground': '#939ab766',
    'editorWidget.background': '#1e2030',
    'editorWidget.foreground': '#cad3f5',
    'editorWidget.resizeBorder': '#5b6078',
    errorForeground: '#ed8796',
    'errorLens.errorBackground': '#ed879626',
    'errorLens.errorBackgroundLight': '#ed879626',
    'errorLens.errorForeground': '#ed8796',
    'errorLens.errorForegroundLight': '#ed8796',
    'errorLens.errorMessageBackground': '#ed879626',
    'errorLens.hintBackground': '#a6da9526',
    'errorLens.hintBackgroundLight': '#a6da9526',
    'errorLens.hintForeground': '#a6da95',
    'errorLens.hintForegroundLight': '#a6da95',
    'errorLens.hintMessageBackground': '#a6da9526',
    'errorLens.infoBackground': '#8aadf426',
    'errorLens.infoBackgroundLight': '#8aadf426',
    'errorLens.infoForeground': '#8aadf4',
    'errorLens.infoForegroundLight': '#8aadf4',
    'errorLens.infoMessageBackground': '#8aadf426',
    'errorLens.statusBarErrorForeground': '#ed8796',
    'errorLens.statusBarHintForeground': '#a6da95',
    'errorLens.statusBarIconErrorForeground': '#ed8796',
    'errorLens.statusBarIconWarningForeground': '#f5a97f',
    'errorLens.statusBarInfoForeground': '#8aadf4',
    'errorLens.statusBarWarningForeground': '#f5a97f',
    'errorLens.warningBackground': '#f5a97f26',
    'errorLens.warningBackgroundLight': '#f5a97f26',
    'errorLens.warningForeground': '#f5a97f',
    'errorLens.warningForegroundLight': '#f5a97f',
    'errorLens.warningMessageBackground': '#f5a97f26',
    'extensionBadge.remoteBackground': '#8aadf4',
    'extensionBadge.remoteForeground': '#181926',
    'extensionButton.prominentBackground': '#c6a0f6',
    'extensionButton.prominentForeground': '#181926',
    'extensionButton.prominentHoverBackground': '#dac1f9',
    'extensionButton.separator': '#24273a',
    'extensionIcon.preReleaseForeground': '#5b6078',
    'extensionIcon.sponsorForeground': '#f5bde6',
    'extensionIcon.starForeground': '#eed49f',
    'extensionIcon.verifiedForeground': '#a6da95',
    focusBorder: '#c6a0f6',
    foreground: '#cad3f5',
    'gitDecoration.addedResourceForeground': '#a6da95',
    'gitDecoration.conflictingResourceForeground': '#c6a0f6',
    'gitDecoration.deletedResourceForeground': '#ed8796',
    'gitDecoration.ignoredResourceForeground': '#6e738d',
    'gitDecoration.modifiedResourceForeground': '#eed49f',
    'gitDecoration.stageDeletedResourceForeground': '#ed8796',
    'gitDecoration.stageModifiedResourceForeground': '#eed49f',
    'gitDecoration.submoduleResourceForeground': '#8aadf4',
    'gitDecoration.untrackedResourceForeground': '#a6da95',
    'gitlens.closedAutolinkedIssueIconColor': '#c6a0f6',
    'gitlens.closedPullRequestIconColor': '#ed8796',
    'gitlens.decorations.branchAheadForegroundColor': '#a6da95',
    'gitlens.decorations.branchBehindForegroundColor': '#f5a97f',
    'gitlens.decorations.branchDivergedForegroundColor': '#eed49f',
    'gitlens.decorations.branchMissingUpstreamForegroundColor': '#f5a97f',
    'gitlens.decorations.branchUnpublishedForegroundColor': '#a6da95',
    'gitlens.decorations.statusMergingOrRebasingConflictForegroundColor':
      '#ee99a0',
    'gitlens.decorations.statusMergingOrRebasingForegroundColor': '#eed49f',
    'gitlens.decorations.workspaceCurrentForegroundColor': '#c6a0f6',
    'gitlens.decorations.workspaceRepoMissingForegroundColor': '#a5adcb',
    'gitlens.decorations.workspaceRepoOpenForegroundColor': '#c6a0f6',
    'gitlens.decorations.worktreeHasUncommittedChangesForegroundColor':
      '#f5a97f',
    'gitlens.decorations.worktreeMissingForegroundColor': '#ee99a0',
    'gitlens.graphChangesColumnAddedColor': '#a6da95',
    'gitlens.graphChangesColumnDeletedColor': '#ed8796',
    'gitlens.graphLane10Color': '#f5bde6',
    'gitlens.graphLane1Color': '#c6a0f6',
    'gitlens.graphLane2Color': '#eed49f',
    'gitlens.graphLane3Color': '#8aadf4',
    'gitlens.graphLane4Color': '#f0c6c6',
    'gitlens.graphLane5Color': '#a6da95',
    'gitlens.graphLane6Color': '#b7bdf8',
    'gitlens.graphLane7Color': '#f4dbd6',
    'gitlens.graphLane8Color': '#ed8796',
    'gitlens.graphLane9Color': '#8bd5ca',
    'gitlens.graphMinimapMarkerHeadColor': '#a6da95',
    'gitlens.graphMinimapMarkerHighlightsColor': '#eed49f',
    'gitlens.graphMinimapMarkerLocalBranchesColor': '#8aadf4',
    'gitlens.graphMinimapMarkerRemoteBranchesColor': '#739df2',
    'gitlens.graphMinimapMarkerStashesColor': '#c6a0f6',
    'gitlens.graphMinimapMarkerTagsColor': '#f0c6c6',
    'gitlens.graphMinimapMarkerUpstreamColor': '#96d382',
    'gitlens.graphScrollMarkerHeadColor': '#a6da95',
    'gitlens.graphScrollMarkerHighlightsColor': '#eed49f',
    'gitlens.graphScrollMarkerLocalBranchesColor': '#8aadf4',
    'gitlens.graphScrollMarkerRemoteBranchesColor': '#739df2',
    'gitlens.graphScrollMarkerStashesColor': '#c6a0f6',
    'gitlens.graphScrollMarkerTagsColor': '#f0c6c6',
    'gitlens.graphScrollMarkerUpstreamColor': '#96d382',
    'gitlens.gutterBackgroundColor': '#363a4f4d',
    'gitlens.gutterForegroundColor': '#cad3f5',
    'gitlens.gutterUncommittedForegroundColor': '#c6a0f6',
    'gitlens.lineHighlightBackgroundColor': '#c6a0f626',
    'gitlens.lineHighlightOverviewRulerColor': '#c6a0f6cc',
    'gitlens.mergedPullRequestIconColor': '#c6a0f6',
    'gitlens.openAutolinkedIssueIconColor': '#a6da95',
    'gitlens.openPullRequestIconColor': '#a6da95',
    'gitlens.trailingLineBackgroundColor': '#00000000',
    'gitlens.trailingLineForegroundColor': '#cad3f54d',
    'gitlens.unpublishedChangesIconColor': '#a6da95',
    'gitlens.unpublishedCommitIconColor': '#a6da95',
    'gitlens.unpulledChangesIconColor': '#f5a97f',
    'icon.foreground': '#c6a0f6',
    'input.background': '#363a4f',
    'input.border': '#00000000',
    'input.foreground': '#cad3f5',
    'input.placeholderForeground': '#cad3f573',
    'inputOption.activeBackground': '#5b6078',
    'inputOption.activeBorder': '#c6a0f6',
    'inputOption.activeForeground': '#cad3f5',
    'inputValidation.errorBackground': '#ed8796',
    'inputValidation.errorBorder': '#18192633',
    'inputValidation.errorForeground': '#181926',
    'inputValidation.infoBackground': '#8aadf4',
    'inputValidation.infoBorder': '#18192633',
    'inputValidation.infoForeground': '#181926',
    'inputValidation.warningBackground': '#f5a97f',
    'inputValidation.warningBorder': '#18192633',
    'inputValidation.warningForeground': '#181926',
    'issues.closed': '#c6a0f6',
    'issues.newIssueDecoration': '#f4dbd6',
    'issues.open': '#a6da95',
    'list.activeSelectionBackground': '#363a4f',
    'list.activeSelectionForeground': '#cad3f5',
    'list.dropBackground': '#c6a0f633',
    'list.focusAndSelectionBackground': '#494d64',
    'list.focusBackground': '#363a4f',
    'list.focusForeground': '#cad3f5',
    'list.focusOutline': '#00000000',
    'list.highlightForeground': '#c6a0f6',
    'list.hoverBackground': '#363a4f80',
    'list.hoverForeground': '#cad3f5',
    'list.inactiveSelectionBackground': '#363a4f',
    'list.inactiveSelectionForeground': '#cad3f5',
    'list.warningForeground': '#f5a97f',
    'listFilterWidget.background': '#494d64',
    'listFilterWidget.noMatchesOutline': '#ed8796',
    'listFilterWidget.outline': '#00000000',
    'menu.background': '#24273a',
    'menu.border': '#24273a80',
    'menu.foreground': '#cad3f5',
    'menu.selectionBackground': '#5b6078',
    'menu.selectionBorder': '#00000000',
    'menu.selectionForeground': '#cad3f5',
    'menu.separatorBackground': '#5b6078',
    'menubar.selectionBackground': '#494d64',
    'menubar.selectionForeground': '#cad3f5',
    'merge.commonContentBackground': '#494d64',
    'merge.commonHeaderBackground': '#5b6078',
    'merge.currentContentBackground': '#a6da9533',
    'merge.currentHeaderBackground': '#a6da9566',
    'merge.incomingContentBackground': '#8aadf433',
    'merge.incomingHeaderBackground': '#8aadf466',
    'minimap.background': '#1e203080',
    'minimap.errorHighlight': '#ed8796bf',
    'minimap.findMatchHighlight': '#91d7e34d',
    'minimap.selectionHighlight': '#5b6078bf',
    'minimap.selectionOccurrenceHighlight': '#5b6078bf',
    'minimap.warningHighlight': '#f5a97fbf',
    'minimapGutter.addedBackground': '#a6da95bf',
    'minimapGutter.deletedBackground': '#ed8796bf',
    'minimapGutter.modifiedBackground': '#eed49fbf',
    'minimapSlider.activeBackground': '#c6a0f699',
    'minimapSlider.background': '#c6a0f633',
    'minimapSlider.hoverBackground': '#c6a0f666',
    'notificationCenter.border': '#c6a0f6',
    'notificationCenterHeader.background': '#1e2030',
    'notificationCenterHeader.foreground': '#cad3f5',
    'notificationLink.foreground': '#8aadf4',
    'notificationToast.border': '#c6a0f6',
    'notifications.background': '#1e2030',
    'notifications.border': '#c6a0f6',
    'notifications.foreground': '#cad3f5',
    'notificationsErrorIcon.foreground': '#ed8796',
    'notificationsInfoIcon.foreground': '#8aadf4',
    'notificationsWarningIcon.foreground': '#f5a97f',
    'panel.background': '#24273a',
    'panel.border': '#5b6078',
    'panelSection.border': '#5b6078',
    'panelSection.dropBackground': '#c6a0f633',
    'panelTitle.activeBorder': '#c6a0f6',
    'panelTitle.activeForeground': '#cad3f5',
    'panelTitle.inactiveForeground': '#a5adcb',
    'peekView.border': '#c6a0f6',
    'peekViewEditor.background': '#1e2030',
    'peekViewEditor.matchHighlightBackground': '#91d7e34d',
    'peekViewEditor.matchHighlightBorder': '#00000000',
    'peekViewEditorGutter.background': '#1e2030',
    'peekViewResult.background': '#1e2030',
    'peekViewResult.fileForeground': '#cad3f5',
    'peekViewResult.lineForeground': '#cad3f5',
    'peekViewResult.matchHighlightBackground': '#91d7e34d',
    'peekViewResult.selectionBackground': '#363a4f',
    'peekViewResult.selectionForeground': '#cad3f5',
    'peekViewTitle.background': '#24273a',
    'peekViewTitleDescription.foreground': '#b8c0e0b3',
    'peekViewTitleLabel.foreground': '#cad3f5',
    'pickerGroup.border': '#c6a0f6',
    'pickerGroup.foreground': '#c6a0f6',
    'problemsErrorIcon.foreground': '#ed8796',
    'problemsInfoIcon.foreground': '#8aadf4',
    'problemsWarningIcon.foreground': '#f5a97f',
    'progressBar.background': '#c6a0f6',
    'pullRequests.closed': '#ed8796',
    'pullRequests.draft': '#939ab7',
    'pullRequests.merged': '#c6a0f6',
    'pullRequests.notification': '#cad3f5',
    'pullRequests.open': '#a6da95',
    'sash.hoverBorder': '#c6a0f6',
    'scrollbar.shadow': '#181926',
    'scrollbarSlider.activeBackground': '#363a4f66',
    'scrollbarSlider.background': '#5b607880',
    'scrollbarSlider.hoverBackground': '#6e738d',
    'selection.background': '#c6a0f666',
    'settings.dropdownBackground': '#494d64',
    'settings.dropdownListBorder': '#00000000',
    'settings.focusedRowBackground': '#5b607833',
    'settings.headerForeground': '#cad3f5',
    'settings.modifiedItemIndicator': '#c6a0f6',
    'settings.numberInputBackground': '#494d64',
    'settings.numberInputBorder': '#00000000',
    'settings.textInputBackground': '#494d64',
    'settings.textInputBorder': '#00000000',
    'sideBar.background': '#1e2030',
    'sideBar.border': '#00000000',
    'sideBar.dropBackground': '#c6a0f633',
    'sideBar.foreground': '#cad3f5',
    'sideBarSectionHeader.background': '#1e2030',
    'sideBarSectionHeader.foreground': '#cad3f5',
    'sideBarTitle.foreground': '#c6a0f6',
    'statusBar.background': '#181926',
    'statusBar.border': '#00000000',
    'statusBar.debuggingBackground': '#f5a97f',
    'statusBar.debuggingBorder': '#00000000',
    'statusBar.debuggingForeground': '#181926',
    'statusBar.foreground': '#cad3f5',
    'statusBar.noFolderBackground': '#181926',
    'statusBar.noFolderBorder': '#00000000',
    'statusBar.noFolderForeground': '#cad3f5',
    'statusBarItem.activeBackground': '#5b607866',
    'statusBarItem.errorBackground': '#00000000',
    'statusBarItem.errorForeground': '#ed8796',
    'statusBarItem.hoverBackground': '#5b607833',
    'statusBarItem.prominentBackground': '#00000000',
    'statusBarItem.prominentForeground': '#c6a0f6',
    'statusBarItem.prominentHoverBackground': '#5b607833',
    'statusBarItem.remoteBackground': '#8aadf4',
    'statusBarItem.remoteForeground': '#181926',
    'statusBarItem.warningBackground': '#00000000',
    'statusBarItem.warningForeground': '#f5a97f',
    'symbolIcon.arrayForeground': '#f5a97f',
    'symbolIcon.booleanForeground': '#c6a0f6',
    'symbolIcon.classForeground': '#eed49f',
    'symbolIcon.colorForeground': '#f5bde6',
    'symbolIcon.constantForeground': '#f5a97f',
    'symbolIcon.constructorForeground': '#b7bdf8',
    'symbolIcon.enumeratorForeground': '#eed49f',
    'symbolIcon.enumeratorMemberForeground': '#eed49f',
    'symbolIcon.eventForeground': '#f5bde6',
    'symbolIcon.fieldForeground': '#cad3f5',
    'symbolIcon.fileForeground': '#c6a0f6',
    'symbolIcon.folderForeground': '#c6a0f6',
    'symbolIcon.functionForeground': '#8aadf4',
    'symbolIcon.interfaceForeground': '#eed49f',
    'symbolIcon.keyForeground': '#8bd5ca',
    'symbolIcon.keywordForeground': '#c6a0f6',
    'symbolIcon.methodForeground': '#8aadf4',
    'symbolIcon.moduleForeground': '#cad3f5',
    'symbolIcon.namespaceForeground': '#eed49f',
    'symbolIcon.nullForeground': '#ee99a0',
    'symbolIcon.numberForeground': '#f5a97f',
    'symbolIcon.objectForeground': '#eed49f',
    'symbolIcon.operatorForeground': '#8bd5ca',
    'symbolIcon.packageForeground': '#f0c6c6',
    'symbolIcon.propertyForeground': '#ee99a0',
    'symbolIcon.referenceForeground': '#eed49f',
    'symbolIcon.snippetForeground': '#f0c6c6',
    'symbolIcon.stringForeground': '#a6da95',
    'symbolIcon.structForeground': '#8bd5ca',
    'symbolIcon.textForeground': '#cad3f5',
    'symbolIcon.typeParameterForeground': '#ee99a0',
    'symbolIcon.unitForeground': '#cad3f5',
    'symbolIcon.variableForeground': '#cad3f5',
    'tab.activeBackground': '#24273a',
    'tab.activeBorder': '#00000000',
    'tab.activeBorderTop': '#c6a0f6',
    'tab.activeForeground': '#c6a0f6',
    'tab.activeModifiedBorder': '#eed49f',
    'tab.border': '#1e2030',
    'tab.hoverBackground': '#2e324a',
    'tab.hoverBorder': '#00000000',
    'tab.hoverForeground': '#c6a0f6',
    'tab.inactiveBackground': '#1e2030',
    'tab.inactiveForeground': '#6e738d',
    'tab.inactiveModifiedBorder': '#eed49f4d',
    'tab.lastPinnedBorder': '#c6a0f6',
    'tab.unfocusedActiveBackground': '#1e2030',
    'tab.unfocusedActiveBorder': '#00000000',
    'tab.unfocusedActiveBorderTop': '#c6a0f64d',
    'tab.unfocusedInactiveBackground': '#141620',
    'table.headerBackground': '#363a4f',
    'table.headerForeground': '#cad3f5',
    'terminal.ansiBlack': '#a5adcb',
    'terminal.ansiBlue': '#8aadf4',
    'terminal.ansiBrightBlack': '#5b6078',
    'terminal.ansiBrightBlue': '#8aadf4',
    'terminal.ansiBrightCyan': '#91d7e3',
    'terminal.ansiBrightGreen': '#a6da95',
    'terminal.ansiBrightMagenta': '#f5bde6',
    'terminal.ansiBrightRed': '#ed8796',
    'terminal.ansiBrightWhite': '#494d64',
    'terminal.ansiBrightYellow': '#eed49f',
    'terminal.ansiCyan': '#91d7e3',
    'terminal.ansiGreen': '#a6da95',
    'terminal.ansiMagenta': '#f5bde6',
    'terminal.ansiRed': '#ed8796',
    'terminal.ansiWhite': '#b8c0e0',
    'terminal.ansiYellow': '#eed49f',
    'terminal.border': '#5b6078',
    'terminal.dropBackground': '#c6a0f633',
    'terminal.foreground': '#cad3f5',
    'terminal.inactiveSelectionBackground': '#5b607880',
    'terminal.selectionBackground': '#5b6078',
    'terminal.tab.activeBorder': '#c6a0f6',
    'terminalCommandDecoration.defaultBackground': '#5b6078',
    'terminalCommandDecoration.errorBackground': '#ed8796',
    'terminalCommandDecoration.successBackground': '#a6da95',
    'terminalCursor.background': '#24273a',
    'terminalCursor.foreground': '#f4dbd6',
    'textBlockQuote.background': '#1e2030',
    'textBlockQuote.border': '#181926',
    'textCodeBlock.background': '#24273a',
    'textLink.activeForeground': '#91d7e3',
    'textLink.foreground': '#8aadf4',
    'textPreformat.foreground': '#cad3f5',
    'textSeparator.foreground': '#c6a0f6',
    'titleBar.activeBackground': '#181926',
    'titleBar.activeForeground': '#cad3f5',
    'titleBar.border': '#00000000',
    'titleBar.inactiveBackground': '#181926',
    'titleBar.inactiveForeground': '#cad3f580',
    'tree.inactiveIndentGuidesStroke': '#494d64',
    'tree.indentGuidesStroke': '#939ab7',
    'walkThrough.embeddedEditorBackground': '#24273a4d',
    'welcomePage.progress.background': '#181926',
    'welcomePage.progress.foreground': '#c6a0f6',
    'welcomePage.tileBackground': '#1e2030',
    'widget.shadow': '#1e203080',
    'window.activeBorder': '#00000000',
    'window.inactiveBorder': '#00000000',
  },
  rules: [
    {
      token: 'text',
      foreground: 'cad3f5',
    },
    {
      token: 'source',
      foreground: 'cad3f5',
    },
    {
      token: 'variable.other.readwrite',
      foreground: 'cad3f5',
    },
    {
      token: 'punctuation.definition.variable',
      foreground: 'cad3f5',
    },
    {
      token: 'punctuation',
      foreground: '939ab7',
    },
    {
      token: 'comment',
      foreground: '6e738d',
    },
    {
      token: 'punctuation.definition.comment',
      foreground: '6e738d',
    },
    {
      token: 'string',
      foreground: 'a6da95',
    },
    {
      token: 'punctuation.definition.string',
      foreground: 'a6da95',
    },
    {
      token: 'constant.character.escape',
      foreground: 'f5bde6',
    },
    {
      token: 'constant.numeric',
      foreground: 'f5a97f',
    },
    {
      token: 'variable.other.constant',
      foreground: 'f5a97f',
    },
    {
      token: 'entity.name.constant',
      foreground: 'f5a97f',
    },
    {
      token: 'constant.language.boolean',
      foreground: 'f5a97f',
    },
    {
      token: 'constant.language.false',
      foreground: 'f5a97f',
    },
    {
      token: 'constant.language.true',
      foreground: 'f5a97f',
    },
    {
      token: 'keyword.other.unit.user-defined',
      foreground: 'f5a97f',
    },
    {
      token: 'keyword.other.unit.suffix.floating-point',
      foreground: 'f5a97f',
    },
    {
      token: 'keyword',
      foreground: 'c6a0f6',
    },
    {
      token: 'keyword.operator.word',
      foreground: 'c6a0f6',
    },
    {
      token: 'keyword.operator.new',
      foreground: 'c6a0f6',
    },
    {
      token: 'variable.language.super',
      foreground: 'c6a0f6',
    },
    {
      token: 'support.type.primitive',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.type',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.modifier',
      foreground: 'c6a0f6',
    },
    {
      token: 'punctuation.definition.keyword',
      foreground: 'c6a0f6',
    },
    {
      token: 'entity.name.tag.documentation',
      foreground: 'c6a0f6',
    },
    {
      token: 'keyword.operator',
      foreground: '8bd5ca',
    },
    {
      token: 'punctuation.accessor',
      foreground: '8bd5ca',
    },
    {
      token: 'punctuation.definition.generic',
      foreground: '8bd5ca',
    },
    {
      token: 'meta.function.closure punctuation.section.parameters',
      foreground: '8bd5ca',
    },
    {
      token: 'punctuation.definition.tag',
      foreground: '8bd5ca',
    },
    {
      token: 'punctuation.separator.key-value',
      foreground: '8bd5ca',
    },
    {
      token: 'entity.name.function',
      foreground: '8aadf4',
    },
    {
      token: 'meta.function-call.method',
      foreground: '8aadf4',
    },
    {
      token: 'support.function',
      foreground: '8aadf4',
    },
    {
      token: 'support.function.misc',
      foreground: '8aadf4',
    },
    {
      token: 'variable.function',
      foreground: '8aadf4',
    },
    {
      token: 'entity.name.class',
      foreground: 'eed49f',
    },
    {
      token: 'entity.other.inherited-class',
      foreground: 'eed49f',
    },
    {
      token: 'support.class',
      foreground: 'eed49f',
    },
    {
      token: 'meta.function-call.constructor',
      foreground: 'eed49f',
    },
    {
      token: 'entity.name.struct',
      foreground: 'eed49f',
    },
    {
      token: 'entity.name.enum',
      foreground: 'eed49f',
    },
    {
      token: 'meta.enum variable.other.readwrite',
      foreground: '8bd5ca',
    },
    {
      token: 'variable.other.enummember',
      foreground: '8bd5ca',
    },
    {
      token: 'meta.property.object',
      foreground: '8bd5ca',
    },
    {
      token: 'meta.type',
      foreground: 'eed49f',
    },
    {
      token: 'meta.type-alias',
      foreground: 'eed49f',
    },
    {
      token: 'support.type',
      foreground: 'eed49f',
    },
    {
      token: 'entity.name.type',
      foreground: 'eed49f',
    },
    {
      token: 'meta.annotation variable.function',
      foreground: 'f5a97f',
    },
    {
      token: 'meta.annotation variable.annotation.function',
      foreground: 'f5a97f',
    },
    {
      token: 'meta.annotation punctuation.definition.annotation',
      foreground: 'f5a97f',
    },
    {
      token: 'meta.decorator',
      foreground: 'f5a97f',
    },
    {
      token: 'punctuation.decorator',
      foreground: 'f5a97f',
    },
    {
      token: 'variable.parameter',
      foreground: 'ee99a0',
    },
    {
      token: 'meta.function.parameters',
      foreground: 'ee99a0',
    },
    {
      token: 'constant.language',
      foreground: 'ed8796',
    },
    {
      token: 'support.function.builtin',
      foreground: 'ed8796',
    },
    {
      token: 'entity.other.attribute-name.documentation',
      foreground: 'ed8796',
    },
    {
      token: 'keyword.control.directive',
      foreground: 'eed49f',
    },
    {
      token: 'punctuation.definition.directive',
      foreground: 'eed49f',
    },
    {
      token: 'punctuation.definition.typeparameters',
      foreground: '91d7e3',
    },
    {
      token: 'entity.name.namespace',
      foreground: 'eed49f',
    },
    {
      token: 'support.type.property-name.css',
      foreground: '8aadf4',
    },
    {
      token: 'variable.language.this',
      foreground: 'ed8796',
    },
    {
      token: 'variable.language.this punctuation.definition.variable',
      foreground: 'ed8796',
    },
    {
      token: 'variable.object.property',
      foreground: 'cad3f5',
    },
    {
      token: 'string.template variable',
      foreground: 'cad3f5',
    },
    {
      token: 'string variable',
      foreground: 'cad3f5',
    },
    {
      token: 'storage.modifier.specifier.extern.cpp',
      foreground: 'c6a0f6',
    },
    {
      token: 'entity.name.scope-resolution.template.call.cpp',
      foreground: 'eed49f',
    },
    {
      token: 'entity.name.scope-resolution.parameter.cpp',
      foreground: 'eed49f',
    },
    {
      token: 'entity.name.scope-resolution.cpp',
      foreground: 'eed49f',
    },
    {
      token: 'entity.name.scope-resolution.function.definition.cpp',
      foreground: 'eed49f',
    },
    {
      token: 'storage.modifier.reference.cpp',
      foreground: '8bd5ca',
    },
    {
      token: 'meta.interpolation.cs',
      foreground: 'cad3f5',
    },
    {
      token: 'comment.block.documentation.cs',
      foreground: 'cad3f5',
    },
    {
      token: 'source.css entity.other.attribute-name.class.css',
      foreground: 'eed49f',
    },
    {
      token:
        'entity.other.attribute-name.parent-selector.css punctuation.definition.entity.css',
      foreground: 'eed49f',
    },
    {
      token: 'punctuation.separator.operator.css',
      foreground: '8bd5ca',
    },
    {
      token: 'source.css entity.other.attribute-name.pseudo-class',
      foreground: '8bd5ca',
    },
    {
      token: 'source.css constant.other.unicode-range',
      foreground: 'f5a97f',
    },
    {
      token: 'source.css variable.parameter.url',
      foreground: 'a6da95',
    },
    {
      token: 'support.type.vendored.property-name',
      foreground: '91d7e3',
    },
    {
      token: 'source.css meta.property-value variable',
      foreground: 'ee99a0',
    },
    {
      token: 'source.css meta.property-value variable.other.less',
      foreground: 'ee99a0',
    },
    {
      token:
        'source.css meta.property-value variable.other.less punctuation.definition.variable.less',
      foreground: 'ee99a0',
    },
    {
      token: 'meta.definition.variable.scss',
      foreground: 'ee99a0',
    },
    {
      token: 'source.css meta.property-list variable',
      foreground: '8aadf4',
    },
    {
      token: 'meta.property-list variable.other.less',
      foreground: '8aadf4',
    },
    {
      token:
        'meta.property-list variable.other.less punctuation.definition.variable.less',
      foreground: '8aadf4',
    },
    {
      token: 'keyword.other.unit.percentage.css',
      foreground: 'f5a97f',
    },
    {
      token: 'source.css meta.attribute-selector',
      foreground: 'a6da95',
    },
    {
      token: 'keyword.other.definition.ini',
      foreground: '8aadf4',
    },
    {
      token: 'punctuation.support.type.property-name.json',
      foreground: '8aadf4',
    },
    {
      token: 'support.type.property-name.json',
      foreground: '8aadf4',
    },
    {
      token: 'punctuation.support.type.property-name.toml',
      foreground: '8aadf4',
    },
    {
      token: 'support.type.property-name.toml',
      foreground: '8aadf4',
    },
    {
      token: 'entity.name.tag.yaml',
      foreground: '8aadf4',
    },
    {
      token: 'punctuation.support.type.property-name.yaml',
      foreground: '8aadf4',
    },
    {
      token: 'support.type.property-name.yaml',
      foreground: '8aadf4',
    },
    {
      token: 'constant.language.json',
      foreground: 'f5a97f',
    },
    {
      token: 'constant.language.yaml',
      foreground: 'f5a97f',
    },
    {
      token: 'entity.name.type.anchor.yaml',
      foreground: 'eed49f',
    },
    {
      token: 'variable.other.alias.yaml',
      foreground: 'eed49f',
    },
    {
      token: 'support.type.property-name.table',
      foreground: 'eed49f',
    },
    {
      token: 'entity.name.section.group-title.ini',
      foreground: 'eed49f',
    },
    {
      token: 'constant.other.time.datetime.offset.toml',
      foreground: 'f5bde6',
    },
    {
      token: 'punctuation.definition.anchor.yaml',
      foreground: 'f5bde6',
    },
    {
      token: 'punctuation.definition.alias.yaml',
      foreground: 'f5bde6',
    },
    {
      token: 'entity.other.document.begin.yaml',
      foreground: 'f5bde6',
    },
    {
      token: 'markup.changed.diff',
      foreground: 'f5a97f',
    },
    {
      token: 'meta.diff.header.from-file',
      foreground: '8aadf4',
    },
    {
      token: 'meta.diff.header.to-file',
      foreground: '8aadf4',
    },
    {
      token: 'punctuation.definition.from-file.diff',
      foreground: '8aadf4',
    },
    {
      token: 'punctuation.definition.to-file.diff',
      foreground: '8aadf4',
    },
    {
      token: 'markup.inserted.diff',
      foreground: 'a6da95',
    },
    {
      token: 'markup.deleted.diff',
      foreground: 'ed8796',
    },
    {
      token: 'variable.other.env',
      foreground: '8aadf4',
    },
    {
      token: 'string.quoted variable.other.env',
      foreground: 'cad3f5',
    },
    {
      token: 'support.function.builtin.gdscript',
      foreground: '8aadf4',
    },
    {
      token: 'constant.language.gdscript',
      foreground: 'f5a97f',
    },
    {
      token: 'comment meta.annotation.go',
      foreground: 'ee99a0',
    },
    {
      token: 'comment meta.annotation.parameters.go',
      foreground: 'f5a97f',
    },
    {
      token: 'constant.language.go',
      foreground: 'f5a97f',
    },
    {
      token: 'variable.graphql',
      foreground: 'cad3f5',
    },
    {
      token: 'string.unquoted.alias.graphql',
      foreground: 'f0c6c6',
    },
    {
      token: 'constant.character.enum.graphql',
      foreground: '8bd5ca',
    },
    {
      token:
        'meta.objectvalues.graphql constant.object.key.graphql string.unquoted.graphql',
      foreground: 'f0c6c6',
    },
    {
      token: 'keyword.other.doctype',
      foreground: 'c6a0f6',
    },
    {
      token: 'meta.tag.sgml.doctype punctuation.definition.tag',
      foreground: 'c6a0f6',
    },
    {
      token: 'meta.tag.metadata.doctype entity.name.tag',
      foreground: 'c6a0f6',
    },
    {
      token: 'meta.tag.metadata.doctype punctuation.definition.tag',
      foreground: 'c6a0f6',
    },
    {
      token: 'entity.name.tag',
      foreground: '8aadf4',
    },
    {
      token: 'text.html constant.character.entity',
      foreground: 'ed8796',
    },
    {
      token: 'text.html constant.character.entity punctuation',
      foreground: 'ed8796',
    },
    {
      token: 'constant.character.entity.xml',
      foreground: 'ed8796',
    },
    {
      token: 'constant.character.entity.xml punctuation',
      foreground: 'ed8796',
    },
    {
      token: 'constant.character.entity.js.jsx',
      foreground: 'ed8796',
    },
    {
      token: 'constant.charactger.entity.js.jsx punctuation',
      foreground: 'ed8796',
    },
    {
      token: 'constant.character.entity.tsx',
      foreground: 'ed8796',
    },
    {
      token: 'constant.character.entity.tsx punctuation',
      foreground: 'ed8796',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: 'eed49f',
    },
    {
      token: 'support.class.component',
      foreground: 'f5bde6',
    },
    {
      token: 'support.class.component.jsx',
      foreground: 'f5bde6',
    },
    {
      token: 'support.class.component.tsx',
      foreground: 'f5bde6',
    },
    {
      token: 'support.class.component.vue',
      foreground: 'f5bde6',
    },
    {
      token: 'punctuation.definition.annotation',
      foreground: 'f5a97f',
    },
    {
      token: 'storage.type.annotation',
      foreground: 'f5a97f',
    },
    {
      token: 'constant.other.enum.java',
      foreground: '8bd5ca',
    },
    {
      token: 'storage.modifier.import.java',
      foreground: 'cad3f5',
    },
    {
      token: 'meta.export variable.other.readwrite.js',
      foreground: 'ee99a0',
    },
    {
      token: 'variable.other.constant.js',
      foreground: 'cad3f5',
    },
    {
      token: 'variable.other.constant.ts',
      foreground: 'cad3f5',
    },
    {
      token: 'variable.other.property.js',
      foreground: 'cad3f5',
    },
    {
      token: 'variable.other.property.ts',
      foreground: 'cad3f5',
    },
    {
      token: 'variable.other.jsdoc',
      foreground: 'ee99a0',
    },
    {
      token: 'comment.block.documentation variable.other',
      foreground: 'ee99a0',
    },
    {
      token: 'support.type.object.console.js',
      foreground: 'cad3f5',
    },
    {
      token: 'support.constant.node',
      foreground: 'c6a0f6',
    },
    {
      token: 'support.type.object.module.js',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.modifier.implements',
      foreground: 'c6a0f6',
    },
    {
      token: 'constant.language.null.js',
      foreground: 'c6a0f6',
    },
    {
      token: 'constant.language.null.ts',
      foreground: 'c6a0f6',
    },
    {
      token: 'constant.language.undefined.js',
      foreground: 'c6a0f6',
    },
    {
      token: 'constant.language.undefined.ts',
      foreground: 'c6a0f6',
    },
    {
      token: 'support.type.builtin.ts',
      foreground: 'c6a0f6',
    },
    {
      token: 'variable.parameter.generic',
      foreground: 'eed49f',
    },
    {
      token: 'keyword.declaration.function.arrow.js',
      foreground: '8bd5ca',
    },
    {
      token: 'storage.type.function.arrow.ts',
      foreground: '8bd5ca',
    },
    {
      token: 'punctuation.decorator.ts',
      foreground: '8aadf4',
    },
    {
      token: 'keyword.operator.expression.in.js',
      foreground: 'c6a0f6',
    },
    {
      token: 'keyword.operator.expression.in.ts',
      foreground: 'c6a0f6',
    },
    {
      token: 'keyword.operator.expression.infer.ts',
      foreground: 'c6a0f6',
    },
    {
      token: 'keyword.operator.expression.instanceof.js',
      foreground: 'c6a0f6',
    },
    {
      token: 'keyword.operator.expression.instanceof.ts',
      foreground: 'c6a0f6',
    },
    {
      token: 'keyword.operator.expression.is',
      foreground: 'c6a0f6',
    },
    {
      token: 'keyword.operator.expression.keyof.ts',
      foreground: 'c6a0f6',
    },
    {
      token: 'keyword.operator.expression.of.js',
      foreground: 'c6a0f6',
    },
    {
      token: 'keyword.operator.expression.of.ts',
      foreground: 'c6a0f6',
    },
    {
      token: 'keyword.operator.expression.typeof.ts',
      foreground: 'c6a0f6',
    },
    {
      token: 'support.function.macro.julia',
      foreground: '8bd5ca',
    },
    {
      token: 'constant.language.julia',
      foreground: 'f5a97f',
    },
    {
      token: 'constant.other.symbol.julia',
      foreground: 'ee99a0',
    },
    {
      token: 'text.tex keyword.control.preamble',
      foreground: '8bd5ca',
    },
    {
      token: 'text.tex support.function.be',
      foreground: '91d7e3',
    },
    {
      token: 'constant.other.general.math.tex',
      foreground: 'f0c6c6',
    },
    {
      token:
        'comment.line.double-dash.documentation.lua storage.type.annotation.lua',
      foreground: 'c6a0f6',
    },
    {
      token:
        'comment.line.double-dash.documentation.lua entity.name.variable.lua',
      foreground: 'cad3f5',
    },
    {
      token: 'comment.line.double-dash.documentation.lua variable.lua',
      foreground: 'cad3f5',
    },
    {
      token: 'heading.1.markdown punctuation.definition.heading.markdown',
      foreground: 'ed8796',
    },
    {
      token: 'heading.1.markdown',
      foreground: 'ed8796',
    },
    {
      token: 'heading.1.quarto punctuation.definition.heading.quarto',
      foreground: 'ed8796',
    },
    {
      token: 'heading.1.quarto',
      foreground: 'ed8796',
    },
    {
      token: 'markup.heading.atx.1.mdx',
      foreground: 'ed8796',
    },
    {
      token: 'markup.heading.atx.1.mdx punctuation.definition.heading.mdx',
      foreground: 'ed8796',
    },
    {
      token: 'markup.heading.setext.1.markdown',
      foreground: 'ed8796',
    },
    {
      token: 'markup.heading.heading-0.asciidoc',
      foreground: 'ed8796',
    },
    {
      token: 'heading.2.markdown punctuation.definition.heading.markdown',
      foreground: 'f5a97f',
    },
    {
      token: 'heading.2.markdown',
      foreground: 'f5a97f',
    },
    {
      token: 'heading.2.quarto punctuation.definition.heading.quarto',
      foreground: 'f5a97f',
    },
    {
      token: 'heading.2.quarto',
      foreground: 'f5a97f',
    },
    {
      token: 'markup.heading.atx.2.mdx',
      foreground: 'f5a97f',
    },
    {
      token: 'markup.heading.atx.2.mdx punctuation.definition.heading.mdx',
      foreground: 'f5a97f',
    },
    {
      token: 'markup.heading.setext.2.markdown',
      foreground: 'f5a97f',
    },
    {
      token: 'markup.heading.heading-1.asciidoc',
      foreground: 'f5a97f',
    },
    {
      token: 'heading.3.markdown punctuation.definition.heading.markdown',
      foreground: 'eed49f',
    },
    {
      token: 'heading.3.markdown',
      foreground: 'eed49f',
    },
    {
      token: 'heading.3.quarto punctuation.definition.heading.quarto',
      foreground: 'eed49f',
    },
    {
      token: 'heading.3.quarto',
      foreground: 'eed49f',
    },
    {
      token: 'markup.heading.atx.3.mdx',
      foreground: 'eed49f',
    },
    {
      token: 'markup.heading.atx.3.mdx punctuation.definition.heading.mdx',
      foreground: 'eed49f',
    },
    {
      token: 'markup.heading.heading-2.asciidoc',
      foreground: 'eed49f',
    },
    {
      token: 'heading.4.markdown punctuation.definition.heading.markdown',
      foreground: 'a6da95',
    },
    {
      token: 'heading.4.markdown',
      foreground: 'a6da95',
    },
    {
      token: 'heading.4.quarto punctuation.definition.heading.quarto',
      foreground: 'a6da95',
    },
    {
      token: 'heading.4.quarto',
      foreground: 'a6da95',
    },
    {
      token: 'markup.heading.atx.4.mdx',
      foreground: 'a6da95',
    },
    {
      token: 'markup.heading.atx.4.mdx punctuation.definition.heading.mdx',
      foreground: 'a6da95',
    },
    {
      token: 'markup.heading.heading-3.asciidoc',
      foreground: 'a6da95',
    },
    {
      token: 'heading.5.markdown punctuation.definition.heading.markdown',
      foreground: '8aadf4',
    },
    {
      token: 'heading.5.markdown',
      foreground: '8aadf4',
    },
    {
      token: 'heading.5.quarto punctuation.definition.heading.quarto',
      foreground: '8aadf4',
    },
    {
      token: 'heading.5.quarto',
      foreground: '8aadf4',
    },
    {
      token: 'markup.heading.atx.5.mdx',
      foreground: '8aadf4',
    },
    {
      token: 'markup.heading.atx.5.mdx punctuation.definition.heading.mdx',
      foreground: '8aadf4',
    },
    {
      token: 'markup.heading.heading-4.asciidoc',
      foreground: '8aadf4',
    },
    {
      token: 'heading.6.markdown punctuation.definition.heading.markdown',
      foreground: 'c6a0f6',
    },
    {
      token: 'heading.6.markdown',
      foreground: 'c6a0f6',
    },
    {
      token: 'heading.6.quarto punctuation.definition.heading.quarto',
      foreground: 'c6a0f6',
    },
    {
      token: 'heading.6.quarto',
      foreground: 'c6a0f6',
    },
    {
      token: 'markup.heading.atx.6.mdx',
      foreground: 'c6a0f6',
    },
    {
      token: 'markup.heading.atx.6.mdx punctuation.definition.heading.mdx',
      foreground: 'c6a0f6',
    },
    {
      token: 'markup.heading.heading-5.asciidoc',
      foreground: 'c6a0f6',
    },
    {
      token: 'markup.bold',
      foreground: 'ed8796',
    },
    {
      token: 'markup.italic',
      foreground: 'ed8796',
    },
    {
      token: 'markup.strikethrough',
      foreground: 'a5adcb',
    },
    {
      token: 'punctuation.definition.link',
      foreground: '8aadf4',
    },
    {
      token: 'markup.underline.link',
      foreground: '8aadf4',
    },
    {
      token: 'text.html.markdown punctuation.definition.link.title',
      foreground: 'b7bdf8',
    },
    {
      token: 'text.html.quarto punctuation.definition.link.title',
      foreground: 'b7bdf8',
    },
    {
      token: 'string.other.link.title.markdown',
      foreground: 'b7bdf8',
    },
    {
      token: 'string.other.link.title.quarto',
      foreground: 'b7bdf8',
    },
    {
      token: 'markup.link',
      foreground: 'b7bdf8',
    },
    {
      token: 'punctuation.definition.constant.markdown',
      foreground: 'b7bdf8',
    },
    {
      token: 'punctuation.definition.constant.quarto',
      foreground: 'b7bdf8',
    },
    {
      token: 'constant.other.reference.link.markdown',
      foreground: 'b7bdf8',
    },
    {
      token: 'constant.other.reference.link.quarto',
      foreground: 'b7bdf8',
    },
    {
      token: 'markup.substitution.attribute-reference',
      foreground: 'b7bdf8',
    },
    {
      token: 'punctuation.definition.raw.markdown',
      foreground: 'a6da95',
    },
    {
      token: 'punctuation.definition.raw.quarto',
      foreground: 'a6da95',
    },
    {
      token: 'markup.inline.raw.string.markdown',
      foreground: 'a6da95',
    },
    {
      token: 'markup.inline.raw.string.quarto',
      foreground: 'a6da95',
    },
    {
      token: 'markup.raw.block.markdown',
      foreground: 'a6da95',
    },
    {
      token: 'markup.raw.block.quarto',
      foreground: 'a6da95',
    },
    {
      token: 'fenced_code.block.language',
      foreground: '91d7e3',
    },
    {
      token: 'markup.fenced_code.block punctuation.definition',
      foreground: '939ab7',
    },
    {
      token: 'markup.raw support.asciidoc',
      foreground: '939ab7',
    },
    {
      token: 'markup.quote',
      foreground: 'f5bde6',
    },
    {
      token: 'punctuation.definition.quote.begin',
      foreground: 'f5bde6',
    },
    {
      token: 'meta.separator.markdown',
      foreground: '8bd5ca',
    },
    {
      token: 'punctuation.definition.list.begin.markdown',
      foreground: '8bd5ca',
    },
    {
      token: 'punctuation.definition.list.begin.quarto',
      foreground: '8bd5ca',
    },
    {
      token: 'markup.list.bullet',
      foreground: '8bd5ca',
    },
    {
      token: 'entity.other.attribute-name.multipart.nix',
      foreground: '8aadf4',
    },
    {
      token: 'entity.other.attribute-name.single.nix',
      foreground: '8aadf4',
    },
    {
      token: 'variable.parameter.name.nix',
      foreground: 'cad3f5',
    },
    {
      token: 'meta.embedded variable.parameter.name.nix',
      foreground: 'b7bdf8',
    },
    {
      token: 'string.unquoted.path.nix',
      foreground: 'f5bde6',
    },
    {
      token: 'support.attribute.builtin',
      foreground: 'eed49f',
    },
    {
      token: 'meta.attribute.php',
      foreground: 'eed49f',
    },
    {
      token: 'meta.function.parameters.php punctuation.definition.variable.php',
      foreground: 'ee99a0',
    },
    {
      token: 'constant.language.php',
      foreground: 'c6a0f6',
    },
    {
      token: 'text.html.php support.function',
      foreground: '91d7e3',
    },
    {
      token: 'support.variable.magic.python',
      foreground: 'cad3f5',
    },
    {
      token: 'meta.function-call.arguments.python',
      foreground: 'cad3f5',
    },
    {
      token: 'support.function.magic.python',
      foreground: '91d7e3',
    },
    {
      token: 'variable.parameter.function.language.special.self.python',
      foreground: 'ed8796',
    },
    {
      token: 'variable.language.special.self.python',
      foreground: 'ed8796',
    },
    {
      token: 'keyword.control.flow.python',
      foreground: 'c6a0f6',
    },
    {
      token: 'keyword.operator.logical.python',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.type.function.python',
      foreground: 'c6a0f6',
    },
    {
      token: 'support.token.decorator.python',
      foreground: '91d7e3',
    },
    {
      token: 'meta.function.decorator.identifier.python',
      foreground: '91d7e3',
    },
    {
      token: 'meta.function-call.python',
      foreground: '8aadf4',
    },
    {
      token: 'entity.name.function.decorator.python',
      foreground: 'f5a97f',
    },
    {
      token: 'punctuation.definition.decorator.python',
      foreground: 'f5a97f',
    },
    {
      token: 'constant.character.format.placeholder.other.python',
      foreground: 'f5bde6',
    },
    {
      token: 'support.type.exception.python',
      foreground: 'f5a97f',
    },
    {
      token: 'support.function.builtin.python',
      foreground: 'f5a97f',
    },
    {
      token: 'support.type.python',
      foreground: 'f5a97f',
    },
    {
      token: 'constant.language.python',
      foreground: 'c6a0f6',
    },
    {
      token: 'meta.indexed-name.python',
      foreground: 'ee99a0',
    },
    {
      token: 'meta.item-access.python',
      foreground: 'ee99a0',
    },
    {
      token: 'storage.type.string.python',
      foreground: 'a6da95',
    },
    {
      token: 'string.regexp punctuation.definition.string.begin',
      foreground: 'f5bde6',
    },
    {
      token: 'string.regexp punctuation.definition.string.end',
      foreground: 'f5bde6',
    },
    {
      token: 'keyword.control.anchor.regexp',
      foreground: 'c6a0f6',
    },
    {
      token: 'string.regexp.ts',
      foreground: 'cad3f5',
    },
    {
      token: 'punctuation.definition.group.regexp',
      foreground: 'a6da95',
    },
    {
      token: 'keyword.other.back-reference.regexp',
      foreground: 'a6da95',
    },
    {
      token: 'punctuation.definition.character-class.regexp',
      foreground: 'eed49f',
    },
    {
      token: 'constant.other.character-class.regexp',
      foreground: 'f5bde6',
    },
    {
      token: 'constant.other.character-class.range.regexp',
      foreground: 'f4dbd6',
    },
    {
      token: 'keyword.operator.quantifier.regexp',
      foreground: '8bd5ca',
    },
    {
      token: 'constant.character.numeric.regexp',
      foreground: 'f5a97f',
    },
    {
      token: 'punctuation.definition.group.no-capture.regexp',
      foreground: '8aadf4',
    },
    {
      token: 'meta.assertion.look-ahead.regexp',
      foreground: '8aadf4',
    },
    {
      token: 'meta.assertion.negative-look-ahead.regexp',
      foreground: '8aadf4',
    },
    {
      token: 'meta.annotation.rust',
      foreground: 'eed49f',
    },
    {
      token: 'meta.annotation.rust punctuation',
      foreground: 'eed49f',
    },
    {
      token: 'meta.attribute.rust',
      foreground: 'eed49f',
    },
    {
      token: 'punctuation.definition.attribute.rust',
      foreground: 'eed49f',
    },
    {
      token: 'entity.name.function.macro.rules.rust',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.type.module.rust',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.modifier.rust',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.type.struct.rust',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.type.enum.rust',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.type.trait.rust',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.type.union.rust',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.type.impl.rust',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.type.rust',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.type.function.rust',
      foreground: 'c6a0f6',
    },
    {
      token: 'storage.type.type.rust',
      foreground: 'c6a0f6',
    },
    {
      token: 'entity.name.type.numeric.rust',
      foreground: 'c6a0f6',
    },
    {
      token: 'meta.generic.rust',
      foreground: 'f5a97f',
    },
    {
      token: 'entity.name.impl.rust',
      foreground: 'eed49f',
    },
    {
      token: 'entity.name.module.rust',
      foreground: 'f5a97f',
    },
    {
      token: 'entity.name.trait.rust',
      foreground: 'eed49f',
    },
    {
      token: 'storage.type.source.rust',
      foreground: 'eed49f',
    },
    {
      token: 'entity.name.union.rust',
      foreground: 'eed49f',
    },
    {
      token: 'meta.enum.rust storage.type.source.rust',
      foreground: '8bd5ca',
    },
    {
      token: 'support.macro.rust',
      foreground: '8aadf4',
    },
    {
      token: 'meta.macro.rust support.function.rust',
      foreground: '8aadf4',
    },
    {
      token: 'entity.name.function.macro.rust',
      foreground: '8aadf4',
    },
    {
      token: 'storage.modifier.lifetime.rust',
      foreground: '8aadf4',
    },
    {
      token: 'entity.name.type.lifetime',
      foreground: '8aadf4',
    },
    {
      token: 'string.quoted.double.rust constant.other.placeholder.rust',
      foreground: 'f5bde6',
    },
    {
      token:
        'meta.function.return-type.rust meta.generic.rust storage.type.rust',
      foreground: 'cad3f5',
    },
    {
      token: 'meta.function.call.rust',
      foreground: '8aadf4',
    },
    {
      token: 'punctuation.brackets.angle.rust',
      foreground: '91d7e3',
    },
    {
      token: 'constant.other.caps.rust',
      foreground: 'f5a97f',
    },
    {
      token: 'meta.function.definition.rust variable.other.rust',
      foreground: 'ee99a0',
    },
    {
      token: 'meta.function.call.rust variable.other.rust',
      foreground: 'cad3f5',
    },
    {
      token: 'variable.language.self.rust',
      foreground: 'ed8796',
    },
    {
      token: 'variable.other.metavariable.name.rust',
      foreground: 'f5bde6',
    },
    {
      token: 'meta.macro.metavariable.rust keyword.operator.macro.dollar.rust',
      foreground: 'f5bde6',
    },
    {
      token: 'comment.line.shebang',
      foreground: 'f5bde6',
    },
    {
      token: 'comment.line.shebang punctuation.definition.comment',
      foreground: 'f5bde6',
    },
    {
      token: 'comment.line.shebang',
      foreground: 'f5bde6',
    },
    {
      token: 'punctuation.definition.comment.shebang.shell',
      foreground: 'f5bde6',
    },
    {
      token: 'meta.shebang.shell',
      foreground: 'f5bde6',
    },
    {
      token: 'comment.line.shebang constant.language',
      foreground: '8bd5ca',
    },
    {
      token:
        'meta.function-call.arguments.shell punctuation.definition.variable.shell',
      foreground: 'ed8796',
    },
    {
      token:
        'meta.function-call.arguments.shell punctuation.section.interpolation',
      foreground: 'ed8796',
    },
    {
      token:
        'meta.function-call.arguments.shell punctuation.definition.variable.shell',
      foreground: 'ed8796',
    },
    {
      token:
        'meta.function-call.arguments.shell punctuation.section.interpolation',
      foreground: 'ed8796',
    },
    {
      token:
        'meta.string meta.interpolation.parameter.shell variable.other.readwrite',
      foreground: 'f5a97f',
    },
    {
      token: 'source.shell punctuation.section.interpolation',
      foreground: '8bd5ca',
    },
    {
      token: 'punctuation.definition.evaluation.backticks.shell',
      foreground: '8bd5ca',
    },
    {
      token: 'entity.name.tag.heredoc.shell',
      foreground: 'c6a0f6',
    },
    {
      token: 'string.quoted.double.shell variable.other.normal.shell',
      foreground: 'cad3f5',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
