import * as monaco from 'monaco-editor';

export default {
  base: 'vs',
  inherit: false,
  colors: {
    'activityBar.activeBorder': '#80CBC4',
    'activityBar.background': '#FAFAFA',
    'activityBar.border': '#FAFAFA60',
    'activityBar.dropBackground': '#E5393580',
    'activityBar.foreground': '#90A4AE',
    'activityBarBadge.background': '#80CBC4',
    'activityBarBadge.foreground': '#000000',
    'badge.background': '#CCD7DA30',
    'badge.foreground': '#90A4AE',
    'breadcrumb.activeSelectionForeground': '#80CBC4',
    'breadcrumb.background': '#FAFAFA',
    'breadcrumb.focusForeground': '#90A4AE',
    'breadcrumb.foreground': '#758a95',
    'breadcrumbPicker.background': '#FAFAFA',
    'button.background': '#80CBC440',
    'button.foreground': '#ffffff',
    'debugConsole.errorForeground': '#E53935',
    'debugConsole.infoForeground': '#39ADB5',
    'debugConsole.warningForeground': '#E2931D',
    'debugToolBar.background': '#FAFAFA',
    'diffEditor.insertedTextBackground': '#39ADB520',
    'diffEditor.removedTextBackground': '#FF537020',
    'dropdown.background': '#FAFAFA',
    'dropdown.border': '#00000010',
    'editor.background': '#FAFAFA',
    'editor.findMatchBackground': '#00000020',
    'editor.findMatchBorder': '#80CBC4',
    'editor.findMatchHighlight': '#90A4AE',
    'editor.findMatchHighlightBackground': '#00000010',
    'editor.findMatchHighlightBorder': '#00000030',
    'editor.findRangeHighlightBackground': '#E2931D30',
    'editor.foreground': '#90A4AE',
    'editor.lineHighlightBackground': '#CCD7DA50',
    'editor.lineHighlightBorder': '#CCD7DA00',
    'editor.rangeHighlightBackground': '#FFFFFF0d',
    'editor.selectionBackground': '#80CBC440',
    'editor.selectionHighlightBackground': '#27272720',
    'editor.wordHighlightBackground': '#FF537030',
    'editor.wordHighlightStrongBackground': '#91B85930',
    'editorBracketMatch.background': '#FAFAFA',
    'editorBracketMatch.border': '#27272750',
    'editorCursor.foreground': '#272727',
    'editorError.foreground': '#E5393570',
    'editorGroup.border': '#00000020',
    'editorGroup.dropBackground': '#E5393580',
    'editorGroup.focusedEmptyBorder': '#E53935',
    'editorGroupHeader.tabsBackground': '#FAFAFA',
    'editorGutter.addedBackground': '#91B85960',
    'editorGutter.deletedBackground': '#E5393560',
    'editorGutter.modifiedBackground': '#6182B860',
    'editorHoverWidget.background': '#FAFAFA',
    'editorHoverWidget.border': '#00000010',
    'editorIndentGuide.activeBackground': '#B0BEC5',
    'editorIndentGuide.background': '#B0BEC570',
    'editorInfo.foreground': '#6182B870',
    'editorLineNumber.activeForeground': '#758a95',
    'editorLineNumber.foreground': '#CFD8DC',
    'editorLink.activeForeground': '#90A4AE',
    'editorMarkerNavigation.background': '#90A4AE05',
    'editorOverviewRuler.border': '#FAFAFA',
    'editorOverviewRuler.errorForeground': '#E5393540',
    'editorOverviewRuler.findMatchForeground': '#80CBC4',
    'editorOverviewRuler.infoForeground': '#6182B840',
    'editorOverviewRuler.warningForeground': '#E2931D40',
    'editorRuler.foreground': '#B0BEC5',
    'editorSuggestWidget.background': '#FAFAFA',
    'editorSuggestWidget.border': '#00000010',
    'editorSuggestWidget.foreground': '#90A4AE',
    'editorSuggestWidget.highlightForeground': '#80CBC4',
    'editorSuggestWidget.selectedBackground': '#CCD7DA50',
    'editorWarning.foreground': '#E2931D70',
    'editorWhitespace.foreground': '#90A4AE40',
    'editorWidget.background': '#FAFAFA',
    'editorWidget.border': '#80CBC4',
    'editorWidget.resizeBorder': '#80CBC4',
    'extensionBadge.remoteForeground': '#90A4AE',
    'extensionButton.prominentBackground': '#91B85990',
    'extensionButton.prominentForeground': '#90A4AE',
    'extensionButton.prominentHoverBackground': '#91B859',
    focusBorder: '#FFFFFF00',
    foreground: '#90A4AE',
    'gitDecoration.conflictingResourceForeground': '#E2931D90',
    'gitDecoration.deletedResourceForeground': '#E5393590',
    'gitDecoration.ignoredResourceForeground': '#758a9590',
    'gitDecoration.modifiedResourceForeground': '#6182B890',
    'gitDecoration.untrackedResourceForeground': '#91B85990',
    'input.background': '#EEEEEE',
    'input.border': '#00000010',
    'input.foreground': '#90A4AE',
    'input.placeholderForeground': '#90A4AE60',
    'inputOption.activeBackground': '#90A4AE30',
    'inputOption.activeBorder': '#90A4AE30',
    'inputValidation.errorBorder': '#E53935',
    'inputValidation.infoBorder': '#6182B8',
    'inputValidation.warningBorder': '#E2931D',
    'list.activeSelectionBackground': '#FAFAFA',
    'list.activeSelectionForeground': '#80CBC4',
    'list.dropBackground': '#E5393580',
    'list.focusBackground': '#90A4AE20',
    'list.focusForeground': '#90A4AE',
    'list.highlightForeground': '#80CBC4',
    'list.hoverBackground': '#FAFAFA',
    'list.hoverForeground': '#B1C7D3',
    'list.inactiveSelectionBackground': '#CCD7DA50',
    'list.inactiveSelectionForeground': '#80CBC4',
    'listFilterWidget.background': '#CCD7DA50',
    'listFilterWidget.noMatchesOutline': '#CCD7DA50',
    'listFilterWidget.outline': '#CCD7DA50',
    'menu.background': '#FAFAFA',
    'menu.foreground': '#90A4AE',
    'menu.selectionBackground': '#CCD7DA50',
    'menu.selectionBorder': '#CCD7DA50',
    'menu.selectionForeground': '#80CBC4',
    'menu.separatorBackground': '#90A4AE',
    'menubar.selectionBackground': '#CCD7DA50',
    'menubar.selectionBorder': '#CCD7DA50',
    'menubar.selectionForeground': '#80CBC4',
    'notebook.focusedCellBorder': '#80CBC4',
    'notebook.inactiveFocusedCellBorder': '#80CBC450',
    'notificationLink.foreground': '#80CBC4',
    'notifications.background': '#FAFAFA',
    'notifications.foreground': '#90A4AE',
    'panel.background': '#FAFAFA',
    'panel.border': '#FAFAFA60',
    'panel.dropBackground': '#90A4AE',
    'panelTitle.activeBorder': '#80CBC4',
    'panelTitle.activeForeground': '#000000',
    'panelTitle.inactiveForeground': '#90A4AE',
    'peekView.border': '#00000020',
    'peekViewEditor.background': '#90A4AE05',
    'peekViewEditor.matchHighlightBackground': '#80CBC440',
    'peekViewEditorGutter.background': '#90A4AE05',
    'peekViewResult.background': '#90A4AE05',
    'peekViewResult.matchHighlightBackground': '#80CBC440',
    'peekViewResult.selectionBackground': '#758a9570',
    'peekViewTitle.background': '#90A4AE05',
    'peekViewTitleDescription.foreground': '#90A4AE60',
    'pickerGroup.border': '#FFFFFF1a',
    'pickerGroup.foreground': '#80CBC4',
    'progressBar.background': '#80CBC4',
    'quickInput.background': '#FAFAFA',
    'quickInput.foreground': '#758a95',
    'quickInput.list.focusBackground': '#90A4AE20',
    'sash.hoverBorder': '#80CBC450',
    'scrollbar.shadow': '#00000020',
    'scrollbarSlider.activeBackground': '#80CBC4',
    'scrollbarSlider.background': '#90A4AE20',
    'scrollbarSlider.hoverBackground': '#90A4AE10',
    'selection.background': '#CCD7DA80',
    'settings.checkboxBackground': '#FAFAFA',
    'settings.checkboxForeground': '#90A4AE',
    'settings.dropdownBackground': '#FAFAFA',
    'settings.dropdownForeground': '#90A4AE',
    'settings.headerForeground': '#80CBC4',
    'settings.modifiedItemIndicator': '#80CBC4',
    'settings.numberInputBackground': '#FAFAFA',
    'settings.numberInputForeground': '#90A4AE',
    'settings.textInputBackground': '#FAFAFA',
    'settings.textInputForeground': '#90A4AE',
    'sideBar.background': '#FAFAFA',
    'sideBar.border': '#FAFAFA60',
    'sideBar.foreground': '#758a95',
    'sideBarSectionHeader.background': '#FAFAFA',
    'sideBarSectionHeader.border': '#FAFAFA60',
    'sideBarTitle.foreground': '#90A4AE',
    'statusBar.background': '#FAFAFA',
    'statusBar.border': '#FAFAFA60',
    'statusBar.debuggingBackground': '#9C3EDA',
    'statusBar.debuggingForeground': '#FFFFFF',
    'statusBar.foreground': '#7E939E',
    'statusBar.noFolderBackground': '#FAFAFA',
    'statusBarItem.activeBackground': '#E5393580',
    'statusBarItem.hoverBackground': '#90A4AE20',
    'statusBarItem.remoteBackground': '#80CBC4',
    'statusBarItem.remoteForeground': '#000000',
    'tab.activeBackground': '#FAFAFA',
    'tab.activeBorder': '#80CBC4',
    'tab.activeForeground': '#000000',
    'tab.activeModifiedBorder': '#758a95',
    'tab.border': '#FAFAFA',
    'tab.inactiveBackground': '#FAFAFA',
    'tab.inactiveForeground': '#758a95',
    'tab.inactiveModifiedBorder': '#89221f',
    'tab.unfocusedActiveBorder': '#90A4AE',
    'tab.unfocusedActiveForeground': '#90A4AE',
    'tab.unfocusedActiveModifiedBorder': '#b72d2a',
    'tab.unfocusedInactiveModifiedBorder': '#89221f',
    'terminal.ansiBlack': '#000000',
    'terminal.ansiBlue': '#6182B8',
    'terminal.ansiBrightBlack': '#90A4AE',
    'terminal.ansiBrightBlue': '#6182B8',
    'terminal.ansiBrightCyan': '#39ADB5',
    'terminal.ansiBrightGreen': '#91B859',
    'terminal.ansiBrightMagenta': '#9C3EDA',
    'terminal.ansiBrightRed': '#E53935',
    'terminal.ansiBrightWhite': '#FFFFFF',
    'terminal.ansiBrightYellow': '#E2931D',
    'terminal.ansiCyan': '#39ADB5',
    'terminal.ansiGreen': '#91B859',
    'terminal.ansiMagenta': '#9C3EDA',
    'terminal.ansiRed': '#E53935',
    'terminal.ansiWhite': '#FFFFFF',
    'terminal.ansiYellow': '#E2931D',
    'terminalCursor.background': '#000000',
    'terminalCursor.foreground': '#E2931D',
    'textLink.activeForeground': '#90A4AE',
    'textLink.foreground': '#80CBC4',
    'titleBar.activeBackground': '#FAFAFA',
    'titleBar.activeForeground': '#90A4AE',
    'titleBar.border': '#FAFAFA60',
    'titleBar.inactiveBackground': '#FAFAFA',
    'titleBar.inactiveForeground': '#758a95',
    'tree.indentGuidesStroke': '#B0BEC5',
    'widget.shadow': '#00000020',
  },
  rules: [
    {
      token: 'string',
      foreground: '91B859',
    },
    {
      token: 'punctuation, constant.other.symbol',
      foreground: '39ADB5',
    },
    {
      token:
        'constant.character.escape, text.html constant.character.entity.named',
      foreground: '90A4AE',
    },
    {
      token: 'constant.language.boolean',
      foreground: 'FF5370',
    },
    {
      token: 'constant.numeric',
      foreground: 'F76D47',
    },
    {
      token:
        'variable, variable.parameter, support.variable, variable.language, support.constant, meta.definition.variable entity.name.function, meta.function-call.arguments',
      foreground: '90A4AE',
    },
    {
      token: 'keyword.other',
      foreground: 'F76D47',
    },
    {
      token:
        'keyword, modifier, variable.language.this, support.type.object, constant.language',
      foreground: '39ADB5',
    },
    {
      token: 'entity.name.function, support.function',
      foreground: '6182B8',
    },
    {
      token: 'storage.type, storage.modifier, storage.control',
      foreground: '9C3EDA',
    },
    {
      token: 'support.module, support.node',
      foreground: 'E53935',
    },
    {
      token: 'support.type, constant.other.key',
      foreground: 'E2931D',
    },
    {
      token: 'entity.name.type, entity.other.inherited-class, entity.other',
      foreground: 'E2931D',
    },
    {
      token: 'comment',
      foreground: '90A4AE',
    },
    {
      token: 'comment punctuation.definition.comment, string.quoted.docstring',
      foreground: '90A4AE',
    },
    {
      token: 'punctuation',
      foreground: '39ADB5',
    },
    {
      token:
        'entity.name, entity.name.type.class, support.type, support.class, meta.use',
      foreground: 'E2931D',
    },
    {
      token:
        'variable.object.property, meta.field.declaration entity.name.function',
      foreground: 'E53935',
    },
    {
      token: 'meta.definition.method entity.name.function',
      foreground: 'E53935',
    },
    {
      token: 'meta.function entity.name.function',
      foreground: '6182B8',
    },
    {
      token:
        'template.expression.begin, template.expression.end, punctuation.definition.template-expression.begin, punctuation.definition.template-expression.end',
      foreground: '39ADB5',
    },
    {
      token: 'meta.embedded, source.groovy.embedded, meta.template.expression',
      foreground: '90A4AE',
    },
    {
      token: 'entity.name.tag.yaml',
      foreground: 'E53935',
    },
    {
      token:
        'meta.object-literal.key, meta.object-literal.key string, support.type.property-name.json',
      foreground: 'E53935',
    },
    {
      token: 'constant.language.json',
      foreground: '39ADB5',
    },
    {
      token: 'entity.other.attribute-name.class',
      foreground: 'E2931D',
    },
    {
      token: 'entity.other.attribute-name.id',
      foreground: 'F76D47',
    },
    {
      token: 'source.css entity.name.tag',
      foreground: 'E2931D',
    },
    {
      token: 'support.type.property-name.css',
      foreground: '8796B0',
    },
    {
      token: 'meta.tag, punctuation.definition.tag',
      foreground: '39ADB5',
    },
    {
      token: 'entity.name.tag',
      foreground: 'E53935',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: '9C3EDA',
    },
    {
      token: 'punctuation.definition.entity.html',
      foreground: '90A4AE',
    },
    {
      token: 'markup.heading',
      foreground: '39ADB5',
    },
    {
      token: 'text.html.markdown meta.link.inline, meta.link.reference',
      foreground: 'E53935',
    },
    {
      token: 'text.html.markdown beginning.punctuation.definition.list',
      foreground: '39ADB5',
    },
    {
      token: 'markup.italic',
      foreground: 'E53935',
    },
    {
      token: 'markup.bold',
      foreground: 'E53935',
    },
    {
      token: 'markup.bold markup.italic, markup.italic markup.bold',
      foreground: 'E53935',
    },
    {
      token:
        'markup.fenced_code.block.markdown punctuation.definition.markdown',
      foreground: '91B859',
    },
    {
      token: 'markup.inline.raw.string.markdown',
      foreground: '91B859',
    },
    {
      token: 'keyword.other.definition.ini',
      foreground: 'E53935',
    },
    {
      token: 'entity.name.section.group-title.ini',
      foreground: '39ADB5',
    },
    {
      token: 'source.cs meta.class.identifier storage.type',
      foreground: 'E2931D',
    },
    {
      token: 'source.cs meta.method.identifier entity.name.function',
      foreground: 'E53935',
    },
    {
      token:
        'source.cs meta.method-call meta.method, source.cs entity.name.function',
      foreground: '6182B8',
    },
    {
      token: 'source.cs storage.type',
      foreground: 'E2931D',
    },
    {
      token: 'source.cs meta.method.return-type',
      foreground: 'E2931D',
    },
    {
      token: 'source.cs meta.preprocessor',
      foreground: '90A4AE',
    },
    {
      token: 'source.cs entity.name.type.namespace',
      foreground: '90A4AE',
    },
    {
      token: 'meta.jsx.children, SXNested',
      foreground: '90A4AE',
    },
    {
      token: 'support.class.component',
      foreground: 'E2931D',
    },
    {
      token: 'source.cpp meta.block variable.other',
      foreground: '90A4AE',
    },
    {
      token: 'source.python meta.member.access.python',
      foreground: 'E53935',
    },
    {
      token:
        'source.python meta.function-call.python, meta.function-call.arguments',
      foreground: '6182B8',
    },
    {
      token: 'meta.block',
      foreground: 'E53935',
    },
    {
      token: 'entity.name.function.call',
      foreground: '6182B8',
    },
    {
      token:
        'source.php support.other.namespace, source.php meta.use support.class',
      foreground: '90A4AE',
    },
    {
      token: 'constant.keyword',
      foreground: '39ADB5',
    },
    {
      token: 'entity.name.function',
      foreground: '6182B8',
    },
    {
      token: 'constant.other.placeholder',
      foreground: 'E53935',
    },
    {
      token: 'markup.deleted',
      foreground: 'E53935',
    },
    {
      token: 'markup.inserted',
      foreground: '91B859',
    },
    {
      token: 'keyword.control',
      foreground: '39ADB5',
    },
    {
      token: 'variable.parameter.function.language.special.self.python',
      foreground: 'E53935',
    },
    {
      token: 'constant.character.format.placeholder.other.python',
      foreground: 'F76D47',
    },
    {
      token: 'markup.quote',
      foreground: '39ADB5',
    },
    {
      token: 'markup.fenced_code.block',
      foreground: '90A4AE90',
    },
    {
      token: 'punctuation.definition.quote',
      foreground: 'FF5370',
    },
    {
      token: 'meta.structure.dictionary.json support.type.property-name.json',
      foreground: '9C3EDA',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: 'E2931D',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: 'F76D47',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: 'E53935',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: '916b53',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: '6182B8',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: 'FF5370',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: '9C3EDA',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: '91B859',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
