import * as monaco from 'monaco-editor';

export default {
  base: 'vs',
  inherit: false,
  colors: {
    'activityBar.background': '#f6f6f6',
    'activityBar.foreground': '#9E9E9E',
    'activityBarBadge.background': '#616161',
    'badge.background': '#E0E0E0',
    'badge.foreground': '#616161',
    'button.background': '#757575',
    'button.hoverBackground': '#616161',
    'debugIcon.breakpointCurrentStackframeForeground': '#1976D2',
    'debugIcon.breakpointDisabledForeground': '#848484',
    'debugIcon.breakpointForeground': '#D32F2F',
    'debugIcon.breakpointStackframeForeground': '#1976D2',
    'debugIcon.continueForeground': '#6f42c1',
    'debugIcon.disconnectForeground': '#6f42c1',
    'debugIcon.pauseForeground': '#6f42c1',
    'debugIcon.restartForeground': '#1976D2',
    'debugIcon.startForeground': '#1976D2',
    'debugIcon.stepBackForeground': '#6f42c1',
    'debugIcon.stepIntoForeground': '#6f42c1',
    'debugIcon.stepOutForeground': '#6f42c1',
    'debugIcon.stepOverForeground': '#6f42c1',
    'debugIcon.stopForeground': '#1976D2',
    'diffEditor.insertedTextBackground': '#b7e7a44b',
    'diffEditor.removedTextBackground': '#e597af52',
    'editor.background': '#ffffff',
    'editor.foreground': '#212121',
    'editor.lineHighlightBorder': '#f2f2f2',
    'editorBracketMatch.background': '#E7F3FF',
    'editorBracketMatch.border': '#c8e1ff',
    'editorGroupHeader.tabsBackground': '#f6f6f6',
    'editorGroupHeader.tabsBorder': '#ffffff',
    'editorIndentGuide.background': '#EEEEEE',
    'editorLineNumber.activeForeground': '#757575',
    'editorLineNumber.foreground': '#CCCCCC',
    'editorSuggestWidget.background': '#F3F3F3',
    'extensionButton.prominentBackground': '#000000AA',
    'extensionButton.prominentHoverBackground': '#000000BB',
    focusBorder: '#D0D0D0',
    foreground: '#757575',
    'gitDecoration.ignoredResourceForeground': '#AAAAAA',
    'input.border': '#E9E9E9',
    'inputOption.activeBackground': '#EDEDED',
    'list.activeSelectionBackground': '#EEEEEE',
    'list.activeSelectionForeground': '#212121',
    'list.focusBackground': '#dddddd',
    'list.focusForeground': '#212121',
    'list.highlightForeground': '#212121',
    'list.inactiveSelectionBackground': '#E0E0E0',
    'list.inactiveSelectionForeground': '#212121',
    'panel.background': '#ffffff',
    'panel.border': '#f4f4f4',
    'panelTitle.activeBorder': '#ffffff',
    'panelTitle.inactiveForeground': '#BDBDBD',
    'peekView.border': '#E0E0E0',
    'peekViewEditor.background': '#f8f8f8',
    'pickerGroup.foreground': '#000000',
    'progressBar.background': '#000000',
    'scrollbar.shadow': '#FFFFFF',
    'sideBar.background': '#f6f6f6',
    'sideBar.border': '#f6f6f6',
    'sideBarSectionHeader.background': '#EEEEEE',
    'sideBarTitle.foreground': '#999999',
    'statusBar.background': '#f6f6f6',
    'statusBar.border': '#f6f6f6',
    'statusBar.debuggingBackground': '#f6f6f6',
    'statusBar.foreground': '#7E7E7E',
    'statusBar.noFolderBackground': '#f6f6f6',
    'statusBarItem.prominentBackground': '#0000001a',
    'statusBarItem.remoteBackground': '#f6f6f600',
    'statusBarItem.remoteForeground': '#7E7E7E',
    'symbolIcon.classForeground': '#dd8500',
    'symbolIcon.constructorForeground': '#6f42c1',
    'symbolIcon.enumeratorForeground': '#dd8500',
    'symbolIcon.enumeratorMemberForeground': '#1976D2',
    'symbolIcon.eventForeground': '#dd8500',
    'symbolIcon.fieldForeground': '#1976D2',
    'symbolIcon.functionForeground': '#6f42c1',
    'symbolIcon.interfaceForeground': '#1976D2',
    'symbolIcon.methodForeground': '#6f42c1',
    'symbolIcon.variableForeground': '#1976D2',
    'tab.activeBorder': '#FFFFFF',
    'tab.activeForeground': '#424242',
    'tab.border': '#f6f6f6',
    'tab.inactiveBackground': '#f6f6f6',
    'tab.inactiveForeground': '#BDBDBD',
    'tab.unfocusedActiveBorder': '#ffffff',
    'terminal.ansiBlack': '#333333',
    'terminal.ansiBlue': '#e0e0e0',
    'terminal.ansiBrightBlack': '#a1a1a1',
    'terminal.ansiBrightBlue': '#6871ff',
    'terminal.ansiBrightCyan': '#57d9ad',
    'terminal.ansiBrightGreen': '#a3d900',
    'terminal.ansiBrightMagenta': '#a37acc',
    'terminal.ansiBrightRed': '#d6656a',
    'terminal.ansiBrightWhite': '#7E7E7E',
    'terminal.ansiBrightYellow': '#e7c547',
    'terminal.ansiCyan': '#4dbf99',
    'terminal.ansiGreen': '#77cc00',
    'terminal.ansiMagenta': '#9966cc',
    'terminal.ansiRed': '#D32F2F',
    'terminal.ansiWhite': '#c7c7c7',
    'terminal.ansiYellow': '#f29718',
    'terminal.background': '#ffffff',
    'textLink.activeForeground': '#000000',
    'textLink.foreground': '#000000',
    'titleBar.activeBackground': '#f6f6f6',
    'titleBar.border': '#FFFFFF00',
    'titleBar.inactiveBackground': '#f6f6f6',
  },
  rules: [
    {
      token: 'keyword.operator.accessor',
      foreground: '24292eff',
    },
    {
      token: 'meta.group.braces.round.function.arguments',
      foreground: '24292eff',
    },
    {
      token: 'meta.template.expression',
      foreground: '24292eff',
    },
    {
      token: 'markup.fenced_code meta.embedded.block',
      foreground: '24292eff',
    },
    {
      token: 'meta.link.inline.markdown',
      foreground: '1976D2',
    },
    {
      token: 'string',
      foreground: '2b5581',
    },
    {
      token: 'markup.fenced_code',
      foreground: '2b5581',
    },
    {
      token: 'markup.inline',
      foreground: '2b5581',
    },
    {
      token: 'comment',
      foreground: 'c2c3c5',
    },
    {
      token: 'string.quoted.docstring.multi',
      foreground: 'c2c3c5',
    },
    {
      token: 'constant.numeric',
      foreground: '1976D2',
    },
    {
      token: 'constant.language',
      foreground: '1976D2',
    },
    {
      token: 'constant.other.placeholder',
      foreground: '1976D2',
    },
    {
      token: 'constant.character.format.placeholder',
      foreground: '1976D2',
    },
    {
      token: 'variable.language.this',
      foreground: '1976D2',
    },
    {
      token: 'variable.other.object',
      foreground: '1976D2',
    },
    {
      token: 'variable.other.class',
      foreground: '1976D2',
    },
    {
      token: 'variable.other.constant',
      foreground: '1976D2',
    },
    {
      token: 'meta.property-name',
      foreground: '1976D2',
    },
    {
      token: 'meta.property-value',
      foreground: '1976D2',
    },
    {
      token: 'support',
      foreground: '1976D2',
    },
    {
      token: 'keyword',
      foreground: 'D32F2F',
    },
    {
      token: 'storage.modifier',
      foreground: 'D32F2F',
    },
    {
      token: 'storage.type',
      foreground: 'D32F2F',
    },
    {
      token: 'storage.control.clojure',
      foreground: 'D32F2F',
    },
    {
      token: 'entity.name.function.clojure',
      foreground: 'D32F2F',
    },
    {
      token: 'entity.name.tag.yaml',
      foreground: 'D32F2F',
    },
    {
      token: 'support.function.node',
      foreground: 'D32F2F',
    },
    {
      token: 'support.type.property-name.json',
      foreground: 'D32F2F',
    },
    {
      token: 'punctuation.separator.key-value',
      foreground: 'D32F2F',
    },
    {
      token: 'punctuation.definition.template-expression',
      foreground: 'D32F2F',
    },
    {
      token: 'variable.parameter.function',
      foreground: 'FF9800',
    },
    {
      token: 'support.function',
      foreground: '6f42c1',
    },
    {
      token: 'entity.name.type',
      foreground: '6f42c1',
    },
    {
      token: 'entity.other.inherited-class',
      foreground: '6f42c1',
    },
    {
      token: 'meta.function-call',
      foreground: '6f42c1',
    },
    {
      token: 'meta.instance.constructor',
      foreground: '6f42c1',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: '6f42c1',
    },
    {
      token: 'entity.name.function',
      foreground: '6f42c1',
    },
    {
      token: 'constant.keyword.clojure',
      foreground: '6f42c1',
    },
    {
      token: 'entity.name.tag',
      foreground: '22863a',
    },
    {
      token: 'string.quoted',
      foreground: '22863a',
    },
    {
      token: 'string.regexp',
      foreground: '22863a',
    },
    {
      token: 'string.interpolated',
      foreground: '22863a',
    },
    {
      token: 'string.template',
      foreground: '22863a',
    },
    {
      token: 'string.unquoted.plain.out.yaml',
      foreground: '22863a',
    },
    {
      token: 'keyword.other.template',
      foreground: '22863a',
    },
    {
      token: 'token.info-token',
      foreground: '316bcd',
    },
    {
      token: 'token.warn-token',
      foreground: 'cd9731',
    },
    {
      token: 'token.error-token',
      foreground: 'cd3131',
    },
    {
      token: 'token.debug-token',
      foreground: '800080',
    },
    {
      token: 'strong',
      foreground: '6f42c1',
    },
    {
      token: 'markup.heading.markdown',
      foreground: '6f42c1',
    },
    {
      token: 'markup.bold.markdown',
      foreground: '6f42c1',
    },
    {
      token: 'punctuation.definition.arguments',
      foreground: '212121',
    },
    {
      token: 'punctuation.definition.dict',
      foreground: '212121',
    },
    {
      token: 'punctuation.separator',
      foreground: '212121',
    },
    {
      token: 'meta.function-call.arguments',
      foreground: '212121',
    },
    {
      token: 'markup.underline.link',
      foreground: '22863a',
    },
    {
      token: 'punctuation.definition.metadata.markdown',
      foreground: '22863a',
    },
    {
      token: 'beginning.punctuation.definition.list.markdown',
      foreground: '6f42c1',
    },
    {
      token: 'punctuation.definition.string.begin.markdown',
      foreground: 'd32f2f',
    },
    {
      token: 'punctuation.definition.string.end.markdown',
      foreground: 'd32f2f',
    },
    {
      token: 'string.other.link.title.markdown',
      foreground: 'd32f2f',
    },
    {
      token: 'string.other.link.description.markdown',
      foreground: 'd32f2f',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
