import * as monaco from 'monaco-editor';

export default {
  base: 'vs-dark',
  inherit: false,
  colors: {
    'activityBar.activeBorder': '#f9826c',
    'activityBar.background': '#24292e',
    'activityBar.border': '#1b1f23',
    'activityBar.foreground': '#e1e4e8',
    'activityBar.inactiveForeground': '#6a737d',
    'activityBarBadge.background': '#0366d6',
    'activityBarBadge.foreground': '#ffffff',
    'badge.background': '#044289',
    'badge.foreground': '#c8e1ff',
    'breadcrumb.activeSelectionForeground': '#d1d5da',
    'breadcrumb.focusForeground': '#e1e4e8',
    'breadcrumb.foreground': '#959da5',
    'breadcrumbPicker.background': '#2b3036',
    'button.background': '#176f2c',
    'button.foreground': '#dcffe4',
    'button.hoverBackground': '#22863a',
    'button.secondaryBackground': '#444d56',
    'button.secondaryForeground': '#ffffff',
    'button.secondaryHoverBackground': '#586069',
    'checkbox.background': '#444d56',
    'checkbox.border': '#1b1f23',
    'debugToolBar.background': '#2b3036',
    descriptionForeground: '#959da5',
    'diffEditor.insertedTextBackground': '#28a74530',
    'diffEditor.removedTextBackground': '#d73a4930',
    'dropdown.background': '#2f363d',
    'dropdown.border': '#1b1f23',
    'dropdown.foreground': '#e1e4e8',
    'dropdown.listBackground': '#24292e',
    'editor.background': '#24292e',
    'editor.findMatchBackground': '#ffd33d44',
    'editor.findMatchHighlightBackground': '#ffd33d22',
    'editor.focusedStackFrameHighlightBackground': '#2b6a3033',
    'editor.foldBackground': '#58606915',
    'editor.foreground': '#e1e4e8',
    'editor.inactiveSelectionBackground': '#3392FF22',
    'editor.lineHighlightBackground': '#2b3036',
    'editor.linkedEditingBackground': '#3392FF22',
    'editor.selectionBackground': '#3392FF44',
    'editor.selectionHighlightBackground': '#17E5E633',
    'editor.selectionHighlightBorder': '#17E5E600',
    'editor.stackFrameHighlightBackground': '#C6902625',
    'editor.wordHighlightBackground': '#17E5E600',
    'editor.wordHighlightBorder': '#17E5E699',
    'editor.wordHighlightStrongBackground': '#17E5E600',
    'editor.wordHighlightStrongBorder': '#17E5E666',
    'editorBracketHighlight.foreground1': '#79b8ff',
    'editorBracketHighlight.foreground2': '#ffab70',
    'editorBracketHighlight.foreground3': '#b392f0',
    'editorBracketHighlight.foreground4': '#79b8ff',
    'editorBracketHighlight.foreground5': '#ffab70',
    'editorBracketHighlight.foreground6': '#b392f0',
    'editorBracketMatch.background': '#17E5E650',
    'editorBracketMatch.border': '#17E5E600',
    'editorCursor.foreground': '#c8e1ff',
    'editorError.foreground': '#f97583',
    'editorGroup.border': '#1b1f23',
    'editorGroupHeader.tabsBackground': '#1f2428',
    'editorGroupHeader.tabsBorder': '#1b1f23',
    'editorGutter.addedBackground': '#28a745',
    'editorGutter.deletedBackground': '#ea4a5a',
    'editorGutter.modifiedBackground': '#2188ff',
    'editorIndentGuide.activeBackground': '#444d56',
    'editorIndentGuide.background': '#2f363d',
    'editorLineNumber.activeForeground': '#e1e4e8',
    'editorLineNumber.foreground': '#444d56',
    'editorOverviewRuler.border': '#1b1f23',
    'editorWarning.foreground': '#ffea7f',
    'editorWhitespace.foreground': '#444d56',
    'editorWidget.background': '#1f2428',
    errorForeground: '#f97583',
    focusBorder: '#005cc5',
    foreground: '#d1d5da',
    'gitDecoration.addedResourceForeground': '#34d058',
    'gitDecoration.conflictingResourceForeground': '#ffab70',
    'gitDecoration.deletedResourceForeground': '#ea4a5a',
    'gitDecoration.ignoredResourceForeground': '#6a737d',
    'gitDecoration.modifiedResourceForeground': '#79b8ff',
    'gitDecoration.submoduleResourceForeground': '#6a737d',
    'gitDecoration.untrackedResourceForeground': '#34d058',
    'input.background': '#2f363d',
    'input.border': '#1b1f23',
    'input.foreground': '#e1e4e8',
    'input.placeholderForeground': '#959da5',
    'list.activeSelectionBackground': '#39414a',
    'list.activeSelectionForeground': '#e1e4e8',
    'list.focusBackground': '#044289',
    'list.hoverBackground': '#282e34',
    'list.hoverForeground': '#e1e4e8',
    'list.inactiveFocusBackground': '#1d2d3e',
    'list.inactiveSelectionBackground': '#282e34',
    'list.inactiveSelectionForeground': '#e1e4e8',
    'notificationCenterHeader.background': '#24292e',
    'notificationCenterHeader.foreground': '#959da5',
    'notifications.background': '#2f363d',
    'notifications.border': '#1b1f23',
    'notifications.foreground': '#e1e4e8',
    'notificationsErrorIcon.foreground': '#ea4a5a',
    'notificationsInfoIcon.foreground': '#79b8ff',
    'notificationsWarningIcon.foreground': '#ffab70',
    'panel.background': '#1f2428',
    'panel.border': '#1b1f23',
    'panelInput.border': '#2f363d',
    'panelTitle.activeBorder': '#f9826c',
    'panelTitle.activeForeground': '#e1e4e8',
    'panelTitle.inactiveForeground': '#959da5',
    'peekViewEditor.background': '#1f242888',
    'peekViewEditor.matchHighlightBackground': '#ffd33d33',
    'peekViewResult.background': '#1f2428',
    'peekViewResult.matchHighlightBackground': '#ffd33d33',
    'pickerGroup.border': '#444d56',
    'pickerGroup.foreground': '#e1e4e8',
    'progressBar.background': '#0366d6',
    'quickInput.background': '#24292e',
    'quickInput.foreground': '#e1e4e8',
    'scrollbar.shadow': '#00000088',
    'scrollbarSlider.activeBackground': '#6a737d88',
    'scrollbarSlider.background': '#6a737d33',
    'scrollbarSlider.hoverBackground': '#6a737d44',
    'settings.headerForeground': '#e1e4e8',
    'settings.modifiedItemIndicator': '#0366d6',
    'sideBar.background': '#1f2428',
    'sideBar.border': '#1b1f23',
    'sideBar.foreground': '#d1d5da',
    'sideBarSectionHeader.background': '#1f2428',
    'sideBarSectionHeader.border': '#1b1f23',
    'sideBarSectionHeader.foreground': '#e1e4e8',
    'sideBarTitle.foreground': '#e1e4e8',
    'statusBar.background': '#24292e',
    'statusBar.border': '#1b1f23',
    'statusBar.debuggingBackground': '#931c06',
    'statusBar.debuggingForeground': '#ffffff',
    'statusBar.foreground': '#d1d5da',
    'statusBar.noFolderBackground': '#24292e',
    'statusBarItem.prominentBackground': '#282e34',
    'statusBarItem.remoteBackground': '#24292e',
    'statusBarItem.remoteForeground': '#d1d5da',
    'tab.activeBackground': '#24292e',
    'tab.activeBorder': '#24292e',
    'tab.activeBorderTop': '#f9826c',
    'tab.activeForeground': '#e1e4e8',
    'tab.border': '#1b1f23',
    'tab.hoverBackground': '#24292e',
    'tab.inactiveBackground': '#1f2428',
    'tab.inactiveForeground': '#959da5',
    'tab.unfocusedActiveBorder': '#24292e',
    'tab.unfocusedActiveBorderTop': '#1b1f23',
    'tab.unfocusedHoverBackground': '#24292e',
    'terminal.ansiBlack': '#586069',
    'terminal.ansiBlue': '#2188ff',
    'terminal.ansiBrightBlack': '#959da5',
    'terminal.ansiBrightBlue': '#79b8ff',
    'terminal.ansiBrightCyan': '#56d4dd',
    'terminal.ansiBrightGreen': '#85e89d',
    'terminal.ansiBrightMagenta': '#b392f0',
    'terminal.ansiBrightRed': '#f97583',
    'terminal.ansiBrightWhite': '#fafbfc',
    'terminal.ansiBrightYellow': '#ffea7f',
    'terminal.ansiCyan': '#39c5cf',
    'terminal.ansiGreen': '#34d058',
    'terminal.ansiMagenta': '#b392f0',
    'terminal.ansiRed': '#ea4a5a',
    'terminal.ansiWhite': '#d1d5da',
    'terminal.ansiYellow': '#ffea7f',
    'terminal.foreground': '#d1d5da',
    'terminal.tab.activeBorder': '#f9826c',
    'terminalCursor.background': '#586069',
    'terminalCursor.foreground': '#79b8ff',
    'textBlockQuote.background': '#24292e',
    'textBlockQuote.border': '#444d56',
    'textCodeBlock.background': '#2f363d',
    'textLink.activeForeground': '#c8e1ff',
    'textLink.foreground': '#79b8ff',
    'textPreformat.foreground': '#d1d5da',
    'textSeparator.foreground': '#586069',
    'titleBar.activeBackground': '#24292e',
    'titleBar.activeForeground': '#e1e4e8',
    'titleBar.border': '#1b1f23',
    'titleBar.inactiveBackground': '#1f2428',
    'titleBar.inactiveForeground': '#959da5',
    'tree.indentGuidesStroke': '#2f363d',
    'welcomePage.buttonBackground': '#2f363d',
    'welcomePage.buttonHoverBackground': '#444d56',
  },
  rules: [
    {
      token: 'comment',
      foreground: '6a737d',
    },
    {
      token: 'punctuation.definition.comment',
      foreground: '6a737d',
    },
    {
      token: 'string.comment',
      foreground: '6a737d',
    },
    {
      token: 'constant',
      foreground: '79b8ff',
    },
    {
      token: 'entity.name.constant',
      foreground: '79b8ff',
    },
    {
      token: 'variable.other.constant',
      foreground: '79b8ff',
    },
    {
      token: 'variable.other.enummember',
      foreground: '79b8ff',
    },
    {
      token: 'variable.language',
      foreground: '79b8ff',
    },
    {
      token: 'entity',
      foreground: 'b392f0',
    },
    {
      token: 'entity.name',
      foreground: 'b392f0',
    },
    {
      token: 'variable.parameter.function',
      foreground: 'e1e4e8',
    },
    {
      token: 'entity.name.tag',
      foreground: '85e89d',
    },
    {
      token: 'keyword',
      foreground: 'f97583',
    },
    {
      token: 'storage',
      foreground: 'f97583',
    },
    {
      token: 'storage.type',
      foreground: 'f97583',
    },
    {
      token: 'storage.modifier.package',
      foreground: 'e1e4e8',
    },
    {
      token: 'storage.modifier.import',
      foreground: 'e1e4e8',
    },
    {
      token: 'storage.type.java',
      foreground: 'e1e4e8',
    },
    {
      token: 'string',
      foreground: '9ecbff',
    },
    {
      token: 'punctuation.definition.string',
      foreground: '9ecbff',
    },
    {
      token: 'string punctuation.section.embedded source',
      foreground: '9ecbff',
    },
    {
      token: 'support',
      foreground: '79b8ff',
    },
    {
      token: 'meta.property-name',
      foreground: '79b8ff',
    },
    {
      token: 'variable',
      foreground: 'ffab70',
    },
    {
      token: 'variable.other',
      foreground: 'e1e4e8',
    },
    {
      token: 'invalid.broken',
      foreground: 'fdaeb7',
    },
    {
      token: 'invalid.deprecated',
      foreground: 'fdaeb7',
    },
    {
      token: 'invalid.illegal',
      foreground: 'fdaeb7',
    },
    {
      token: 'invalid.unimplemented',
      foreground: 'fdaeb7',
    },
    {
      token: 'carriage-return',
      foreground: '24292e',
    },
    {
      token: 'message.error',
      foreground: 'fdaeb7',
    },
    {
      token: 'string variable',
      foreground: '79b8ff',
    },
    {
      token: 'source.regexp',
      foreground: 'dbedff',
    },
    {
      token: 'string.regexp',
      foreground: 'dbedff',
    },
    {
      token: 'string.regexp.character-class',
      foreground: 'dbedff',
    },
    {
      token: 'string.regexp constant.character.escape',
      foreground: 'dbedff',
    },
    {
      token: 'string.regexp source.ruby.embedded',
      foreground: 'dbedff',
    },
    {
      token: 'string.regexp string.regexp.arbitrary-repitition',
      foreground: 'dbedff',
    },
    {
      token: 'string.regexp constant.character.escape',
      foreground: '85e89d',
    },
    {
      token: 'support.constant',
      foreground: '79b8ff',
    },
    {
      token: 'support.variable',
      foreground: '79b8ff',
    },
    {
      token: 'meta.module-reference',
      foreground: '79b8ff',
    },
    {
      token: 'punctuation.definition.list.begin.markdown',
      foreground: 'ffab70',
    },
    {
      token: 'markup.heading',
      foreground: '79b8ff',
    },
    {
      token: 'markup.heading entity.name',
      foreground: '79b8ff',
    },
    {
      token: 'markup.quote',
      foreground: '85e89d',
    },
    {
      token: 'markup.italic',
      foreground: 'e1e4e8',
    },
    {
      token: 'markup.bold',
      foreground: 'e1e4e8',
    },
    {
      token: 'markup.inline.raw',
      foreground: '79b8ff',
    },
    {
      token: 'markup.deleted',
      foreground: 'fdaeb7',
    },
    {
      token: 'meta.diff.header.from-file',
      foreground: 'fdaeb7',
    },
    {
      token: 'punctuation.definition.deleted',
      foreground: 'fdaeb7',
    },
    {
      token: 'markup.inserted',
      foreground: '85e89d',
    },
    {
      token: 'meta.diff.header.to-file',
      foreground: '85e89d',
    },
    {
      token: 'punctuation.definition.inserted',
      foreground: '85e89d',
    },
    {
      token: 'markup.changed',
      foreground: 'ffab70',
    },
    {
      token: 'punctuation.definition.changed',
      foreground: 'ffab70',
    },
    {
      token: 'markup.ignored',
      foreground: '2f363d',
    },
    {
      token: 'markup.untracked',
      foreground: '2f363d',
    },
    {
      token: 'meta.diff.range',
      foreground: 'b392f0',
    },
    {
      token: 'meta.diff.header',
      foreground: '79b8ff',
    },
    {
      token: 'meta.separator',
      foreground: '79b8ff',
    },
    {
      token: 'meta.output',
      foreground: '79b8ff',
    },
    {
      token: 'brackethighlighter.tag',
      foreground: 'd1d5da',
    },
    {
      token: 'brackethighlighter.curly',
      foreground: 'd1d5da',
    },
    {
      token: 'brackethighlighter.round',
      foreground: 'd1d5da',
    },
    {
      token: 'brackethighlighter.square',
      foreground: 'd1d5da',
    },
    {
      token: 'brackethighlighter.angle',
      foreground: 'd1d5da',
    },
    {
      token: 'brackethighlighter.quote',
      foreground: 'd1d5da',
    },
    {
      token: 'brackethighlighter.unmatched',
      foreground: 'fdaeb7',
    },
    {
      token: 'constant.other.reference.link',
      foreground: 'dbedff',
    },
    {
      token: 'string.other.link',
      foreground: 'dbedff',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
