import * as monaco from 'monaco-editor';

export default {
  base: 'vs-dark',
  inherit: false,
  rules: [
    {
      token: 'comment',
      foreground: '8B949E',
    },
    {
      token: 'punctuation.definition.comment',
      foreground: '8B949E',
    },
    {
      token: 'string.comment',
      foreground: '8B949E',
    },
    {
      token: 'constant.other.placeholder',
      foreground: 'FF7B72',
    },
    {
      token: 'constant.character',
      foreground: 'FF7B72',
    },
    {
      token: 'constant',
      foreground: '79C0FF',
    },
    {
      token: 'entity.name.constant',
      foreground: '79C0FF',
    },
    {
      token: 'variable.other.constant',
      foreground: '79C0FF',
    },
    {
      token: 'variable.other.enummember',
      foreground: '79C0FF',
    },
    {
      token: 'variable.language',
      foreground: '79C0FF',
    },
    {
      token: 'entity',
      foreground: '79C0FF',
    },
    {
      token: 'entity.name',
      foreground: 'FFA657',
    },
    {
      token: 'meta.export.default',
      foreground: 'FFA657',
    },
    {
      token: 'meta.definition.variable',
      foreground: 'FFA657',
    },
    {
      token: 'variable.parameter.function',
      foreground: 'E6EDF3',
    },
    {
      token: 'meta.jsx.children',
      foreground: 'E6EDF3',
    },
    {
      token: 'meta.block',
      foreground: 'E6EDF3',
    },
    {
      token: 'meta.tag.attributes',
      foreground: 'E6EDF3',
    },
    {
      token: 'entity.name.constant',
      foreground: 'E6EDF3',
    },
    {
      token: 'meta.object.member',
      foreground: 'E6EDF3',
    },
    {
      token: 'meta.embedded.expression',
      foreground: 'E6EDF3',
    },
    {
      token: 'entity.name.function',
      foreground: 'D2A8FF',
    },
    {
      token: 'entity.name.tag',
      foreground: '7EE787',
    },
    {
      token: 'support.class.component',
      foreground: '7EE787',
    },
    {
      token: 'keyword',
      foreground: 'FF7B72',
    },
    {
      token: 'storage',
      foreground: 'FF7B72',
    },
    {
      token: 'storage.type',
      foreground: 'FF7B72',
    },
    {
      token: 'storage.modifier.package',
      foreground: 'E6EDF3',
    },
    {
      token: 'storage.modifier.import',
      foreground: 'E6EDF3',
    },
    {
      token: 'storage.type.java',
      foreground: 'E6EDF3',
    },
    {
      token: 'string',
      foreground: 'A5D6FF',
    },
    {
      token: 'string punctuation.section.embedded source',
      foreground: 'A5D6FF',
    },
    {
      token: 'support',
      foreground: '79C0FF',
    },
    {
      token: 'meta.property-name',
      foreground: '79C0FF',
    },
    {
      token: 'variable',
      foreground: 'FFA657',
    },
    {
      token: 'variable.other',
      foreground: 'E6EDF3',
    },
    {
      token: 'invalid.broken',
      foreground: 'FFA198',
      fontStyle: 'italic',
    },
    {
      token: 'invalid.deprecated',
      foreground: 'FFA198',
      fontStyle: 'italic',
    },
    {
      token: 'invalid.illegal',
      foreground: 'FFA198',
      fontStyle: 'italic',
    },
    {
      token: 'invalid.unimplemented',
      foreground: 'FFA198',
      fontStyle: 'italic',
    },
    {
      token: 'carriage-return',
      foreground: 'F0F6FC',
      fontStyle: 'italic underline',
    },
    {
      token: 'message.error',
      foreground: 'FFA198',
    },
    {
      token: 'string variable',
      foreground: '79C0FF',
    },
    {
      token: 'source.regexp',
      foreground: 'A5D6FF',
    },
    {
      token: 'string.regexp',
      foreground: 'A5D6FF',
    },
    {
      token: 'string.regexp.character-class',
      foreground: 'A5D6FF',
    },
    {
      token: 'string.regexp constant.character.escape',
      foreground: 'A5D6FF',
    },
    {
      token: 'string.regexp source.ruby.embedded',
      foreground: 'A5D6FF',
    },
    {
      token: 'string.regexp string.regexp.arbitrary-repitition',
      foreground: 'A5D6FF',
    },
    {
      token: 'string.regexp constant.character.escape',
      foreground: '7EE787',
      fontStyle: 'bold',
    },
    {
      token: 'support.constant',
      foreground: '79C0FF',
    },
    {
      token: 'support.variable',
      foreground: '79C0FF',
    },
    {
      token: 'support.type.property-name.json',
      foreground: '7EE787',
    },
    {
      token: 'meta.module-reference',
      foreground: '79C0FF',
    },
    {
      token: 'punctuation.definition.list.begin.markdown',
      foreground: 'FFA657',
    },
    {
      token: 'markup.heading',
      foreground: '79C0FF',
      fontStyle: 'bold',
    },
    {
      token: 'markup.heading entity.name',
      foreground: '79C0FF',
      fontStyle: 'bold',
    },
    {
      token: 'markup.quote',
      foreground: '7EE787',
    },
    {
      token: 'markup.italic',
      foreground: 'E6EDF3',
      fontStyle: 'italic',
    },
    {
      token: 'markup.bold',
      foreground: 'E6EDF3',
      fontStyle: 'bold',
    },
    {
      token: 'markup.underline',
      fontStyle: 'underline',
    },
    {
      token: 'markup.strikethrough',
      fontStyle: 'strikethrough',
    },
    {
      token: 'markup.inline.raw',
      foreground: '79C0FF',
    },
    {
      token: 'markup.deleted',
      foreground: 'FFA198',
    },
    {
      token: 'meta.diff.header.from-file',
      foreground: 'FFA198',
    },
    {
      token: 'punctuation.definition.deleted',
      foreground: 'FFA198',
    },
    {
      token: 'punctuation.section.embedded',
      foreground: 'FF7B72',
    },
    {
      token: 'markup.inserted',
      foreground: '7EE787',
    },
    {
      token: 'meta.diff.header.to-file',
      foreground: '7EE787',
    },
    {
      token: 'punctuation.definition.inserted',
      foreground: '7EE787',
    },
    {
      token: 'markup.changed',
      foreground: 'FFA657',
    },
    {
      token: 'punctuation.definition.changed',
      foreground: 'FFA657',
    },
    {
      token: 'markup.ignored',
      foreground: '161B22',
    },
    {
      token: 'markup.untracked',
      foreground: '161B22',
    },
    {
      token: 'meta.diff.range',
      foreground: 'D2A8FF',
      fontStyle: 'bold',
    },
    {
      token: 'meta.diff.header',
      foreground: '79C0FF',
    },
    {
      token: 'meta.separator',
      foreground: '79C0FF',
      fontStyle: 'bold',
    },
    {
      token: 'meta.output',
      foreground: '79C0FF',
    },
    {
      token: 'brackethighlighter.tag',
      foreground: '8B949E',
    },
    {
      token: 'brackethighlighter.curly',
      foreground: '8B949E',
    },
    {
      token: 'brackethighlighter.round',
      foreground: '8B949E',
    },
    {
      token: 'brackethighlighter.square',
      foreground: '8B949E',
    },
    {
      token: 'brackethighlighter.angle',
      foreground: '8B949E',
    },
    {
      token: 'brackethighlighter.quote',
      foreground: '8B949E',
    },
    {
      token: 'brackethighlighter.unmatched',
      foreground: 'FFA198',
    },
    {
      token: 'constant.other.reference.link',
      foreground: 'A5D6FF',
    },
    {
      token: 'string.other.link',
      foreground: 'A5D6FF',
    },
  ],
  colors: {
    focusBorder: '1F6FEB',
    foreground: 'E6EDF3',
    descriptionForeground: '7D8590',
    errorForeground: 'F85149',
    'textLink.foreground': '2F81F7',
    'textLink.activeForeground': '2F81F7',
    'textBlockQuote.background': '010409',
    'textBlockQuote.border': '30363D',
    'textCodeBlock.background': '6E768166',
    'textPreformat.foreground': '7D8590',
    'textSeparator.foreground': '21262D',
    'icon.foreground': '7D8590',
    'keybindingLabel.foreground': 'E6EDF3',
    'button.background': '238636',
    'button.foreground': 'FFFFFF',
    'button.hoverBackground': '2EA043',
    'button.secondaryBackground': '282E33',
    'button.secondaryForeground': 'C9D1D9',
    'button.secondaryHoverBackground': '30363D',
    'checkbox.background': '161B22',
    'checkbox.border': '30363D',
    'dropdown.background': '161B22',
    'dropdown.border': '30363D',
    'dropdown.foreground': 'E6EDF3',
    'dropdown.listBackground': '161B22',
    'input.background': '0D1117',
    'input.border': '30363D',
    'input.foreground': 'E6EDF3',
    'input.placeholderForeground': '6E7681',
    'badge.foreground': 'FFFFFF',
    'badge.background': '1F6FEB',
    'progressBar.background': '1F6FEB',
    'titleBar.activeForeground': '7D8590',
    'titleBar.activeBackground': '0D1117',
    'titleBar.inactiveForeground': '7D8590',
    'titleBar.inactiveBackground': '010409',
    'titleBar.border': '30363D',
    'activityBar.foreground': 'E6EDF3',
    'activityBar.inactiveForeground': '7D8590',
    'activityBar.background': '0D1117',
    'activityBarBadge.foreground': 'FFFFFF',
    'activityBarBadge.background': '1F6FEB',
    'activityBar.activeBorder': 'F78166',
    'activityBar.border': '30363D',
    'sideBar.foreground': 'E6EDF3',
    'sideBar.background': '010409',
    'sideBar.border': '30363D',
    'sideBarTitle.foreground': 'E6EDF3',
    'sideBarSectionHeader.foreground': 'E6EDF3',
    'sideBarSectionHeader.background': '010409',
    'sideBarSectionHeader.border': '30363D',
    'list.hoverForeground': 'E6EDF3',
    'list.inactiveSelectionForeground': 'E6EDF3',
    'list.activeSelectionForeground': 'E6EDF3',
    'list.hoverBackground': '6E76811A',
    'list.inactiveSelectionBackground': '6E768166',
    'list.activeSelectionBackground': '6E768166',
    'list.focusForeground': 'E6EDF3',
    'list.focusBackground': '388BFD26',
    'list.inactiveFocusBackground': '388BFD26',
    'list.highlightForeground': '2F81F7',
    'tree.indentGuidesStroke': '21262D',
    'notificationCenterHeader.foreground': '7D8590',
    'notificationCenterHeader.background': '161B22',
    'notifications.foreground': 'E6EDF3',
    'notifications.background': '161B22',
    'notifications.border': '30363D',
    'notificationsErrorIcon.foreground': 'F85149',
    'notificationsWarningIcon.foreground': 'D29922',
    'notificationsInfoIcon.foreground': '2F81F7',
    'pickerGroup.border': '30363D',
    'pickerGroup.foreground': '7D8590',
    'quickInput.background': '161B22',
    'quickInput.foreground': 'E6EDF3',
    'statusBar.foreground': '7D8590',
    'statusBar.background': '0D1117',
    'statusBar.border': '30363D',
    'statusBar.focusBorder': '1F6FEB80',
    'statusBar.noFolderBackground': '0D1117',
    'statusBar.debuggingForeground': 'FFFFFF',
    'statusBar.debuggingBackground': 'DA3633',
    'statusBarItem.prominentBackground': '6E768166',
    'statusBarItem.remoteForeground': 'E6EDF3',
    'statusBarItem.remoteBackground': '30363D',
    'statusBarItem.hoverBackground': 'E6EDF314',
    'statusBarItem.activeBackground': 'E6EDF31F',
    'statusBarItem.focusBorder': '1F6FEB',
    'editorGroupHeader.tabsBackground': '010409',
    'editorGroupHeader.tabsBorder': '30363D',
    'editorGroup.border': '30363D',
    'tab.activeForeground': 'E6EDF3',
    'tab.inactiveForeground': '7D8590',
    'tab.inactiveBackground': '010409',
    'tab.activeBackground': '0D1117',
    'tab.hoverBackground': '0D1117',
    'tab.unfocusedHoverBackground': '6E76811A',
    'tab.border': '30363D',
    'tab.unfocusedActiveBorderTop': '30363D',
    'tab.activeBorder': '0D1117',
    'tab.unfocusedActiveBorder': '0D1117',
    'tab.activeBorderTop': 'F78166',
    'breadcrumb.foreground': '7D8590',
    'breadcrumb.focusForeground': 'E6EDF3',
    'breadcrumb.activeSelectionForeground': '7D8590',
    'breadcrumbPicker.background': '161B22',
    'editor.foreground': 'E6EDF3',
    'editor.background': '0D1117',
    'editorWidget.background': '161B22',
    'editor.foldBackground': '6E76811A',
    'editor.lineHighlightBackground': '6E76811A',
    'editorLineNumber.foreground': '6E7681',
    'editorLineNumber.activeForeground': 'E6EDF3',
    'editorIndentGuide.background': 'E6EDF31F',
    'editorIndentGuide.activeBackground': 'E6EDF33D',
    'editorWhitespace.foreground': '484F58',
    'editorCursor.foreground': '2F81F7',
    'editor.findMatchBackground': '9E6A03',
    'editor.findMatchHighlightBackground': 'F2CC6080',
    'editor.linkedEditingBackground': '2F81F712',
    'editor.selectionHighlightBackground': '3FB95040',
    'editor.wordHighlightBackground': '6E768180',
    'editor.wordHighlightBorder': '6E768199',
    'editor.wordHighlightStrongBackground': '6E76814D',
    'editor.wordHighlightStrongBorder': '6E768199',
    'editorBracketMatch.background': '3FB95040',
    'editorBracketMatch.border': '3FB95099',
    'editorInlayHint.background': '8B949E33',
    'editorInlayHint.foreground': '7D8590',
    'editorInlayHint.typeBackground': '8B949E33',
    'editorInlayHint.typeForeground': '7D8590',
    'editorInlayHint.paramBackground': '8B949E33',
    'editorInlayHint.paramForeground': '7D8590',
    'editorGutter.modifiedBackground': 'BB800966',
    'editorGutter.addedBackground': '2EA04366',
    'editorGutter.deletedBackground': 'F8514966',
    'diffEditor.insertedLineBackground': '23863626',
    'diffEditor.insertedTextBackground': '3FB9504D',
    'diffEditor.removedLineBackground': 'DA363326',
    'diffEditor.removedTextBackground': 'FF7B724D',
    'scrollbar.shadow': '484F5833',
    'scrollbarSlider.background': '8B949E33',
    'scrollbarSlider.hoverBackground': '8B949E3D',
    'scrollbarSlider.activeBackground': '8B949E47',
    'editorOverviewRuler.border': '010409',
    'minimapSlider.background': '8B949E33',
    'minimapSlider.hoverBackground': '8B949E3D',
    'minimapSlider.activeBackground': '8B949E47',
    'panel.background': '010409',
    'panel.border': '30363D',
    'panelTitle.activeBorder': 'F78166',
    'panelTitle.activeForeground': 'E6EDF3',
    'panelTitle.inactiveForeground': '7D8590',
    'panelInput.border': '30363D',
    'debugIcon.breakpointForeground': 'F85149',
    'debugConsole.infoForeground': '8B949E',
    'debugConsole.warningForeground': 'D29922',
    'debugConsole.errorForeground': 'FFA198',
    'debugConsole.sourceForeground': 'E3B341',
    'debugConsoleInputIcon.foreground': 'BC8CFF',
    'debugTokenExpression.name': '79C0FF',
    'debugTokenExpression.value': 'A5D6FF',
    'debugTokenExpression.string': 'A5D6FF',
    'debugTokenExpression.boolean': '56D364',
    'debugTokenExpression.number': '56D364',
    'debugTokenExpression.error': 'FFA198',
    'symbolIcon.arrayForeground': 'F0883E',
    'symbolIcon.booleanForeground': '58A6FF',
    'symbolIcon.classForeground': 'F0883E',
    'symbolIcon.colorForeground': '79C0FF',
    'symbolIcon.constructorForeground': 'D2A8FF',
    'symbolIcon.enumeratorForeground': 'F0883E',
    'symbolIcon.enumeratorMemberForeground': '58A6FF',
    'symbolIcon.eventForeground': '6E7681',
    'symbolIcon.fieldForeground': 'F0883E',
    'symbolIcon.fileForeground': 'D29922',
    'symbolIcon.folderForeground': 'D29922',
    'symbolIcon.functionForeground': 'BC8CFF',
    'symbolIcon.interfaceForeground': 'F0883E',
    'symbolIcon.keyForeground': '58A6FF',
    'symbolIcon.keywordForeground': 'FF7B72',
    'symbolIcon.methodForeground': 'BC8CFF',
    'symbolIcon.moduleForeground': 'FF7B72',
    'symbolIcon.namespaceForeground': 'FF7B72',
    'symbolIcon.nullForeground': '58A6FF',
    'symbolIcon.numberForeground': '3FB950',
    'symbolIcon.objectForeground': 'F0883E',
    'symbolIcon.operatorForeground': '79C0FF',
    'symbolIcon.packageForeground': 'F0883E',
    'symbolIcon.propertyForeground': 'F0883E',
    'symbolIcon.referenceForeground': '58A6FF',
    'symbolIcon.snippetForeground': '58A6FF',
    'symbolIcon.stringForeground': '79C0FF',
    'symbolIcon.structForeground': 'F0883E',
    'symbolIcon.textForeground': '79C0FF',
    'symbolIcon.typeParameterForeground': '79C0FF',
    'symbolIcon.unitForeground': '58A6FF',
    'symbolIcon.variableForeground': 'F0883E',
    'terminal.foreground': 'E6EDF3',
    'terminal.ansiBlack': '484F58',
    'terminal.ansiRed': 'FF7B72',
    'terminal.ansiGreen': '3FB950',
    'terminal.ansiYellow': 'D29922',
    'terminal.ansiBlue': '58A6FF',
    'terminal.ansiMagenta': 'BC8CFF',
    'terminal.ansiCyan': '39C5CF',
    'terminal.ansiWhite': 'B1BAC4',
    'terminal.ansiBrightBlack': '6E7681',
    'terminal.ansiBrightRed': 'FFA198',
    'terminal.ansiBrightGreen': '56D364',
    'terminal.ansiBrightYellow': 'E3B341',
    'terminal.ansiBrightBlue': '79C0FF',
    'terminal.ansiBrightMagenta': 'D2A8FF',
    'terminal.ansiBrightCyan': '56D4DD',
    'terminal.ansiBrightWhite': 'FFFFFF',
    'editorBracketHighlight.foreground1': '79C0FF',
    'editorBracketHighlight.foreground2': '56D364',
    'editorBracketHighlight.foreground3': 'E3B341',
    'editorBracketHighlight.foreground4': 'FFA198',
    'editorBracketHighlight.foreground5': 'FF9BCE',
    'editorBracketHighlight.foreground6': 'D2A8FF',
    'editorBracketHighlight.unexpectedBracket.foreground': '7D8590',
    'gitDecoration.addedResourceForeground': '3FB950',
    'gitDecoration.modifiedResourceForeground': 'D29922',
    'gitDecoration.deletedResourceForeground': 'F85149',
    'gitDecoration.untrackedResourceForeground': '3FB950',
    'gitDecoration.ignoredResourceForeground': '6E7681',
    'gitDecoration.conflictingResourceForeground': 'DB6D28',
    'gitDecoration.submoduleResourceForeground': '7D8590',
    'debugToolBar.background': '161B22',
    'editor.stackFrameHighlightBackground': 'BB800966',
    'editor.focusedStackFrameHighlightBackground': '2EA04366',
    'peekViewEditor.matchHighlightBackground': 'BB800966',
    'peekViewResult.matchHighlightBackground': 'BB800966',
    'peekViewEditor.background': '6E76811A',
    'peekViewResult.background': '0D1117',
    'settings.headerForeground': 'E6EDF3',
    'settings.modifiedItemIndicator': 'BB800966',
    'welcomePage.buttonBackground': '21262D',
    'welcomePage.buttonHoverBackground': '30363D',
  },
} as const satisfies monaco.editor.IStandaloneThemeData;
