import * as monaco from 'monaco-editor';

export default {
  base: 'vs-dark',
  inherit: false,
  colors: {
    'activityBar.background': '#272822',
    'activityBar.foreground': '#f8f8f2',
    'badge.background': '#75715E',
    'badge.foreground': '#f8f8f2',
    'button.background': '#75715E',
    'debugToolBar.background': '#1e1f1c',
    'diffEditor.insertedTextBackground': '#4b661680',
    'diffEditor.removedTextBackground': '#90274A70',
    'dropdown.background': '#414339',
    'dropdown.listBackground': '#1e1f1c',
    'editor.background': '#272822',
    'editor.foreground': '#f8f8f2',
    'editor.lineHighlightBackground': '#3e3d32',
    'editor.selectionBackground': '#878b9180',
    'editor.selectionHighlightBackground': '#575b6180',
    'editor.wordHighlightBackground': '#4a4a7680',
    'editor.wordHighlightStrongBackground': '#6a6a9680',
    'editorCursor.foreground': '#f8f8f0',
    'editorGroup.border': '#34352f',
    'editorGroup.dropBackground': '#41433980',
    'editorGroupHeader.tabsBackground': '#1e1f1c',
    'editorHoverWidget.background': '#414339',
    'editorHoverWidget.border': '#75715E',
    'editorIndentGuide.activeBackground': '#767771',
    'editorIndentGuide.background': '#464741',
    'editorLineNumber.activeForeground': '#c2c2bf',
    'editorLineNumber.foreground': '#90908a',
    'editorSuggestWidget.background': '#272822',
    'editorSuggestWidget.border': '#75715E',
    'editorWhitespace.foreground': '#464741',
    'editorWidget.background': '#1e1f1c',
    focusBorder: '#99947c',
    'input.background': '#414339',
    'inputOption.activeBorder': '#75715E',
    'inputValidation.errorBackground': '#90274A',
    'inputValidation.errorBorder': '#f92672',
    'inputValidation.infoBackground': '#546190',
    'inputValidation.infoBorder': '#819aff',
    'inputValidation.warningBackground': '#848528',
    'inputValidation.warningBorder': '#e2e22e',
    'list.activeSelectionBackground': '#75715E',
    'list.dropBackground': '#414339',
    'list.highlightForeground': '#f8f8f2',
    'list.hoverBackground': '#3e3d32',
    'list.inactiveSelectionBackground': '#414339',
    'menu.background': '#1e1f1c',
    'menu.foreground': '#cccccc',
    'minimap.selectionHighlight': '#878b9180',
    'panel.border': '#414339',
    'panelTitle.activeBorder': '#75715E',
    'panelTitle.activeForeground': '#f8f8f2',
    'panelTitle.inactiveForeground': '#75715E',
    'peekView.border': '#75715E',
    'peekViewEditor.background': '#272822',
    'peekViewEditor.matchHighlightBackground': '#75715E',
    'peekViewResult.background': '#1e1f1c',
    'peekViewResult.matchHighlightBackground': '#75715E',
    'peekViewResult.selectionBackground': '#414339',
    'peekViewTitle.background': '#1e1f1c',
    'pickerGroup.foreground': '#75715E',
    'ports.iconRunningProcessForeground': '#ccccc7',
    'progressBar.background': '#75715E',
    'quickInputList.focusBackground': '#414339',
    'selection.background': '#878b9180',
    'settings.focusedRowBackground': '#4143395A',
    'sideBar.background': '#1e1f1c',
    'sideBarSectionHeader.background': '#272822',
    'statusBar.background': '#414339',
    'statusBar.debuggingBackground': '#75715E',
    'statusBar.noFolderBackground': '#414339',
    'statusBarItem.remoteBackground': '#AC6218',
    'tab.border': '#1e1f1c',
    'tab.inactiveBackground': '#34352f',
    'tab.inactiveForeground': '#ccccc7',
    'tab.lastPinnedBorder': '#414339',
    'terminal.ansiBlack': '#333333',
    'terminal.ansiBlue': '#6A7EC8',
    'terminal.ansiBrightBlack': '#666666',
    'terminal.ansiBrightBlue': '#819aff',
    'terminal.ansiBrightCyan': '#66D9EF',
    'terminal.ansiBrightGreen': '#A6E22E',
    'terminal.ansiBrightMagenta': '#AE81FF',
    'terminal.ansiBrightRed': '#f92672',
    'terminal.ansiBrightWhite': '#f8f8f2',
    'terminal.ansiBrightYellow': '#e2e22e',
    'terminal.ansiCyan': '#56ADBC',
    'terminal.ansiGreen': '#86B42B',
    'terminal.ansiMagenta': '#8C6BC8',
    'terminal.ansiRed': '#C4265E',
    'terminal.ansiWhite': '#e3e3dd',
    'terminal.ansiYellow': '#B3B42B',
    'titleBar.activeBackground': '#1e1f1c',
    'widget.shadow': '#00000098',
  },
  rules: [
    {
      token: 'meta.embedded',
      foreground: 'F8F8F2',
    },
    {
      token: 'source.groovy.embedded',
      foreground: 'F8F8F2',
    },
    {
      token: 'string meta.image.inline.markdown',
      foreground: 'F8F8F2',
    },
    {
      token: 'variable.legacy.builtin.python',
      foreground: 'F8F8F2',
    },
    {
      token: 'comment',
      foreground: '88846f',
    },
    {
      token: 'string',
      foreground: 'E6DB74',
    },
    {
      token: 'punctuation.definition.template-expression',
      foreground: 'F92672',
    },
    {
      token: 'punctuation.section.embedded',
      foreground: 'F92672',
    },
    {
      token: 'meta.template.expression',
      foreground: 'F8F8F2',
    },
    {
      token: 'constant.numeric',
      foreground: 'AE81FF',
    },
    {
      token: 'constant.language',
      foreground: 'AE81FF',
    },
    {
      token: 'constant.character, constant.other',
      foreground: 'AE81FF',
    },
    {
      token: 'variable',
      foreground: 'F8F8F2',
    },
    {
      token: 'keyword',
      foreground: 'F92672',
    },
    {
      token: 'storage',
      foreground: 'F92672',
    },
    {
      token: 'storage.type',
      foreground: '66D9EF',
    },
    {
      token:
        'entity.name.type, entity.name.class, entity.name.namespace, entity.name.scope-resolution',
      foreground: 'A6E22E',
    },
    {
      token: 'entity.other.inherited-class',
      foreground: 'A6E22E',
    },
    {
      token: 'entity.name.function',
      foreground: 'A6E22E',
    },
    {
      token: 'variable.parameter',
      foreground: 'FD971F',
    },
    {
      token: 'entity.name.tag',
      foreground: 'F92672',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: 'A6E22E',
    },
    {
      token: 'support.function',
      foreground: '66D9EF',
    },
    {
      token: 'support.constant',
      foreground: '66D9EF',
    },
    {
      token: 'support.type, support.class',
      foreground: '66D9EF',
    },
    {
      token: 'invalid',
      foreground: 'F44747',
    },
    {
      token: 'invalid.deprecated',
      foreground: 'F44747',
    },
    {
      token: 'meta.structure.dictionary.json string.quoted.double.json',
      foreground: 'CFCFC2',
    },
    {
      token: 'meta.diff, meta.diff.header',
      foreground: '75715E',
    },
    {
      token: 'markup.deleted',
      foreground: 'F92672',
    },
    {
      token: 'markup.inserted',
      foreground: 'A6E22E',
    },
    {
      token: 'markup.changed',
      foreground: 'E6DB74',
    },
    {
      token: 'constant.numeric.line-number.find-in-files - match',
      foreground: 'AE81FFA0',
    },
    {
      token: 'entity.name.filename.find-in-files',
      foreground: 'E6DB74',
    },
    {
      token: 'markup.quote',
      foreground: 'F92672',
    },
    {
      token: 'markup.list',
      foreground: 'E6DB74',
    },
    {
      token: 'markup.bold, markup.italic',
      foreground: '66D9EF',
    },
    {
      token: 'markup.inline.raw',
      foreground: 'FD971F',
    },
    {
      token: 'markup.heading',
      foreground: 'A6E22E',
    },
    {
      token: 'markup.heading.setext',
      foreground: 'A6E22E',
    },
    {
      token: 'markup.quote.markdown',
      foreground: '75715E',
    },
    {
      token:
        'string.other.link.title.markdown,string.other.link.description.markdown',
      foreground: 'AE81FF',
    },
    {
      token:
        'markup.underline.link.markdown,markup.underline.link.image.markdown',
      foreground: 'E6DB74',
    },
    {
      token: 'markup.list.unnumbered.markdown, markup.list.numbered.markdown',
      foreground: 'f8f8f2',
    },
    {
      token: 'punctuation.definition.list.begin.markdown',
      foreground: 'A6E22E',
    },
    {
      token: 'token.info-token',
      foreground: '6796e6',
    },
    {
      token: 'token.warn-token',
      foreground: 'cd9731',
    },
    {
      token: 'token.error-token',
      foreground: 'f44747',
    },
    {
      token: 'token.debug-token',
      foreground: 'b267e6',
    },
    {
      token: 'variable.language',
      foreground: 'FD971F',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
