import * as monaco from 'monaco-editor';

export default {
  base: 'vs-dark',
  inherit: false,
  colors: {
    'activityBar.activeBackground': '#00000000',
    'activityBar.activeBorder': '#00000000',
    'activityBar.activeFocusBorder': '#00000000',
    'activityBar.background': '#232634',
    'activityBar.border': '#00000000',
    'activityBar.dropBorder': '#ca9ee633',
    'activityBar.foreground': '#ca9ee6',
    'activityBar.inactiveForeground': '#737994',
    'activityBarBadge.background': '#ca9ee6',
    'activityBarBadge.foreground': '#232634',
    'activityBarTop.activeBorder': '#00000000',
    'activityBarTop.dropBorder': '#ca9ee633',
    'activityBarTop.foreground': '#ca9ee6',
    'activityBarTop.inactiveForeground': '#737994',
    'badge.background': '#51576d',
    'badge.foreground': '#c6d0f5',
    'banner.background': '#51576d',
    'banner.foreground': '#c6d0f5',
    'banner.iconForeground': '#c6d0f5',
    'breadcrumb.activeSelectionForeground': '#ca9ee6',
    'breadcrumb.background': '#303446',
    'breadcrumb.focusForeground': '#ca9ee6',
    'breadcrumb.foreground': '#c6d0f5cc',
    'breadcrumbPicker.background': '#292c3c',
    'button.background': '#ca9ee6',
    'button.border': '#00000000',
    'button.foreground': '#232634',
    'button.hoverBackground': '#d9baed',
    'button.secondaryBackground': '#626880',
    'button.secondaryBorder': '#ca9ee6',
    'button.secondaryForeground': '#c6d0f5',
    'button.secondaryHoverBackground': '#727993',
    'button.separator': '#00000000',
    'charts.blue': '#8caaee',
    'charts.foreground': '#c6d0f5',
    'charts.green': '#a6d189',
    'charts.lines': '#b5bfe2',
    'charts.orange': '#ef9f76',
    'charts.purple': '#ca9ee6',
    'charts.red': '#e78284',
    'charts.yellow': '#e5c890',
    'checkbox.background': '#51576d',
    'checkbox.border': '#00000000',
    'checkbox.foreground': '#ca9ee6',
    'commandCenter.activeBackground': '#62688033',
    'commandCenter.activeBorder': '#ca9ee6',
    'commandCenter.activeForeground': '#ca9ee6',
    'commandCenter.background': '#292c3c',
    'commandCenter.border': '#00000000',
    'commandCenter.foreground': '#b5bfe2',
    'commandCenter.inactiveBorder': '#00000000',
    'commandCenter.inactiveForeground': '#b5bfe2',
    'debugConsole.errorForeground': '#e78284',
    'debugConsole.infoForeground': '#8caaee',
    'debugConsole.sourceForeground': '#f2d5cf',
    'debugConsole.warningForeground': '#ef9f76',
    'debugConsoleInputIcon.foreground': '#c6d0f5',
    'debugExceptionWidget.background': '#232634',
    'debugExceptionWidget.border': '#ca9ee6',
    'debugIcon.breakpointCurrentStackframeForeground': '#626880',
    'debugIcon.breakpointDisabledForeground': '#e7828499',
    'debugIcon.breakpointForeground': '#e78284',
    'debugIcon.breakpointStackframeForeground': '#626880',
    'debugIcon.breakpointUnverifiedForeground': '#a57582',
    'debugIcon.continueForeground': '#a6d189',
    'debugIcon.disconnectForeground': '#626880',
    'debugIcon.pauseForeground': '#8caaee',
    'debugIcon.restartForeground': '#81c8be',
    'debugIcon.startForeground': '#a6d189',
    'debugIcon.stepBackForeground': '#626880',
    'debugIcon.stepIntoForeground': '#c6d0f5',
    'debugIcon.stepOutForeground': '#c6d0f5',
    'debugIcon.stepOverForeground': '#ca9ee6',
    'debugIcon.stopForeground': '#e78284',
    'debugTokenExpression.boolean': '#ca9ee6',
    'debugTokenExpression.error': '#e78284',
    'debugTokenExpression.number': '#ef9f76',
    'debugTokenExpression.string': '#a6d189',
    'debugToolBar.background': '#232634',
    'debugToolBar.border': '#00000000',
    descriptionForeground: '#c6d0f5',
    'diffEditor.border': '#626880',
    'diffEditor.diagonalFill': '#62688099',
    'diffEditor.insertedLineBackground': '#a6d18926',
    'diffEditor.insertedTextBackground': '#a6d1891a',
    'diffEditor.removedLineBackground': '#e7828426',
    'diffEditor.removedTextBackground': '#e782841a',
    'diffEditorOverview.insertedForeground': '#a6d189cc',
    'diffEditorOverview.removedForeground': '#e78284cc',
    disabledForeground: '#a5adce',
    'dropdown.background': '#292c3c',
    'dropdown.border': '#ca9ee6',
    'dropdown.foreground': '#c6d0f5',
    'dropdown.listBackground': '#626880',
    'editor.background': '#303446',
    'editor.findMatchBackground': '#674b59',
    'editor.findMatchBorder': '#e7828433',
    'editor.findMatchHighlightBackground': '#506373',
    'editor.findMatchHighlightBorder': '#99d1db33',
    'editor.findRangeHighlightBackground': '#506373',
    'editor.findRangeHighlightBorder': '#99d1db33',
    'editor.focusedStackFrameHighlightBackground': '#a6d18926',
    'editor.foldBackground': '#99d1db40',
    'editor.foreground': '#c6d0f5',
    'editor.hoverHighlightBackground': '#99d1db40',
    'editor.lineHighlightBackground': '#c6d0f512',
    'editor.lineHighlightBorder': '#00000000',
    'editor.rangeHighlightBackground': '#99d1db40',
    'editor.rangeHighlightBorder': '#00000000',
    'editor.selectionBackground': '#949cbb40',
    'editor.selectionHighlightBackground': '#949cbb33',
    'editor.selectionHighlightBorder': '#949cbb33',
    'editor.stackFrameHighlightBackground': '#e5c89026',
    'editor.wordHighlightBackground': '#949cbb33',
    'editorBracketHighlight.foreground1': '#e78284',
    'editorBracketHighlight.foreground2': '#ef9f76',
    'editorBracketHighlight.foreground3': '#e5c890',
    'editorBracketHighlight.foreground4': '#a6d189',
    'editorBracketHighlight.foreground5': '#85c1dc',
    'editorBracketHighlight.foreground6': '#ca9ee6',
    'editorBracketHighlight.unexpectedBracket.foreground': '#ea999c',
    'editorBracketMatch.background': '#949cbb1a',
    'editorBracketMatch.border': '#949cbb',
    'editorCodeLens.foreground': '#838ba7',
    'editorCursor.background': '#303446',
    'editorCursor.foreground': '#f2d5cf',
    'editorError.background': '#00000000',
    'editorError.border': '#00000000',
    'editorError.foreground': '#e78284',
    'editorGroup.border': '#626880',
    'editorGroup.dropBackground': '#ca9ee633',
    'editorGroup.emptyBackground': '#303446',
    'editorGroupHeader.tabsBackground': '#232634',
    'editorGutter.addedBackground': '#a6d189',
    'editorGutter.background': '#303446',
    'editorGutter.commentRangeForeground': '#949cbb',
    'editorGutter.deletedBackground': '#e78284',
    'editorGutter.foldingControlForeground': '#949cbb',
    'editorGutter.modifiedBackground': '#e5c890',
    'editorHoverWidget.background': '#292c3c',
    'editorHoverWidget.border': '#626880',
    'editorHoverWidget.foreground': '#c6d0f5',
    'editorIndentGuide.activeBackground': '#626880',
    'editorIndentGuide.background': '#51576d',
    'editorInfo.background': '#00000000',
    'editorInfo.border': '#00000000',
    'editorInfo.foreground': '#8caaee',
    'editorInlayHint.background': '#292c3cbf',
    'editorInlayHint.foreground': '#626880',
    'editorInlayHint.parameterBackground': '#292c3cbf',
    'editorInlayHint.parameterForeground': '#a5adce',
    'editorInlayHint.typeBackground': '#292c3cbf',
    'editorInlayHint.typeForeground': '#b5bfe2',
    'editorLightBulb.foreground': '#e5c890',
    'editorLineNumber.activeForeground': '#ca9ee6',
    'editorLineNumber.foreground': '#838ba7',
    'editorLink.activeForeground': '#ca9ee6',
    'editorMarkerNavigation.background': '#292c3c',
    'editorMarkerNavigationError.background': '#e78284',
    'editorMarkerNavigationInfo.background': '#8caaee',
    'editorMarkerNavigationWarning.background': '#ef9f76',
    'editorOverviewRuler.background': '#292c3c',
    'editorOverviewRuler.border': '#c6d0f512',
    'editorOverviewRuler.modifiedForeground': '#e5c890',
    'editorRuler.foreground': '#626880',
    'editorStickyScrollHover.background': '#414559',
    'editorSuggestWidget.background': '#292c3c',
    'editorSuggestWidget.border': '#626880',
    'editorSuggestWidget.foreground': '#c6d0f5',
    'editorSuggestWidget.highlightForeground': '#ca9ee6',
    'editorSuggestWidget.selectedBackground': '#414559',
    'editorWarning.background': '#00000000',
    'editorWarning.border': '#00000000',
    'editorWarning.foreground': '#ef9f76',
    'editorWhitespace.foreground': '#949cbb66',
    'editorWidget.background': '#292c3c',
    'editorWidget.foreground': '#c6d0f5',
    'editorWidget.resizeBorder': '#626880',
    errorForeground: '#e78284',
    'errorLens.errorBackground': '#e7828426',
    'errorLens.errorBackgroundLight': '#e7828426',
    'errorLens.errorForeground': '#e78284',
    'errorLens.errorForegroundLight': '#e78284',
    'errorLens.errorMessageBackground': '#e7828426',
    'errorLens.hintBackground': '#a6d18926',
    'errorLens.hintBackgroundLight': '#a6d18926',
    'errorLens.hintForeground': '#a6d189',
    'errorLens.hintForegroundLight': '#a6d189',
    'errorLens.hintMessageBackground': '#a6d18926',
    'errorLens.infoBackground': '#8caaee26',
    'errorLens.infoBackgroundLight': '#8caaee26',
    'errorLens.infoForeground': '#8caaee',
    'errorLens.infoForegroundLight': '#8caaee',
    'errorLens.infoMessageBackground': '#8caaee26',
    'errorLens.statusBarErrorForeground': '#e78284',
    'errorLens.statusBarHintForeground': '#a6d189',
    'errorLens.statusBarIconErrorForeground': '#e78284',
    'errorLens.statusBarIconWarningForeground': '#ef9f76',
    'errorLens.statusBarInfoForeground': '#8caaee',
    'errorLens.statusBarWarningForeground': '#ef9f76',
    'errorLens.warningBackground': '#ef9f7626',
    'errorLens.warningBackgroundLight': '#ef9f7626',
    'errorLens.warningForeground': '#ef9f76',
    'errorLens.warningForegroundLight': '#ef9f76',
    'errorLens.warningMessageBackground': '#ef9f7626',
    'extensionBadge.remoteBackground': '#8caaee',
    'extensionBadge.remoteForeground': '#232634',
    'extensionButton.prominentBackground': '#ca9ee6',
    'extensionButton.prominentForeground': '#232634',
    'extensionButton.prominentHoverBackground': '#d9baed',
    'extensionButton.separator': '#303446',
    'extensionIcon.preReleaseForeground': '#626880',
    'extensionIcon.sponsorForeground': '#f4b8e4',
    'extensionIcon.starForeground': '#e5c890',
    'extensionIcon.verifiedForeground': '#a6d189',
    focusBorder: '#ca9ee6',
    foreground: '#c6d0f5',
    'gitDecoration.addedResourceForeground': '#a6d189',
    'gitDecoration.conflictingResourceForeground': '#ca9ee6',
    'gitDecoration.deletedResourceForeground': '#e78284',
    'gitDecoration.ignoredResourceForeground': '#737994',
    'gitDecoration.modifiedResourceForeground': '#e5c890',
    'gitDecoration.stageDeletedResourceForeground': '#e78284',
    'gitDecoration.stageModifiedResourceForeground': '#e5c890',
    'gitDecoration.submoduleResourceForeground': '#8caaee',
    'gitDecoration.untrackedResourceForeground': '#a6d189',
    'gitlens.closedAutolinkedIssueIconColor': '#ca9ee6',
    'gitlens.closedPullRequestIconColor': '#e78284',
    'gitlens.decorations.branchAheadForegroundColor': '#a6d189',
    'gitlens.decorations.branchBehindForegroundColor': '#ef9f76',
    'gitlens.decorations.branchDivergedForegroundColor': '#e5c890',
    'gitlens.decorations.branchMissingUpstreamForegroundColor': '#ef9f76',
    'gitlens.decorations.branchUnpublishedForegroundColor': '#a6d189',
    'gitlens.decorations.statusMergingOrRebasingConflictForegroundColor':
      '#ea999c',
    'gitlens.decorations.statusMergingOrRebasingForegroundColor': '#e5c890',
    'gitlens.decorations.workspaceCurrentForegroundColor': '#ca9ee6',
    'gitlens.decorations.workspaceRepoMissingForegroundColor': '#a5adce',
    'gitlens.decorations.workspaceRepoOpenForegroundColor': '#ca9ee6',
    'gitlens.decorations.worktreeHasUncommittedChangesForegroundColor':
      '#ef9f76',
    'gitlens.decorations.worktreeMissingForegroundColor': '#ea999c',
    'gitlens.graphChangesColumnAddedColor': '#a6d189',
    'gitlens.graphChangesColumnDeletedColor': '#e78284',
    'gitlens.graphLane10Color': '#f4b8e4',
    'gitlens.graphLane1Color': '#ca9ee6',
    'gitlens.graphLane2Color': '#e5c890',
    'gitlens.graphLane3Color': '#8caaee',
    'gitlens.graphLane4Color': '#eebebe',
    'gitlens.graphLane5Color': '#a6d189',
    'gitlens.graphLane6Color': '#babbf1',
    'gitlens.graphLane7Color': '#f2d5cf',
    'gitlens.graphLane8Color': '#e78284',
    'gitlens.graphLane9Color': '#81c8be',
    'gitlens.graphMinimapMarkerHeadColor': '#a6d189',
    'gitlens.graphMinimapMarkerHighlightsColor': '#e5c890',
    'gitlens.graphMinimapMarkerLocalBranchesColor': '#8caaee',
    'gitlens.graphMinimapMarkerRemoteBranchesColor': '#769aeb',
    'gitlens.graphMinimapMarkerStashesColor': '#ca9ee6',
    'gitlens.graphMinimapMarkerTagsColor': '#eebebe',
    'gitlens.graphMinimapMarkerUpstreamColor': '#98ca77',
    'gitlens.graphScrollMarkerHeadColor': '#a6d189',
    'gitlens.graphScrollMarkerHighlightsColor': '#e5c890',
    'gitlens.graphScrollMarkerLocalBranchesColor': '#8caaee',
    'gitlens.graphScrollMarkerRemoteBranchesColor': '#769aeb',
    'gitlens.graphScrollMarkerStashesColor': '#ca9ee6',
    'gitlens.graphScrollMarkerTagsColor': '#eebebe',
    'gitlens.graphScrollMarkerUpstreamColor': '#98ca77',
    'gitlens.gutterBackgroundColor': '#4145594d',
    'gitlens.gutterForegroundColor': '#c6d0f5',
    'gitlens.gutterUncommittedForegroundColor': '#ca9ee6',
    'gitlens.lineHighlightBackgroundColor': '#ca9ee626',
    'gitlens.lineHighlightOverviewRulerColor': '#ca9ee6cc',
    'gitlens.mergedPullRequestIconColor': '#ca9ee6',
    'gitlens.openAutolinkedIssueIconColor': '#a6d189',
    'gitlens.openPullRequestIconColor': '#a6d189',
    'gitlens.trailingLineBackgroundColor': '#00000000',
    'gitlens.trailingLineForegroundColor': '#c6d0f54d',
    'gitlens.unpublishedChangesIconColor': '#a6d189',
    'gitlens.unpublishedCommitIconColor': '#a6d189',
    'gitlens.unpulledChangesIconColor': '#ef9f76',
    'icon.foreground': '#ca9ee6',
    'input.background': '#414559',
    'input.border': '#00000000',
    'input.foreground': '#c6d0f5',
    'input.placeholderForeground': '#c6d0f573',
    'inputOption.activeBackground': '#626880',
    'inputOption.activeBorder': '#ca9ee6',
    'inputOption.activeForeground': '#c6d0f5',
    'inputValidation.errorBackground': '#e78284',
    'inputValidation.errorBorder': '#23263433',
    'inputValidation.errorForeground': '#232634',
    'inputValidation.infoBackground': '#8caaee',
    'inputValidation.infoBorder': '#23263433',
    'inputValidation.infoForeground': '#232634',
    'inputValidation.warningBackground': '#ef9f76',
    'inputValidation.warningBorder': '#23263433',
    'inputValidation.warningForeground': '#232634',
    'issues.closed': '#ca9ee6',
    'issues.newIssueDecoration': '#f2d5cf',
    'issues.open': '#a6d189',
    'list.activeSelectionBackground': '#414559',
    'list.activeSelectionForeground': '#c6d0f5',
    'list.dropBackground': '#ca9ee633',
    'list.focusAndSelectionBackground': '#51576d',
    'list.focusBackground': '#414559',
    'list.focusForeground': '#c6d0f5',
    'list.focusOutline': '#00000000',
    'list.highlightForeground': '#ca9ee6',
    'list.hoverBackground': '#41455980',
    'list.hoverForeground': '#c6d0f5',
    'list.inactiveSelectionBackground': '#414559',
    'list.inactiveSelectionForeground': '#c6d0f5',
    'list.warningForeground': '#ef9f76',
    'listFilterWidget.background': '#51576d',
    'listFilterWidget.noMatchesOutline': '#e78284',
    'listFilterWidget.outline': '#00000000',
    'menu.background': '#303446',
    'menu.border': '#30344680',
    'menu.foreground': '#c6d0f5',
    'menu.selectionBackground': '#626880',
    'menu.selectionBorder': '#00000000',
    'menu.selectionForeground': '#c6d0f5',
    'menu.separatorBackground': '#626880',
    'menubar.selectionBackground': '#51576d',
    'menubar.selectionForeground': '#c6d0f5',
    'merge.commonContentBackground': '#51576d',
    'merge.commonHeaderBackground': '#626880',
    'merge.currentContentBackground': '#a6d18933',
    'merge.currentHeaderBackground': '#a6d18966',
    'merge.incomingContentBackground': '#8caaee33',
    'merge.incomingHeaderBackground': '#8caaee66',
    'minimap.background': '#292c3c80',
    'minimap.errorHighlight': '#e78284bf',
    'minimap.findMatchHighlight': '#99d1db4d',
    'minimap.selectionHighlight': '#626880bf',
    'minimap.selectionOccurrenceHighlight': '#626880bf',
    'minimap.warningHighlight': '#ef9f76bf',
    'minimapGutter.addedBackground': '#a6d189bf',
    'minimapGutter.deletedBackground': '#e78284bf',
    'minimapGutter.modifiedBackground': '#e5c890bf',
    'minimapSlider.activeBackground': '#ca9ee699',
    'minimapSlider.background': '#ca9ee633',
    'minimapSlider.hoverBackground': '#ca9ee666',
    'notificationCenter.border': '#ca9ee6',
    'notificationCenterHeader.background': '#292c3c',
    'notificationCenterHeader.foreground': '#c6d0f5',
    'notificationLink.foreground': '#8caaee',
    'notificationToast.border': '#ca9ee6',
    'notifications.background': '#292c3c',
    'notifications.border': '#ca9ee6',
    'notifications.foreground': '#c6d0f5',
    'notificationsErrorIcon.foreground': '#e78284',
    'notificationsInfoIcon.foreground': '#8caaee',
    'notificationsWarningIcon.foreground': '#ef9f76',
    'panel.background': '#303446',
    'panel.border': '#626880',
    'panelSection.border': '#626880',
    'panelSection.dropBackground': '#ca9ee633',
    'panelTitle.activeBorder': '#ca9ee6',
    'panelTitle.activeForeground': '#c6d0f5',
    'panelTitle.inactiveForeground': '#a5adce',
    'peekView.border': '#ca9ee6',
    'peekViewEditor.background': '#292c3c',
    'peekViewEditor.matchHighlightBackground': '#99d1db4d',
    'peekViewEditor.matchHighlightBorder': '#00000000',
    'peekViewEditorGutter.background': '#292c3c',
    'peekViewResult.background': '#292c3c',
    'peekViewResult.fileForeground': '#c6d0f5',
    'peekViewResult.lineForeground': '#c6d0f5',
    'peekViewResult.matchHighlightBackground': '#99d1db4d',
    'peekViewResult.selectionBackground': '#414559',
    'peekViewResult.selectionForeground': '#c6d0f5',
    'peekViewTitle.background': '#303446',
    'peekViewTitleDescription.foreground': '#b5bfe2b3',
    'peekViewTitleLabel.foreground': '#c6d0f5',
    'pickerGroup.border': '#ca9ee6',
    'pickerGroup.foreground': '#ca9ee6',
    'problemsErrorIcon.foreground': '#e78284',
    'problemsInfoIcon.foreground': '#8caaee',
    'problemsWarningIcon.foreground': '#ef9f76',
    'progressBar.background': '#ca9ee6',
    'pullRequests.closed': '#e78284',
    'pullRequests.draft': '#949cbb',
    'pullRequests.merged': '#ca9ee6',
    'pullRequests.notification': '#c6d0f5',
    'pullRequests.open': '#a6d189',
    'sash.hoverBorder': '#ca9ee6',
    'scrollbar.shadow': '#232634',
    'scrollbarSlider.activeBackground': '#41455966',
    'scrollbarSlider.background': '#62688080',
    'scrollbarSlider.hoverBackground': '#737994',
    'selection.background': '#ca9ee666',
    'settings.dropdownBackground': '#51576d',
    'settings.dropdownListBorder': '#00000000',
    'settings.focusedRowBackground': '#62688033',
    'settings.headerForeground': '#c6d0f5',
    'settings.modifiedItemIndicator': '#ca9ee6',
    'settings.numberInputBackground': '#51576d',
    'settings.numberInputBorder': '#00000000',
    'settings.textInputBackground': '#51576d',
    'settings.textInputBorder': '#00000000',
    'sideBar.background': '#292c3c',
    'sideBar.border': '#00000000',
    'sideBar.dropBackground': '#ca9ee633',
    'sideBar.foreground': '#c6d0f5',
    'sideBarSectionHeader.background': '#292c3c',
    'sideBarSectionHeader.foreground': '#c6d0f5',
    'sideBarTitle.foreground': '#ca9ee6',
    'statusBar.background': '#232634',
    'statusBar.border': '#00000000',
    'statusBar.debuggingBackground': '#ef9f76',
    'statusBar.debuggingBorder': '#00000000',
    'statusBar.debuggingForeground': '#232634',
    'statusBar.foreground': '#c6d0f5',
    'statusBar.noFolderBackground': '#232634',
    'statusBar.noFolderBorder': '#00000000',
    'statusBar.noFolderForeground': '#c6d0f5',
    'statusBarItem.activeBackground': '#62688066',
    'statusBarItem.errorBackground': '#00000000',
    'statusBarItem.errorForeground': '#e78284',
    'statusBarItem.hoverBackground': '#62688033',
    'statusBarItem.prominentBackground': '#00000000',
    'statusBarItem.prominentForeground': '#ca9ee6',
    'statusBarItem.prominentHoverBackground': '#62688033',
    'statusBarItem.remoteBackground': '#8caaee',
    'statusBarItem.remoteForeground': '#232634',
    'statusBarItem.warningBackground': '#00000000',
    'statusBarItem.warningForeground': '#ef9f76',
    'symbolIcon.arrayForeground': '#ef9f76',
    'symbolIcon.booleanForeground': '#ca9ee6',
    'symbolIcon.classForeground': '#e5c890',
    'symbolIcon.colorForeground': '#f4b8e4',
    'symbolIcon.constantForeground': '#ef9f76',
    'symbolIcon.constructorForeground': '#babbf1',
    'symbolIcon.enumeratorForeground': '#e5c890',
    'symbolIcon.enumeratorMemberForeground': '#e5c890',
    'symbolIcon.eventForeground': '#f4b8e4',
    'symbolIcon.fieldForeground': '#c6d0f5',
    'symbolIcon.fileForeground': '#ca9ee6',
    'symbolIcon.folderForeground': '#ca9ee6',
    'symbolIcon.functionForeground': '#8caaee',
    'symbolIcon.interfaceForeground': '#e5c890',
    'symbolIcon.keyForeground': '#81c8be',
    'symbolIcon.keywordForeground': '#ca9ee6',
    'symbolIcon.methodForeground': '#8caaee',
    'symbolIcon.moduleForeground': '#c6d0f5',
    'symbolIcon.namespaceForeground': '#e5c890',
    'symbolIcon.nullForeground': '#ea999c',
    'symbolIcon.numberForeground': '#ef9f76',
    'symbolIcon.objectForeground': '#e5c890',
    'symbolIcon.operatorForeground': '#81c8be',
    'symbolIcon.packageForeground': '#eebebe',
    'symbolIcon.propertyForeground': '#ea999c',
    'symbolIcon.referenceForeground': '#e5c890',
    'symbolIcon.snippetForeground': '#eebebe',
    'symbolIcon.stringForeground': '#a6d189',
    'symbolIcon.structForeground': '#81c8be',
    'symbolIcon.textForeground': '#c6d0f5',
    'symbolIcon.typeParameterForeground': '#ea999c',
    'symbolIcon.unitForeground': '#c6d0f5',
    'symbolIcon.variableForeground': '#c6d0f5',
    'tab.activeBackground': '#303446',
    'tab.activeBorder': '#00000000',
    'tab.activeBorderTop': '#ca9ee6',
    'tab.activeForeground': '#ca9ee6',
    'tab.activeModifiedBorder': '#e5c890',
    'tab.border': '#292c3c',
    'tab.hoverBackground': '#3a3f55',
    'tab.hoverBorder': '#00000000',
    'tab.hoverForeground': '#ca9ee6',
    'tab.inactiveBackground': '#292c3c',
    'tab.inactiveForeground': '#737994',
    'tab.inactiveModifiedBorder': '#e5c8904d',
    'tab.lastPinnedBorder': '#ca9ee6',
    'tab.unfocusedActiveBackground': '#292c3c',
    'tab.unfocusedActiveBorder': '#00000000',
    'tab.unfocusedActiveBorderTop': '#ca9ee64d',
    'tab.unfocusedInactiveBackground': '#1f212d',
    'table.headerBackground': '#414559',
    'table.headerForeground': '#c6d0f5',
    'terminal.ansiBlack': '#a5adce',
    'terminal.ansiBlue': '#8caaee',
    'terminal.ansiBrightBlack': '#626880',
    'terminal.ansiBrightBlue': '#8caaee',
    'terminal.ansiBrightCyan': '#99d1db',
    'terminal.ansiBrightGreen': '#a6d189',
    'terminal.ansiBrightMagenta': '#f4b8e4',
    'terminal.ansiBrightRed': '#e78284',
    'terminal.ansiBrightWhite': '#51576d',
    'terminal.ansiBrightYellow': '#e5c890',
    'terminal.ansiCyan': '#99d1db',
    'terminal.ansiGreen': '#a6d189',
    'terminal.ansiMagenta': '#f4b8e4',
    'terminal.ansiRed': '#e78284',
    'terminal.ansiWhite': '#b5bfe2',
    'terminal.ansiYellow': '#e5c890',
    'terminal.border': '#626880',
    'terminal.dropBackground': '#ca9ee633',
    'terminal.foreground': '#c6d0f5',
    'terminal.inactiveSelectionBackground': '#62688080',
    'terminal.selectionBackground': '#626880',
    'terminal.tab.activeBorder': '#ca9ee6',
    'terminalCommandDecoration.defaultBackground': '#626880',
    'terminalCommandDecoration.errorBackground': '#e78284',
    'terminalCommandDecoration.successBackground': '#a6d189',
    'terminalCursor.background': '#303446',
    'terminalCursor.foreground': '#f2d5cf',
    'textBlockQuote.background': '#292c3c',
    'textBlockQuote.border': '#232634',
    'textCodeBlock.background': '#303446',
    'textLink.activeForeground': '#99d1db',
    'textLink.foreground': '#8caaee',
    'textPreformat.foreground': '#c6d0f5',
    'textSeparator.foreground': '#ca9ee6',
    'titleBar.activeBackground': '#232634',
    'titleBar.activeForeground': '#c6d0f5',
    'titleBar.border': '#00000000',
    'titleBar.inactiveBackground': '#232634',
    'titleBar.inactiveForeground': '#c6d0f580',
    'tree.inactiveIndentGuidesStroke': '#51576d',
    'tree.indentGuidesStroke': '#949cbb',
    'walkThrough.embeddedEditorBackground': '#3034464d',
    'welcomePage.progress.background': '#232634',
    'welcomePage.progress.foreground': '#ca9ee6',
    'welcomePage.tileBackground': '#292c3c',
    'widget.shadow': '#292c3c80',
    'window.activeBorder': '#00000000',
    'window.inactiveBorder': '#00000000',
  },
  rules: [
    {
      token: 'text',
      foreground: 'c6d0f5',
    },
    {
      token: 'source',
      foreground: 'c6d0f5',
    },
    {
      token: 'variable.other.readwrite',
      foreground: 'c6d0f5',
    },
    {
      token: 'punctuation.definition.variable',
      foreground: 'c6d0f5',
    },
    {
      token: 'punctuation',
      foreground: '949cbb',
    },
    {
      token: 'comment',
      foreground: '737994',
    },
    {
      token: 'punctuation.definition.comment',
      foreground: '737994',
    },
    {
      token: 'string',
      foreground: 'a6d189',
    },
    {
      token: 'punctuation.definition.string',
      foreground: 'a6d189',
    },
    {
      token: 'constant.character.escape',
      foreground: 'f4b8e4',
    },
    {
      token: 'constant.numeric',
      foreground: 'ef9f76',
    },
    {
      token: 'variable.other.constant',
      foreground: 'ef9f76',
    },
    {
      token: 'entity.name.constant',
      foreground: 'ef9f76',
    },
    {
      token: 'constant.language.boolean',
      foreground: 'ef9f76',
    },
    {
      token: 'constant.language.false',
      foreground: 'ef9f76',
    },
    {
      token: 'constant.language.true',
      foreground: 'ef9f76',
    },
    {
      token: 'keyword.other.unit.user-defined',
      foreground: 'ef9f76',
    },
    {
      token: 'keyword.other.unit.suffix.floating-point',
      foreground: 'ef9f76',
    },
    {
      token: 'keyword',
      foreground: 'ca9ee6',
    },
    {
      token: 'keyword.operator.word',
      foreground: 'ca9ee6',
    },
    {
      token: 'keyword.operator.new',
      foreground: 'ca9ee6',
    },
    {
      token: 'variable.language.super',
      foreground: 'ca9ee6',
    },
    {
      token: 'support.type.primitive',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.type',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.modifier',
      foreground: 'ca9ee6',
    },
    {
      token: 'punctuation.definition.keyword',
      foreground: 'ca9ee6',
    },
    {
      token: 'entity.name.tag.documentation',
      foreground: 'ca9ee6',
    },
    {
      token: 'keyword.operator',
      foreground: '81c8be',
    },
    {
      token: 'punctuation.accessor',
      foreground: '81c8be',
    },
    {
      token: 'punctuation.definition.generic',
      foreground: '81c8be',
    },
    {
      token: 'meta.function.closure punctuation.section.parameters',
      foreground: '81c8be',
    },
    {
      token: 'punctuation.definition.tag',
      foreground: '81c8be',
    },
    {
      token: 'punctuation.separator.key-value',
      foreground: '81c8be',
    },
    {
      token: 'entity.name.function',
      foreground: '8caaee',
    },
    {
      token: 'meta.function-call.method',
      foreground: '8caaee',
    },
    {
      token: 'support.function',
      foreground: '8caaee',
    },
    {
      token: 'support.function.misc',
      foreground: '8caaee',
    },
    {
      token: 'variable.function',
      foreground: '8caaee',
    },
    {
      token: 'entity.name.class',
      foreground: 'e5c890',
    },
    {
      token: 'entity.other.inherited-class',
      foreground: 'e5c890',
    },
    {
      token: 'support.class',
      foreground: 'e5c890',
    },
    {
      token: 'meta.function-call.constructor',
      foreground: 'e5c890',
    },
    {
      token: 'entity.name.struct',
      foreground: 'e5c890',
    },
    {
      token: 'entity.name.enum',
      foreground: 'e5c890',
    },
    {
      token: 'meta.enum variable.other.readwrite',
      foreground: '81c8be',
    },
    {
      token: 'variable.other.enummember',
      foreground: '81c8be',
    },
    {
      token: 'meta.property.object',
      foreground: '81c8be',
    },
    {
      token: 'meta.type',
      foreground: 'e5c890',
    },
    {
      token: 'meta.type-alias',
      foreground: 'e5c890',
    },
    {
      token: 'support.type',
      foreground: 'e5c890',
    },
    {
      token: 'entity.name.type',
      foreground: 'e5c890',
    },
    {
      token: 'meta.annotation variable.function',
      foreground: 'ef9f76',
    },
    {
      token: 'meta.annotation variable.annotation.function',
      foreground: 'ef9f76',
    },
    {
      token: 'meta.annotation punctuation.definition.annotation',
      foreground: 'ef9f76',
    },
    {
      token: 'meta.decorator',
      foreground: 'ef9f76',
    },
    {
      token: 'punctuation.decorator',
      foreground: 'ef9f76',
    },
    {
      token: 'variable.parameter',
      foreground: 'ea999c',
    },
    {
      token: 'meta.function.parameters',
      foreground: 'ea999c',
    },
    {
      token: 'constant.language',
      foreground: 'e78284',
    },
    {
      token: 'support.function.builtin',
      foreground: 'e78284',
    },
    {
      token: 'entity.other.attribute-name.documentation',
      foreground: 'e78284',
    },
    {
      token: 'keyword.control.directive',
      foreground: 'e5c890',
    },
    {
      token: 'punctuation.definition.directive',
      foreground: 'e5c890',
    },
    {
      token: 'punctuation.definition.typeparameters',
      foreground: '99d1db',
    },
    {
      token: 'entity.name.namespace',
      foreground: 'e5c890',
    },
    {
      token: 'support.type.property-name.css',
      foreground: '8caaee',
    },
    {
      token: 'variable.language.this',
      foreground: 'e78284',
    },
    {
      token: 'variable.language.this punctuation.definition.variable',
      foreground: 'e78284',
    },
    {
      token: 'variable.object.property',
      foreground: 'c6d0f5',
    },
    {
      token: 'string.template variable',
      foreground: 'c6d0f5',
    },
    {
      token: 'string variable',
      foreground: 'c6d0f5',
    },
    {
      token: 'storage.modifier.specifier.extern.cpp',
      foreground: 'ca9ee6',
    },
    {
      token: 'entity.name.scope-resolution.template.call.cpp',
      foreground: 'e5c890',
    },
    {
      token: 'entity.name.scope-resolution.parameter.cpp',
      foreground: 'e5c890',
    },
    {
      token: 'entity.name.scope-resolution.cpp',
      foreground: 'e5c890',
    },
    {
      token: 'entity.name.scope-resolution.function.definition.cpp',
      foreground: 'e5c890',
    },
    {
      token: 'storage.modifier.reference.cpp',
      foreground: '81c8be',
    },
    {
      token: 'meta.interpolation.cs',
      foreground: 'c6d0f5',
    },
    {
      token: 'comment.block.documentation.cs',
      foreground: 'c6d0f5',
    },
    {
      token: 'source.css entity.other.attribute-name.class.css',
      foreground: 'e5c890',
    },
    {
      token:
        'entity.other.attribute-name.parent-selector.css punctuation.definition.entity.css',
      foreground: 'e5c890',
    },
    {
      token: 'punctuation.separator.operator.css',
      foreground: '81c8be',
    },
    {
      token: 'source.css entity.other.attribute-name.pseudo-class',
      foreground: '81c8be',
    },
    {
      token: 'source.css constant.other.unicode-range',
      foreground: 'ef9f76',
    },
    {
      token: 'source.css variable.parameter.url',
      foreground: 'a6d189',
    },
    {
      token: 'support.type.vendored.property-name',
      foreground: '99d1db',
    },
    {
      token: 'source.css meta.property-value variable',
      foreground: 'ea999c',
    },
    {
      token: 'source.css meta.property-value variable.other.less',
      foreground: 'ea999c',
    },
    {
      token:
        'source.css meta.property-value variable.other.less punctuation.definition.variable.less',
      foreground: 'ea999c',
    },
    {
      token: 'meta.definition.variable.scss',
      foreground: 'ea999c',
    },
    {
      token: 'source.css meta.property-list variable',
      foreground: '8caaee',
    },
    {
      token: 'meta.property-list variable.other.less',
      foreground: '8caaee',
    },
    {
      token:
        'meta.property-list variable.other.less punctuation.definition.variable.less',
      foreground: '8caaee',
    },
    {
      token: 'keyword.other.unit.percentage.css',
      foreground: 'ef9f76',
    },
    {
      token: 'source.css meta.attribute-selector',
      foreground: 'a6d189',
    },
    {
      token: 'keyword.other.definition.ini',
      foreground: '8caaee',
    },
    {
      token: 'punctuation.support.type.property-name.json',
      foreground: '8caaee',
    },
    {
      token: 'support.type.property-name.json',
      foreground: '8caaee',
    },
    {
      token: 'punctuation.support.type.property-name.toml',
      foreground: '8caaee',
    },
    {
      token: 'support.type.property-name.toml',
      foreground: '8caaee',
    },
    {
      token: 'entity.name.tag.yaml',
      foreground: '8caaee',
    },
    {
      token: 'punctuation.support.type.property-name.yaml',
      foreground: '8caaee',
    },
    {
      token: 'support.type.property-name.yaml',
      foreground: '8caaee',
    },
    {
      token: 'constant.language.json',
      foreground: 'ef9f76',
    },
    {
      token: 'constant.language.yaml',
      foreground: 'ef9f76',
    },
    {
      token: 'entity.name.type.anchor.yaml',
      foreground: 'e5c890',
    },
    {
      token: 'variable.other.alias.yaml',
      foreground: 'e5c890',
    },
    {
      token: 'support.type.property-name.table',
      foreground: 'e5c890',
    },
    {
      token: 'entity.name.section.group-title.ini',
      foreground: 'e5c890',
    },
    {
      token: 'constant.other.time.datetime.offset.toml',
      foreground: 'f4b8e4',
    },
    {
      token: 'punctuation.definition.anchor.yaml',
      foreground: 'f4b8e4',
    },
    {
      token: 'punctuation.definition.alias.yaml',
      foreground: 'f4b8e4',
    },
    {
      token: 'entity.other.document.begin.yaml',
      foreground: 'f4b8e4',
    },
    {
      token: 'markup.changed.diff',
      foreground: 'ef9f76',
    },
    {
      token: 'meta.diff.header.from-file',
      foreground: '8caaee',
    },
    {
      token: 'meta.diff.header.to-file',
      foreground: '8caaee',
    },
    {
      token: 'punctuation.definition.from-file.diff',
      foreground: '8caaee',
    },
    {
      token: 'punctuation.definition.to-file.diff',
      foreground: '8caaee',
    },
    {
      token: 'markup.inserted.diff',
      foreground: 'a6d189',
    },
    {
      token: 'markup.deleted.diff',
      foreground: 'e78284',
    },
    {
      token: 'variable.other.env',
      foreground: '8caaee',
    },
    {
      token: 'string.quoted variable.other.env',
      foreground: 'c6d0f5',
    },
    {
      token: 'support.function.builtin.gdscript',
      foreground: '8caaee',
    },
    {
      token: 'constant.language.gdscript',
      foreground: 'ef9f76',
    },
    {
      token: 'comment meta.annotation.go',
      foreground: 'ea999c',
    },
    {
      token: 'comment meta.annotation.parameters.go',
      foreground: 'ef9f76',
    },
    {
      token: 'constant.language.go',
      foreground: 'ef9f76',
    },
    {
      token: 'variable.graphql',
      foreground: 'c6d0f5',
    },
    {
      token: 'string.unquoted.alias.graphql',
      foreground: 'eebebe',
    },
    {
      token: 'constant.character.enum.graphql',
      foreground: '81c8be',
    },
    {
      token:
        'meta.objectvalues.graphql constant.object.key.graphql string.unquoted.graphql',
      foreground: 'eebebe',
    },
    {
      token: 'keyword.other.doctype',
      foreground: 'ca9ee6',
    },
    {
      token: 'meta.tag.sgml.doctype punctuation.definition.tag',
      foreground: 'ca9ee6',
    },
    {
      token: 'meta.tag.metadata.doctype entity.name.tag',
      foreground: 'ca9ee6',
    },
    {
      token: 'meta.tag.metadata.doctype punctuation.definition.tag',
      foreground: 'ca9ee6',
    },
    {
      token: 'entity.name.tag',
      foreground: '8caaee',
    },
    {
      token: 'text.html constant.character.entity',
      foreground: 'e78284',
    },
    {
      token: 'text.html constant.character.entity punctuation',
      foreground: 'e78284',
    },
    {
      token: 'constant.character.entity.xml',
      foreground: 'e78284',
    },
    {
      token: 'constant.character.entity.xml punctuation',
      foreground: 'e78284',
    },
    {
      token: 'constant.character.entity.js.jsx',
      foreground: 'e78284',
    },
    {
      token: 'constant.charactger.entity.js.jsx punctuation',
      foreground: 'e78284',
    },
    {
      token: 'constant.character.entity.tsx',
      foreground: 'e78284',
    },
    {
      token: 'constant.character.entity.tsx punctuation',
      foreground: 'e78284',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: 'e5c890',
    },
    {
      token: 'support.class.component',
      foreground: 'f4b8e4',
    },
    {
      token: 'support.class.component.jsx',
      foreground: 'f4b8e4',
    },
    {
      token: 'support.class.component.tsx',
      foreground: 'f4b8e4',
    },
    {
      token: 'support.class.component.vue',
      foreground: 'f4b8e4',
    },
    {
      token: 'punctuation.definition.annotation',
      foreground: 'ef9f76',
    },
    {
      token: 'storage.type.annotation',
      foreground: 'ef9f76',
    },
    {
      token: 'constant.other.enum.java',
      foreground: '81c8be',
    },
    {
      token: 'storage.modifier.import.java',
      foreground: 'c6d0f5',
    },
    {
      token: 'meta.export variable.other.readwrite.js',
      foreground: 'ea999c',
    },
    {
      token: 'variable.other.constant.js',
      foreground: 'c6d0f5',
    },
    {
      token: 'variable.other.constant.ts',
      foreground: 'c6d0f5',
    },
    {
      token: 'variable.other.property.js',
      foreground: 'c6d0f5',
    },
    {
      token: 'variable.other.property.ts',
      foreground: 'c6d0f5',
    },
    {
      token: 'variable.other.jsdoc',
      foreground: 'ea999c',
    },
    {
      token: 'comment.block.documentation variable.other',
      foreground: 'ea999c',
    },
    {
      token: 'support.type.object.console.js',
      foreground: 'c6d0f5',
    },
    {
      token: 'support.constant.node',
      foreground: 'ca9ee6',
    },
    {
      token: 'support.type.object.module.js',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.modifier.implements',
      foreground: 'ca9ee6',
    },
    {
      token: 'constant.language.null.js',
      foreground: 'ca9ee6',
    },
    {
      token: 'constant.language.null.ts',
      foreground: 'ca9ee6',
    },
    {
      token: 'constant.language.undefined.js',
      foreground: 'ca9ee6',
    },
    {
      token: 'constant.language.undefined.ts',
      foreground: 'ca9ee6',
    },
    {
      token: 'support.type.builtin.ts',
      foreground: 'ca9ee6',
    },
    {
      token: 'variable.parameter.generic',
      foreground: 'e5c890',
    },
    {
      token: 'keyword.declaration.function.arrow.js',
      foreground: '81c8be',
    },
    {
      token: 'storage.type.function.arrow.ts',
      foreground: '81c8be',
    },
    {
      token: 'punctuation.decorator.ts',
      foreground: '8caaee',
    },
    {
      token: 'keyword.operator.expression.in.js',
      foreground: 'ca9ee6',
    },
    {
      token: 'keyword.operator.expression.in.ts',
      foreground: 'ca9ee6',
    },
    {
      token: 'keyword.operator.expression.infer.ts',
      foreground: 'ca9ee6',
    },
    {
      token: 'keyword.operator.expression.instanceof.js',
      foreground: 'ca9ee6',
    },
    {
      token: 'keyword.operator.expression.instanceof.ts',
      foreground: 'ca9ee6',
    },
    {
      token: 'keyword.operator.expression.is',
      foreground: 'ca9ee6',
    },
    {
      token: 'keyword.operator.expression.keyof.ts',
      foreground: 'ca9ee6',
    },
    {
      token: 'keyword.operator.expression.of.js',
      foreground: 'ca9ee6',
    },
    {
      token: 'keyword.operator.expression.of.ts',
      foreground: 'ca9ee6',
    },
    {
      token: 'keyword.operator.expression.typeof.ts',
      foreground: 'ca9ee6',
    },
    {
      token: 'support.function.macro.julia',
      foreground: '81c8be',
    },
    {
      token: 'constant.language.julia',
      foreground: 'ef9f76',
    },
    {
      token: 'constant.other.symbol.julia',
      foreground: 'ea999c',
    },
    {
      token: 'text.tex keyword.control.preamble',
      foreground: '81c8be',
    },
    {
      token: 'text.tex support.function.be',
      foreground: '99d1db',
    },
    {
      token: 'constant.other.general.math.tex',
      foreground: 'eebebe',
    },
    {
      token:
        'comment.line.double-dash.documentation.lua storage.type.annotation.lua',
      foreground: 'ca9ee6',
    },
    {
      token:
        'comment.line.double-dash.documentation.lua entity.name.variable.lua',
      foreground: 'c6d0f5',
    },
    {
      token: 'comment.line.double-dash.documentation.lua variable.lua',
      foreground: 'c6d0f5',
    },
    {
      token: 'heading.1.markdown punctuation.definition.heading.markdown',
      foreground: 'e78284',
    },
    {
      token: 'heading.1.markdown',
      foreground: 'e78284',
    },
    {
      token: 'heading.1.quarto punctuation.definition.heading.quarto',
      foreground: 'e78284',
    },
    {
      token: 'heading.1.quarto',
      foreground: 'e78284',
    },
    {
      token: 'markup.heading.atx.1.mdx',
      foreground: 'e78284',
    },
    {
      token: 'markup.heading.atx.1.mdx punctuation.definition.heading.mdx',
      foreground: 'e78284',
    },
    {
      token: 'markup.heading.setext.1.markdown',
      foreground: 'e78284',
    },
    {
      token: 'markup.heading.heading-0.asciidoc',
      foreground: 'e78284',
    },
    {
      token: 'heading.2.markdown punctuation.definition.heading.markdown',
      foreground: 'ef9f76',
    },
    {
      token: 'heading.2.markdown',
      foreground: 'ef9f76',
    },
    {
      token: 'heading.2.quarto punctuation.definition.heading.quarto',
      foreground: 'ef9f76',
    },
    {
      token: 'heading.2.quarto',
      foreground: 'ef9f76',
    },
    {
      token: 'markup.heading.atx.2.mdx',
      foreground: 'ef9f76',
    },
    {
      token: 'markup.heading.atx.2.mdx punctuation.definition.heading.mdx',
      foreground: 'ef9f76',
    },
    {
      token: 'markup.heading.setext.2.markdown',
      foreground: 'ef9f76',
    },
    {
      token: 'markup.heading.heading-1.asciidoc',
      foreground: 'ef9f76',
    },
    {
      token: 'heading.3.markdown punctuation.definition.heading.markdown',
      foreground: 'e5c890',
    },
    {
      token: 'heading.3.markdown',
      foreground: 'e5c890',
    },
    {
      token: 'heading.3.quarto punctuation.definition.heading.quarto',
      foreground: 'e5c890',
    },
    {
      token: 'heading.3.quarto',
      foreground: 'e5c890',
    },
    {
      token: 'markup.heading.atx.3.mdx',
      foreground: 'e5c890',
    },
    {
      token: 'markup.heading.atx.3.mdx punctuation.definition.heading.mdx',
      foreground: 'e5c890',
    },
    {
      token: 'markup.heading.heading-2.asciidoc',
      foreground: 'e5c890',
    },
    {
      token: 'heading.4.markdown punctuation.definition.heading.markdown',
      foreground: 'a6d189',
    },
    {
      token: 'heading.4.markdown',
      foreground: 'a6d189',
    },
    {
      token: 'heading.4.quarto punctuation.definition.heading.quarto',
      foreground: 'a6d189',
    },
    {
      token: 'heading.4.quarto',
      foreground: 'a6d189',
    },
    {
      token: 'markup.heading.atx.4.mdx',
      foreground: 'a6d189',
    },
    {
      token: 'markup.heading.atx.4.mdx punctuation.definition.heading.mdx',
      foreground: 'a6d189',
    },
    {
      token: 'markup.heading.heading-3.asciidoc',
      foreground: 'a6d189',
    },
    {
      token: 'heading.5.markdown punctuation.definition.heading.markdown',
      foreground: '8caaee',
    },
    {
      token: 'heading.5.markdown',
      foreground: '8caaee',
    },
    {
      token: 'heading.5.quarto punctuation.definition.heading.quarto',
      foreground: '8caaee',
    },
    {
      token: 'heading.5.quarto',
      foreground: '8caaee',
    },
    {
      token: 'markup.heading.atx.5.mdx',
      foreground: '8caaee',
    },
    {
      token: 'markup.heading.atx.5.mdx punctuation.definition.heading.mdx',
      foreground: '8caaee',
    },
    {
      token: 'markup.heading.heading-4.asciidoc',
      foreground: '8caaee',
    },
    {
      token: 'heading.6.markdown punctuation.definition.heading.markdown',
      foreground: 'ca9ee6',
    },
    {
      token: 'heading.6.markdown',
      foreground: 'ca9ee6',
    },
    {
      token: 'heading.6.quarto punctuation.definition.heading.quarto',
      foreground: 'ca9ee6',
    },
    {
      token: 'heading.6.quarto',
      foreground: 'ca9ee6',
    },
    {
      token: 'markup.heading.atx.6.mdx',
      foreground: 'ca9ee6',
    },
    {
      token: 'markup.heading.atx.6.mdx punctuation.definition.heading.mdx',
      foreground: 'ca9ee6',
    },
    {
      token: 'markup.heading.heading-5.asciidoc',
      foreground: 'ca9ee6',
    },
    {
      token: 'markup.bold',
      foreground: 'e78284',
    },
    {
      token: 'markup.italic',
      foreground: 'e78284',
    },
    {
      token: 'markup.strikethrough',
      foreground: 'a5adce',
    },
    {
      token: 'punctuation.definition.link',
      foreground: '8caaee',
    },
    {
      token: 'markup.underline.link',
      foreground: '8caaee',
    },
    {
      token: 'text.html.markdown punctuation.definition.link.title',
      foreground: 'babbf1',
    },
    {
      token: 'text.html.quarto punctuation.definition.link.title',
      foreground: 'babbf1',
    },
    {
      token: 'string.other.link.title.markdown',
      foreground: 'babbf1',
    },
    {
      token: 'string.other.link.title.quarto',
      foreground: 'babbf1',
    },
    {
      token: 'markup.link',
      foreground: 'babbf1',
    },
    {
      token: 'punctuation.definition.constant.markdown',
      foreground: 'babbf1',
    },
    {
      token: 'punctuation.definition.constant.quarto',
      foreground: 'babbf1',
    },
    {
      token: 'constant.other.reference.link.markdown',
      foreground: 'babbf1',
    },
    {
      token: 'constant.other.reference.link.quarto',
      foreground: 'babbf1',
    },
    {
      token: 'markup.substitution.attribute-reference',
      foreground: 'babbf1',
    },
    {
      token: 'punctuation.definition.raw.markdown',
      foreground: 'a6d189',
    },
    {
      token: 'punctuation.definition.raw.quarto',
      foreground: 'a6d189',
    },
    {
      token: 'markup.inline.raw.string.markdown',
      foreground: 'a6d189',
    },
    {
      token: 'markup.inline.raw.string.quarto',
      foreground: 'a6d189',
    },
    {
      token: 'markup.raw.block.markdown',
      foreground: 'a6d189',
    },
    {
      token: 'markup.raw.block.quarto',
      foreground: 'a6d189',
    },
    {
      token: 'fenced_code.block.language',
      foreground: '99d1db',
    },
    {
      token: 'markup.fenced_code.block punctuation.definition',
      foreground: '949cbb',
    },
    {
      token: 'markup.raw support.asciidoc',
      foreground: '949cbb',
    },
    {
      token: 'markup.quote',
      foreground: 'f4b8e4',
    },
    {
      token: 'punctuation.definition.quote.begin',
      foreground: 'f4b8e4',
    },
    {
      token: 'meta.separator.markdown',
      foreground: '81c8be',
    },
    {
      token: 'punctuation.definition.list.begin.markdown',
      foreground: '81c8be',
    },
    {
      token: 'punctuation.definition.list.begin.quarto',
      foreground: '81c8be',
    },
    {
      token: 'markup.list.bullet',
      foreground: '81c8be',
    },
    {
      token: 'entity.other.attribute-name.multipart.nix',
      foreground: '8caaee',
    },
    {
      token: 'entity.other.attribute-name.single.nix',
      foreground: '8caaee',
    },
    {
      token: 'variable.parameter.name.nix',
      foreground: 'c6d0f5',
    },
    {
      token: 'meta.embedded variable.parameter.name.nix',
      foreground: 'babbf1',
    },
    {
      token: 'string.unquoted.path.nix',
      foreground: 'f4b8e4',
    },
    {
      token: 'support.attribute.builtin',
      foreground: 'e5c890',
    },
    {
      token: 'meta.attribute.php',
      foreground: 'e5c890',
    },
    {
      token: 'meta.function.parameters.php punctuation.definition.variable.php',
      foreground: 'ea999c',
    },
    {
      token: 'constant.language.php',
      foreground: 'ca9ee6',
    },
    {
      token: 'text.html.php support.function',
      foreground: '99d1db',
    },
    {
      token: 'support.variable.magic.python',
      foreground: 'c6d0f5',
    },
    {
      token: 'meta.function-call.arguments.python',
      foreground: 'c6d0f5',
    },
    {
      token: 'support.function.magic.python',
      foreground: '99d1db',
    },
    {
      token: 'variable.parameter.function.language.special.self.python',
      foreground: 'e78284',
    },
    {
      token: 'variable.language.special.self.python',
      foreground: 'e78284',
    },
    {
      token: 'keyword.control.flow.python',
      foreground: 'ca9ee6',
    },
    {
      token: 'keyword.operator.logical.python',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.type.function.python',
      foreground: 'ca9ee6',
    },
    {
      token: 'support.token.decorator.python',
      foreground: '99d1db',
    },
    {
      token: 'meta.function.decorator.identifier.python',
      foreground: '99d1db',
    },
    {
      token: 'meta.function-call.python',
      foreground: '8caaee',
    },
    {
      token: 'entity.name.function.decorator.python',
      foreground: 'ef9f76',
    },
    {
      token: 'punctuation.definition.decorator.python',
      foreground: 'ef9f76',
    },
    {
      token: 'constant.character.format.placeholder.other.python',
      foreground: 'f4b8e4',
    },
    {
      token: 'support.type.exception.python',
      foreground: 'ef9f76',
    },
    {
      token: 'support.function.builtin.python',
      foreground: 'ef9f76',
    },
    {
      token: 'support.type.python',
      foreground: 'ef9f76',
    },
    {
      token: 'constant.language.python',
      foreground: 'ca9ee6',
    },
    {
      token: 'meta.indexed-name.python',
      foreground: 'ea999c',
    },
    {
      token: 'meta.item-access.python',
      foreground: 'ea999c',
    },
    {
      token: 'storage.type.string.python',
      foreground: 'a6d189',
    },
    {
      token: 'string.regexp punctuation.definition.string.begin',
      foreground: 'f4b8e4',
    },
    {
      token: 'string.regexp punctuation.definition.string.end',
      foreground: 'f4b8e4',
    },
    {
      token: 'keyword.control.anchor.regexp',
      foreground: 'ca9ee6',
    },
    {
      token: 'string.regexp.ts',
      foreground: 'c6d0f5',
    },
    {
      token: 'punctuation.definition.group.regexp',
      foreground: 'a6d189',
    },
    {
      token: 'keyword.other.back-reference.regexp',
      foreground: 'a6d189',
    },
    {
      token: 'punctuation.definition.character-class.regexp',
      foreground: 'e5c890',
    },
    {
      token: 'constant.other.character-class.regexp',
      foreground: 'f4b8e4',
    },
    {
      token: 'constant.other.character-class.range.regexp',
      foreground: 'f2d5cf',
    },
    {
      token: 'keyword.operator.quantifier.regexp',
      foreground: '81c8be',
    },
    {
      token: 'constant.character.numeric.regexp',
      foreground: 'ef9f76',
    },
    {
      token: 'punctuation.definition.group.no-capture.regexp',
      foreground: '8caaee',
    },
    {
      token: 'meta.assertion.look-ahead.regexp',
      foreground: '8caaee',
    },
    {
      token: 'meta.assertion.negative-look-ahead.regexp',
      foreground: '8caaee',
    },
    {
      token: 'meta.annotation.rust',
      foreground: 'e5c890',
    },
    {
      token: 'meta.annotation.rust punctuation',
      foreground: 'e5c890',
    },
    {
      token: 'meta.attribute.rust',
      foreground: 'e5c890',
    },
    {
      token: 'punctuation.definition.attribute.rust',
      foreground: 'e5c890',
    },
    {
      token: 'entity.name.function.macro.rules.rust',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.type.module.rust',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.modifier.rust',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.type.struct.rust',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.type.enum.rust',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.type.trait.rust',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.type.union.rust',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.type.impl.rust',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.type.rust',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.type.function.rust',
      foreground: 'ca9ee6',
    },
    {
      token: 'storage.type.type.rust',
      foreground: 'ca9ee6',
    },
    {
      token: 'entity.name.type.numeric.rust',
      foreground: 'ca9ee6',
    },
    {
      token: 'meta.generic.rust',
      foreground: 'ef9f76',
    },
    {
      token: 'entity.name.impl.rust',
      foreground: 'e5c890',
    },
    {
      token: 'entity.name.module.rust',
      foreground: 'ef9f76',
    },
    {
      token: 'entity.name.trait.rust',
      foreground: 'e5c890',
    },
    {
      token: 'storage.type.source.rust',
      foreground: 'e5c890',
    },
    {
      token: 'entity.name.union.rust',
      foreground: 'e5c890',
    },
    {
      token: 'meta.enum.rust storage.type.source.rust',
      foreground: '81c8be',
    },
    {
      token: 'support.macro.rust',
      foreground: '8caaee',
    },
    {
      token: 'meta.macro.rust support.function.rust',
      foreground: '8caaee',
    },
    {
      token: 'entity.name.function.macro.rust',
      foreground: '8caaee',
    },
    {
      token: 'storage.modifier.lifetime.rust',
      foreground: '8caaee',
    },
    {
      token: 'entity.name.type.lifetime',
      foreground: '8caaee',
    },
    {
      token: 'string.quoted.double.rust constant.other.placeholder.rust',
      foreground: 'f4b8e4',
    },
    {
      token:
        'meta.function.return-type.rust meta.generic.rust storage.type.rust',
      foreground: 'c6d0f5',
    },
    {
      token: 'meta.function.call.rust',
      foreground: '8caaee',
    },
    {
      token: 'punctuation.brackets.angle.rust',
      foreground: '99d1db',
    },
    {
      token: 'constant.other.caps.rust',
      foreground: 'ef9f76',
    },
    {
      token: 'meta.function.definition.rust variable.other.rust',
      foreground: 'ea999c',
    },
    {
      token: 'meta.function.call.rust variable.other.rust',
      foreground: 'c6d0f5',
    },
    {
      token: 'variable.language.self.rust',
      foreground: 'e78284',
    },
    {
      token: 'variable.other.metavariable.name.rust',
      foreground: 'f4b8e4',
    },
    {
      token: 'meta.macro.metavariable.rust keyword.operator.macro.dollar.rust',
      foreground: 'f4b8e4',
    },
    {
      token: 'comment.line.shebang',
      foreground: 'f4b8e4',
    },
    {
      token: 'comment.line.shebang punctuation.definition.comment',
      foreground: 'f4b8e4',
    },
    {
      token: 'comment.line.shebang',
      foreground: 'f4b8e4',
    },
    {
      token: 'punctuation.definition.comment.shebang.shell',
      foreground: 'f4b8e4',
    },
    {
      token: 'meta.shebang.shell',
      foreground: 'f4b8e4',
    },
    {
      token: 'comment.line.shebang constant.language',
      foreground: '81c8be',
    },
    {
      token:
        'meta.function-call.arguments.shell punctuation.definition.variable.shell',
      foreground: 'e78284',
    },
    {
      token:
        'meta.function-call.arguments.shell punctuation.section.interpolation',
      foreground: 'e78284',
    },
    {
      token:
        'meta.function-call.arguments.shell punctuation.definition.variable.shell',
      foreground: 'e78284',
    },
    {
      token:
        'meta.function-call.arguments.shell punctuation.section.interpolation',
      foreground: 'e78284',
    },
    {
      token:
        'meta.string meta.interpolation.parameter.shell variable.other.readwrite',
      foreground: 'ef9f76',
    },
    {
      token: 'source.shell punctuation.section.interpolation',
      foreground: '81c8be',
    },
    {
      token: 'punctuation.definition.evaluation.backticks.shell',
      foreground: '81c8be',
    },
    {
      token: 'entity.name.tag.heredoc.shell',
      foreground: 'ca9ee6',
    },
    {
      token: 'string.quoted.double.shell variable.other.normal.shell',
      foreground: 'c6d0f5',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
