import * as monaco from 'monaco-editor';

export default {
  base: 'vs',
  inherit: false,
  colors: {
    'activityBar.activeBackground': '#00000000',
    'activityBar.activeBorder': '#00000000',
    'activityBar.activeFocusBorder': '#00000000',
    'activityBar.background': '#dce0e8',
    'activityBar.border': '#00000000',
    'activityBar.dropBorder': '#8839ef33',
    'activityBar.foreground': '#8839ef',
    'activityBar.inactiveForeground': '#9ca0b0',
    'activityBarBadge.background': '#8839ef',
    'activityBarBadge.foreground': '#dce0e8',
    'activityBarTop.activeBorder': '#00000000',
    'activityBarTop.dropBorder': '#8839ef33',
    'activityBarTop.foreground': '#8839ef',
    'activityBarTop.inactiveForeground': '#9ca0b0',
    'badge.background': '#bcc0cc',
    'badge.foreground': '#4c4f69',
    'banner.background': '#bcc0cc',
    'banner.foreground': '#4c4f69',
    'banner.iconForeground': '#4c4f69',
    'breadcrumb.activeSelectionForeground': '#8839ef',
    'breadcrumb.background': '#eff1f5',
    'breadcrumb.focusForeground': '#8839ef',
    'breadcrumb.foreground': '#4c4f69cc',
    'breadcrumbPicker.background': '#e6e9ef',
    'button.background': '#8839ef',
    'button.border': '#00000000',
    'button.foreground': '#dce0e8',
    'button.hoverBackground': '#9c5af2',
    'button.secondaryBackground': '#acb0be',
    'button.secondaryBorder': '#8839ef',
    'button.secondaryForeground': '#4c4f69',
    'button.secondaryHoverBackground': '#c0c3ce',
    'button.separator': '#00000000',
    'charts.blue': '#1e66f5',
    'charts.foreground': '#4c4f69',
    'charts.green': '#40a02b',
    'charts.lines': '#5c5f77',
    'charts.orange': '#fe640b',
    'charts.purple': '#8839ef',
    'charts.red': '#d20f39',
    'charts.yellow': '#df8e1d',
    'checkbox.background': '#bcc0cc',
    'checkbox.border': '#00000000',
    'checkbox.foreground': '#8839ef',
    'commandCenter.activeBackground': '#acb0be33',
    'commandCenter.activeBorder': '#8839ef',
    'commandCenter.activeForeground': '#8839ef',
    'commandCenter.background': '#e6e9ef',
    'commandCenter.border': '#00000000',
    'commandCenter.foreground': '#5c5f77',
    'commandCenter.inactiveBorder': '#00000000',
    'commandCenter.inactiveForeground': '#5c5f77',
    'debugConsole.errorForeground': '#d20f39',
    'debugConsole.infoForeground': '#1e66f5',
    'debugConsole.sourceForeground': '#dc8a78',
    'debugConsole.warningForeground': '#fe640b',
    'debugConsoleInputIcon.foreground': '#4c4f69',
    'debugExceptionWidget.background': '#dce0e8',
    'debugExceptionWidget.border': '#8839ef',
    'debugIcon.breakpointCurrentStackframeForeground': '#acb0be',
    'debugIcon.breakpointDisabledForeground': '#d20f3999',
    'debugIcon.breakpointForeground': '#d20f39',
    'debugIcon.breakpointStackframeForeground': '#acb0be',
    'debugIcon.breakpointUnverifiedForeground': '#bf607c',
    'debugIcon.continueForeground': '#40a02b',
    'debugIcon.disconnectForeground': '#acb0be',
    'debugIcon.pauseForeground': '#1e66f5',
    'debugIcon.restartForeground': '#179299',
    'debugIcon.startForeground': '#40a02b',
    'debugIcon.stepBackForeground': '#acb0be',
    'debugIcon.stepIntoForeground': '#4c4f69',
    'debugIcon.stepOutForeground': '#4c4f69',
    'debugIcon.stepOverForeground': '#8839ef',
    'debugIcon.stopForeground': '#d20f39',
    'debugTokenExpression.boolean': '#8839ef',
    'debugTokenExpression.error': '#d20f39',
    'debugTokenExpression.number': '#fe640b',
    'debugTokenExpression.string': '#40a02b',
    'debugToolBar.background': '#dce0e8',
    'debugToolBar.border': '#00000000',
    descriptionForeground: '#4c4f69',
    'diffEditor.border': '#acb0be',
    'diffEditor.diagonalFill': '#acb0be99',
    'diffEditor.insertedLineBackground': '#40a02b26',
    'diffEditor.insertedTextBackground': '#40a02b1a',
    'diffEditor.removedLineBackground': '#d20f3926',
    'diffEditor.removedTextBackground': '#d20f391a',
    'diffEditorOverview.insertedForeground': '#40a02bcc',
    'diffEditorOverview.removedForeground': '#d20f39cc',
    disabledForeground: '#6c6f85',
    'dropdown.background': '#e6e9ef',
    'dropdown.border': '#8839ef',
    'dropdown.foreground': '#4c4f69',
    'dropdown.listBackground': '#acb0be',
    'editor.background': '#eff1f5',
    'editor.findMatchBackground': '#e6adbd',
    'editor.findMatchBorder': '#d20f3933',
    'editor.findMatchHighlightBackground': '#a9daf0',
    'editor.findMatchHighlightBorder': '#04a5e533',
    'editor.findRangeHighlightBackground': '#a9daf0',
    'editor.findRangeHighlightBorder': '#04a5e533',
    'editor.focusedStackFrameHighlightBackground': '#40a02b26',
    'editor.foldBackground': '#04a5e540',
    'editor.foreground': '#4c4f69',
    'editor.hoverHighlightBackground': '#04a5e540',
    'editor.lineHighlightBackground': '#4c4f6912',
    'editor.lineHighlightBorder': '#00000000',
    'editor.rangeHighlightBackground': '#04a5e540',
    'editor.rangeHighlightBorder': '#00000000',
    'editor.selectionBackground': '#7c7f934d',
    'editor.selectionHighlightBackground': '#7c7f9333',
    'editor.selectionHighlightBorder': '#7c7f9333',
    'editor.stackFrameHighlightBackground': '#df8e1d26',
    'editor.wordHighlightBackground': '#7c7f9333',
    'editorBracketHighlight.foreground1': '#d20f39',
    'editorBracketHighlight.foreground2': '#fe640b',
    'editorBracketHighlight.foreground3': '#df8e1d',
    'editorBracketHighlight.foreground4': '#40a02b',
    'editorBracketHighlight.foreground5': '#209fb5',
    'editorBracketHighlight.foreground6': '#8839ef',
    'editorBracketHighlight.unexpectedBracket.foreground': '#e64553',
    'editorBracketMatch.background': '#7c7f931a',
    'editorBracketMatch.border': '#7c7f93',
    'editorCodeLens.foreground': '#8c8fa1',
    'editorCursor.background': '#eff1f5',
    'editorCursor.foreground': '#dc8a78',
    'editorError.background': '#00000000',
    'editorError.border': '#00000000',
    'editorError.foreground': '#d20f39',
    'editorGroup.border': '#acb0be',
    'editorGroup.dropBackground': '#8839ef33',
    'editorGroup.emptyBackground': '#eff1f5',
    'editorGroupHeader.tabsBackground': '#dce0e8',
    'editorGutter.addedBackground': '#40a02b',
    'editorGutter.background': '#eff1f5',
    'editorGutter.commentRangeForeground': '#7c7f93',
    'editorGutter.deletedBackground': '#d20f39',
    'editorGutter.foldingControlForeground': '#7c7f93',
    'editorGutter.modifiedBackground': '#df8e1d',
    'editorHoverWidget.background': '#e6e9ef',
    'editorHoverWidget.border': '#acb0be',
    'editorHoverWidget.foreground': '#4c4f69',
    'editorIndentGuide.activeBackground': '#acb0be',
    'editorIndentGuide.background': '#bcc0cc',
    'editorInfo.background': '#00000000',
    'editorInfo.border': '#00000000',
    'editorInfo.foreground': '#1e66f5',
    'editorInlayHint.background': '#e6e9efbf',
    'editorInlayHint.foreground': '#acb0be',
    'editorInlayHint.parameterBackground': '#e6e9efbf',
    'editorInlayHint.parameterForeground': '#6c6f85',
    'editorInlayHint.typeBackground': '#e6e9efbf',
    'editorInlayHint.typeForeground': '#5c5f77',
    'editorLightBulb.foreground': '#df8e1d',
    'editorLineNumber.activeForeground': '#8839ef',
    'editorLineNumber.foreground': '#8c8fa1',
    'editorLink.activeForeground': '#8839ef',
    'editorMarkerNavigation.background': '#e6e9ef',
    'editorMarkerNavigationError.background': '#d20f39',
    'editorMarkerNavigationInfo.background': '#1e66f5',
    'editorMarkerNavigationWarning.background': '#fe640b',
    'editorOverviewRuler.background': '#e6e9ef',
    'editorOverviewRuler.border': '#4c4f6912',
    'editorOverviewRuler.modifiedForeground': '#df8e1d',
    'editorRuler.foreground': '#acb0be',
    'editorStickyScrollHover.background': '#ccd0da',
    'editorSuggestWidget.background': '#e6e9ef',
    'editorSuggestWidget.border': '#acb0be',
    'editorSuggestWidget.foreground': '#4c4f69',
    'editorSuggestWidget.highlightForeground': '#8839ef',
    'editorSuggestWidget.selectedBackground': '#ccd0da',
    'editorWarning.background': '#00000000',
    'editorWarning.border': '#00000000',
    'editorWarning.foreground': '#fe640b',
    'editorWhitespace.foreground': '#7c7f9366',
    'editorWidget.background': '#e6e9ef',
    'editorWidget.foreground': '#4c4f69',
    'editorWidget.resizeBorder': '#acb0be',
    errorForeground: '#d20f39',
    'errorLens.errorBackground': '#d20f3926',
    'errorLens.errorBackgroundLight': '#d20f3926',
    'errorLens.errorForeground': '#d20f39',
    'errorLens.errorForegroundLight': '#d20f39',
    'errorLens.errorMessageBackground': '#d20f3926',
    'errorLens.hintBackground': '#40a02b26',
    'errorLens.hintBackgroundLight': '#40a02b26',
    'errorLens.hintForeground': '#40a02b',
    'errorLens.hintForegroundLight': '#40a02b',
    'errorLens.hintMessageBackground': '#40a02b26',
    'errorLens.infoBackground': '#1e66f526',
    'errorLens.infoBackgroundLight': '#1e66f526',
    'errorLens.infoForeground': '#1e66f5',
    'errorLens.infoForegroundLight': '#1e66f5',
    'errorLens.infoMessageBackground': '#1e66f526',
    'errorLens.statusBarErrorForeground': '#d20f39',
    'errorLens.statusBarHintForeground': '#40a02b',
    'errorLens.statusBarIconErrorForeground': '#d20f39',
    'errorLens.statusBarIconWarningForeground': '#fe640b',
    'errorLens.statusBarInfoForeground': '#1e66f5',
    'errorLens.statusBarWarningForeground': '#fe640b',
    'errorLens.warningBackground': '#fe640b26',
    'errorLens.warningBackgroundLight': '#fe640b26',
    'errorLens.warningForeground': '#fe640b',
    'errorLens.warningForegroundLight': '#fe640b',
    'errorLens.warningMessageBackground': '#fe640b26',
    'extensionBadge.remoteBackground': '#1e66f5',
    'extensionBadge.remoteForeground': '#dce0e8',
    'extensionButton.prominentBackground': '#8839ef',
    'extensionButton.prominentForeground': '#dce0e8',
    'extensionButton.prominentHoverBackground': '#9c5af2',
    'extensionButton.separator': '#eff1f5',
    'extensionIcon.preReleaseForeground': '#acb0be',
    'extensionIcon.sponsorForeground': '#ea76cb',
    'extensionIcon.starForeground': '#df8e1d',
    'extensionIcon.verifiedForeground': '#40a02b',
    focusBorder: '#8839ef',
    foreground: '#4c4f69',
    'gitDecoration.addedResourceForeground': '#40a02b',
    'gitDecoration.conflictingResourceForeground': '#8839ef',
    'gitDecoration.deletedResourceForeground': '#d20f39',
    'gitDecoration.ignoredResourceForeground': '#9ca0b0',
    'gitDecoration.modifiedResourceForeground': '#df8e1d',
    'gitDecoration.stageDeletedResourceForeground': '#d20f39',
    'gitDecoration.stageModifiedResourceForeground': '#df8e1d',
    'gitDecoration.submoduleResourceForeground': '#1e66f5',
    'gitDecoration.untrackedResourceForeground': '#40a02b',
    'gitlens.closedAutolinkedIssueIconColor': '#8839ef',
    'gitlens.closedPullRequestIconColor': '#d20f39',
    'gitlens.decorations.branchAheadForegroundColor': '#40a02b',
    'gitlens.decorations.branchBehindForegroundColor': '#fe640b',
    'gitlens.decorations.branchDivergedForegroundColor': '#df8e1d',
    'gitlens.decorations.branchMissingUpstreamForegroundColor': '#fe640b',
    'gitlens.decorations.branchUnpublishedForegroundColor': '#40a02b',
    'gitlens.decorations.statusMergingOrRebasingConflictForegroundColor':
      '#e64553',
    'gitlens.decorations.statusMergingOrRebasingForegroundColor': '#df8e1d',
    'gitlens.decorations.workspaceCurrentForegroundColor': '#8839ef',
    'gitlens.decorations.workspaceRepoMissingForegroundColor': '#6c6f85',
    'gitlens.decorations.workspaceRepoOpenForegroundColor': '#8839ef',
    'gitlens.decorations.worktreeHasUncommittedChangesForegroundColor':
      '#fe640b',
    'gitlens.decorations.worktreeMissingForegroundColor': '#e64553',
    'gitlens.graphChangesColumnAddedColor': '#40a02b',
    'gitlens.graphChangesColumnDeletedColor': '#d20f39',
    'gitlens.graphLane10Color': '#ea76cb',
    'gitlens.graphLane1Color': '#8839ef',
    'gitlens.graphLane2Color': '#df8e1d',
    'gitlens.graphLane3Color': '#1e66f5',
    'gitlens.graphLane4Color': '#dd7878',
    'gitlens.graphLane5Color': '#40a02b',
    'gitlens.graphLane6Color': '#7287fd',
    'gitlens.graphLane7Color': '#dc8a78',
    'gitlens.graphLane8Color': '#d20f39',
    'gitlens.graphLane9Color': '#179299',
    'gitlens.graphMinimapMarkerHeadColor': '#40a02b',
    'gitlens.graphMinimapMarkerHighlightsColor': '#df8e1d',
    'gitlens.graphMinimapMarkerLocalBranchesColor': '#1e66f5',
    'gitlens.graphMinimapMarkerRemoteBranchesColor': '#0b57ef',
    'gitlens.graphMinimapMarkerStashesColor': '#8839ef',
    'gitlens.graphMinimapMarkerTagsColor': '#dd7878',
    'gitlens.graphMinimapMarkerUpstreamColor': '#388c26',
    'gitlens.graphScrollMarkerHeadColor': '#40a02b',
    'gitlens.graphScrollMarkerHighlightsColor': '#df8e1d',
    'gitlens.graphScrollMarkerLocalBranchesColor': '#1e66f5',
    'gitlens.graphScrollMarkerRemoteBranchesColor': '#0b57ef',
    'gitlens.graphScrollMarkerStashesColor': '#8839ef',
    'gitlens.graphScrollMarkerTagsColor': '#dd7878',
    'gitlens.graphScrollMarkerUpstreamColor': '#388c26',
    'gitlens.gutterBackgroundColor': '#ccd0da4d',
    'gitlens.gutterForegroundColor': '#4c4f69',
    'gitlens.gutterUncommittedForegroundColor': '#8839ef',
    'gitlens.lineHighlightBackgroundColor': '#8839ef26',
    'gitlens.lineHighlightOverviewRulerColor': '#8839efcc',
    'gitlens.mergedPullRequestIconColor': '#8839ef',
    'gitlens.openAutolinkedIssueIconColor': '#40a02b',
    'gitlens.openPullRequestIconColor': '#40a02b',
    'gitlens.trailingLineBackgroundColor': '#00000000',
    'gitlens.trailingLineForegroundColor': '#4c4f694d',
    'gitlens.unpublishedChangesIconColor': '#40a02b',
    'gitlens.unpublishedCommitIconColor': '#40a02b',
    'gitlens.unpulledChangesIconColor': '#fe640b',
    'icon.foreground': '#8839ef',
    'input.background': '#ccd0da',
    'input.border': '#00000000',
    'input.foreground': '#4c4f69',
    'input.placeholderForeground': '#4c4f6973',
    'inputOption.activeBackground': '#acb0be',
    'inputOption.activeBorder': '#8839ef',
    'inputOption.activeForeground': '#4c4f69',
    'inputValidation.errorBackground': '#d20f39',
    'inputValidation.errorBorder': '#dce0e833',
    'inputValidation.errorForeground': '#dce0e8',
    'inputValidation.infoBackground': '#1e66f5',
    'inputValidation.infoBorder': '#dce0e833',
    'inputValidation.infoForeground': '#dce0e8',
    'inputValidation.warningBackground': '#fe640b',
    'inputValidation.warningBorder': '#dce0e833',
    'inputValidation.warningForeground': '#dce0e8',
    'issues.closed': '#8839ef',
    'issues.newIssueDecoration': '#dc8a78',
    'issues.open': '#40a02b',
    'list.activeSelectionBackground': '#ccd0da',
    'list.activeSelectionForeground': '#4c4f69',
    'list.dropBackground': '#8839ef33',
    'list.focusAndSelectionBackground': '#bcc0cc',
    'list.focusBackground': '#ccd0da',
    'list.focusForeground': '#4c4f69',
    'list.focusOutline': '#00000000',
    'list.highlightForeground': '#8839ef',
    'list.hoverBackground': '#ccd0da80',
    'list.hoverForeground': '#4c4f69',
    'list.inactiveSelectionBackground': '#ccd0da',
    'list.inactiveSelectionForeground': '#4c4f69',
    'list.warningForeground': '#fe640b',
    'listFilterWidget.background': '#bcc0cc',
    'listFilterWidget.noMatchesOutline': '#d20f39',
    'listFilterWidget.outline': '#00000000',
    'menu.background': '#eff1f5',
    'menu.border': '#eff1f580',
    'menu.foreground': '#4c4f69',
    'menu.selectionBackground': '#acb0be',
    'menu.selectionBorder': '#00000000',
    'menu.selectionForeground': '#4c4f69',
    'menu.separatorBackground': '#acb0be',
    'menubar.selectionBackground': '#bcc0cc',
    'menubar.selectionForeground': '#4c4f69',
    'merge.commonContentBackground': '#bcc0cc',
    'merge.commonHeaderBackground': '#acb0be',
    'merge.currentContentBackground': '#40a02b33',
    'merge.currentHeaderBackground': '#40a02b66',
    'merge.incomingContentBackground': '#1e66f533',
    'merge.incomingHeaderBackground': '#1e66f566',
    'minimap.background': '#e6e9ef80',
    'minimap.errorHighlight': '#d20f39bf',
    'minimap.findMatchHighlight': '#04a5e54d',
    'minimap.selectionHighlight': '#acb0bebf',
    'minimap.selectionOccurrenceHighlight': '#acb0bebf',
    'minimap.warningHighlight': '#fe640bbf',
    'minimapGutter.addedBackground': '#40a02bbf',
    'minimapGutter.deletedBackground': '#d20f39bf',
    'minimapGutter.modifiedBackground': '#df8e1dbf',
    'minimapSlider.activeBackground': '#8839ef99',
    'minimapSlider.background': '#8839ef33',
    'minimapSlider.hoverBackground': '#8839ef66',
    'notificationCenter.border': '#8839ef',
    'notificationCenterHeader.background': '#e6e9ef',
    'notificationCenterHeader.foreground': '#4c4f69',
    'notificationLink.foreground': '#1e66f5',
    'notificationToast.border': '#8839ef',
    'notifications.background': '#e6e9ef',
    'notifications.border': '#8839ef',
    'notifications.foreground': '#4c4f69',
    'notificationsErrorIcon.foreground': '#d20f39',
    'notificationsInfoIcon.foreground': '#1e66f5',
    'notificationsWarningIcon.foreground': '#fe640b',
    'panel.background': '#eff1f5',
    'panel.border': '#acb0be',
    'panelSection.border': '#acb0be',
    'panelSection.dropBackground': '#8839ef33',
    'panelTitle.activeBorder': '#8839ef',
    'panelTitle.activeForeground': '#4c4f69',
    'panelTitle.inactiveForeground': '#6c6f85',
    'peekView.border': '#8839ef',
    'peekViewEditor.background': '#e6e9ef',
    'peekViewEditor.matchHighlightBackground': '#04a5e54d',
    'peekViewEditor.matchHighlightBorder': '#00000000',
    'peekViewEditorGutter.background': '#e6e9ef',
    'peekViewResult.background': '#e6e9ef',
    'peekViewResult.fileForeground': '#4c4f69',
    'peekViewResult.lineForeground': '#4c4f69',
    'peekViewResult.matchHighlightBackground': '#04a5e54d',
    'peekViewResult.selectionBackground': '#ccd0da',
    'peekViewResult.selectionForeground': '#4c4f69',
    'peekViewTitle.background': '#eff1f5',
    'peekViewTitleDescription.foreground': '#5c5f77b3',
    'peekViewTitleLabel.foreground': '#4c4f69',
    'pickerGroup.border': '#8839ef',
    'pickerGroup.foreground': '#8839ef',
    'problemsErrorIcon.foreground': '#d20f39',
    'problemsInfoIcon.foreground': '#1e66f5',
    'problemsWarningIcon.foreground': '#fe640b',
    'progressBar.background': '#8839ef',
    'pullRequests.closed': '#d20f39',
    'pullRequests.draft': '#7c7f93',
    'pullRequests.merged': '#8839ef',
    'pullRequests.notification': '#4c4f69',
    'pullRequests.open': '#40a02b',
    'sash.hoverBorder': '#8839ef',
    'scrollbar.shadow': '#dce0e8',
    'scrollbarSlider.activeBackground': '#ccd0da66',
    'scrollbarSlider.background': '#acb0be80',
    'scrollbarSlider.hoverBackground': '#9ca0b0',
    'selection.background': '#8839ef66',
    'settings.dropdownBackground': '#bcc0cc',
    'settings.dropdownListBorder': '#00000000',
    'settings.focusedRowBackground': '#acb0be33',
    'settings.headerForeground': '#4c4f69',
    'settings.modifiedItemIndicator': '#8839ef',
    'settings.numberInputBackground': '#bcc0cc',
    'settings.numberInputBorder': '#00000000',
    'settings.textInputBackground': '#bcc0cc',
    'settings.textInputBorder': '#00000000',
    'sideBar.background': '#e6e9ef',
    'sideBar.border': '#00000000',
    'sideBar.dropBackground': '#8839ef33',
    'sideBar.foreground': '#4c4f69',
    'sideBarSectionHeader.background': '#e6e9ef',
    'sideBarSectionHeader.foreground': '#4c4f69',
    'sideBarTitle.foreground': '#8839ef',
    'statusBar.background': '#dce0e8',
    'statusBar.border': '#00000000',
    'statusBar.debuggingBackground': '#fe640b',
    'statusBar.debuggingBorder': '#00000000',
    'statusBar.debuggingForeground': '#dce0e8',
    'statusBar.foreground': '#4c4f69',
    'statusBar.noFolderBackground': '#dce0e8',
    'statusBar.noFolderBorder': '#00000000',
    'statusBar.noFolderForeground': '#4c4f69',
    'statusBarItem.activeBackground': '#acb0be66',
    'statusBarItem.errorBackground': '#00000000',
    'statusBarItem.errorForeground': '#d20f39',
    'statusBarItem.hoverBackground': '#acb0be33',
    'statusBarItem.prominentBackground': '#00000000',
    'statusBarItem.prominentForeground': '#8839ef',
    'statusBarItem.prominentHoverBackground': '#acb0be33',
    'statusBarItem.remoteBackground': '#1e66f5',
    'statusBarItem.remoteForeground': '#dce0e8',
    'statusBarItem.warningBackground': '#00000000',
    'statusBarItem.warningForeground': '#fe640b',
    'symbolIcon.arrayForeground': '#fe640b',
    'symbolIcon.booleanForeground': '#8839ef',
    'symbolIcon.classForeground': '#df8e1d',
    'symbolIcon.colorForeground': '#ea76cb',
    'symbolIcon.constantForeground': '#fe640b',
    'symbolIcon.constructorForeground': '#7287fd',
    'symbolIcon.enumeratorForeground': '#df8e1d',
    'symbolIcon.enumeratorMemberForeground': '#df8e1d',
    'symbolIcon.eventForeground': '#ea76cb',
    'symbolIcon.fieldForeground': '#4c4f69',
    'symbolIcon.fileForeground': '#8839ef',
    'symbolIcon.folderForeground': '#8839ef',
    'symbolIcon.functionForeground': '#1e66f5',
    'symbolIcon.interfaceForeground': '#df8e1d',
    'symbolIcon.keyForeground': '#179299',
    'symbolIcon.keywordForeground': '#8839ef',
    'symbolIcon.methodForeground': '#1e66f5',
    'symbolIcon.moduleForeground': '#4c4f69',
    'symbolIcon.namespaceForeground': '#df8e1d',
    'symbolIcon.nullForeground': '#e64553',
    'symbolIcon.numberForeground': '#fe640b',
    'symbolIcon.objectForeground': '#df8e1d',
    'symbolIcon.operatorForeground': '#179299',
    'symbolIcon.packageForeground': '#dd7878',
    'symbolIcon.propertyForeground': '#e64553',
    'symbolIcon.referenceForeground': '#df8e1d',
    'symbolIcon.snippetForeground': '#dd7878',
    'symbolIcon.stringForeground': '#40a02b',
    'symbolIcon.structForeground': '#179299',
    'symbolIcon.textForeground': '#4c4f69',
    'symbolIcon.typeParameterForeground': '#e64553',
    'symbolIcon.unitForeground': '#4c4f69',
    'symbolIcon.variableForeground': '#4c4f69',
    'tab.activeBackground': '#eff1f5',
    'tab.activeBorder': '#00000000',
    'tab.activeBorderTop': '#8839ef',
    'tab.activeForeground': '#8839ef',
    'tab.activeModifiedBorder': '#df8e1d',
    'tab.border': '#e6e9ef',
    'tab.hoverBackground': '#ffffff',
    'tab.hoverBorder': '#00000000',
    'tab.hoverForeground': '#8839ef',
    'tab.inactiveBackground': '#e6e9ef',
    'tab.inactiveForeground': '#9ca0b0',
    'tab.inactiveModifiedBorder': '#df8e1d4d',
    'tab.lastPinnedBorder': '#8839ef',
    'tab.unfocusedActiveBackground': '#e6e9ef',
    'tab.unfocusedActiveBorder': '#00000000',
    'tab.unfocusedActiveBorderTop': '#8839ef4d',
    'tab.unfocusedInactiveBackground': '#d6dbe5',
    'table.headerBackground': '#ccd0da',
    'table.headerForeground': '#4c4f69',
    'terminal.ansiBlack': '#bcc0cc',
    'terminal.ansiBlue': '#1e66f5',
    'terminal.ansiBrightBlack': '#6c6f85',
    'terminal.ansiBrightBlue': '#1e66f5',
    'terminal.ansiBrightCyan': '#04a5e5',
    'terminal.ansiBrightGreen': '#40a02b',
    'terminal.ansiBrightMagenta': '#ea76cb',
    'terminal.ansiBrightRed': '#d20f39',
    'terminal.ansiBrightWhite': '#5c5f77',
    'terminal.ansiBrightYellow': '#df8e1d',
    'terminal.ansiCyan': '#04a5e5',
    'terminal.ansiGreen': '#40a02b',
    'terminal.ansiMagenta': '#ea76cb',
    'terminal.ansiRed': '#d20f39',
    'terminal.ansiWhite': '#acb0be',
    'terminal.ansiYellow': '#df8e1d',
    'terminal.border': '#acb0be',
    'terminal.dropBackground': '#8839ef33',
    'terminal.foreground': '#4c4f69',
    'terminal.inactiveSelectionBackground': '#acb0be80',
    'terminal.selectionBackground': '#acb0be',
    'terminal.tab.activeBorder': '#8839ef',
    'terminalCommandDecoration.defaultBackground': '#acb0be',
    'terminalCommandDecoration.errorBackground': '#d20f39',
    'terminalCommandDecoration.successBackground': '#40a02b',
    'terminalCursor.background': '#eff1f5',
    'terminalCursor.foreground': '#dc8a78',
    'textBlockQuote.background': '#e6e9ef',
    'textBlockQuote.border': '#dce0e8',
    'textCodeBlock.background': '#eff1f5',
    'textLink.activeForeground': '#04a5e5',
    'textLink.foreground': '#1e66f5',
    'textPreformat.foreground': '#4c4f69',
    'textSeparator.foreground': '#8839ef',
    'titleBar.activeBackground': '#dce0e8',
    'titleBar.activeForeground': '#4c4f69',
    'titleBar.border': '#00000000',
    'titleBar.inactiveBackground': '#dce0e8',
    'titleBar.inactiveForeground': '#4c4f6980',
    'tree.inactiveIndentGuidesStroke': '#bcc0cc',
    'tree.indentGuidesStroke': '#7c7f93',
    'walkThrough.embeddedEditorBackground': '#eff1f54d',
    'welcomePage.progress.background': '#dce0e8',
    'welcomePage.progress.foreground': '#8839ef',
    'welcomePage.tileBackground': '#e6e9ef',
    'widget.shadow': '#e6e9ef80',
    'window.activeBorder': '#00000000',
    'window.inactiveBorder': '#00000000',
  },
  rules: [
    {
      token: 'text',
      foreground: '4c4f69',
    },
    {
      token: 'source',
      foreground: '4c4f69',
    },
    {
      token: 'variable.other.readwrite',
      foreground: '4c4f69',
    },
    {
      token: 'punctuation.definition.variable',
      foreground: '4c4f69',
    },
    {
      token: 'punctuation',
      foreground: '7c7f93',
    },
    {
      token: 'comment',
      foreground: '9ca0b0',
    },
    {
      token: 'punctuation.definition.comment',
      foreground: '9ca0b0',
    },
    {
      token: 'string',
      foreground: '40a02b',
    },
    {
      token: 'punctuation.definition.string',
      foreground: '40a02b',
    },
    {
      token: 'constant.character.escape',
      foreground: 'ea76cb',
    },
    {
      token: 'constant.numeric',
      foreground: 'fe640b',
    },
    {
      token: 'variable.other.constant',
      foreground: 'fe640b',
    },
    {
      token: 'entity.name.constant',
      foreground: 'fe640b',
    },
    {
      token: 'constant.language.boolean',
      foreground: 'fe640b',
    },
    {
      token: 'constant.language.false',
      foreground: 'fe640b',
    },
    {
      token: 'constant.language.true',
      foreground: 'fe640b',
    },
    {
      token: 'keyword.other.unit.user-defined',
      foreground: 'fe640b',
    },
    {
      token: 'keyword.other.unit.suffix.floating-point',
      foreground: 'fe640b',
    },
    {
      token: 'keyword',
      foreground: '8839ef',
    },
    {
      token: 'keyword.operator.word',
      foreground: '8839ef',
    },
    {
      token: 'keyword.operator.new',
      foreground: '8839ef',
    },
    {
      token: 'variable.language.super',
      foreground: '8839ef',
    },
    {
      token: 'support.type.primitive',
      foreground: '8839ef',
    },
    {
      token: 'storage.type',
      foreground: '8839ef',
    },
    {
      token: 'storage.modifier',
      foreground: '8839ef',
    },
    {
      token: 'punctuation.definition.keyword',
      foreground: '8839ef',
    },
    {
      token: 'entity.name.tag.documentation',
      foreground: '8839ef',
    },
    {
      token: 'keyword.operator',
      foreground: '179299',
    },
    {
      token: 'punctuation.accessor',
      foreground: '179299',
    },
    {
      token: 'punctuation.definition.generic',
      foreground: '179299',
    },
    {
      token: 'meta.function.closure punctuation.section.parameters',
      foreground: '179299',
    },
    {
      token: 'punctuation.definition.tag',
      foreground: '179299',
    },
    {
      token: 'punctuation.separator.key-value',
      foreground: '179299',
    },
    {
      token: 'entity.name.function',
      foreground: '1e66f5',
    },
    {
      token: 'meta.function-call.method',
      foreground: '1e66f5',
    },
    {
      token: 'support.function',
      foreground: '1e66f5',
    },
    {
      token: 'support.function.misc',
      foreground: '1e66f5',
    },
    {
      token: 'variable.function',
      foreground: '1e66f5',
    },
    {
      token: 'entity.name.class',
      foreground: 'df8e1d',
    },
    {
      token: 'entity.other.inherited-class',
      foreground: 'df8e1d',
    },
    {
      token: 'support.class',
      foreground: 'df8e1d',
    },
    {
      token: 'meta.function-call.constructor',
      foreground: 'df8e1d',
    },
    {
      token: 'entity.name.struct',
      foreground: 'df8e1d',
    },
    {
      token: 'entity.name.enum',
      foreground: 'df8e1d',
    },
    {
      token: 'meta.enum variable.other.readwrite',
      foreground: '179299',
    },
    {
      token: 'variable.other.enummember',
      foreground: '179299',
    },
    {
      token: 'meta.property.object',
      foreground: '179299',
    },
    {
      token: 'meta.type',
      foreground: 'df8e1d',
    },
    {
      token: 'meta.type-alias',
      foreground: 'df8e1d',
    },
    {
      token: 'support.type',
      foreground: 'df8e1d',
    },
    {
      token: 'entity.name.type',
      foreground: 'df8e1d',
    },
    {
      token: 'meta.annotation variable.function',
      foreground: 'fe640b',
    },
    {
      token: 'meta.annotation variable.annotation.function',
      foreground: 'fe640b',
    },
    {
      token: 'meta.annotation punctuation.definition.annotation',
      foreground: 'fe640b',
    },
    {
      token: 'meta.decorator',
      foreground: 'fe640b',
    },
    {
      token: 'punctuation.decorator',
      foreground: 'fe640b',
    },
    {
      token: 'variable.parameter',
      foreground: 'e64553',
    },
    {
      token: 'meta.function.parameters',
      foreground: 'e64553',
    },
    {
      token: 'constant.language',
      foreground: 'd20f39',
    },
    {
      token: 'support.function.builtin',
      foreground: 'd20f39',
    },
    {
      token: 'entity.other.attribute-name.documentation',
      foreground: 'd20f39',
    },
    {
      token: 'keyword.control.directive',
      foreground: 'df8e1d',
    },
    {
      token: 'punctuation.definition.directive',
      foreground: 'df8e1d',
    },
    {
      token: 'punctuation.definition.typeparameters',
      foreground: '04a5e5',
    },
    {
      token: 'entity.name.namespace',
      foreground: 'df8e1d',
    },
    {
      token: 'support.type.property-name.css',
      foreground: '1e66f5',
    },
    {
      token: 'variable.language.this',
      foreground: 'd20f39',
    },
    {
      token: 'variable.language.this punctuation.definition.variable',
      foreground: 'd20f39',
    },
    {
      token: 'variable.object.property',
      foreground: '4c4f69',
    },
    {
      token: 'string.template variable',
      foreground: '4c4f69',
    },
    {
      token: 'string variable',
      foreground: '4c4f69',
    },
    {
      token: 'storage.modifier.specifier.extern.cpp',
      foreground: '8839ef',
    },
    {
      token: 'entity.name.scope-resolution.template.call.cpp',
      foreground: 'df8e1d',
    },
    {
      token: 'entity.name.scope-resolution.parameter.cpp',
      foreground: 'df8e1d',
    },
    {
      token: 'entity.name.scope-resolution.cpp',
      foreground: 'df8e1d',
    },
    {
      token: 'entity.name.scope-resolution.function.definition.cpp',
      foreground: 'df8e1d',
    },
    {
      token: 'storage.modifier.reference.cpp',
      foreground: '179299',
    },
    {
      token: 'meta.interpolation.cs',
      foreground: '4c4f69',
    },
    {
      token: 'comment.block.documentation.cs',
      foreground: '4c4f69',
    },
    {
      token: 'source.css entity.other.attribute-name.class.css',
      foreground: 'df8e1d',
    },
    {
      token:
        'entity.other.attribute-name.parent-selector.css punctuation.definition.entity.css',
      foreground: 'df8e1d',
    },
    {
      token: 'punctuation.separator.operator.css',
      foreground: '179299',
    },
    {
      token: 'source.css entity.other.attribute-name.pseudo-class',
      foreground: '179299',
    },
    {
      token: 'source.css constant.other.unicode-range',
      foreground: 'fe640b',
    },
    {
      token: 'source.css variable.parameter.url',
      foreground: '40a02b',
    },
    {
      token: 'support.type.vendored.property-name',
      foreground: '04a5e5',
    },
    {
      token: 'source.css meta.property-value variable',
      foreground: 'e64553',
    },
    {
      token: 'source.css meta.property-value variable.other.less',
      foreground: 'e64553',
    },
    {
      token:
        'source.css meta.property-value variable.other.less punctuation.definition.variable.less',
      foreground: 'e64553',
    },
    {
      token: 'meta.definition.variable.scss',
      foreground: 'e64553',
    },
    {
      token: 'source.css meta.property-list variable',
      foreground: '1e66f5',
    },
    {
      token: 'meta.property-list variable.other.less',
      foreground: '1e66f5',
    },
    {
      token:
        'meta.property-list variable.other.less punctuation.definition.variable.less',
      foreground: '1e66f5',
    },
    {
      token: 'keyword.other.unit.percentage.css',
      foreground: 'fe640b',
    },
    {
      token: 'source.css meta.attribute-selector',
      foreground: '40a02b',
    },
    {
      token: 'keyword.other.definition.ini',
      foreground: '1e66f5',
    },
    {
      token: 'punctuation.support.type.property-name.json',
      foreground: '1e66f5',
    },
    {
      token: 'support.type.property-name.json',
      foreground: '1e66f5',
    },
    {
      token: 'punctuation.support.type.property-name.toml',
      foreground: '1e66f5',
    },
    {
      token: 'support.type.property-name.toml',
      foreground: '1e66f5',
    },
    {
      token: 'entity.name.tag.yaml',
      foreground: '1e66f5',
    },
    {
      token: 'punctuation.support.type.property-name.yaml',
      foreground: '1e66f5',
    },
    {
      token: 'support.type.property-name.yaml',
      foreground: '1e66f5',
    },
    {
      token: 'constant.language.json',
      foreground: 'fe640b',
    },
    {
      token: 'constant.language.yaml',
      foreground: 'fe640b',
    },
    {
      token: 'entity.name.type.anchor.yaml',
      foreground: 'df8e1d',
    },
    {
      token: 'variable.other.alias.yaml',
      foreground: 'df8e1d',
    },
    {
      token: 'support.type.property-name.table',
      foreground: 'df8e1d',
    },
    {
      token: 'entity.name.section.group-title.ini',
      foreground: 'df8e1d',
    },
    {
      token: 'constant.other.time.datetime.offset.toml',
      foreground: 'ea76cb',
    },
    {
      token: 'punctuation.definition.anchor.yaml',
      foreground: 'ea76cb',
    },
    {
      token: 'punctuation.definition.alias.yaml',
      foreground: 'ea76cb',
    },
    {
      token: 'entity.other.document.begin.yaml',
      foreground: 'ea76cb',
    },
    {
      token: 'markup.changed.diff',
      foreground: 'fe640b',
    },
    {
      token: 'meta.diff.header.from-file',
      foreground: '1e66f5',
    },
    {
      token: 'meta.diff.header.to-file',
      foreground: '1e66f5',
    },
    {
      token: 'punctuation.definition.from-file.diff',
      foreground: '1e66f5',
    },
    {
      token: 'punctuation.definition.to-file.diff',
      foreground: '1e66f5',
    },
    {
      token: 'markup.inserted.diff',
      foreground: '40a02b',
    },
    {
      token: 'markup.deleted.diff',
      foreground: 'd20f39',
    },
    {
      token: 'variable.other.env',
      foreground: '1e66f5',
    },
    {
      token: 'string.quoted variable.other.env',
      foreground: '4c4f69',
    },
    {
      token: 'support.function.builtin.gdscript',
      foreground: '1e66f5',
    },
    {
      token: 'constant.language.gdscript',
      foreground: 'fe640b',
    },
    {
      token: 'comment meta.annotation.go',
      foreground: 'e64553',
    },
    {
      token: 'comment meta.annotation.parameters.go',
      foreground: 'fe640b',
    },
    {
      token: 'constant.language.go',
      foreground: 'fe640b',
    },
    {
      token: 'variable.graphql',
      foreground: '4c4f69',
    },
    {
      token: 'string.unquoted.alias.graphql',
      foreground: 'dd7878',
    },
    {
      token: 'constant.character.enum.graphql',
      foreground: '179299',
    },
    {
      token:
        'meta.objectvalues.graphql constant.object.key.graphql string.unquoted.graphql',
      foreground: 'dd7878',
    },
    {
      token: 'keyword.other.doctype',
      foreground: '8839ef',
    },
    {
      token: 'meta.tag.sgml.doctype punctuation.definition.tag',
      foreground: '8839ef',
    },
    {
      token: 'meta.tag.metadata.doctype entity.name.tag',
      foreground: '8839ef',
    },
    {
      token: 'meta.tag.metadata.doctype punctuation.definition.tag',
      foreground: '8839ef',
    },
    {
      token: 'entity.name.tag',
      foreground: '1e66f5',
    },
    {
      token: 'text.html constant.character.entity',
      foreground: 'd20f39',
    },
    {
      token: 'text.html constant.character.entity punctuation',
      foreground: 'd20f39',
    },
    {
      token: 'constant.character.entity.xml',
      foreground: 'd20f39',
    },
    {
      token: 'constant.character.entity.xml punctuation',
      foreground: 'd20f39',
    },
    {
      token: 'constant.character.entity.js.jsx',
      foreground: 'd20f39',
    },
    {
      token: 'constant.charactger.entity.js.jsx punctuation',
      foreground: 'd20f39',
    },
    {
      token: 'constant.character.entity.tsx',
      foreground: 'd20f39',
    },
    {
      token: 'constant.character.entity.tsx punctuation',
      foreground: 'd20f39',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: 'df8e1d',
    },
    {
      token: 'support.class.component',
      foreground: 'ea76cb',
    },
    {
      token: 'support.class.component.jsx',
      foreground: 'ea76cb',
    },
    {
      token: 'support.class.component.tsx',
      foreground: 'ea76cb',
    },
    {
      token: 'support.class.component.vue',
      foreground: 'ea76cb',
    },
    {
      token: 'punctuation.definition.annotation',
      foreground: 'fe640b',
    },
    {
      token: 'storage.type.annotation',
      foreground: 'fe640b',
    },
    {
      token: 'constant.other.enum.java',
      foreground: '179299',
    },
    {
      token: 'storage.modifier.import.java',
      foreground: '4c4f69',
    },
    {
      token: 'meta.export variable.other.readwrite.js',
      foreground: 'e64553',
    },
    {
      token: 'variable.other.constant.js',
      foreground: '4c4f69',
    },
    {
      token: 'variable.other.constant.ts',
      foreground: '4c4f69',
    },
    {
      token: 'variable.other.property.js',
      foreground: '4c4f69',
    },
    {
      token: 'variable.other.property.ts',
      foreground: '4c4f69',
    },
    {
      token: 'variable.other.jsdoc',
      foreground: 'e64553',
    },
    {
      token: 'comment.block.documentation variable.other',
      foreground: 'e64553',
    },
    {
      token: 'support.type.object.console.js',
      foreground: '4c4f69',
    },
    {
      token: 'support.constant.node',
      foreground: '8839ef',
    },
    {
      token: 'support.type.object.module.js',
      foreground: '8839ef',
    },
    {
      token: 'storage.modifier.implements',
      foreground: '8839ef',
    },
    {
      token: 'constant.language.null.js',
      foreground: '8839ef',
    },
    {
      token: 'constant.language.null.ts',
      foreground: '8839ef',
    },
    {
      token: 'constant.language.undefined.js',
      foreground: '8839ef',
    },
    {
      token: 'constant.language.undefined.ts',
      foreground: '8839ef',
    },
    {
      token: 'support.type.builtin.ts',
      foreground: '8839ef',
    },
    {
      token: 'variable.parameter.generic',
      foreground: 'df8e1d',
    },
    {
      token: 'keyword.declaration.function.arrow.js',
      foreground: '179299',
    },
    {
      token: 'storage.type.function.arrow.ts',
      foreground: '179299',
    },
    {
      token: 'punctuation.decorator.ts',
      foreground: '1e66f5',
    },
    {
      token: 'keyword.operator.expression.in.js',
      foreground: '8839ef',
    },
    {
      token: 'keyword.operator.expression.in.ts',
      foreground: '8839ef',
    },
    {
      token: 'keyword.operator.expression.infer.ts',
      foreground: '8839ef',
    },
    {
      token: 'keyword.operator.expression.instanceof.js',
      foreground: '8839ef',
    },
    {
      token: 'keyword.operator.expression.instanceof.ts',
      foreground: '8839ef',
    },
    {
      token: 'keyword.operator.expression.is',
      foreground: '8839ef',
    },
    {
      token: 'keyword.operator.expression.keyof.ts',
      foreground: '8839ef',
    },
    {
      token: 'keyword.operator.expression.of.js',
      foreground: '8839ef',
    },
    {
      token: 'keyword.operator.expression.of.ts',
      foreground: '8839ef',
    },
    {
      token: 'keyword.operator.expression.typeof.ts',
      foreground: '8839ef',
    },
    {
      token: 'support.function.macro.julia',
      foreground: '179299',
    },
    {
      token: 'constant.language.julia',
      foreground: 'fe640b',
    },
    {
      token: 'constant.other.symbol.julia',
      foreground: 'e64553',
    },
    {
      token: 'text.tex keyword.control.preamble',
      foreground: '179299',
    },
    {
      token: 'text.tex support.function.be',
      foreground: '04a5e5',
    },
    {
      token: 'constant.other.general.math.tex',
      foreground: 'dd7878',
    },
    {
      token:
        'comment.line.double-dash.documentation.lua storage.type.annotation.lua',
      foreground: '8839ef',
    },
    {
      token:
        'comment.line.double-dash.documentation.lua entity.name.variable.lua',
      foreground: '4c4f69',
    },
    {
      token: 'comment.line.double-dash.documentation.lua variable.lua',
      foreground: '4c4f69',
    },
    {
      token: 'heading.1.markdown punctuation.definition.heading.markdown',
      foreground: 'd20f39',
    },
    {
      token: 'heading.1.markdown',
      foreground: 'd20f39',
    },
    {
      token: 'heading.1.quarto punctuation.definition.heading.quarto',
      foreground: 'd20f39',
    },
    {
      token: 'heading.1.quarto',
      foreground: 'd20f39',
    },
    {
      token: 'markup.heading.atx.1.mdx',
      foreground: 'd20f39',
    },
    {
      token: 'markup.heading.atx.1.mdx punctuation.definition.heading.mdx',
      foreground: 'd20f39',
    },
    {
      token: 'markup.heading.setext.1.markdown',
      foreground: 'd20f39',
    },
    {
      token: 'markup.heading.heading-0.asciidoc',
      foreground: 'd20f39',
    },
    {
      token: 'heading.2.markdown punctuation.definition.heading.markdown',
      foreground: 'fe640b',
    },
    {
      token: 'heading.2.markdown',
      foreground: 'fe640b',
    },
    {
      token: 'heading.2.quarto punctuation.definition.heading.quarto',
      foreground: 'fe640b',
    },
    {
      token: 'heading.2.quarto',
      foreground: 'fe640b',
    },
    {
      token: 'markup.heading.atx.2.mdx',
      foreground: 'fe640b',
    },
    {
      token: 'markup.heading.atx.2.mdx punctuation.definition.heading.mdx',
      foreground: 'fe640b',
    },
    {
      token: 'markup.heading.setext.2.markdown',
      foreground: 'fe640b',
    },
    {
      token: 'markup.heading.heading-1.asciidoc',
      foreground: 'fe640b',
    },
    {
      token: 'heading.3.markdown punctuation.definition.heading.markdown',
      foreground: 'df8e1d',
    },
    {
      token: 'heading.3.markdown',
      foreground: 'df8e1d',
    },
    {
      token: 'heading.3.quarto punctuation.definition.heading.quarto',
      foreground: 'df8e1d',
    },
    {
      token: 'heading.3.quarto',
      foreground: 'df8e1d',
    },
    {
      token: 'markup.heading.atx.3.mdx',
      foreground: 'df8e1d',
    },
    {
      token: 'markup.heading.atx.3.mdx punctuation.definition.heading.mdx',
      foreground: 'df8e1d',
    },
    {
      token: 'markup.heading.heading-2.asciidoc',
      foreground: 'df8e1d',
    },
    {
      token: 'heading.4.markdown punctuation.definition.heading.markdown',
      foreground: '40a02b',
    },
    {
      token: 'heading.4.markdown',
      foreground: '40a02b',
    },
    {
      token: 'heading.4.quarto punctuation.definition.heading.quarto',
      foreground: '40a02b',
    },
    {
      token: 'heading.4.quarto',
      foreground: '40a02b',
    },
    {
      token: 'markup.heading.atx.4.mdx',
      foreground: '40a02b',
    },
    {
      token: 'markup.heading.atx.4.mdx punctuation.definition.heading.mdx',
      foreground: '40a02b',
    },
    {
      token: 'markup.heading.heading-3.asciidoc',
      foreground: '40a02b',
    },
    {
      token: 'heading.5.markdown punctuation.definition.heading.markdown',
      foreground: '1e66f5',
    },
    {
      token: 'heading.5.markdown',
      foreground: '1e66f5',
    },
    {
      token: 'heading.5.quarto punctuation.definition.heading.quarto',
      foreground: '1e66f5',
    },
    {
      token: 'heading.5.quarto',
      foreground: '1e66f5',
    },
    {
      token: 'markup.heading.atx.5.mdx',
      foreground: '1e66f5',
    },
    {
      token: 'markup.heading.atx.5.mdx punctuation.definition.heading.mdx',
      foreground: '1e66f5',
    },
    {
      token: 'markup.heading.heading-4.asciidoc',
      foreground: '1e66f5',
    },
    {
      token: 'heading.6.markdown punctuation.definition.heading.markdown',
      foreground: '8839ef',
    },
    {
      token: 'heading.6.markdown',
      foreground: '8839ef',
    },
    {
      token: 'heading.6.quarto punctuation.definition.heading.quarto',
      foreground: '8839ef',
    },
    {
      token: 'heading.6.quarto',
      foreground: '8839ef',
    },
    {
      token: 'markup.heading.atx.6.mdx',
      foreground: '8839ef',
    },
    {
      token: 'markup.heading.atx.6.mdx punctuation.definition.heading.mdx',
      foreground: '8839ef',
    },
    {
      token: 'markup.heading.heading-5.asciidoc',
      foreground: '8839ef',
    },
    {
      token: 'markup.bold',
      foreground: 'd20f39',
    },
    {
      token: 'markup.italic',
      foreground: 'd20f39',
    },
    {
      token: 'markup.strikethrough',
      foreground: '6c6f85',
    },
    {
      token: 'punctuation.definition.link',
      foreground: '1e66f5',
    },
    {
      token: 'markup.underline.link',
      foreground: '1e66f5',
    },
    {
      token: 'text.html.markdown punctuation.definition.link.title',
      foreground: '7287fd',
    },
    {
      token: 'text.html.quarto punctuation.definition.link.title',
      foreground: '7287fd',
    },
    {
      token: 'string.other.link.title.markdown',
      foreground: '7287fd',
    },
    {
      token: 'string.other.link.title.quarto',
      foreground: '7287fd',
    },
    {
      token: 'markup.link',
      foreground: '7287fd',
    },
    {
      token: 'punctuation.definition.constant.markdown',
      foreground: '7287fd',
    },
    {
      token: 'punctuation.definition.constant.quarto',
      foreground: '7287fd',
    },
    {
      token: 'constant.other.reference.link.markdown',
      foreground: '7287fd',
    },
    {
      token: 'constant.other.reference.link.quarto',
      foreground: '7287fd',
    },
    {
      token: 'markup.substitution.attribute-reference',
      foreground: '7287fd',
    },
    {
      token: 'punctuation.definition.raw.markdown',
      foreground: '40a02b',
    },
    {
      token: 'punctuation.definition.raw.quarto',
      foreground: '40a02b',
    },
    {
      token: 'markup.inline.raw.string.markdown',
      foreground: '40a02b',
    },
    {
      token: 'markup.inline.raw.string.quarto',
      foreground: '40a02b',
    },
    {
      token: 'markup.raw.block.markdown',
      foreground: '40a02b',
    },
    {
      token: 'markup.raw.block.quarto',
      foreground: '40a02b',
    },
    {
      token: 'fenced_code.block.language',
      foreground: '04a5e5',
    },
    {
      token: 'markup.fenced_code.block punctuation.definition',
      foreground: '7c7f93',
    },
    {
      token: 'markup.raw support.asciidoc',
      foreground: '7c7f93',
    },
    {
      token: 'markup.quote',
      foreground: 'ea76cb',
    },
    {
      token: 'punctuation.definition.quote.begin',
      foreground: 'ea76cb',
    },
    {
      token: 'meta.separator.markdown',
      foreground: '179299',
    },
    {
      token: 'punctuation.definition.list.begin.markdown',
      foreground: '179299',
    },
    {
      token: 'punctuation.definition.list.begin.quarto',
      foreground: '179299',
    },
    {
      token: 'markup.list.bullet',
      foreground: '179299',
    },
    {
      token: 'entity.other.attribute-name.multipart.nix',
      foreground: '1e66f5',
    },
    {
      token: 'entity.other.attribute-name.single.nix',
      foreground: '1e66f5',
    },
    {
      token: 'variable.parameter.name.nix',
      foreground: '4c4f69',
    },
    {
      token: 'meta.embedded variable.parameter.name.nix',
      foreground: '7287fd',
    },
    {
      token: 'string.unquoted.path.nix',
      foreground: 'ea76cb',
    },
    {
      token: 'support.attribute.builtin',
      foreground: 'df8e1d',
    },
    {
      token: 'meta.attribute.php',
      foreground: 'df8e1d',
    },
    {
      token: 'meta.function.parameters.php punctuation.definition.variable.php',
      foreground: 'e64553',
    },
    {
      token: 'constant.language.php',
      foreground: '8839ef',
    },
    {
      token: 'text.html.php support.function',
      foreground: '04a5e5',
    },
    {
      token: 'support.variable.magic.python',
      foreground: '4c4f69',
    },
    {
      token: 'meta.function-call.arguments.python',
      foreground: '4c4f69',
    },
    {
      token: 'support.function.magic.python',
      foreground: '04a5e5',
    },
    {
      token: 'variable.parameter.function.language.special.self.python',
      foreground: 'd20f39',
    },
    {
      token: 'variable.language.special.self.python',
      foreground: 'd20f39',
    },
    {
      token: 'keyword.control.flow.python',
      foreground: '8839ef',
    },
    {
      token: 'keyword.operator.logical.python',
      foreground: '8839ef',
    },
    {
      token: 'storage.type.function.python',
      foreground: '8839ef',
    },
    {
      token: 'support.token.decorator.python',
      foreground: '04a5e5',
    },
    {
      token: 'meta.function.decorator.identifier.python',
      foreground: '04a5e5',
    },
    {
      token: 'meta.function-call.python',
      foreground: '1e66f5',
    },
    {
      token: 'entity.name.function.decorator.python',
      foreground: 'fe640b',
    },
    {
      token: 'punctuation.definition.decorator.python',
      foreground: 'fe640b',
    },
    {
      token: 'constant.character.format.placeholder.other.python',
      foreground: 'ea76cb',
    },
    {
      token: 'support.type.exception.python',
      foreground: 'fe640b',
    },
    {
      token: 'support.function.builtin.python',
      foreground: 'fe640b',
    },
    {
      token: 'support.type.python',
      foreground: 'fe640b',
    },
    {
      token: 'constant.language.python',
      foreground: '8839ef',
    },
    {
      token: 'meta.indexed-name.python',
      foreground: 'e64553',
    },
    {
      token: 'meta.item-access.python',
      foreground: 'e64553',
    },
    {
      token: 'storage.type.string.python',
      foreground: '40a02b',
    },
    {
      token: 'string.regexp punctuation.definition.string.begin',
      foreground: 'ea76cb',
    },
    {
      token: 'string.regexp punctuation.definition.string.end',
      foreground: 'ea76cb',
    },
    {
      token: 'keyword.control.anchor.regexp',
      foreground: '8839ef',
    },
    {
      token: 'string.regexp.ts',
      foreground: '4c4f69',
    },
    {
      token: 'punctuation.definition.group.regexp',
      foreground: '40a02b',
    },
    {
      token: 'keyword.other.back-reference.regexp',
      foreground: '40a02b',
    },
    {
      token: 'punctuation.definition.character-class.regexp',
      foreground: 'df8e1d',
    },
    {
      token: 'constant.other.character-class.regexp',
      foreground: 'ea76cb',
    },
    {
      token: 'constant.other.character-class.range.regexp',
      foreground: 'dc8a78',
    },
    {
      token: 'keyword.operator.quantifier.regexp',
      foreground: '179299',
    },
    {
      token: 'constant.character.numeric.regexp',
      foreground: 'fe640b',
    },
    {
      token: 'punctuation.definition.group.no-capture.regexp',
      foreground: '1e66f5',
    },
    {
      token: 'meta.assertion.look-ahead.regexp',
      foreground: '1e66f5',
    },
    {
      token: 'meta.assertion.negative-look-ahead.regexp',
      foreground: '1e66f5',
    },
    {
      token: 'meta.annotation.rust',
      foreground: 'df8e1d',
    },
    {
      token: 'meta.annotation.rust punctuation',
      foreground: 'df8e1d',
    },
    {
      token: 'meta.attribute.rust',
      foreground: 'df8e1d',
    },
    {
      token: 'punctuation.definition.attribute.rust',
      foreground: 'df8e1d',
    },
    {
      token: 'entity.name.function.macro.rules.rust',
      foreground: '8839ef',
    },
    {
      token: 'storage.type.module.rust',
      foreground: '8839ef',
    },
    {
      token: 'storage.modifier.rust',
      foreground: '8839ef',
    },
    {
      token: 'storage.type.struct.rust',
      foreground: '8839ef',
    },
    {
      token: 'storage.type.enum.rust',
      foreground: '8839ef',
    },
    {
      token: 'storage.type.trait.rust',
      foreground: '8839ef',
    },
    {
      token: 'storage.type.union.rust',
      foreground: '8839ef',
    },
    {
      token: 'storage.type.impl.rust',
      foreground: '8839ef',
    },
    {
      token: 'storage.type.rust',
      foreground: '8839ef',
    },
    {
      token: 'storage.type.function.rust',
      foreground: '8839ef',
    },
    {
      token: 'storage.type.type.rust',
      foreground: '8839ef',
    },
    {
      token: 'entity.name.type.numeric.rust',
      foreground: '8839ef',
    },
    {
      token: 'meta.generic.rust',
      foreground: 'fe640b',
    },
    {
      token: 'entity.name.impl.rust',
      foreground: 'df8e1d',
    },
    {
      token: 'entity.name.module.rust',
      foreground: 'fe640b',
    },
    {
      token: 'entity.name.trait.rust',
      foreground: 'df8e1d',
    },
    {
      token: 'storage.type.source.rust',
      foreground: 'df8e1d',
    },
    {
      token: 'entity.name.union.rust',
      foreground: 'df8e1d',
    },
    {
      token: 'meta.enum.rust storage.type.source.rust',
      foreground: '179299',
    },
    {
      token: 'support.macro.rust',
      foreground: '1e66f5',
    },
    {
      token: 'meta.macro.rust support.function.rust',
      foreground: '1e66f5',
    },
    {
      token: 'entity.name.function.macro.rust',
      foreground: '1e66f5',
    },
    {
      token: 'storage.modifier.lifetime.rust',
      foreground: '1e66f5',
    },
    {
      token: 'entity.name.type.lifetime',
      foreground: '1e66f5',
    },
    {
      token: 'string.quoted.double.rust constant.other.placeholder.rust',
      foreground: 'ea76cb',
    },
    {
      token:
        'meta.function.return-type.rust meta.generic.rust storage.type.rust',
      foreground: '4c4f69',
    },
    {
      token: 'meta.function.call.rust',
      foreground: '1e66f5',
    },
    {
      token: 'punctuation.brackets.angle.rust',
      foreground: '04a5e5',
    },
    {
      token: 'constant.other.caps.rust',
      foreground: 'fe640b',
    },
    {
      token: 'meta.function.definition.rust variable.other.rust',
      foreground: 'e64553',
    },
    {
      token: 'meta.function.call.rust variable.other.rust',
      foreground: '4c4f69',
    },
    {
      token: 'variable.language.self.rust',
      foreground: 'd20f39',
    },
    {
      token: 'variable.other.metavariable.name.rust',
      foreground: 'ea76cb',
    },
    {
      token: 'meta.macro.metavariable.rust keyword.operator.macro.dollar.rust',
      foreground: 'ea76cb',
    },
    {
      token: 'comment.line.shebang',
      foreground: 'ea76cb',
    },
    {
      token: 'comment.line.shebang punctuation.definition.comment',
      foreground: 'ea76cb',
    },
    {
      token: 'comment.line.shebang',
      foreground: 'ea76cb',
    },
    {
      token: 'punctuation.definition.comment.shebang.shell',
      foreground: 'ea76cb',
    },
    {
      token: 'meta.shebang.shell',
      foreground: 'ea76cb',
    },
    {
      token: 'comment.line.shebang constant.language',
      foreground: '179299',
    },
    {
      token:
        'meta.function-call.arguments.shell punctuation.definition.variable.shell',
      foreground: 'd20f39',
    },
    {
      token:
        'meta.function-call.arguments.shell punctuation.section.interpolation',
      foreground: 'd20f39',
    },
    {
      token:
        'meta.function-call.arguments.shell punctuation.definition.variable.shell',
      foreground: 'd20f39',
    },
    {
      token:
        'meta.function-call.arguments.shell punctuation.section.interpolation',
      foreground: 'd20f39',
    },
    {
      token:
        'meta.string meta.interpolation.parameter.shell variable.other.readwrite',
      foreground: 'fe640b',
    },
    {
      token: 'source.shell punctuation.section.interpolation',
      foreground: '179299',
    },
    {
      token: 'punctuation.definition.evaluation.backticks.shell',
      foreground: '179299',
    },
    {
      token: 'entity.name.tag.heredoc.shell',
      foreground: '8839ef',
    },
    {
      token: 'string.quoted.double.shell variable.other.normal.shell',
      foreground: '4c4f69',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
