import * as monaco from 'monaco-editor';

export default {
  base: 'vs-dark',
  inherit: false,
  colors: {
    'activityBar.background': '#23262E',
    'activityBar.dropBackground': '#3a404e',
    'activityBar.foreground': '#BAAFC0',
    'activityBarBadge.background': '#00b0ff',
    'activityBarBadge.foreground': '#20232B',
    'badge.background': '#00b0ff',
    'badge.foreground': '#20232B',
    'button.background': '#00e8c5cc',
    'button.hoverBackground': '#07d4b6cc',
    'debugExceptionWidget.background': '#FF9F2E60',
    'debugExceptionWidget.border': '#FF9F2E60',
    'debugToolBar.background': '#20232A',
    'diffEditor.insertedTextBackground': '#29BF1220',
    'diffEditor.removedTextBackground': '#F21B3F20',
    'dropdown.background': '#2b303b',
    'dropdown.border': '#363c49',
    'editor.background': '#23262E',
    'editor.findMatchBackground': '#f39d1256',
    'editor.findMatchBorder': '#f39d12b6',
    'editor.findMatchHighlightBackground': '#59b8b377',
    'editor.foreground': '#D5CED9',
    'editor.hoverHighlightBackground': '#373941',
    'editor.lineHighlightBackground': '#2e323d',
    'editor.lineHighlightBorder': '#2e323d',
    'editor.rangeHighlightBackground': '#372F3C',
    'editor.selectionBackground': '#3D4352',
    'editor.selectionHighlightBackground': '#4F435580',
    'editor.wordHighlightBackground': '#4F4355',
    'editor.wordHighlightStrongBackground': '#db45a280',
    'editorBracketMatch.background': '#746f77',
    'editorBracketMatch.border': '#746f77',
    'editorCodeLens.foreground': '#746f77',
    'editorCursor.foreground': '#FFFFFF',
    'editorError.foreground': '#FC644D',
    'editorGroup.background': '#23262E',
    'editorGroup.dropBackground': '#495061d7',
    'editorGroupHeader.tabsBackground': '#23262E',
    'editorGutter.addedBackground': '#9BC53DBB',
    'editorGutter.deletedBackground': '#FC644DBB',
    'editorGutter.modifiedBackground': '#5BC0EBBB',
    'editorHoverWidget.background': '#373941',
    'editorHoverWidget.border': '#00e8c5cc',
    'editorIndentGuide.activeBackground': '#585C66',
    'editorIndentGuide.background': '#333844',
    'editorLineNumber.foreground': '#746f77',
    'editorLink.activeForeground': '#3B79C7',
    'editorOverviewRuler.border': '#1B1D23',
    'editorRuler.foreground': '#4F4355',
    'editorSuggestWidget.background': '#20232A',
    'editorSuggestWidget.border': '#372F3C',
    'editorSuggestWidget.selectedBackground': '#373941',
    'editorWarning.foreground': '#FF9F2E',
    'editorWhitespace.foreground': '#333844',
    'editorWidget.background': '#20232A',
    errorForeground: '#FC644D',
    'extensionButton.prominentBackground': '#07d4b6cc',
    'extensionButton.prominentHoverBackground': '#07d4b5b0',
    focusBorder: '#746f77',
    foreground: '#D5CED9',
    'gitDecoration.ignoredResourceForeground': '#555555',
    'input.background': '#2b303b',
    'input.placeholderForeground': '#746f77',
    'inputOption.activeBorder': '#C668BA',
    'inputValidation.errorBackground': '#D65343',
    'inputValidation.errorBorder': '#D65343',
    'inputValidation.infoBackground': '#3A6395',
    'inputValidation.infoBorder': '#3A6395',
    'inputValidation.warningBackground': '#DE9237',
    'inputValidation.warningBorder': '#DE9237',
    'list.activeSelectionBackground': '#23262E',
    'list.activeSelectionForeground': '#00e8c6',
    'list.dropBackground': '#3a404e',
    'list.focusBackground': '#282b35',
    'list.focusForeground': '#eeeeee',
    'list.hoverBackground': '#23262E',
    'list.hoverForeground': '#eeeeee',
    'list.inactiveSelectionBackground': '#23262E',
    'list.inactiveSelectionForeground': '#00e8c6',
    'merge.currentContentBackground': '#F9267240',
    'merge.currentHeaderBackground': '#F92672',
    'merge.incomingContentBackground': '#3B79C740',
    'merge.incomingHeaderBackground': '#3B79C7BB',
    'minimapSlider.activeBackground': '#60698060',
    'minimapSlider.background': '#58607460',
    'minimapSlider.hoverBackground': '#60698060',
    'notification.background': '#2d313b',
    'notification.buttonBackground': '#00e8c5cc',
    'notification.buttonHoverBackground': '#07d4b5b0',
    'notification.errorBackground': '#FC644D',
    'notification.infoBackground': '#00b0ff',
    'notification.warningBackground': '#FF9F2E',
    'panel.background': '#23262E',
    'panel.border': '#1B1D23',
    'panelTitle.activeBorder': '#23262E',
    'panelTitle.inactiveForeground': '#746f77',
    'peekView.border': '#23262E',
    'peekViewEditor.background': '#1A1C22',
    'peekViewEditor.matchHighlightBackground': '#FF9F2E60',
    'peekViewResult.background': '#1A1C22',
    'peekViewResult.matchHighlightBackground': '#FF9F2E60',
    'peekViewResult.selectionBackground': '#23262E',
    'peekViewTitle.background': '#1A1C22',
    'peekViewTitleDescription.foreground': '#746f77',
    'pickerGroup.border': '#4F4355',
    'pickerGroup.foreground': '#746f77',
    'progressBar.background': '#C668BA',
    'scrollbar.shadow': '#23262E',
    'scrollbarSlider.activeBackground': '#3A3F4CCC',
    'scrollbarSlider.background': '#3A3F4C77',
    'scrollbarSlider.hoverBackground': '#3A3F4CAA',
    'selection.background': '#746f77',
    'sideBar.background': '#23262E',
    'sideBar.foreground': '#999999',
    'sideBarSectionHeader.background': '#23262E',
    'sideBarTitle.foreground': '#00e8c6',
    'statusBar.background': '#23262E',
    'statusBar.debuggingBackground': '#FC644D',
    'statusBar.noFolderBackground': '#23262E',
    'statusBarItem.activeBackground': '#00e8c5cc',
    'statusBarItem.hoverBackground': '#07d4b5b0',
    'statusBarItem.prominentBackground': '#07d4b5b0',
    'statusBarItem.prominentHoverBackground': '#00e8c5cc',
    'tab.activeBackground': '#23262e',
    'tab.activeBorder': '#00e8c6',
    'tab.activeForeground': '#00e8c6',
    'tab.inactiveBackground': '#23262E',
    'tab.inactiveForeground': '#746f77',
    'terminal.ansiBlue': '#7cb7ff',
    'terminal.ansiBrightBlue': '#7cb7ff',
    'terminal.ansiBrightCyan': '#00e8c6',
    'terminal.ansiBrightGreen': '#96E072',
    'terminal.ansiBrightMagenta': '#ff00aa',
    'terminal.ansiBrightRed': '#ee5d43',
    'terminal.ansiBrightYellow': '#FFE66D',
    'terminal.ansiCyan': '#00e8c6',
    'terminal.ansiGreen': '#96E072',
    'terminal.ansiMagenta': '#ff00aa',
    'terminal.ansiRed': '#ee5d43',
    'terminal.ansiYellow': '#FFE66D',
    'terminalCursor.background': '#23262E',
    'terminalCursor.foreground': '#FFE66D',
    'titleBar.activeBackground': '#23262E',
    'walkThrough.embeddedEditorBackground': '#23262E',
    'widget.shadow': '#14151A',
  },
  rules: [
    {
      token: 'comment',
      foreground: 'A0A1A7cc',
    },
    {
      token: 'markup.quote.markdown',
      foreground: 'A0A1A7cc',
    },
    {
      token: 'meta.diff',
      foreground: 'A0A1A7cc',
    },
    {
      token: 'meta.diff.header',
      foreground: 'A0A1A7cc',
    },
    {
      token: 'meta.template.expression.js',
      foreground: 'D5CED9',
    },
    {
      token: 'constant.name.attribute.tag.jade',
      foreground: 'D5CED9',
    },
    {
      token: 'punctuation.definition.metadata.markdown',
      foreground: 'D5CED9',
    },
    {
      token: 'punctuation.definition.string.end.markdown',
      foreground: 'D5CED9',
    },
    {
      token: 'punctuation.definition.string.begin.markdown',
      foreground: 'D5CED9',
    },
    {
      token: 'variable',
      foreground: '00e8c6',
    },
    {
      token: 'support.variable',
      foreground: '00e8c6',
    },
    {
      token: 'entity.name.tag.yaml',
      foreground: '00e8c6',
    },
    {
      token: 'constant.character.entity.html',
      foreground: '00e8c6',
    },
    {
      token: 'source.css entity.name.tag.reference',
      foreground: '00e8c6',
    },
    {
      token: 'beginning.punctuation.definition.list.markdown',
      foreground: '00e8c6',
    },
    {
      token: 'source.css entity.other.attribute-name.parent-selector',
      foreground: '00e8c6',
    },
    {
      token: 'meta.structure.dictionary.json support.type.property-name',
      foreground: '00e8c6',
    },
    {
      token: 'markup.bold',
      foreground: 'f39c12',
    },
    {
      token: 'constant.numeric',
      foreground: 'f39c12',
    },
    {
      token: 'meta.group.regexp',
      foreground: 'f39c12',
    },
    {
      token: 'constant.other.php',
      foreground: 'f39c12',
    },
    {
      token: 'support.constant.ext.php',
      foreground: 'f39c12',
    },
    {
      token: 'constant.other.class.php',
      foreground: 'f39c12',
    },
    {
      token: 'support.constant.core.php',
      foreground: 'f39c12',
    },
    {
      token: 'fenced_code.block.language',
      foreground: 'f39c12',
    },
    {
      token: 'constant.other.caps.python',
      foreground: 'f39c12',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: 'f39c12',
    },
    {
      token: 'support.type.exception.python',
      foreground: 'f39c12',
    },
    {
      token: 'source.css keyword.other.unit',
      foreground: 'f39c12',
    },
    {
      token: 'variable.other.object.property.js.jsx',
      foreground: 'f39c12',
    },
    {
      token: 'variable.other.object.js',
      foreground: 'f39c12',
    },
    {
      token: 'markup.list',
      foreground: 'FFE66D',
    },
    {
      token: 'text.xml string',
      foreground: 'FFE66D',
    },
    {
      token: 'entity.name.type',
      foreground: 'FFE66D',
    },
    {
      token: 'support.function',
      foreground: 'FFE66D',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: 'FFE66D',
    },
    {
      token: 'meta.at-rule.extend',
      foreground: 'FFE66D',
    },
    {
      token: 'entity.name.function',
      foreground: 'FFE66D',
    },
    {
      token: 'entity.other.inherited-class',
      foreground: 'FFE66D',
    },
    {
      token: 'entity.other.keyframe-offset.css',
      foreground: 'FFE66D',
    },
    {
      token: 'text.html.markdown string.quoted',
      foreground: 'FFE66D',
    },
    {
      token: 'meta.function-call.generic.python',
      foreground: 'FFE66D',
    },
    {
      token: 'meta.at-rule.extend support.constant',
      foreground: 'FFE66D',
    },
    {
      token: 'entity.other.attribute-name.class.jade',
      foreground: 'FFE66D',
    },
    {
      token: 'source.css entity.other.attribute-name',
      foreground: 'FFE66D',
    },
    {
      token: 'text.xml punctuation.definition.string',
      foreground: 'FFE66D',
    },
    {
      token: 'markup.heading',
      foreground: 'ff00aa',
    },
    {
      token: 'variable.language.this.js',
      foreground: 'ff00aa',
    },
    {
      token: 'variable.language.special.self.python',
      foreground: 'ff00aa',
    },
    {
      token: 'punctuation.definition.interpolation',
      foreground: 'f92672',
    },
    {
      token: 'punctuation.section.embedded.end.php',
      foreground: 'f92672',
    },
    {
      token: 'punctuation.section.embedded.end.ruby',
      foreground: 'f92672',
    },
    {
      token: 'punctuation.section.embedded.begin.php',
      foreground: 'f92672',
    },
    {
      token: 'punctuation.section.embedded.begin.ruby',
      foreground: 'f92672',
    },
    {
      token: 'punctuation.definition.template-expression',
      foreground: 'f92672',
    },
    {
      token: 'entity.name.tag',
      foreground: 'f92672',
    },
    {
      token: 'storage',
      foreground: 'c74ded',
    },
    {
      token: 'keyword',
      foreground: 'c74ded',
    },
    {
      token: 'meta.link',
      foreground: 'c74ded',
    },
    {
      token: 'meta.image',
      foreground: 'c74ded',
    },
    {
      token: 'markup.italic',
      foreground: 'c74ded',
    },
    {
      token: 'source.js support.type',
      foreground: 'c74ded',
    },
    {
      token: 'string.regexp',
      foreground: '7cb7ff',
    },
    {
      token: 'markup.changed',
      foreground: '7cb7ff',
    },
    {
      token: 'constant',
      foreground: 'ee5d43',
    },
    {
      token: 'support.class',
      foreground: 'ee5d43',
    },
    {
      token: 'keyword.operator',
      foreground: 'ee5d43',
    },
    {
      token: 'support.constant',
      foreground: 'ee5d43',
    },
    {
      token: 'text.html.markdown string',
      foreground: 'ee5d43',
    },
    {
      token: 'source.css support.function',
      foreground: 'ee5d43',
    },
    {
      token: 'source.php support.function',
      foreground: 'ee5d43',
    },
    {
      token: 'support.function.magic.python',
      foreground: 'ee5d43',
    },
    {
      token: 'entity.other.attribute-name.id',
      foreground: 'ee5d43',
    },
    {
      token: 'markup.deleted',
      foreground: 'ee5d43',
    },
    {
      token: 'string',
      foreground: '96E072',
    },
    {
      token: 'text.html.php string',
      foreground: '96E072',
    },
    {
      token: 'markup.inline.raw',
      foreground: '96E072',
    },
    {
      token: 'markup.inserted',
      foreground: '96E072',
    },
    {
      token: 'punctuation.definition.string',
      foreground: '96E072',
    },
    {
      token: 'punctuation.definition.markdown',
      foreground: '96E072',
    },
    {
      token: 'text.html meta.embedded source.js string',
      foreground: '96E072',
    },
    {
      token: 'text.html.php punctuation.definition.string',
      foreground: '96E072',
    },
    {
      token: 'text.html meta.embedded source.js punctuation.definition.string',
      foreground: '96E072',
    },
    {
      token: 'text.html punctuation.definition.string',
      foreground: '96E072',
    },
    {
      token: 'text.html string',
      foreground: '96E072',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
