import * as monaco from 'monaco-editor';

export default {
  base: 'vs',
  inherit: false,
  colors: {
    'activityBar.background': '#161F26',
    'activityBar.dropBackground': '#FFFFFF',
    'activityBar.foreground': '#FFFFFF',
    'activityBarBadge.background': '#8AE773',
    'activityBarBadge.foreground': '#FFFFFF',
    'badge.background': '#8AE773',
    'breadcrumb.focusForeground': '#475663',
    'breadcrumb.foreground': '#161F26',
    'button.background': '#475663',
    'button.foreground': '#FFFFFF',
    'button.hoverBackground': '#161F26',
    'debugExceptionWidget.background': '#AED4FB',
    'debugExceptionWidget.border': '#161F26',
    'debugToolBar.background': '#161F26',
    'dropdown.background': '#FFFFFF',
    'dropdown.border': '#DCDEDF',
    'dropdown.foreground': '#DCDEDF',
    'dropdown.listBackground': '#FFFFFF',
    'editor.background': '#FFFFFF',
    'editor.findMatchBackground': '#AED4FB',
    'editor.foreground': '#000000',
    'editor.lineHighlightBackground': '#EEEEEE',
    'editor.selectionBackground': '#AED4FB',
    'editor.wordHighlightBackground': '#AED4FB',
    'editor.wordHighlightStrongBackground': '#EEEEEE',
    'editorActiveLineNumber.foreground': '#475663',
    'editorGroup.emptyBackground': '#2D3E4C',
    'editorGroup.focusedEmptyBorder': '#2D3E4C',
    'editorGroupHeader.tabsBackground': '#2D3E4C',
    'editorHint.border': '#F9F9F9',
    'editorHint.foreground': '#F9F9F9',
    'editorIndentGuide.activeBackground': '#dbdbdb',
    'editorIndentGuide.background': '#F3F3F3',
    'editorLineNumber.foreground': '#b9b9b9',
    'editorMarkerNavigation.background': '#F9F9F9',
    'editorMarkerNavigationError.background': '#F44C5E',
    'editorMarkerNavigationInfo.background': '#6182b8',
    'editorMarkerNavigationWarning.background': '#F6B555',
    'editorPane.background': '#2D3E4C',
    'editorSuggestWidget.foreground': '#2D3E4C',
    'editorSuggestWidget.highlightForeground': '#2D3E4C',
    'editorSuggestWidget.selectedBackground': '#b9b9b9',
    'editorWidget.background': '#F9F9F9',
    'editorWidget.border': '#dbdbdb',
    'extensionButton.prominentBackground': '#475663',
    'extensionButton.prominentForeground': '#F6F6F6',
    'extensionButton.prominentHoverBackground': '#161F26',
    focusBorder: '#161F26',
    foreground: '#616161',
    'gitDecoration.addedResourceForeground': '#ECB22E',
    'gitDecoration.conflictingResourceForeground': '#FFFFFF',
    'gitDecoration.deletedResourceForeground': '#FFFFFF',
    'gitDecoration.ignoredResourceForeground': '#877583',
    'gitDecoration.modifiedResourceForeground': '#ECB22E',
    'gitDecoration.untrackedResourceForeground': '#ECB22E',
    'input.background': '#FFFFFF',
    'input.border': '#161F26',
    'input.foreground': '#000000',
    'input.placeholderForeground': '#a0a0a0',
    'inputOption.activeBorder': '#3E313C',
    'inputValidation.errorBackground': '#F44C5E',
    'inputValidation.errorForeground': '#FFFFFF',
    'inputValidation.infoBackground': '#6182b8',
    'inputValidation.infoForeground': '#FFFFFF',
    'inputValidation.warningBackground': '#F6B555',
    'inputValidation.warningForeground': '#000000',
    'list.activeSelectionBackground': '#5899C5',
    'list.activeSelectionForeground': '#ffffff',
    'list.focusBackground': '#d5e1ea',
    'list.focusForeground': '#ffffff',
    'list.highlightForeground': '#2D3E4C',
    'list.hoverBackground': '#d5e1ea',
    'list.hoverForeground': '#ffffff',
    'list.inactiveFocusBackground': '#161F26',
    'list.inactiveSelectionBackground': '#5899C5',
    'list.inactiveSelectionForeground': '#ffffff',
    'list.invalidItemForeground': '#ffffff',
    'menu.background': '#161F26',
    'menu.foreground': '#F9FAFA',
    'menu.separatorBackground': '#F9FAFA',
    'notificationCenter.border': '#161F26',
    'notificationCenterHeader.foreground': '#FFFFFF',
    'notificationLink.foreground': '#FFFFFF',
    'notificationToast.border': '#161F26',
    'notifications.background': '#161F26',
    'notifications.border': '#161F26',
    'notifications.foreground': '#FFFFFF',
    'panel.border': '#2D3E4C',
    'panelTitle.activeForeground': '#161F26',
    'progressBar.background': '#8AE773',
    'scrollbar.shadow': '#ffffff00',
    'scrollbarSlider.activeBackground': '#161F267e',
    'scrollbarSlider.background': '#161F267e',
    'scrollbarSlider.hoverBackground': '#161F267e',
    'settings.dropdownBorder': '#161F26',
    'settings.dropdownForeground': '#161F26',
    'settings.headerForeground': '#161F26',
    'sideBar.background': '#2D3E4C',
    'sideBar.foreground': '#DCDEDF',
    'sideBarSectionHeader.background': '#161F26',
    'sideBarSectionHeader.foreground': '#FFFFFF',
    'sideBarTitle.foreground': '#FFFFFF',
    'statusBar.background': '#5899C5',
    'statusBar.debuggingBackground': '#8AE773',
    'statusBar.foreground': '#FFFFFF',
    'statusBar.noFolderBackground': '#161F26',
    'tab.activeBackground': '#FFFFFF',
    'tab.activeForeground': '#000000',
    'tab.border': '#F3F3F3',
    'tab.inactiveBackground': '#F3F3F3',
    'tab.inactiveForeground': '#686868',
    'terminal.ansiBlack': '#000000',
    'terminal.ansiBlue': '#6182b8',
    'terminal.ansiBrightBlack': '#90a4ae',
    'terminal.ansiBrightBlue': '#6182b8',
    'terminal.ansiBrightCyan': '#39adb5',
    'terminal.ansiBrightGreen': '#91b859',
    'terminal.ansiBrightMagenta': '#7c4dff',
    'terminal.ansiBrightRed': '#e53935',
    'terminal.ansiBrightWhite': '#ffffff',
    'terminal.ansiBrightYellow': '#ffb62c',
    'terminal.ansiCyan': '#39adb5',
    'terminal.ansiGreen': '#91b859',
    'terminal.ansiMagenta': '#7c4dff',
    'terminal.ansiRed': '#e53935',
    'terminal.ansiWhite': '#ffffff',
    'terminal.ansiYellow': '#ffb62c',
    'terminal.border': '#2D3E4C',
    'terminal.foreground': '#161F26',
    'terminal.selectionBackground': '#00000066',
    'textPreformat.foreground': '#161F26',
    'titleBar.activeBackground': '#2D3E4C',
    'titleBar.activeForeground': '#FFFFFF',
    'titleBar.border': '#2D3E4C',
    'titleBar.inactiveBackground': '#161F26',
    'titleBar.inactiveForeground': '#685C66',
    'welcomePage.buttonBackground': '#F3F3F3',
    'welcomePage.buttonHoverBackground': '#ECECEC',
    'widget.shadow': '#161F2694',
  },
  rules: [
    {
      token: 'meta.paragraph.markdown',
      foreground: '110000',
    },
    {
      token: 'string.other.link.description.title.markdown',
      foreground: '110000',
    },
    {
      token: 'entity.name.section.markdown',
      foreground: '034c7c',
    },
    {
      token: 'punctuation.definition.heading.markdown',
      foreground: '034c7c',
    },
    {
      token: 'punctuation.definition.string.begin.markdown',
      foreground: '00AC8F',
    },
    {
      token: 'punctuation.definition.string.end.markdown',
      foreground: '00AC8F',
    },
    {
      token: 'markup.quote.markdown',
      foreground: '00AC8F',
    },
    {
      token: 'markup.quote.markdown',
      foreground: '003494',
    },
    {
      token: 'markup.bold.markdown',
      foreground: '4e76b5',
    },
    {
      token: 'punctuation.definition.bold.markdown',
      foreground: '4e76b5',
    },
    {
      token: 'markup.italic.markdown',
      foreground: 'C792EA',
    },
    {
      token: 'punctuation.definition.italic.markdown',
      foreground: 'C792EA',
    },
    {
      token: 'markup.inline.raw.string.markdown',
      foreground: '0460b1',
    },
    {
      token: 'markup.fenced_code.block.markdown',
      foreground: '0460b1',
    },
    {
      token: 'punctuation.definition.metadata.markdown',
      foreground: '00AC8F',
    },
    {
      token: 'markup.underline.link.image.markdown',
      foreground: '924205',
    },
    {
      token: 'markup.underline.link.markdown',
      foreground: '924205',
    },
    {
      token: 'comment',
      foreground: '357b42',
    },
    {
      token: 'string',
      foreground: 'a44185',
    },
    {
      token: 'constant.numeric',
      foreground: '174781',
    },
    {
      token: 'constant',
      foreground: '174781',
    },
    {
      token: 'language.method',
      foreground: '174781',
    },
    {
      token: 'constant.character',
      foreground: '174781',
    },
    {
      token: 'constant.other',
      foreground: '174781',
    },
    {
      token: 'variable',
      foreground: '2f86d2',
    },
    {
      token: 'variable.language.this',
      foreground: '000000',
    },
    {
      token: 'keyword',
      foreground: '7b30d0',
    },
    {
      token: 'storage',
      foreground: 'da5221',
    },
    {
      token: 'storage.type',
      foreground: '0991b6',
    },
    {
      token: 'entity.name.class',
      foreground: '1172c7',
    },
    {
      token: 'entity.other.inherited-class',
      foreground: 'b02767',
    },
    {
      token: 'entity.name.function',
      foreground: '7eb233',
    },
    {
      token: 'variable.parameter',
      foreground: 'b1108e',
    },
    {
      token: 'entity.name.tag',
      foreground: '0444ac',
    },
    {
      token: 'text.html.basic',
      foreground: '0071ce',
    },
    {
      token: 'entity.name.type',
      foreground: '0444ac',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: 'df8618',
    },
    {
      token: 'support.function',
      foreground: '1ab394',
    },
    {
      token: 'support.constant',
      foreground: '174781',
    },
    {
      token: 'support.type',
      foreground: 'dc3eb7',
    },
    {
      token: 'support.class',
      foreground: 'dc3eb7',
    },
    {
      token: 'support.other.variable',
      foreground: '224555',
    },
    {
      token: 'invalid',
      foreground: '207bb8',
    },
    {
      token: 'invalid.deprecated',
      foreground: '207bb8',
    },
    {
      token: 'source.json support',
      foreground: '6dbdfa',
    },
    {
      token: 'source.json string',
      foreground: '00820f',
    },
    {
      token: 'source.json punctuation.definition.string',
      foreground: '00820f',
    },
    {
      token: 'markup.list',
      foreground: '207bb8',
    },
    {
      token: 'markup.heading punctuation.definition.heading',
      foreground: '4FB4D8',
    },
    {
      token: 'entity.name.section',
      foreground: '4FB4D8',
    },
    {
      token: 'text.html.markdown meta.paragraph meta.link.inline',
      foreground: '87429A',
    },
    {
      token:
        'text.html.markdown meta.paragraph meta.link.inline punctuation.definition.string.begin.markdown',
      foreground: '87429A',
    },
    {
      token:
        'text.html.markdown meta.paragraph meta.link.inline punctuation.definition.string.end.markdown',
      foreground: '87429A',
    },
    {
      token: 'markup.quote',
      foreground: '87429A',
    },
    {
      token: 'markup.bold',
      foreground: '08134A',
    },
    {
      token: 'markup.italic',
      foreground: '174781',
    },
    {
      token: 'punctuation.definition.italic',
      foreground: '174781',
    },
    {
      token: 'meta.link',
      foreground: '87429A',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
