import * as monaco from 'monaco-editor';

export default {
  base: 'vs-dark',
  inherit: false,
  colors: {
    'activityBar.activeBackground': '#3b4252',
    'activityBar.activeBorder': '#88c0d0',
    'activityBar.background': '#2e3440',
    'activityBar.dropBackground': '#3b4252',
    'activityBar.foreground': '#d8dee9',
    'activityBarBadge.background': '#88c0d0',
    'activityBarBadge.foreground': '#2e3440',
    'badge.background': '#88c0d0',
    'badge.foreground': '#2e3440',
    'button.background': '#88c0d0ee',
    'button.foreground': '#2e3440',
    'button.hoverBackground': '#88c0d0',
    'button.secondaryBackground': '#434c5e',
    'button.secondaryForeground': '#d8dee9',
    'button.secondaryHoverBackground': '#4c566a',
    'charts.blue': '#81a1c1',
    'charts.foreground': '#d8dee9',
    'charts.green': '#a3be8c',
    'charts.lines': '#88c0d0',
    'charts.orange': '#d08770',
    'charts.purple': '#b48ead',
    'charts.red': '#bf616a',
    'charts.yellow': '#ebcb8b',
    'debugConsole.errorForeground': '#bf616a',
    'debugConsole.infoForeground': '#88c0d0',
    'debugConsole.sourceForeground': '#616e88',
    'debugConsole.warningForeground': '#ebcb8b',
    'debugConsoleInputIcon.foreground': '#81a1c1',
    'debugExceptionWidget.background': '#4c566a',
    'debugExceptionWidget.border': '#2e3440',
    'debugToolBar.background': '#3b4252',
    descriptionForeground: '#d8dee9e6',
    'diffEditor.insertedTextBackground': '#81a1c133',
    'diffEditor.removedTextBackground': '#bf616a4d',
    'dropdown.background': '#3b4252',
    'dropdown.border': '#3b4252',
    'dropdown.foreground': '#d8dee9',
    'editor.background': '#2e3440',
    'editor.findMatchBackground': '#88c0d066',
    'editor.findMatchHighlightBackground': '#88c0d033',
    'editor.findRangeHighlightBackground': '#88c0d033',
    'editor.focusedStackFrameHighlightBackground': '#5e81ac',
    'editor.foreground': '#d8dee9',
    'editor.hoverHighlightBackground': '#3b4252',
    'editor.inactiveSelectionBackground': '#434c5ecc',
    'editor.inlineValuesBackground': '#4c566a',
    'editor.inlineValuesForeground': '#eceff4',
    'editor.lineHighlightBackground': '#3b4252',
    'editor.lineHighlightBorder': '#3b4252',
    'editor.rangeHighlightBackground': '#434c5e52',
    'editor.selectionBackground': '#434c5ecc',
    'editor.selectionHighlightBackground': '#434c5ecc',
    'editor.stackFrameHighlightBackground': '#5e81ac',
    'editor.wordHighlightBackground': '#81a1c166',
    'editor.wordHighlightStrongBackground': '#81a1c199',
    'editorActiveLineNumber.foreground': '#d8dee9cc',
    'editorBracketHighlight.foreground1': '#8fbcbb',
    'editorBracketHighlight.foreground2': '#88c0d0',
    'editorBracketHighlight.foreground3': '#81a1c1',
    'editorBracketHighlight.foreground4': '#5e81ac',
    'editorBracketHighlight.foreground5': '#8fbcbb',
    'editorBracketHighlight.foreground6': '#88c0d0',
    'editorBracketHighlight.unexpectedBracket.foreground': '#bf616a',
    'editorBracketMatch.background': '#2e344000',
    'editorBracketMatch.border': '#88c0d0',
    'editorCodeLens.foreground': '#4c566a',
    'editorCursor.foreground': '#d8dee9',
    'editorError.border': '#bf616a00',
    'editorError.foreground': '#bf616a',
    'editorGroup.background': '#2e3440',
    'editorGroup.border': '#3b425201',
    'editorGroup.dropBackground': '#3b425299',
    'editorGroupHeader.border': '#3b425200',
    'editorGroupHeader.noTabsBackground': '#2e3440',
    'editorGroupHeader.tabsBackground': '#2e3440',
    'editorGroupHeader.tabsBorder': '#3b425200',
    'editorGutter.addedBackground': '#a3be8c',
    'editorGutter.background': '#2e3440',
    'editorGutter.deletedBackground': '#bf616a',
    'editorGutter.modifiedBackground': '#ebcb8b',
    'editorHint.border': '#ebcb8b00',
    'editorHint.foreground': '#ebcb8b',
    'editorHoverWidget.background': '#3b4252',
    'editorHoverWidget.border': '#3b4252',
    'editorIndentGuide.activeBackground': '#4c566a',
    'editorIndentGuide.background': '#434c5eb3',
    'editorInlayHint.background': '#434c5e',
    'editorInlayHint.foreground': '#d8dee9',
    'editorLineNumber.activeForeground': '#d8dee9',
    'editorLineNumber.foreground': '#4c566a',
    'editorLink.activeForeground': '#88c0d0',
    'editorMarkerNavigation.background': '#5e81acc0',
    'editorMarkerNavigationError.background': '#bf616ac0',
    'editorMarkerNavigationWarning.background': '#ebcb8bc0',
    'editorOverviewRuler.addedForeground': '#a3be8c',
    'editorOverviewRuler.border': '#3b4252',
    'editorOverviewRuler.currentContentForeground': '#3b4252',
    'editorOverviewRuler.deletedForeground': '#bf616a',
    'editorOverviewRuler.errorForeground': '#bf616a',
    'editorOverviewRuler.findMatchForeground': '#88c0d066',
    'editorOverviewRuler.incomingContentForeground': '#3b4252',
    'editorOverviewRuler.infoForeground': '#81a1c1',
    'editorOverviewRuler.modifiedForeground': '#ebcb8b',
    'editorOverviewRuler.rangeHighlightForeground': '#88c0d066',
    'editorOverviewRuler.selectionHighlightForeground': '#88c0d066',
    'editorOverviewRuler.warningForeground': '#ebcb8b',
    'editorOverviewRuler.wordHighlightForeground': '#88c0d066',
    'editorOverviewRuler.wordHighlightStrongForeground': '#88c0d066',
    'editorRuler.foreground': '#434c5e',
    'editorSuggestWidget.background': '#2e3440',
    'editorSuggestWidget.border': '#3b4252',
    'editorSuggestWidget.focusHighlightForeground': '#88c0d0',
    'editorSuggestWidget.foreground': '#d8dee9',
    'editorSuggestWidget.highlightForeground': '#88c0d0',
    'editorSuggestWidget.selectedBackground': '#434c5e',
    'editorSuggestWidget.selectedForeground': '#d8dee9',
    'editorWarning.border': '#ebcb8b00',
    'editorWarning.foreground': '#ebcb8b',
    'editorWhitespace.foreground': '#4c566ab3',
    'editorWidget.background': '#2e3440',
    'editorWidget.border': '#3b4252',
    errorForeground: '#bf616a',
    'extensionButton.prominentBackground': '#434c5e',
    'extensionButton.prominentForeground': '#d8dee9',
    'extensionButton.prominentHoverBackground': '#4c566a',
    focusBorder: '#3b4252',
    foreground: '#d8dee9',
    'gitDecoration.conflictingResourceForeground': '#5e81ac',
    'gitDecoration.deletedResourceForeground': '#bf616a',
    'gitDecoration.ignoredResourceForeground': '#d8dee966',
    'gitDecoration.modifiedResourceForeground': '#ebcb8b',
    'gitDecoration.stageDeletedResourceForeground': '#bf616a',
    'gitDecoration.stageModifiedResourceForeground': '#ebcb8b',
    'gitDecoration.submoduleResourceForeground': '#8fbcbb',
    'gitDecoration.untrackedResourceForeground': '#a3be8c',
    'input.background': '#3b4252',
    'input.border': '#3b4252',
    'input.foreground': '#d8dee9',
    'input.placeholderForeground': '#d8dee999',
    'inputOption.activeBackground': '#5e81ac',
    'inputOption.activeBorder': '#5e81ac',
    'inputOption.activeForeground': '#eceff4',
    'inputValidation.errorBackground': '#bf616a',
    'inputValidation.errorBorder': '#bf616a',
    'inputValidation.infoBackground': '#81a1c1',
    'inputValidation.infoBorder': '#81a1c1',
    'inputValidation.warningBackground': '#d08770',
    'inputValidation.warningBorder': '#d08770',
    'keybindingLabel.background': '#4c566a',
    'keybindingLabel.border': '#4c566a',
    'keybindingLabel.bottomBorder': '#4c566a',
    'keybindingLabel.foreground': '#d8dee9',
    'list.activeSelectionBackground': '#88c0d0',
    'list.activeSelectionForeground': '#2e3440',
    'list.dropBackground': '#88c0d099',
    'list.errorForeground': '#bf616a',
    'list.focusBackground': '#88c0d099',
    'list.focusForeground': '#d8dee9',
    'list.focusHighlightForeground': '#eceff4',
    'list.highlightForeground': '#88c0d0',
    'list.hoverBackground': '#3b4252',
    'list.hoverForeground': '#eceff4',
    'list.inactiveFocusBackground': '#434c5ecc',
    'list.inactiveSelectionBackground': '#434c5e',
    'list.inactiveSelectionForeground': '#d8dee9',
    'list.warningForeground': '#ebcb8b',
    'merge.border': '#3b425200',
    'merge.currentContentBackground': '#81a1c14d',
    'merge.currentHeaderBackground': '#81a1c166',
    'merge.incomingContentBackground': '#8fbcbb4d',
    'merge.incomingHeaderBackground': '#8fbcbb66',
    'minimap.background': '#2e3440',
    'minimap.errorHighlight': '#bf616acc',
    'minimap.findMatchHighlight': '#88c0d0',
    'minimap.selectionHighlight': '#88c0d0cc',
    'minimap.warningHighlight': '#ebcb8bcc',
    'minimapGutter.addedBackground': '#a3be8c',
    'minimapGutter.deletedBackground': '#bf616a',
    'minimapGutter.modifiedBackground': '#ebcb8b',
    'minimapSlider.activeBackground': '#434c5eaa',
    'minimapSlider.background': '#434c5e99',
    'minimapSlider.hoverBackground': '#434c5eaa',
    'notification.background': '#3b4252',
    'notification.buttonBackground': '#434c5e',
    'notification.buttonForeground': '#d8dee9',
    'notification.buttonHoverBackground': '#4c566a',
    'notification.errorBackground': '#bf616a',
    'notification.errorForeground': '#2e3440',
    'notification.foreground': '#d8dee9',
    'notification.infoBackground': '#88c0d0',
    'notification.infoForeground': '#2e3440',
    'notification.warningBackground': '#ebcb8b',
    'notification.warningForeground': '#2e3440',
    'notificationCenter.border': '#3b425200',
    'notificationCenterHeader.background': '#2e3440',
    'notificationCenterHeader.foreground': '#88c0d0',
    'notificationLink.foreground': '#88c0d0',
    'notificationToast.border': '#3b425200',
    'notifications.background': '#3b4252',
    'notifications.border': '#2e3440',
    'notifications.foreground': '#d8dee9',
    'panel.background': '#2e3440',
    'panel.border': '#3b4252',
    'panelTitle.activeBorder': '#88c0d000',
    'panelTitle.activeForeground': '#88c0d0',
    'panelTitle.inactiveForeground': '#d8dee9',
    'peekView.border': '#4c566a',
    'peekViewEditor.background': '#2e3440',
    'peekViewEditor.matchHighlightBackground': '#88c0d04d',
    'peekViewEditorGutter.background': '#2e3440',
    'peekViewResult.background': '#2e3440',
    'peekViewResult.fileForeground': '#88c0d0',
    'peekViewResult.lineForeground': '#d8dee966',
    'peekViewResult.matchHighlightBackground': '#88c0d0cc',
    'peekViewResult.selectionBackground': '#434c5e',
    'peekViewResult.selectionForeground': '#d8dee9',
    'peekViewTitle.background': '#3b4252',
    'peekViewTitleDescription.foreground': '#d8dee9',
    'peekViewTitleLabel.foreground': '#88c0d0',
    'pickerGroup.border': '#3b4252',
    'pickerGroup.foreground': '#88c0d0',
    'progressBar.background': '#88c0d0',
    'quickInputList.focusBackground': '#88c0d0',
    'quickInputList.focusForeground': '#2e3440',
    'sash.hoverBorder': '#88c0d0',
    'scrollbar.shadow': '#00000066',
    'scrollbarSlider.activeBackground': '#434c5eaa',
    'scrollbarSlider.background': '#434c5e99',
    'scrollbarSlider.hoverBackground': '#434c5eaa',
    'selection.background': '#88c0d099',
    'sideBar.background': '#2e3440',
    'sideBar.border': '#3b4252',
    'sideBar.foreground': '#d8dee9',
    'sideBarSectionHeader.background': '#3b4252',
    'sideBarSectionHeader.foreground': '#d8dee9',
    'sideBarTitle.foreground': '#d8dee9',
    'statusBar.background': '#3b4252',
    'statusBar.border': '#3b425200',
    'statusBar.debuggingBackground': '#5e81ac',
    'statusBar.debuggingForeground': '#d8dee9',
    'statusBar.foreground': '#d8dee9',
    'statusBar.noFolderBackground': '#3b4252',
    'statusBar.noFolderForeground': '#d8dee9',
    'statusBarItem.activeBackground': '#4c566a',
    'statusBarItem.errorBackground': '#3b4252',
    'statusBarItem.errorForeground': '#bf616a',
    'statusBarItem.hoverBackground': '#434c5e',
    'statusBarItem.prominentBackground': '#3b4252',
    'statusBarItem.prominentHoverBackground': '#434c5e',
    'statusBarItem.warningBackground': '#ebcb8b',
    'statusBarItem.warningForeground': '#2e3440',
    'tab.activeBackground': '#3b4252',
    'tab.activeBorder': '#88c0d000',
    'tab.activeBorderTop': '#88c0d000',
    'tab.activeForeground': '#d8dee9',
    'tab.border': '#3b425200',
    'tab.hoverBackground': '#3b4252cc',
    'tab.hoverBorder': '#88c0d000',
    'tab.inactiveBackground': '#2e3440',
    'tab.inactiveForeground': '#d8dee966',
    'tab.lastPinnedBorder': '#4c566a',
    'tab.unfocusedActiveBorder': '#88c0d000',
    'tab.unfocusedActiveBorderTop': '#88c0d000',
    'tab.unfocusedActiveForeground': '#d8dee999',
    'tab.unfocusedHoverBackground': '#3b4252b3',
    'tab.unfocusedHoverBorder': '#88c0d000',
    'tab.unfocusedInactiveForeground': '#d8dee966',
    'terminal.ansiBlack': '#3b4252',
    'terminal.ansiBlue': '#81a1c1',
    'terminal.ansiBrightBlack': '#4c566a',
    'terminal.ansiBrightBlue': '#81a1c1',
    'terminal.ansiBrightCyan': '#8fbcbb',
    'terminal.ansiBrightGreen': '#a3be8c',
    'terminal.ansiBrightMagenta': '#b48ead',
    'terminal.ansiBrightRed': '#bf616a',
    'terminal.ansiBrightWhite': '#eceff4',
    'terminal.ansiBrightYellow': '#ebcb8b',
    'terminal.ansiCyan': '#88c0d0',
    'terminal.ansiGreen': '#a3be8c',
    'terminal.ansiMagenta': '#b48ead',
    'terminal.ansiRed': '#bf616a',
    'terminal.ansiWhite': '#e5e9f0',
    'terminal.ansiYellow': '#ebcb8b',
    'terminal.background': '#2e3440',
    'terminal.foreground': '#d8dee9',
    'terminal.tab.activeBorder': '#88c0d0',
    'textBlockQuote.background': '#3b4252',
    'textBlockQuote.border': '#81a1c1',
    'textCodeBlock.background': '#4c566a',
    'textLink.activeForeground': '#88c0d0',
    'textLink.foreground': '#88c0d0',
    'textPreformat.foreground': '#8fbcbb',
    'textSeparator.foreground': '#eceff4',
    'titleBar.activeBackground': '#2e3440',
    'titleBar.activeForeground': '#d8dee9',
    'titleBar.border': '#2e344000',
    'titleBar.inactiveBackground': '#2e3440',
    'titleBar.inactiveForeground': '#d8dee966',
    'tree.indentGuidesStroke': '#616e88',
    'walkThrough.embeddedEditorBackground': '#2e3440',
    'welcomePage.buttonBackground': '#434c5e',
    'welcomePage.buttonHoverBackground': '#4c566a',
    'widget.shadow': '#00000066',
  },
  rules: [
    {
      token: 'comment',
      foreground: '616E88',
    },
    {
      token: 'constant.character',
      foreground: 'EBCB8B',
    },
    {
      token: 'constant.character.escape',
      foreground: 'EBCB8B',
    },
    {
      token: 'constant.language',
      foreground: '81A1C1',
    },
    {
      token: 'constant.numeric',
      foreground: 'B48EAD',
    },
    {
      token: 'constant.regexp',
      foreground: 'EBCB8B',
    },
    {
      token: 'entity.name.class',
      foreground: '8FBCBB',
    },
    {
      token: 'entity.name.type.class',
      foreground: '8FBCBB',
    },
    {
      token: 'entity.name.function',
      foreground: '88C0D0',
    },
    {
      token: 'entity.name.tag',
      foreground: '81A1C1',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: '8FBCBB',
    },
    {
      token: 'entity.other.inherited-class',
      foreground: '8FBCBB',
    },
    {
      token: 'invalid.deprecated',
      foreground: 'D8DEE9',
    },
    {
      token: 'invalid.illegal',
      foreground: 'D8DEE9',
    },
    {
      token: 'keyword',
      foreground: '81A1C1',
    },
    {
      token: 'keyword.operator',
      foreground: '81A1C1',
    },
    {
      token: 'keyword.other.new',
      foreground: '81A1C1',
    },
    {
      token: 'markup.changed',
      foreground: 'EBCB8B',
    },
    {
      token: 'markup.deleted',
      foreground: 'BF616A',
    },
    {
      token: 'markup.inserted',
      foreground: 'A3BE8C',
    },
    {
      token: 'meta.preprocessor',
      foreground: '5E81AC',
    },
    {
      token: 'punctuation',
      foreground: 'ECEFF4',
    },
    {
      token: 'punctuation.definition.method-parameters',
      foreground: 'ECEFF4',
    },
    {
      token: 'punctuation.definition.function-parameters',
      foreground: 'ECEFF4',
    },
    {
      token: 'punctuation.definition.parameters',
      foreground: 'ECEFF4',
    },
    {
      token: 'punctuation.definition.tag',
      foreground: '81A1C1',
    },
    {
      token: 'punctuation.definition.comment',
      foreground: '616E88',
    },
    {
      token: 'punctuation.end.definition.comment',
      foreground: '616E88',
    },
    {
      token: 'punctuation.start.definition.comment',
      foreground: '616E88',
    },
    {
      token: 'punctuation.section',
      foreground: 'ECEFF4',
    },
    {
      token: 'punctuation.section.embedded.begin',
      foreground: '81A1C1',
    },
    {
      token: 'punctuation.section.embedded.end',
      foreground: '81A1C1',
    },
    {
      token: 'punctuation.terminator',
      foreground: '81A1C1',
    },
    {
      token: 'punctuation.definition.variable',
      foreground: '81A1C1',
    },
    {
      token: 'storage',
      foreground: '81A1C1',
    },
    {
      token: 'string',
      foreground: 'A3BE8C',
    },
    {
      token: 'string.regexp',
      foreground: 'EBCB8B',
    },
    {
      token: 'support.class',
      foreground: '8FBCBB',
    },
    {
      token: 'support.constant',
      foreground: '81A1C1',
    },
    {
      token: 'support.function',
      foreground: '88C0D0',
    },
    {
      token: 'support.function.construct',
      foreground: '81A1C1',
    },
    {
      token: 'support.type',
      foreground: '8FBCBB',
    },
    {
      token: 'support.type.exception',
      foreground: '8FBCBB',
    },
    {
      token: 'token.debug-token',
      foreground: 'b48ead',
    },
    {
      token: 'token.error-token',
      foreground: 'bf616a',
    },
    {
      token: 'token.info-token',
      foreground: '88c0d0',
    },
    {
      token: 'token.warn-token',
      foreground: 'ebcb8b',
    },
    {
      token: 'variable.other',
      foreground: 'D8DEE9',
    },
    {
      token: 'variable.language',
      foreground: '81A1C1',
    },
    {
      token: 'variable.parameter',
      foreground: 'D8DEE9',
    },
    {
      token: 'punctuation.separator.pointer-access.c',
      foreground: '81A1C1',
    },
    {
      token: 'source.c meta.preprocessor.include',
      foreground: '8FBCBB',
    },
    {
      token: 'source.c string.quoted.other.lt-gt.include',
      foreground: '8FBCBB',
    },
    {
      token: 'source.cpp keyword.control.directive.conditional',
      foreground: '5E81AC',
    },
    {
      token: 'source.cpp punctuation.definition.directive',
      foreground: '5E81AC',
    },
    {
      token: 'source.c keyword.control.directive.conditional',
      foreground: '5E81AC',
    },
    {
      token: 'source.c punctuation.definition.directive',
      foreground: '5E81AC',
    },
    {
      token: 'source.css constant.other.color.rgb-value',
      foreground: 'B48EAD',
    },
    {
      token: 'source.css meta.property-value',
      foreground: '88C0D0',
    },
    {
      token: 'source.css keyword.control.at-rule.media',
      foreground: 'D08770',
    },
    {
      token:
        'source.css keyword.control.at-rule.media punctuation.definition.keyword',
      foreground: 'D08770',
    },
    {
      token: 'source.css punctuation.definition.keyword',
      foreground: '81A1C1',
    },
    {
      token: 'source.css support.type.property-name',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.diff meta.diff.range.context',
      foreground: '8FBCBB',
    },
    {
      token: 'source.diff meta.diff.header.from-file',
      foreground: '8FBCBB',
    },
    {
      token: 'source.diff punctuation.definition.from-file',
      foreground: '8FBCBB',
    },
    {
      token: 'source.diff punctuation.definition.range',
      foreground: '8FBCBB',
    },
    {
      token: 'source.diff punctuation.definition.separator',
      foreground: '81A1C1',
    },
    {
      token: 'entity.name.type.module.elixir',
      foreground: '8FBCBB',
    },
    {
      token: 'variable.other.readwrite.module.elixir',
      foreground: 'D8DEE9',
    },
    {
      token: 'constant.other.symbol.elixir',
      foreground: 'D8DEE9',
    },
    {
      token: 'variable.other.constant.elixir',
      foreground: '8FBCBB',
    },
    {
      token: 'source.go constant.other.placeholder.go',
      foreground: 'EBCB8B',
    },
    {
      token:
        'source.java comment.block.documentation.javadoc punctuation.definition.entity.html',
      foreground: '81A1C1',
    },
    {
      token: 'source.java constant.other',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.java keyword.other.documentation',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java keyword.other.documentation.author.javadoc',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java keyword.other.documentation.directive',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java keyword.other.documentation.custom',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java keyword.other.documentation.see.javadoc',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java meta.method-call meta.method',
      foreground: '88C0D0',
    },
    {
      token: 'source.java meta.tag.template.link.javadoc',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java string.other.link.title.javadoc',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java meta.tag.template.value.javadoc',
      foreground: '88C0D0',
    },
    {
      token: 'source.java punctuation.definition.keyword.javadoc',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java punctuation.definition.tag.begin.javadoc',
      foreground: '616E88',
    },
    {
      token: 'source.java punctuation.definition.tag.end.javadoc',
      foreground: '616E88',
    },
    {
      token: 'source.java storage.modifier.import',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java storage.modifier.package',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java storage.type',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java storage.type.annotation',
      foreground: 'D08770',
    },
    {
      token: 'source.java storage.type.generic',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java storage.type.primitive',
      foreground: '81A1C1',
    },
    {
      token: 'source.js punctuation.decorator',
      foreground: 'D08770',
    },
    {
      token: 'source.js meta.decorator variable.other.readwrite',
      foreground: 'D08770',
    },
    {
      token: 'source.js meta.decorator entity.name.function',
      foreground: 'D08770',
    },
    {
      token: 'source.js meta.object-literal.key',
      foreground: '88C0D0',
    },
    {
      token: 'source.js storage.type.class.jsdoc',
      foreground: '8FBCBB',
    },
    {
      token: 'source.js string.quoted.template punctuation.quasi.element.begin',
      foreground: '81A1C1',
    },
    {
      token: 'source.js string.quoted.template punctuation.quasi.element.end',
      foreground: '81A1C1',
    },
    {
      token:
        'source.js string.template punctuation.definition.template-expression',
      foreground: '81A1C1',
    },
    {
      token: 'source.js string.quoted.template meta.method-call.with-arguments',
      foreground: 'ECEFF4',
    },
    {
      token:
        'source.js string.template meta.template.expression support.variable.property',
      foreground: 'D8DEE9',
    },
    {
      token:
        'source.js string.template meta.template.expression variable.other.object',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.js support.type.primitive',
      foreground: '81A1C1',
    },
    {
      token: 'source.js variable.other.object',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.js variable.other.readwrite.alias',
      foreground: '8FBCBB',
    },
    {
      token: 'source.js meta.embedded.line meta.brace.square',
      foreground: 'ECEFF4',
    },
    {
      token: 'source.js meta.embedded.line meta.brace.round',
      foreground: 'ECEFF4',
    },
    {
      token: 'source.js string.quoted.template meta.brace.square',
      foreground: 'ECEFF4',
    },
    {
      token: 'source.js string.quoted.template meta.brace.round',
      foreground: 'ECEFF4',
    },
    {
      token: 'text.html.basic constant.character.entity.html',
      foreground: 'EBCB8B',
    },
    {
      token: 'text.html.basic constant.other.inline-data',
      foreground: 'D08770',
    },
    {
      token: 'text.html.basic meta.tag.sgml.doctype',
      foreground: '5E81AC',
    },
    {
      token: 'text.html.basic punctuation.definition.entity',
      foreground: '81A1C1',
    },
    {
      token: 'source.properties entity.name.section.group-title.ini',
      foreground: '88C0D0',
    },
    {
      token: 'source.properties punctuation.separator.key-value.ini',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown markup.fenced_code.block',
      foreground: '8FBCBB',
    },
    {
      token:
        'text.html.markdown markup.fenced_code.block punctuation.definition',
      foreground: '8FBCBB',
    },
    {
      token: 'markup.heading',
      foreground: '88C0D0',
    },
    {
      token: 'text.html.markdown markup.inline.raw',
      foreground: '8FBCBB',
    },
    {
      token: 'text.html.markdown markup.inline.raw punctuation.definition.raw',
      foreground: '8FBCBB',
    },
    {
      token: 'text.html.markdown beginning.punctuation.definition.list',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown beginning.punctuation.definition.quote',
      foreground: '8FBCBB',
    },
    {
      token: 'text.html.markdown markup.quote',
      foreground: '616E88',
    },
    {
      token: 'text.html.markdown constant.character.math.tex',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown punctuation.definition.math.begin',
      foreground: '5E81AC',
    },
    {
      token: 'text.html.markdown punctuation.definition.math.end',
      foreground: '5E81AC',
    },
    {
      token: 'text.html.markdown punctuation.definition.function.math.tex',
      foreground: '88C0D0',
    },
    {
      token: 'text.html.markdown punctuation.math.operator.latex',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown punctuation.definition.heading',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown punctuation.definition.constant',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown punctuation.definition.string',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown constant.other.reference.link',
      foreground: '88C0D0',
    },
    {
      token: 'text.html.markdown string.other.link.description',
      foreground: '88C0D0',
    },
    {
      token: 'text.html.markdown string.other.link.title',
      foreground: '88C0D0',
    },
    {
      token: 'source.perl punctuation.definition.variable',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.php meta.function-call',
      foreground: '88C0D0',
    },
    {
      token: 'source.php meta.function-call.object',
      foreground: '88C0D0',
    },
    {
      token: 'source.python entity.name.function.decorator',
      foreground: 'D08770',
    },
    {
      token: 'source.python meta.function.decorator support.type',
      foreground: 'D08770',
    },
    {
      token: 'source.python meta.function-call.generic',
      foreground: '88C0D0',
    },
    {
      token: 'source.python support.type',
      foreground: '88C0D0',
    },
    {
      token: 'source.python variable.parameter.function.language',
      foreground: 'D8DEE9',
    },
    {
      token:
        'source.python meta.function.parameters variable.parameter.function.language.special.self',
      foreground: '81A1C1',
    },
    {
      token: 'source.rust entity.name.type',
      foreground: '8FBCBB',
    },
    {
      token: 'source.rust meta.macro entity.name.function',
      foreground: '88C0D0',
    },
    {
      token: 'source.rust meta.attribute',
      foreground: '5E81AC',
    },
    {
      token: 'source.rust meta.attribute punctuation',
      foreground: '5E81AC',
    },
    {
      token: 'source.rust meta.attribute keyword.operator',
      foreground: '5E81AC',
    },
    {
      token: 'source.rust punctuation.definition.interpolation',
      foreground: 'EBCB8B',
    },
    {
      token:
        'source.css.scss punctuation.definition.interpolation.begin.bracket.curly',
      foreground: '81A1C1',
    },
    {
      token:
        'source.css.scss punctuation.definition.interpolation.end.bracket.curly',
      foreground: '81A1C1',
    },
    {
      token: 'source.css.scss variable.interpolation',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.ts punctuation.decorator',
      foreground: 'D08770',
    },
    {
      token: 'source.ts meta.decorator variable.other.readwrite',
      foreground: 'D08770',
    },
    {
      token: 'source.ts meta.decorator entity.name.function',
      foreground: 'D08770',
    },
    {
      token: 'source.tsx punctuation.decorator',
      foreground: 'D08770',
    },
    {
      token: 'source.tsx meta.decorator variable.other.readwrite',
      foreground: 'D08770',
    },
    {
      token: 'source.tsx meta.decorator entity.name.function',
      foreground: 'D08770',
    },
    {
      token: 'source.ts meta.object-literal.key',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.tsx meta.object-literal.key',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.ts meta.object-literal.key entity.name.function',
      foreground: '88C0D0',
    },
    {
      token: 'source.tsx meta.object-literal.key entity.name.function',
      foreground: '88C0D0',
    },
    {
      token: 'source.ts support.class',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts support.type',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts entity.name.type',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts entity.name.class',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx support.class',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx support.type',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx entity.name.type',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx entity.name.class',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts support.constant.math',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts support.constant.dom',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts support.constant.json',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx support.constant.math',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx support.constant.dom',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx support.constant.json',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts support.variable',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.tsx support.variable',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.ts meta.embedded.line meta.brace.square',
      foreground: 'ECEFF4',
    },
    {
      token: 'source.ts meta.embedded.line meta.brace.round',
      foreground: 'ECEFF4',
    },
    {
      token: 'source.tsx meta.embedded.line meta.brace.square',
      foreground: 'ECEFF4',
    },
    {
      token: 'source.tsx meta.embedded.line meta.brace.round',
      foreground: 'ECEFF4',
    },
    {
      token: 'text.xml entity.name.tag.namespace',
      foreground: '8FBCBB',
    },
    {
      token: 'text.xml keyword.other.doctype',
      foreground: '5E81AC',
    },
    {
      token: 'text.xml meta.tag.preprocessor entity.name.tag',
      foreground: '5E81AC',
    },
    {
      token: 'text.xml string.unquoted.cdata',
      foreground: 'D08770',
    },
    {
      token: 'text.xml string.unquoted.cdata punctuation.definition.string',
      foreground: 'D08770',
    },
    {
      token: 'source.yaml entity.name.tag',
      foreground: '8FBCBB',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
