import * as monaco from 'monaco-editor';

export default {
  base: 'vs-dark',
  inherit: false,
  rules: [
    {
      token: 'emphasis',
      fontStyle: 'italic',
    },
    {
      token: 'strong',
      fontStyle: 'bold',
    },
    {
      token: 'comment',
      foreground: '616E88',
    },
    {
      token: 'constant.character',
      foreground: 'EBCB8B',
    },
    {
      token: 'constant.character.escape',
      foreground: 'EBCB8B',
    },
    {
      token: 'constant.language',
      foreground: '81A1C1',
    },
    {
      token: 'constant.numeric',
      foreground: 'B48EAD',
    },
    {
      token: 'constant.regexp',
      foreground: 'EBCB8B',
    },
    {
      token: 'entity.name.class',
      foreground: '8FBCBB',
    },
    {
      token: 'entity.name.type.class',
      foreground: '8FBCBB',
    },
    {
      token: 'entity.name.function',
      foreground: '88C0D0',
    },
    {
      token: 'entity.name.tag',
      foreground: '81A1C1',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: '8FBCBB',
    },
    {
      token: 'entity.other.inherited-class',
      foreground: '8FBCBB',
      fontStyle: 'bold',
    },
    {
      token: 'invalid.deprecated',
      foreground: 'D8DEE9',
    },
    {
      token: 'invalid.illegal',
      foreground: 'D8DEE9',
    },
    {
      token: 'keyword',
      foreground: '81A1C1',
    },
    {
      token: 'keyword.operator',
      foreground: '81A1C1',
    },
    {
      token: 'keyword.other.new',
      foreground: '81A1C1',
    },
    {
      token: 'markup.bold',
      fontStyle: 'bold',
    },
    {
      token: 'markup.changed',
      foreground: 'EBCB8B',
    },
    {
      token: 'markup.deleted',
      foreground: 'BF616A',
    },
    {
      token: 'markup.inserted',
      foreground: 'A3BE8C',
    },
    {
      token: 'meta.preprocessor',
      foreground: '5E81AC',
    },
    {
      token: 'punctuation',
      foreground: 'ECEFF4',
    },
    {
      token: 'punctuation.definition.method-parameters',
      foreground: 'ECEFF4',
    },
    {
      token: 'punctuation.definition.function-parameters',
      foreground: 'ECEFF4',
    },
    {
      token: 'punctuation.definition.parameters',
      foreground: 'ECEFF4',
    },
    {
      token: 'punctuation.definition.tag',
      foreground: '81A1C1',
    },
    {
      token: 'punctuation.definition.comment',
      foreground: '616E88',
    },
    {
      token: 'punctuation.end.definition.comment',
      foreground: '616E88',
    },
    {
      token: 'punctuation.start.definition.comment',
      foreground: '616E88',
    },
    {
      token: 'punctuation.section',
      foreground: 'ECEFF4',
    },
    {
      token: 'punctuation.section.embedded.begin',
      foreground: '81A1C1',
    },
    {
      token: 'punctuation.section.embedded.end',
      foreground: '81A1C1',
    },
    {
      token: 'punctuation.terminator',
      foreground: '81A1C1',
    },
    {
      token: 'punctuation.definition.variable',
      foreground: '81A1C1',
    },
    {
      token: 'storage',
      foreground: '81A1C1',
    },
    {
      token: 'string',
      foreground: 'A3BE8C',
    },
    {
      token: 'string.regexp',
      foreground: 'EBCB8B',
    },
    {
      token: 'support.class',
      foreground: '8FBCBB',
    },
    {
      token: 'support.constant',
      foreground: '81A1C1',
    },
    {
      token: 'support.function',
      foreground: '88C0D0',
    },
    {
      token: 'support.function.construct',
      foreground: '81A1C1',
    },
    {
      token: 'support.type',
      foreground: '8FBCBB',
    },
    {
      token: 'support.type.exception',
      foreground: '8FBCBB',
    },
    {
      token: 'token.debug-token',
      foreground: 'B48EAD',
    },
    {
      token: 'token.error-token',
      foreground: 'BF616A',
    },
    {
      token: 'token.info-token',
      foreground: '88C0D0',
    },
    {
      token: 'token.warn-token',
      foreground: 'EBCB8B',
    },
    {
      token: 'variable.other',
      foreground: 'D8DEE9',
    },
    {
      token: 'variable.language',
      foreground: '81A1C1',
    },
    {
      token: 'variable.parameter',
      foreground: 'D8DEE9',
    },
    {
      token: 'punctuation.separator.pointer-access.c',
      foreground: '81A1C1',
    },
    {
      token: 'source.c meta.preprocessor.include',
      foreground: '8FBCBB',
    },
    {
      token: 'source.c string.quoted.other.lt-gt.include',
      foreground: '8FBCBB',
    },
    {
      token: 'source.cpp keyword.control.directive.conditional',
      foreground: '5E81AC',
      fontStyle: 'bold',
    },
    {
      token: 'source.cpp punctuation.definition.directive',
      foreground: '5E81AC',
      fontStyle: 'bold',
    },
    {
      token: 'source.c keyword.control.directive.conditional',
      foreground: '5E81AC',
      fontStyle: 'bold',
    },
    {
      token: 'source.c punctuation.definition.directive',
      foreground: '5E81AC',
      fontStyle: 'bold',
    },
    {
      token: 'source.css constant.other.color.rgb-value',
      foreground: 'B48EAD',
    },
    {
      token: 'source.css meta.property-value',
      foreground: '88C0D0',
    },
    {
      token: 'source.css keyword.control.at-rule.media',
      foreground: 'D08770',
    },
    {
      token:
        'source.css keyword.control.at-rule.media punctuation.definition.keyword',
      foreground: 'D08770',
    },
    {
      token: 'source.css punctuation.definition.keyword',
      foreground: '81A1C1',
    },
    {
      token: 'source.css support.type.property-name',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.diff meta.diff.range.context',
      foreground: '8FBCBB',
    },
    {
      token: 'source.diff meta.diff.header.from-file',
      foreground: '8FBCBB',
    },
    {
      token: 'source.diff punctuation.definition.from-file',
      foreground: '8FBCBB',
    },
    {
      token: 'source.diff punctuation.definition.range',
      foreground: '8FBCBB',
    },
    {
      token: 'source.diff punctuation.definition.separator',
      foreground: '81A1C1',
    },
    {
      token: 'entity.name.type.module.elixir',
      foreground: '8FBCBB',
    },
    {
      token: 'variable.other.readwrite.module.elixir',
      foreground: 'D8DEE9',
      fontStyle: 'bold',
    },
    {
      token: 'constant.other.symbol.elixir',
      foreground: 'D8DEE9',
      fontStyle: 'bold',
    },
    {
      token: 'variable.other.constant.elixir',
      foreground: '8FBCBB',
    },
    {
      token: 'source.go constant.other.placeholder.go',
      foreground: 'EBCB8B',
    },
    {
      token:
        'source.java comment.block.documentation.javadoc punctuation.definition.entity.html',
      foreground: '81A1C1',
    },
    {
      token: 'source.java constant.other',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.java keyword.other.documentation',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java keyword.other.documentation.author.javadoc',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java keyword.other.documentation.directive',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java keyword.other.documentation.custom',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java keyword.other.documentation.see.javadoc',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java meta.method-call meta.method',
      foreground: '88C0D0',
    },
    {
      token: 'source.java meta.tag.template.link.javadoc',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java string.other.link.title.javadoc',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java meta.tag.template.value.javadoc',
      foreground: '88C0D0',
    },
    {
      token: 'source.java punctuation.definition.keyword.javadoc',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java punctuation.definition.tag.begin.javadoc',
      foreground: '616E88',
    },
    {
      token: 'source.java punctuation.definition.tag.end.javadoc',
      foreground: '616E88',
    },
    {
      token: 'source.java storage.modifier.import',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java storage.modifier.package',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java storage.type',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java storage.type.annotation',
      foreground: 'D08770',
    },
    {
      token: 'source.java storage.type.generic',
      foreground: '8FBCBB',
    },
    {
      token: 'source.java storage.type.primitive',
      foreground: '81A1C1',
    },
    {
      token: 'source.js punctuation.decorator',
      foreground: 'D08770',
    },
    {
      token: 'source.js meta.decorator variable.other.readwrite',
      foreground: 'D08770',
    },
    {
      token: 'source.js meta.decorator entity.name.function',
      foreground: 'D08770',
    },
    {
      token: 'source.js meta.object-literal.key',
      foreground: '88C0D0',
    },
    {
      token: 'source.js storage.type.class.jsdoc',
      foreground: '8FBCBB',
    },
    {
      token: 'source.js string.quoted.template punctuation.quasi.element.begin',
      foreground: '81A1C1',
    },
    {
      token: 'source.js string.quoted.template punctuation.quasi.element.end',
      foreground: '81A1C1',
    },
    {
      token:
        'source.js string.template punctuation.definition.template-expression',
      foreground: '81A1C1',
    },
    {
      token: 'source.js string.quoted.template meta.method-call.with-arguments',
      foreground: 'ECEFF4',
    },
    {
      token:
        'source.js string.template meta.template.expression support.variable.property',
      foreground: 'D8DEE9',
    },
    {
      token:
        'source.js string.template meta.template.expression variable.other.object',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.js support.type.primitive',
      foreground: '81A1C1',
    },
    {
      token: 'source.js variable.other.object',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.js variable.other.readwrite.alias',
      foreground: '8FBCBB',
    },
    {
      token: 'source.js meta.embedded.line meta.brace.square',
      foreground: 'ECEFF4',
    },
    {
      token: 'source.js meta.embedded.line meta.brace.round',
      foreground: 'ECEFF4',
    },
    {
      token: 'source.js string.quoted.template meta.brace.square',
      foreground: 'ECEFF4',
    },
    {
      token: 'source.js string.quoted.template meta.brace.round',
      foreground: 'ECEFF4',
    },
    {
      token: 'text.html.basic constant.character.entity.html',
      foreground: 'EBCB8B',
    },
    {
      token: 'text.html.basic constant.other.inline-data',
      foreground: 'D08770',
      fontStyle: 'italic',
    },
    {
      token: 'text.html.basic meta.tag.sgml.doctype',
      foreground: '5E81AC',
    },
    {
      token: 'text.html.basic punctuation.definition.entity',
      foreground: '81A1C1',
    },
    {
      token: 'source.properties entity.name.section.group-title.ini',
      foreground: '88C0D0',
    },
    {
      token: 'source.properties punctuation.separator.key-value.ini',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown markup.fenced_code.block',
      foreground: '8FBCBB',
    },
    {
      token:
        'text.html.markdown markup.fenced_code.block punctuation.definition',
      foreground: '8FBCBB',
    },
    {
      token: 'markup.heading',
      foreground: '88C0D0',
    },
    {
      token: 'text.html.markdown markup.inline.raw',
      foreground: '8FBCBB',
    },
    {
      token: 'text.html.markdown markup.inline.raw punctuation.definition.raw',
      foreground: '8FBCBB',
    },
    {
      token: 'text.html.markdown markup.italic',
      fontStyle: 'italic',
    },
    {
      token: 'text.html.markdown markup.underline.link',
      fontStyle: 'underline',
    },
    {
      token: 'text.html.markdown beginning.punctuation.definition.list',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown beginning.punctuation.definition.quote',
      foreground: '8FBCBB',
    },
    {
      token: 'text.html.markdown markup.quote',
      foreground: '616E88',
    },
    {
      token: 'text.html.markdown constant.character.math.tex',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown punctuation.definition.math.begin',
      foreground: '5E81AC',
    },
    {
      token: 'text.html.markdown punctuation.definition.math.end',
      foreground: '5E81AC',
    },
    {
      token: 'text.html.markdown punctuation.definition.function.math.tex',
      foreground: '88C0D0',
    },
    {
      token: 'text.html.markdown punctuation.math.operator.latex',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown punctuation.definition.heading',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown punctuation.definition.constant',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown punctuation.definition.string',
      foreground: '81A1C1',
    },
    {
      token: 'text.html.markdown constant.other.reference.link',
      foreground: '88C0D0',
    },
    {
      token: 'text.html.markdown string.other.link.description',
      foreground: '88C0D0',
    },
    {
      token: 'text.html.markdown string.other.link.title',
      foreground: '88C0D0',
    },
    {
      token: 'source.perl punctuation.definition.variable',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.php meta.function-call',
      foreground: '88C0D0',
    },
    {
      token: 'source.php meta.function-call.object',
      foreground: '88C0D0',
    },
    {
      token: 'source.python entity.name.function.decorator',
      foreground: 'D08770',
    },
    {
      token: 'source.python meta.function.decorator support.type',
      foreground: 'D08770',
    },
    {
      token: 'source.python meta.function-call.generic',
      foreground: '88C0D0',
    },
    {
      token: 'source.python support.type',
      foreground: '88C0D0',
    },
    {
      token: 'source.python variable.parameter.function.language',
      foreground: 'D8DEE9',
    },
    {
      token:
        'source.python meta.function.parameters variable.parameter.function.language.special.self',
      foreground: '81A1C1',
    },
    {
      token: 'source.rust entity.name.type',
      foreground: '8FBCBB',
    },
    {
      token: 'source.rust meta.macro entity.name.function',
      foreground: '88C0D0',
      fontStyle: 'bold',
    },
    {
      token: 'source.rust meta.attribute',
      foreground: '5E81AC',
    },
    {
      token: 'source.rust meta.attribute punctuation',
      foreground: '5E81AC',
    },
    {
      token: 'source.rust meta.attribute keyword.operator',
      foreground: '5E81AC',
    },
    {
      token: 'source.rust entity.name.type.trait',
      fontStyle: 'bold',
    },
    {
      token: 'source.rust punctuation.definition.interpolation',
      foreground: 'EBCB8B',
    },
    {
      token:
        'source.css.scss punctuation.definition.interpolation.begin.bracket.curly',
      foreground: '81A1C1',
    },
    {
      token:
        'source.css.scss punctuation.definition.interpolation.end.bracket.curly',
      foreground: '81A1C1',
    },
    {
      token: 'source.css.scss variable.interpolation',
      foreground: 'D8DEE9',
      fontStyle: 'italic',
    },
    {
      token: 'source.ts punctuation.decorator',
      foreground: 'D08770',
    },
    {
      token: 'source.ts meta.decorator variable.other.readwrite',
      foreground: 'D08770',
    },
    {
      token: 'source.ts meta.decorator entity.name.function',
      foreground: 'D08770',
    },
    {
      token: 'source.tsx punctuation.decorator',
      foreground: 'D08770',
    },
    {
      token: 'source.tsx meta.decorator variable.other.readwrite',
      foreground: 'D08770',
    },
    {
      token: 'source.tsx meta.decorator entity.name.function',
      foreground: 'D08770',
    },
    {
      token: 'source.ts meta.object-literal.key',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.tsx meta.object-literal.key',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.ts meta.object-literal.key entity.name.function',
      foreground: '88C0D0',
    },
    {
      token: 'source.tsx meta.object-literal.key entity.name.function',
      foreground: '88C0D0',
    },
    {
      token: 'source.ts support.class',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts support.type',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts entity.name.type',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts entity.name.class',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx support.class',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx support.type',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx entity.name.type',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx entity.name.class',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts support.constant.math',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts support.constant.dom',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts support.constant.json',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx support.constant.math',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx support.constant.dom',
      foreground: '8FBCBB',
    },
    {
      token: 'source.tsx support.constant.json',
      foreground: '8FBCBB',
    },
    {
      token: 'source.ts support.variable',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.tsx support.variable',
      foreground: 'D8DEE9',
    },
    {
      token: 'source.ts meta.embedded.line meta.brace.square',
      foreground: 'ECEFF4',
    },
    {
      token: 'source.ts meta.embedded.line meta.brace.round',
      foreground: 'ECEFF4',
    },
    {
      token: 'source.tsx meta.embedded.line meta.brace.square',
      foreground: 'ECEFF4',
    },
    {
      token: 'source.tsx meta.embedded.line meta.brace.round',
      foreground: 'ECEFF4',
    },
    {
      token: 'text.xml entity.name.tag.namespace',
      foreground: '8FBCBB',
    },
    {
      token: 'text.xml keyword.other.doctype',
      foreground: '5E81AC',
    },
    {
      token: 'text.xml meta.tag.preprocessor entity.name.tag',
      foreground: '5E81AC',
    },
    {
      token: 'text.xml string.unquoted.cdata',
      foreground: 'D08770',
      fontStyle: 'italic',
    },
    {
      token: 'text.xml string.unquoted.cdata punctuation.definition.string',
      foreground: 'D08770',
      fontStyle: 'italic',
    },
    {
      token: 'source.yaml entity.name.tag',
      foreground: '8FBCBB',
    },
  ],
  colors: {
    focusBorder: '3B4252',
    foreground: 'D8DEE9',
    'activityBar.background': '2E3440',
    'activityBar.dropBackground': '3B4252',
    'activityBar.foreground': 'D8DEE9',
    'activityBar.activeBorder': '88C0D0',
    'activityBar.activeBackground': '3B4252',
    'activityBarBadge.background': '88C0D0',
    'activityBarBadge.foreground': '2E3440',
    'badge.foreground': '2E3440',
    'badge.background': '88C0D0',
    'button.background': '88C0D0EE',
    'button.foreground': '2E3440',
    'button.hoverBackground': '88C0D0',
    'button.secondaryBackground': '434C5E',
    'button.secondaryForeground': 'D8DEE9',
    'button.secondaryHoverBackground': '4C566A',
    'charts.red': 'BF616A',
    'charts.blue': '81A1C1',
    'charts.yellow': 'EBCB8B',
    'charts.orange': 'D08770',
    'charts.green': 'A3BE8C',
    'charts.purple': 'B48EAD',
    'charts.foreground': 'D8DEE9',
    'charts.lines': '88C0D0',
    'debugConsole.infoForeground': '88C0D0',
    'debugConsole.warningForeground': 'EBCB8B',
    'debugConsole.errorForeground': 'BF616A',
    'debugConsole.sourceForeground': '616E88',
    'debugConsoleInputIcon.foreground': '81A1C1',
    'debugExceptionWidget.background': '4C566A',
    'debugExceptionWidget.border': '2E3440',
    'debugToolBar.background': '3B4252',
    descriptionForeground: 'D8DEE9E6',
    'diffEditor.insertedTextBackground': '81A1C133',
    'diffEditor.removedTextBackground': 'BF616A4D',
    'dropdown.background': '3B4252',
    'dropdown.border': '3B4252',
    'dropdown.foreground': 'D8DEE9',
    'editorActiveLineNumber.foreground': 'D8DEE9CC',
    'editorCursor.foreground': 'D8DEE9',
    'editorHint.border': 'EBCB8B00',
    'editorHint.foreground': 'EBCB8B',
    'editorIndentGuide.background': '434C5EB3',
    'editorIndentGuide.activeBackground': '4C566A',
    'editorInlayHint.background': '434C5E',
    'editorInlayHint.foreground': 'D8DEE9',
    'editorLineNumber.foreground': '4C566A',
    'editorLineNumber.activeForeground': 'D8DEE9',
    'editorWhitespace.foreground': '4C566AB3',
    'editorWidget.background': '2E3440',
    'editorWidget.border': '3B4252',
    'editor.background': '2E3440',
    'editor.foreground': 'D8DEE9',
    'editor.hoverHighlightBackground': '3B4252',
    'editor.findMatchBackground': '88C0D066',
    'editor.findMatchHighlightBackground': '88C0D033',
    'editor.findRangeHighlightBackground': '88C0D033',
    'editor.lineHighlightBackground': '3B4252',
    'editor.lineHighlightBorder': '3B4252',
    'editor.inactiveSelectionBackground': '434C5ECC',
    'editor.inlineValuesBackground': '4C566A',
    'editor.inlineValuesForeground': 'ECEFF4',
    'editor.selectionBackground': '434C5ECC',
    'editor.selectionHighlightBackground': '434C5ECC',
    'editor.rangeHighlightBackground': '434C5E52',
    'editor.wordHighlightBackground': '81A1C166',
    'editor.wordHighlightStrongBackground': '81A1C199',
    'editor.stackFrameHighlightBackground': '5E81AC',
    'editor.focusedStackFrameHighlightBackground': '5E81AC',
    'editorError.foreground': 'BF616A',
    'editorError.border': 'BF616A00',
    'editorWarning.foreground': 'EBCB8B',
    'editorWarning.border': 'EBCB8B00',
    'editorBracketMatch.background': '2E344000',
    'editorBracketMatch.border': '88C0D0',
    'editorBracketHighlight.foreground1': '8FBCBB',
    'editorBracketHighlight.foreground2': '88C0D0',
    'editorBracketHighlight.foreground3': '81A1C1',
    'editorBracketHighlight.foreground4': '5E81AC',
    'editorBracketHighlight.foreground5': '8FBCBB',
    'editorBracketHighlight.foreground6': '88C0D0',
    'editorBracketHighlight.unexpectedBracket.foreground': 'BF616A',
    'editorCodeLens.foreground': '4C566A',
    'editorGroup.background': '2E3440',
    'editorGroup.border': '3B425201',
    'editorGroup.dropBackground': '3B425299',
    'editorGroupHeader.border': '3B425200',
    'editorGroupHeader.noTabsBackground': '2E3440',
    'editorGroupHeader.tabsBackground': '2E3440',
    'editorGroupHeader.tabsBorder': '3B425200',
    'editorGutter.background': '2E3440',
    'editorGutter.modifiedBackground': 'EBCB8B',
    'editorGutter.addedBackground': 'A3BE8C',
    'editorGutter.deletedBackground': 'BF616A',
    'editorHoverWidget.background': '3B4252',
    'editorHoverWidget.border': '3B4252',
    'editorLink.activeForeground': '88C0D0',
    'editorMarkerNavigation.background': '5E81ACC0',
    'editorMarkerNavigationError.background': 'BF616AC0',
    'editorMarkerNavigationWarning.background': 'EBCB8BC0',
    'editorOverviewRuler.border': '3B4252',
    'editorOverviewRuler.currentContentForeground': '3B4252',
    'editorOverviewRuler.incomingContentForeground': '3B4252',
    'editorOverviewRuler.findMatchForeground': '88C0D066',
    'editorOverviewRuler.rangeHighlightForeground': '88C0D066',
    'editorOverviewRuler.selectionHighlightForeground': '88C0D066',
    'editorOverviewRuler.wordHighlightForeground': '88C0D066',
    'editorOverviewRuler.wordHighlightStrongForeground': '88C0D066',
    'editorOverviewRuler.modifiedForeground': 'EBCB8B',
    'editorOverviewRuler.addedForeground': 'A3BE8C',
    'editorOverviewRuler.deletedForeground': 'BF616A',
    'editorOverviewRuler.errorForeground': 'BF616A',
    'editorOverviewRuler.warningForeground': 'EBCB8B',
    'editorOverviewRuler.infoForeground': '81A1C1',
    'editorRuler.foreground': '434C5E',
    'editorSuggestWidget.background': '2E3440',
    'editorSuggestWidget.border': '3B4252',
    'editorSuggestWidget.foreground': 'D8DEE9',
    'editorSuggestWidget.focusHighlightForeground': '88C0D0',
    'editorSuggestWidget.highlightForeground': '88C0D0',
    'editorSuggestWidget.selectedBackground': '434C5E',
    'editorSuggestWidget.selectedForeground': 'D8DEE9',
    'extensionButton.prominentForeground': 'D8DEE9',
    'extensionButton.prominentBackground': '434C5E',
    'extensionButton.prominentHoverBackground': '4C566A',
    errorForeground: 'BF616A',
    'gitDecoration.modifiedResourceForeground': 'EBCB8B',
    'gitDecoration.deletedResourceForeground': 'BF616A',
    'gitDecoration.untrackedResourceForeground': 'A3BE8C',
    'gitDecoration.ignoredResourceForeground': 'D8DEE966',
    'gitDecoration.conflictingResourceForeground': '5E81AC',
    'gitDecoration.submoduleResourceForeground': '8FBCBB',
    'gitDecoration.stageDeletedResourceForeground': 'BF616A',
    'gitDecoration.stageModifiedResourceForeground': 'EBCB8B',
    'input.background': '3B4252',
    'input.foreground': 'D8DEE9',
    'input.placeholderForeground': 'D8DEE999',
    'input.border': '3B4252',
    'inputOption.activeBackground': '5E81AC',
    'inputOption.activeBorder': '5E81AC',
    'inputOption.activeForeground': 'ECEFF4',
    'inputValidation.errorBackground': 'BF616A',
    'inputValidation.errorBorder': 'BF616A',
    'inputValidation.infoBackground': '81A1C1',
    'inputValidation.infoBorder': '81A1C1',
    'inputValidation.warningBackground': 'D08770',
    'inputValidation.warningBorder': 'D08770',
    'keybindingLabel.background': '4C566A',
    'keybindingLabel.border': '4C566A',
    'keybindingLabel.bottomBorder': '4C566A',
    'keybindingLabel.foreground': 'D8DEE9',
    'list.activeSelectionBackground': '88C0D0',
    'list.activeSelectionForeground': '2E3440',
    'list.inactiveSelectionBackground': '434C5E',
    'list.inactiveSelectionForeground': 'D8DEE9',
    'list.inactiveFocusBackground': '434C5ECC',
    'list.hoverForeground': 'ECEFF4',
    'list.focusForeground': 'D8DEE9',
    'list.focusBackground': '88C0D099',
    'list.focusHighlightForeground': 'ECEFF4',
    'list.hoverBackground': '3B4252',
    'list.dropBackground': '88C0D099',
    'list.highlightForeground': '88C0D0',
    'list.errorForeground': 'BF616A',
    'list.warningForeground': 'EBCB8B',
    'merge.currentHeaderBackground': '81A1C166',
    'merge.currentContentBackground': '81A1C14D',
    'merge.incomingHeaderBackground': '8FBCBB66',
    'merge.incomingContentBackground': '8FBCBB4D',
    'merge.border': '3B425200',
    'minimap.background': '2E3440',
    'minimap.errorHighlight': 'BF616ACC',
    'minimap.findMatchHighlight': '88C0D0',
    'minimap.selectionHighlight': '88C0D0CC',
    'minimap.warningHighlight': 'EBCB8BCC',
    'minimapGutter.addedBackground': 'A3BE8C',
    'minimapGutter.deletedBackground': 'BF616A',
    'minimapGutter.modifiedBackground': 'EBCB8B',
    'minimapSlider.activeBackground': '434C5EAA',
    'minimapSlider.background': '434C5E99',
    'minimapSlider.hoverBackground': '434C5EAA',
    'notification.background': '3B4252',
    'notification.buttonBackground': '434C5E',
    'notification.buttonForeground': 'D8DEE9',
    'notification.buttonHoverBackground': '4C566A',
    'notification.errorBackground': 'BF616A',
    'notification.errorForeground': '2E3440',
    'notification.foreground': 'D8DEE9',
    'notification.infoBackground': '88C0D0',
    'notification.infoForeground': '2E3440',
    'notification.warningBackground': 'EBCB8B',
    'notification.warningForeground': '2E3440',
    'notificationCenter.border': '3B425200',
    'notificationCenterHeader.background': '2E3440',
    'notificationCenterHeader.foreground': '88C0D0',
    'notificationLink.foreground': '88C0D0',
    'notifications.background': '3B4252',
    'notifications.border': '2E3440',
    'notifications.foreground': 'D8DEE9',
    'notificationToast.border': '3B425200',
    'panel.background': '2E3440',
    'panel.border': '3B4252',
    'panelTitle.activeBorder': '88C0D000',
    'panelTitle.activeForeground': '88C0D0',
    'panelTitle.inactiveForeground': 'D8DEE9',
    'peekView.border': '4C566A',
    'peekViewEditor.background': '2E3440',
    'peekViewEditorGutter.background': '2E3440',
    'peekViewEditor.matchHighlightBackground': '88C0D04D',
    'peekViewResult.background': '2E3440',
    'peekViewResult.fileForeground': '88C0D0',
    'peekViewResult.lineForeground': 'D8DEE966',
    'peekViewResult.matchHighlightBackground': '88C0D0CC',
    'peekViewResult.selectionBackground': '434C5E',
    'peekViewResult.selectionForeground': 'D8DEE9',
    'peekViewTitle.background': '3B4252',
    'peekViewTitleDescription.foreground': 'D8DEE9',
    'peekViewTitleLabel.foreground': '88C0D0',
    'pickerGroup.border': '3B4252',
    'pickerGroup.foreground': '88C0D0',
    'progressBar.background': '88C0D0',
    'quickInputList.focusBackground': '88C0D0',
    'quickInputList.focusForeground': '2E3440',
    'sash.hoverBorder': '88C0D0',
    'scrollbar.shadow': '00000066',
    'scrollbarSlider.activeBackground': '434C5EAA',
    'scrollbarSlider.background': '434C5E99',
    'scrollbarSlider.hoverBackground': '434C5EAA',
    'selection.background': '88C0D099',
    'sideBar.background': '2E3440',
    'sideBar.foreground': 'D8DEE9',
    'sideBar.border': '3B4252',
    'sideBarSectionHeader.background': '3B4252',
    'sideBarSectionHeader.foreground': 'D8DEE9',
    'sideBarTitle.foreground': 'D8DEE9',
    'statusBar.background': '3B4252',
    'statusBar.debuggingBackground': '5E81AC',
    'statusBar.debuggingForeground': 'D8DEE9',
    'statusBar.noFolderForeground': 'D8DEE9',
    'statusBar.noFolderBackground': '3B4252',
    'statusBar.foreground': 'D8DEE9',
    'statusBarItem.activeBackground': '4C566A',
    'statusBarItem.hoverBackground': '434C5E',
    'statusBarItem.prominentBackground': '3B4252',
    'statusBarItem.prominentHoverBackground': '434C5E',
    'statusBarItem.errorBackground': '3B4252',
    'statusBarItem.errorForeground': 'BF616A',
    'statusBarItem.warningBackground': 'EBCB8B',
    'statusBarItem.warningForeground': '2E3440',
    'statusBar.border': '3B425200',
    'tab.activeBackground': '3B4252',
    'tab.activeForeground': 'D8DEE9',
    'tab.border': '3B425200',
    'tab.activeBorder': '88C0D000',
    'tab.unfocusedActiveBorder': '88C0D000',
    'tab.inactiveBackground': '2E3440',
    'tab.inactiveForeground': 'D8DEE966',
    'tab.unfocusedActiveForeground': 'D8DEE999',
    'tab.unfocusedInactiveForeground': 'D8DEE966',
    'tab.hoverBackground': '3B4252CC',
    'tab.unfocusedHoverBackground': '3B4252B3',
    'tab.hoverBorder': '88C0D000',
    'tab.unfocusedHoverBorder': '88C0D000',
    'tab.activeBorderTop': '88C0D000',
    'tab.unfocusedActiveBorderTop': '88C0D000',
    'tab.lastPinnedBorder': '4C566A',
    'terminal.background': '2E3440',
    'terminal.foreground': 'D8DEE9',
    'terminal.ansiBlack': '3B4252',
    'terminal.ansiRed': 'BF616A',
    'terminal.ansiGreen': 'A3BE8C',
    'terminal.ansiYellow': 'EBCB8B',
    'terminal.ansiBlue': '81A1C1',
    'terminal.ansiMagenta': 'B48EAD',
    'terminal.ansiCyan': '88C0D0',
    'terminal.ansiWhite': 'E5E9F0',
    'terminal.ansiBrightBlack': '4C566A',
    'terminal.ansiBrightRed': 'BF616A',
    'terminal.ansiBrightGreen': 'A3BE8C',
    'terminal.ansiBrightYellow': 'EBCB8B',
    'terminal.ansiBrightBlue': '81A1C1',
    'terminal.ansiBrightMagenta': 'B48EAD',
    'terminal.ansiBrightCyan': '8FBCBB',
    'terminal.ansiBrightWhite': 'ECEFF4',
    'terminal.tab.activeBorder': '88C0D0',
    'textBlockQuote.background': '3B4252',
    'textBlockQuote.border': '81A1C1',
    'textCodeBlock.background': '4C566A',
    'textLink.activeForeground': '88C0D0',
    'textLink.foreground': '88C0D0',
    'textPreformat.foreground': '8FBCBB',
    'textSeparator.foreground': 'ECEFF4',
    'titleBar.activeBackground': '2E3440',
    'titleBar.activeForeground': 'D8DEE9',
    'titleBar.border': '2E344000',
    'titleBar.inactiveBackground': '2E3440',
    'titleBar.inactiveForeground': 'D8DEE966',
    'tree.indentGuidesStroke': '616E88',
    'walkThrough.embeddedEditorBackground': '2E3440',
    'welcomePage.buttonBackground': '434C5E',
    'welcomePage.buttonHoverBackground': '4C566A',
    'widget.shadow': '00000066',
  },
} as const satisfies monaco.editor.IStandaloneThemeData;
