import type { Metadata } from "next";
import { Geist, Libre_Baskerville, Space_Mono } from "next/font/google";

import "./globals.css";

const fontHeading = Libre_Baskerville({
    variable: "--font-heading",
    subsets: ["latin"],
    weight: ["400", "700"],
});

const fontBody = Geist({
    variable: "--font-body",
    subsets: ["latin"],
});

const fontMono = Space_Mono({
    variable: "--font-mono",
    subsets: ["latin"],
    weight: ["400", "700"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body
                className={`${fontHeading.variable} ${fontBody.variable} ${fontMono.variable} antialiased font-body`}
            >
                {children}
            </body>
        </html>
    );
}
