import * as monaco from 'monaco-editor';

export default {
  base: 'vs-dark',
  inherit: false,
  colors: {
    'activityBar.activeBorder': '#80CBC4',
    'activityBar.background': '#292D3E',
    'activityBar.border': '#292D3E60',
    'activityBar.dropBackground': '#f0717880',
    'activityBar.foreground': '#babed8',
    'activityBarBadge.background': '#80CBC4',
    'activityBarBadge.foreground': '#000000',
    'badge.background': '#00000030',
    'badge.foreground': '#676E95',
    'breadcrumb.activeSelectionForeground': '#80CBC4',
    'breadcrumb.background': '#292D3E',
    'breadcrumb.focusForeground': '#babed8',
    'breadcrumb.foreground': '#676E95',
    'breadcrumbPicker.background': '#292D3E',
    'button.background': '#717CB450',
    'button.foreground': '#ffffff',
    'debugConsole.errorForeground': '#f07178',
    'debugConsole.infoForeground': '#89DDFF',
    'debugConsole.warningForeground': '#FFCB6B',
    'debugToolBar.background': '#292D3E',
    'diffEditor.insertedTextBackground': '#89DDFF20',
    'diffEditor.removedTextBackground': '#ff9cac20',
    'dropdown.background': '#292D3E',
    'dropdown.border': '#FFFFFF10',
    'editor.background': '#292D3E',
    'editor.findMatchBackground': '#000000',
    'editor.findMatchBorder': '#80CBC4',
    'editor.findMatchHighlight': '#babed8',
    'editor.findMatchHighlightBackground': '#00000050',
    'editor.findMatchHighlightBorder': '#ffffff30',
    'editor.findRangeHighlightBackground': '#FFCB6B30',
    'editor.foreground': '#babed8',
    'editor.lineHighlightBackground': '#00000050',
    'editor.lineHighlightBorder': '#00000000',
    'editor.rangeHighlightBackground': '#FFFFFF0d',
    'editor.selectionBackground': '#717CB450',
    'editor.selectionHighlightBackground': '#FFCC0020',
    'editor.wordHighlightBackground': '#ff9cac30',
    'editor.wordHighlightStrongBackground': '#C3E88D30',
    'editorBracketMatch.background': '#292D3E',
    'editorBracketMatch.border': '#FFCC0050',
    'editorCursor.foreground': '#FFCC00',
    'editorError.foreground': '#f0717870',
    'editorGroup.border': '#00000030',
    'editorGroup.dropBackground': '#f0717880',
    'editorGroup.focusedEmptyBorder': '#f07178',
    'editorGroupHeader.tabsBackground': '#292D3E',
    'editorGutter.addedBackground': '#C3E88D60',
    'editorGutter.deletedBackground': '#f0717860',
    'editorGutter.modifiedBackground': '#82AAFF60',
    'editorHoverWidget.background': '#292D3E',
    'editorHoverWidget.border': '#FFFFFF10',
    'editorIndentGuide.activeBackground': '#4E5579',
    'editorIndentGuide.background': '#4E557970',
    'editorInfo.foreground': '#82AAFF70',
    'editorLineNumber.activeForeground': '#676E95',
    'editorLineNumber.foreground': '#3A3F58',
    'editorLink.activeForeground': '#babed8',
    'editorMarkerNavigation.background': '#babed805',
    'editorOverviewRuler.border': '#292D3E',
    'editorOverviewRuler.errorForeground': '#f0717840',
    'editorOverviewRuler.findMatchForeground': '#80CBC4',
    'editorOverviewRuler.infoForeground': '#82AAFF40',
    'editorOverviewRuler.warningForeground': '#FFCB6B40',
    'editorRuler.foreground': '#4E5579',
    'editorSuggestWidget.background': '#292D3E',
    'editorSuggestWidget.border': '#FFFFFF10',
    'editorSuggestWidget.foreground': '#babed8',
    'editorSuggestWidget.highlightForeground': '#80CBC4',
    'editorSuggestWidget.selectedBackground': '#00000050',
    'editorWarning.foreground': '#FFCB6B70',
    'editorWhitespace.foreground': '#babed840',
    'editorWidget.background': '#292D3E',
    'editorWidget.border': '#80CBC4',
    'editorWidget.resizeBorder': '#80CBC4',
    'extensionBadge.remoteForeground': '#babed8',
    'extensionButton.prominentBackground': '#C3E88D90',
    'extensionButton.prominentForeground': '#babed8',
    'extensionButton.prominentHoverBackground': '#C3E88D',
    focusBorder: '#FFFFFF00',
    foreground: '#babed8',
    'gitDecoration.conflictingResourceForeground': '#FFCB6B90',
    'gitDecoration.deletedResourceForeground': '#f0717890',
    'gitDecoration.ignoredResourceForeground': '#676E9590',
    'gitDecoration.modifiedResourceForeground': '#82AAFF90',
    'gitDecoration.untrackedResourceForeground': '#C3E88D90',
    'input.background': '#333747',
    'input.border': '#FFFFFF10',
    'input.foreground': '#babed8',
    'input.placeholderForeground': '#babed860',
    'inputOption.activeBackground': '#babed830',
    'inputOption.activeBorder': '#babed830',
    'inputValidation.errorBorder': '#f07178',
    'inputValidation.infoBorder': '#82AAFF',
    'inputValidation.warningBorder': '#FFCB6B',
    'list.activeSelectionBackground': '#292D3E',
    'list.activeSelectionForeground': '#80CBC4',
    'list.dropBackground': '#f0717880',
    'list.focusBackground': '#babed820',
    'list.focusForeground': '#babed8',
    'list.highlightForeground': '#80CBC4',
    'list.hoverBackground': '#292D3E',
    'list.hoverForeground': '#FFFFFF',
    'list.inactiveSelectionBackground': '#00000030',
    'list.inactiveSelectionForeground': '#80CBC4',
    'listFilterWidget.background': '#00000030',
    'listFilterWidget.noMatchesOutline': '#00000030',
    'listFilterWidget.outline': '#00000030',
    'menu.background': '#292D3E',
    'menu.foreground': '#babed8',
    'menu.selectionBackground': '#00000050',
    'menu.selectionBorder': '#00000030',
    'menu.selectionForeground': '#80CBC4',
    'menu.separatorBackground': '#babed8',
    'menubar.selectionBackground': '#00000030',
    'menubar.selectionBorder': '#00000030',
    'menubar.selectionForeground': '#80CBC4',
    'notebook.focusedCellBorder': '#80CBC4',
    'notebook.inactiveFocusedCellBorder': '#80CBC450',
    'notificationLink.foreground': '#80CBC4',
    'notifications.background': '#292D3E',
    'notifications.foreground': '#babed8',
    'panel.background': '#292D3E',
    'panel.border': '#292D3E60',
    'panel.dropBackground': '#babed8',
    'panelTitle.activeBorder': '#80CBC4',
    'panelTitle.activeForeground': '#FFFFFF',
    'panelTitle.inactiveForeground': '#babed8',
    'peekView.border': '#00000030',
    'peekViewEditor.background': '#babed805',
    'peekViewEditor.matchHighlightBackground': '#717CB450',
    'peekViewEditorGutter.background': '#babed805',
    'peekViewResult.background': '#babed805',
    'peekViewResult.matchHighlightBackground': '#717CB450',
    'peekViewResult.selectionBackground': '#676E9570',
    'peekViewTitle.background': '#babed805',
    'peekViewTitleDescription.foreground': '#babed860',
    'pickerGroup.border': '#FFFFFF1a',
    'pickerGroup.foreground': '#80CBC4',
    'progressBar.background': '#80CBC4',
    'quickInput.background': '#292D3E',
    'quickInput.foreground': '#676E95',
    'quickInput.list.focusBackground': '#babed820',
    'sash.hoverBorder': '#80CBC450',
    'scrollbar.shadow': '#00000030',
    'scrollbarSlider.activeBackground': '#80CBC4',
    'scrollbarSlider.background': '#A6ACCD20',
    'scrollbarSlider.hoverBackground': '#A6ACCD10',
    'selection.background': '#00000080',
    'settings.checkboxBackground': '#292D3E',
    'settings.checkboxForeground': '#babed8',
    'settings.dropdownBackground': '#292D3E',
    'settings.dropdownForeground': '#babed8',
    'settings.headerForeground': '#80CBC4',
    'settings.modifiedItemIndicator': '#80CBC4',
    'settings.numberInputBackground': '#292D3E',
    'settings.numberInputForeground': '#babed8',
    'settings.textInputBackground': '#292D3E',
    'settings.textInputForeground': '#babed8',
    'sideBar.background': '#292D3E',
    'sideBar.border': '#292D3E60',
    'sideBar.foreground': '#676E95',
    'sideBarSectionHeader.background': '#292D3E',
    'sideBarSectionHeader.border': '#292D3E60',
    'sideBarTitle.foreground': '#babed8',
    'statusBar.background': '#292D3E',
    'statusBar.border': '#292D3E60',
    'statusBar.debuggingBackground': '#C792EA',
    'statusBar.debuggingForeground': '#ffffff',
    'statusBar.foreground': '#676E95',
    'statusBar.noFolderBackground': '#292D3E',
    'statusBarItem.activeBackground': '#f0717880',
    'statusBarItem.hoverBackground': '#676E9520',
    'statusBarItem.remoteBackground': '#80CBC4',
    'statusBarItem.remoteForeground': '#000000',
    'tab.activeBackground': '#292D3E',
    'tab.activeBorder': '#80CBC4',
    'tab.activeForeground': '#FFFFFF',
    'tab.activeModifiedBorder': '#676E95',
    'tab.border': '#292D3E',
    'tab.inactiveBackground': '#292D3E',
    'tab.inactiveForeground': '#676E95',
    'tab.inactiveModifiedBorder': '#904348',
    'tab.unfocusedActiveBorder': '#676E95',
    'tab.unfocusedActiveForeground': '#babed8',
    'tab.unfocusedActiveModifiedBorder': '#c05a60',
    'tab.unfocusedInactiveModifiedBorder': '#904348',
    'terminal.ansiBlack': '#000000',
    'terminal.ansiBlue': '#82AAFF',
    'terminal.ansiBrightBlack': '#676E95',
    'terminal.ansiBrightBlue': '#82AAFF',
    'terminal.ansiBrightCyan': '#89DDFF',
    'terminal.ansiBrightGreen': '#C3E88D',
    'terminal.ansiBrightMagenta': '#C792EA',
    'terminal.ansiBrightRed': '#f07178',
    'terminal.ansiBrightWhite': '#ffffff',
    'terminal.ansiBrightYellow': '#FFCB6B',
    'terminal.ansiCyan': '#89DDFF',
    'terminal.ansiGreen': '#C3E88D',
    'terminal.ansiMagenta': '#C792EA',
    'terminal.ansiRed': '#f07178',
    'terminal.ansiWhite': '#ffffff',
    'terminal.ansiYellow': '#FFCB6B',
    'terminalCursor.background': '#000000',
    'terminalCursor.foreground': '#FFCB6B',
    'textLink.activeForeground': '#babed8',
    'textLink.foreground': '#80CBC4',
    'titleBar.activeBackground': '#292D3E',
    'titleBar.activeForeground': '#babed8',
    'titleBar.border': '#292D3E60',
    'titleBar.inactiveBackground': '#292D3E',
    'titleBar.inactiveForeground': '#676E95',
    'tree.indentGuidesStroke': '#4E5579',
    'widget.shadow': '#00000030',
  },
  rules: [
    {
      token: 'string',
      foreground: 'C3E88D',
    },
    {
      token: 'punctuation, constant.other.symbol',
      foreground: '89DDFF',
    },
    {
      token:
        'constant.character.escape, text.html constant.character.entity.named',
      foreground: 'babed8',
    },
    {
      token: 'constant.language.boolean',
      foreground: 'ff9cac',
    },
    {
      token: 'constant.numeric',
      foreground: 'F78C6C',
    },
    {
      token:
        'variable, variable.parameter, support.variable, variable.language, support.constant, meta.definition.variable entity.name.function, meta.function-call.arguments',
      foreground: 'babed8',
    },
    {
      token: 'keyword.other',
      foreground: 'F78C6C',
    },
    {
      token:
        'keyword, modifier, variable.language.this, support.type.object, constant.language',
      foreground: '89DDFF',
    },
    {
      token: 'entity.name.function, support.function',
      foreground: '82AAFF',
    },
    {
      token: 'storage.type, storage.modifier, storage.control',
      foreground: 'C792EA',
    },
    {
      token: 'support.module, support.node',
      foreground: 'f07178',
    },
    {
      token: 'support.type, constant.other.key',
      foreground: 'FFCB6B',
    },
    {
      token: 'entity.name.type, entity.other.inherited-class, entity.other',
      foreground: 'FFCB6B',
    },
    {
      token: 'comment',
      foreground: '676E95',
    },
    {
      token: 'comment punctuation.definition.comment, string.quoted.docstring',
      foreground: '676E95',
    },
    {
      token: 'punctuation',
      foreground: '89DDFF',
    },
    {
      token:
        'entity.name, entity.name.type.class, support.type, support.class, meta.use',
      foreground: 'FFCB6B',
    },
    {
      token:
        'variable.object.property, meta.field.declaration entity.name.function',
      foreground: 'f07178',
    },
    {
      token: 'meta.definition.method entity.name.function',
      foreground: 'f07178',
    },
    {
      token: 'meta.function entity.name.function',
      foreground: '82AAFF',
    },
    {
      token:
        'template.expression.begin, template.expression.end, punctuation.definition.template-expression.begin, punctuation.definition.template-expression.end',
      foreground: '89DDFF',
    },
    {
      token: 'meta.embedded, source.groovy.embedded, meta.template.expression',
      foreground: 'babed8',
    },
    {
      token: 'entity.name.tag.yaml',
      foreground: 'f07178',
    },
    {
      token:
        'meta.object-literal.key, meta.object-literal.key string, support.type.property-name.json',
      foreground: 'f07178',
    },
    {
      token: 'constant.language.json',
      foreground: '89DDFF',
    },
    {
      token: 'entity.other.attribute-name.class',
      foreground: 'FFCB6B',
    },
    {
      token: 'entity.other.attribute-name.id',
      foreground: 'F78C6C',
    },
    {
      token: 'source.css entity.name.tag',
      foreground: 'FFCB6B',
    },
    {
      token: 'support.type.property-name.css',
      foreground: 'B2CCD6',
    },
    {
      token: 'meta.tag, punctuation.definition.tag',
      foreground: '89DDFF',
    },
    {
      token: 'entity.name.tag',
      foreground: 'f07178',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: 'C792EA',
    },
    {
      token: 'punctuation.definition.entity.html',
      foreground: 'babed8',
    },
    {
      token: 'markup.heading',
      foreground: '89DDFF',
    },
    {
      token: 'text.html.markdown meta.link.inline, meta.link.reference',
      foreground: 'f07178',
    },
    {
      token: 'text.html.markdown beginning.punctuation.definition.list',
      foreground: '89DDFF',
    },
    {
      token: 'markup.italic',
      foreground: 'f07178',
    },
    {
      token: 'markup.bold',
      foreground: 'f07178',
    },
    {
      token: 'markup.bold markup.italic, markup.italic markup.bold',
      foreground: 'f07178',
    },
    {
      token:
        'markup.fenced_code.block.markdown punctuation.definition.markdown',
      foreground: 'C3E88D',
    },
    {
      token: 'markup.inline.raw.string.markdown',
      foreground: 'C3E88D',
    },
    {
      token: 'keyword.other.definition.ini',
      foreground: 'f07178',
    },
    {
      token: 'entity.name.section.group-title.ini',
      foreground: '89DDFF',
    },
    {
      token: 'source.cs meta.class.identifier storage.type',
      foreground: 'FFCB6B',
    },
    {
      token: 'source.cs meta.method.identifier entity.name.function',
      foreground: 'f07178',
    },
    {
      token:
        'source.cs meta.method-call meta.method, source.cs entity.name.function',
      foreground: '82AAFF',
    },
    {
      token: 'source.cs storage.type',
      foreground: 'FFCB6B',
    },
    {
      token: 'source.cs meta.method.return-type',
      foreground: 'FFCB6B',
    },
    {
      token: 'source.cs meta.preprocessor',
      foreground: '676E95',
    },
    {
      token: 'source.cs entity.name.type.namespace',
      foreground: 'babed8',
    },
    {
      token: 'meta.jsx.children, SXNested',
      foreground: 'babed8',
    },
    {
      token: 'support.class.component',
      foreground: 'FFCB6B',
    },
    {
      token: 'source.cpp meta.block variable.other',
      foreground: 'babed8',
    },
    {
      token: 'source.python meta.member.access.python',
      foreground: 'f07178',
    },
    {
      token:
        'source.python meta.function-call.python, meta.function-call.arguments',
      foreground: '82AAFF',
    },
    {
      token: 'meta.block',
      foreground: 'f07178',
    },
    {
      token: 'entity.name.function.call',
      foreground: '82AAFF',
    },
    {
      token:
        'source.php support.other.namespace, source.php meta.use support.class',
      foreground: 'babed8',
    },
    {
      token: 'constant.keyword',
      foreground: '89DDFF',
    },
    {
      token: 'entity.name.function',
      foreground: '82AAFF',
    },
    {
      token: 'constant.other.placeholder',
      foreground: 'f07178',
    },
    {
      token: 'markup.deleted',
      foreground: 'f07178',
    },
    {
      token: 'markup.inserted',
      foreground: 'C3E88D',
    },
    {
      token: 'keyword.control',
      foreground: '89DDFF',
    },
    {
      token: 'variable.parameter.function.language.special.self.python',
      foreground: 'f07178',
    },
    {
      token: 'constant.character.format.placeholder.other.python',
      foreground: 'F78C6C',
    },
    {
      token: 'markup.quote',
      foreground: '89DDFF',
    },
    {
      token: 'markup.fenced_code.block',
      foreground: 'babed890',
    },
    {
      token: 'punctuation.definition.quote',
      foreground: 'ff9cac',
    },
    {
      token: 'meta.structure.dictionary.json support.type.property-name.json',
      foreground: 'C792EA',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: 'FFCB6B',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: 'F78C6C',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: 'f07178',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: '916b53',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: '82AAFF',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: 'ff9cac',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: 'C792EA',
    },
    {
      token:
        'meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json meta.structure.dictionary.value.json meta.structure.dictionary.json support.type.property-name.json',
      foreground: 'C3E88D',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
