import {EditorThemeData} from './types/common';

interface CustomThemeCollection {
  [key: string]: EditorThemeData;
}

/**
 * Themes for the Rich Monaco Editor.
 * This file is automatically generated by the 'generate-themes' script.
 * Do not manually modify this file. Instead, add themes to the 'themes' directory and run the script.
 */

export default {
  'codesandbox-dark': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      {
        token: 'string',
        foreground: 'BFD084',
      },
      {
        token: 'punctuation.definition.string',
        foreground: 'BFD084',
      },
      {
        token: 'constant.character.escape',
        foreground: 'BFD084',
      },
      {
        token: 'text.html constant.character.entity.named',
        foreground: 'BFD084',
      },
      {
        token: 'text.html.derivative',
        foreground: 'E5E5E5',
      },
      {
        token: 'punctuation.definition.entity.html',
        foreground: 'BFD084',
      },
      {
        token: 'template.expression.begin',
        foreground: '7AD9FB',
      },
      {
        token: 'template.expression.end',
        foreground: '7AD9FB',
      },
      {
        token: 'punctuation.definition.template-expression.begin',
        foreground: '7AD9FB',
      },
      {
        token: 'punctuation.definition.template-expression.end',
        foreground: '7AD9FB',
      },
      {
        token: 'constant',
        foreground: '7AD9FB',
      },
      {
        token: 'keyword',
        foreground: 'A390FF',
      },
      {
        token: 'modifier',
        foreground: 'A390FF',
      },
      {
        token: 'storage',
        foreground: 'A390FF',
      },
      {
        token: 'punctuation.definition.block',
        foreground: '86897A',
      },
      {
        token: 'punctuation.definition.parameters',
        foreground: '86897A',
      },
      {
        token: 'meta.brace.round',
        foreground: '86897A',
      },
      {
        token: 'meta.jsx.children',
        foreground: 'E5E5E5',
      },
      {
        token: 'punctuation.accessor',
        foreground: '86897A',
      },
      {
        token: 'variable.other',
        foreground: 'FFFFFF',
      },
      {
        token: 'variable.parameter',
        foreground: 'FFFFFF',
      },
      {
        token: 'meta.embedded',
        foreground: 'E5E5E5',
      },
      {
        token: 'source.groovy.embedded',
        foreground: 'E5E5E5',
      },
      {
        token: 'meta.template.expression',
        foreground: 'E5E5E5',
      },
      {
        token: 'comment',
        foreground: '6F6F6F',
      },
      {
        token: 'docblock',
        foreground: '6F6F6F',
      },
      {
        token: 'meta.function-call',
        foreground: 'CDF861',
      },
      {
        token: 'meta.class entity.name.type.class',
        foreground: 'FFFFFF',
        fontStyle: 'underline',
      },
      {
        token: 'meta.class entity.name.type.module',
        foreground: 'CABEFF',
      },
      {
        token: 'meta.class meta.type.annotation',
        foreground: 'A390FF',
      },
      {
        token: 'meta.class support.type.primitive',
        foreground: 'A390FF',
      },
      {
        token: 'meta.interface support.type.primitive',
        foreground: 'A390FF',
      },
      {
        token: 'meta.type.annotation support.type.primitive',
        foreground: 'A390FF',
      },
      {
        token: 'meta.type.annotation entity.name.type',
        foreground: 'CABEFF',
      },
      {
        token: 'variable.object.property',
        foreground: 'FFFFFF',
      },
      {
        token: 'entity.name.function',
        foreground: 'CDF861',
      },
      {
        token: 'meta.definition.variable',
        foreground: 'FFFFFF',
      },
      {
        token: 'modifier',
        foreground: 'A390FF',
      },
      {
        token: 'variable.language.this',
        foreground: 'A390FF',
      },
      {
        token: 'support.type.object',
        foreground: 'A390FF',
      },
      {
        token: 'support.module',
        foreground: '7AD9FB',
        fontStyle: 'italic',
      },
      {
        token: 'support.node',
        foreground: '7AD9FB',
        fontStyle: 'italic',
      },
      {
        token: 'support.type.ts',
        foreground: '7AD9FB',
      },
      {
        token: 'entity.other.inherited-class',
        foreground: '7AD9FB',
      },
      {
        token: 'meta.interface entity.name.type.interface',
        foreground: '7AD9FB',
      },
      {
        token: 'keyword.operator',
        foreground: 'B3E8B4',
      },
      {
        token: 'storage.type.function.arrow',
        foreground: 'B3E8B4',
      },
      {
        token: 'variable.css',
        foreground: '7AD9FB',
      },
      {
        token: 'source.css',
        foreground: 'CDF861',
      },
      {
        token: 'entity.other.attribute-name',
        foreground: 'CDF861',
      },
      {
        token: 'entity.name.tag.css',
        foreground: 'CDF861',
      },
      {
        token: 'entity.other.attribute-name.id',
        foreground: 'CDF861',
      },
      {
        token: 'entity.other.attribute-name.class',
        foreground: 'CDF861',
      },
      {
        token: 'source.css meta.selector.css',
        foreground: 'CDF861',
      },
      {
        token: 'support.type.property-name.css',
        foreground: 'FFFFFF',
      },
      {
        token: 'support.function.css',
        foreground: 'A390FF',
      },
      {
        token: 'support.constant.css',
        foreground: 'A390FF',
      },
      {
        token: 'keyword.css',
        foreground: 'A390FF',
      },
      {
        token: 'constant.numeric.css',
        foreground: 'A390FF',
      },
      {
        token: 'constant.other.color.css',
        foreground: 'A390FF',
      },
      {
        token: 'punctuation.section',
        foreground: '86897A',
      },
      {
        token: 'punctuation.separator',
        foreground: '86897A',
      },
      {
        token: 'punctuation.definition.entity.css',
        foreground: '86897A',
      },
      {
        token: 'punctuation.terminator.rule.css',
        foreground: 'E5E5E5',
      },
      {
        token: 'source.css keyword.other.unit',
        foreground: 'CABEFF',
      },
      {
        token: 'string.css',
        foreground: 'CABEFF',
      },
      {
        token: 'punctuation.definition.string.css',
        foreground: 'CABEFF',
      },
      {
        token: 'support.type.property-name',
        foreground: 'FFFFFF',
      },
      {
        token: 'string.html',
        foreground: 'CDF861',
      },
      {
        token: 'punctuation.definition.tag',
        foreground: '86897A',
      },
      {
        token: 'entity.other.attribute-name',
        foreground: 'CABEFF',
      },
      {
        token: 'entity.name.tag',
        foreground: 'A390FF',
      },
      {
        token: 'entity.name.tag.wildcard',
        foreground: 'CDF861',
      },
      {
        token: 'markup.markdown',
        foreground: 'FFFFFF',
      },
      {
        token: 'markup.heading.markdown',
        foreground: 'B3E8B4',
      },
      {
        token: 'punctuation.definition.bold.markdown',
        foreground: 'B3E8B4',
      },
      {
        token:
          'meta.paragraph.markdown punctuation.definition.link.description',
        foreground: 'B3E8B4',
      },
      {
        token: 'punctuation.definition.raw.markdown',
        foreground: 'B3E8B4',
      },
      {
        token: 'meta.paragraph.markdown',
        foreground: 'E5E5E5',
      },
      {
        token: 'text.html.markdown meta.attribute',
        foreground: 'CABEFF',
      },
      {
        token: 'entity.name.section',
        foreground: 'FFFFFF',
      },
      {
        token: 'string.other',
        foreground: 'FFFFFF',
      },
      {
        token: 'string.other.link',
        foreground: 'FFFFFF',
      },
      {
        token: 'punctuation.definition.markdown',
        foreground: 'B3E8B4',
      },
      {
        token: 'punctuation.definition.string',
        foreground: 'B3E8B4',
      },
      {
        token: 'punctuation.definition.string.begin.shell',
        foreground: 'B3E8B4',
      },
      {
        token: 'markup.underline.link',
        foreground: 'BFD084',
      },
      {
        token: 'markup.inline.raw',
        foreground: '86897A',
      },
      {
        token: 'text.html.vue variable.other.readwrite',
        foreground: 'A390FF',
      },
      {
        token: 'text.html.vue meta.object-literal.key',
        foreground: 'FFFFFF',
      },
      {
        token: 'text.html.vue entity.name.tag.css',
        foreground: 'A390FF',
      },
      {
        token: 'text.html.vue entity.other.attribute-name',
        foreground: 'FFFFFF',
      },
      {
        token: 'text.html.vue constant.numeric.css',
        foreground: '7AD9FB',
      },
      {
        token: 'text.html.vue keyword.other.unit',
        foreground: 'A390FF',
      },
      {
        token: 'text.html.vue support.constant.property-value',
        foreground: 'A390FF',
      },
      {
        token: 'text.html.vue support.constant.color',
        foreground: 'A390FF',
      },
      {
        token: 'function.defaultLibrary',
      },
      {
        token: 'class.defaultLibrary',
      },
    ],
    colors: {
      foreground: '#E5E5E5',
      focusBorder: '#AD9CFF',
      'selection.background': '#6F6F6F',
      'scrollbar.shadow': '#0000007E',
      'input.background': '#0F0E0E',
      'input.foreground': '#999',
      'button.background': '#EDFFA5',
      'button.foreground': '#151515',
      'button.hoverBackground': '#DCFF50',
      'textLink.foreground': '#E5E5E5',
      'list.dropBackground': '#151515',
      'list.focusForeground': '#808080',
      'list.focusBackground': '#E5E5E51A',
      'list.highlightForeground': '#E5E5E5',
      'editor.background': '#151515',
      'editorLineNumber.foreground': '#858585',
      'editorLineNumber.activeForeground': '#C6C6C6',
      'scrollbarSlider.background': '#79797966',
      'scrollbarSlider.hoverBackground': '#646464B3',
      'scrollbarSlider.activeBackground': '#BFBFBF66',
      'widget.shadow': '#0000005C',
      'editorWidget.background': '#252526',
      'pickerGroup.border': '#3F3F46',
      'pickerGroup.foreground': '#3794FF',
      errorForeground: '#F48771',
      'editorError.foreground': '#F48771',
      'editorWarning.foreground': '#F7CC66',
    },
  },
  'github-dark-dimmed': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      {
        token: 'comment',
        foreground: '768390',
      },
      {
        token: 'punctuation.definition.comment',
        foreground: '768390',
      },
      {
        token: 'string.comment',
        foreground: '768390',
      },
      {
        token: 'constant.other.placeholder',
        foreground: 'F47067',
      },
      {
        token: 'constant.character',
        foreground: 'F47067',
      },
      {
        token: 'constant',
        foreground: '6CB6FF',
      },
      {
        token: 'entity.name.constant',
        foreground: '6CB6FF',
      },
      {
        token: 'variable.other.constant',
        foreground: '6CB6FF',
      },
      {
        token: 'variable.other.enummember',
        foreground: '6CB6FF',
      },
      {
        token: 'variable.language',
        foreground: '6CB6FF',
      },
      {
        token: 'entity',
        foreground: '6CB6FF',
      },
      {
        token: 'entity.name',
        foreground: 'F69D50',
      },
      {
        token: 'meta.export.default',
        foreground: 'F69D50',
      },
      {
        token: 'meta.definition.variable',
        foreground: 'F69D50',
      },
      {
        token: 'variable.parameter.function',
        foreground: 'ADBAC7',
      },
      {
        token: 'meta.jsx.children',
        foreground: 'ADBAC7',
      },
      {
        token: 'meta.block',
        foreground: 'ADBAC7',
      },
      {
        token: 'meta.tag.attributes',
        foreground: 'ADBAC7',
      },
      {
        token: 'entity.name.constant',
        foreground: 'ADBAC7',
      },
      {
        token: 'meta.object.member',
        foreground: 'ADBAC7',
      },
      {
        token: 'meta.embedded.expression',
        foreground: 'ADBAC7',
      },
      {
        token: 'entity.name.function',
        foreground: 'DCBDFB',
      },
      {
        token: 'entity.name.tag',
        foreground: '8DDB8C',
      },
      {
        token: 'support.class.component',
        foreground: '8DDB8C',
      },
      {
        token: 'keyword',
        foreground: 'F47067',
      },
      {
        token: 'storage',
        foreground: 'F47067',
      },
      {
        token: 'storage.type',
        foreground: 'F47067',
      },
      {
        token: 'storage.modifier.package',
        foreground: 'ADBAC7',
      },
      {
        token: 'storage.modifier.import',
        foreground: 'ADBAC7',
      },
      {
        token: 'storage.type.java',
        foreground: 'ADBAC7',
      },
      {
        token: 'string',
        foreground: '96D0FF',
      },
      {
        token: 'string punctuation.section.embedded source',
        foreground: '96D0FF',
      },
      {
        token: 'support',
        foreground: '6CB6FF',
      },
      {
        token: 'meta.property-name',
        foreground: '6CB6FF',
      },
      {
        token: 'variable',
        foreground: 'F69D50',
      },
      {
        token: 'variable.other',
        foreground: 'ADBAC7',
      },
      {
        token: 'invalid.broken',
        foreground: 'FF938A',
        fontStyle: 'italic',
      },
      {
        token: 'invalid.deprecated',
        foreground: 'FF938A',
        fontStyle: 'italic',
      },
      {
        token: 'invalid.illegal',
        foreground: 'FF938A',
        fontStyle: 'italic',
      },
      {
        token: 'invalid.unimplemented',
        foreground: 'FF938A',
        fontStyle: 'italic',
      },
      {
        token: 'carriage-return',
        foreground: 'CDD9E5',
        fontStyle: 'italic underline',
      },
      {
        token: 'message.error',
        foreground: 'FF938A',
      },
      {
        token: 'string variable',
        foreground: '6CB6FF',
      },
      {
        token: 'source.regexp',
        foreground: '96D0FF',
      },
      {
        token: 'string.regexp',
        foreground: '96D0FF',
      },
      {
        token: 'string.regexp.character-class',
        foreground: '96D0FF',
      },
      {
        token: 'string.regexp constant.character.escape',
        foreground: '96D0FF',
      },
      {
        token: 'string.regexp source.ruby.embedded',
        foreground: '96D0FF',
      },
      {
        token: 'string.regexp string.regexp.arbitrary-repitition',
        foreground: '96D0FF',
      },
      {
        token: 'string.regexp constant.character.escape',
        foreground: '8DDB8C',
        fontStyle: 'bold',
      },
      {
        token: 'support.constant',
        foreground: '6CB6FF',
      },
      {
        token: 'support.variable',
        foreground: '6CB6FF',
      },
      {
        token: 'support.type.property-name.json',
        foreground: '8DDB8C',
      },
      {
        token: 'meta.module-reference',
        foreground: '6CB6FF',
      },
      {
        token: 'punctuation.definition.list.begin.markdown',
        foreground: 'F69D50',
      },
      {
        token: 'markup.heading',
        foreground: '6CB6FF',
        fontStyle: 'bold',
      },
      {
        token: 'markup.heading entity.name',
        foreground: '6CB6FF',
        fontStyle: 'bold',
      },
      {
        token: 'markup.quote',
        foreground: '8DDB8C',
      },
      {
        token: 'markup.italic',
        foreground: 'ADBAC7',
        fontStyle: 'italic',
      },
      {
        token: 'markup.bold',
        foreground: 'ADBAC7',
        fontStyle: 'bold',
      },
      {
        token: 'markup.underline',
        fontStyle: 'underline',
      },
      {
        token: 'markup.strikethrough',
        fontStyle: 'strikethrough',
      },
      {
        token: 'markup.inline.raw',
        foreground: '6CB6FF',
      },
      {
        token: 'markup.deleted',
        foreground: 'FF938A',
      },
      {
        token: 'meta.diff.header.from-file',
        foreground: 'FF938A',
      },
      {
        token: 'punctuation.definition.deleted',
        foreground: 'FF938A',
      },
      {
        token: 'punctuation.section.embedded',
        foreground: 'F47067',
      },
      {
        token: 'markup.inserted',
        foreground: '8DDB8C',
      },
      {
        token: 'meta.diff.header.to-file',
        foreground: '8DDB8C',
      },
      {
        token: 'punctuation.definition.inserted',
        foreground: '8DDB8C',
      },
      {
        token: 'markup.changed',
        foreground: 'F69D50',
      },
      {
        token: 'punctuation.definition.changed',
        foreground: 'F69D50',
      },
      {
        token: 'markup.ignored',
        foreground: '2D333B',
      },
      {
        token: 'markup.untracked',
        foreground: '2D333B',
      },
      {
        token: 'meta.diff.range',
        foreground: 'DCBDFB',
        fontStyle: 'bold',
      },
      {
        token: 'meta.diff.header',
        foreground: '6CB6FF',
      },
      {
        token: 'meta.separator',
        foreground: '6CB6FF',
        fontStyle: 'bold',
      },
      {
        token: 'meta.output',
        foreground: '6CB6FF',
      },
      {
        token: 'brackethighlighter.tag',
        foreground: '768390',
      },
      {
        token: 'brackethighlighter.curly',
        foreground: '768390',
      },
      {
        token: 'brackethighlighter.round',
        foreground: '768390',
      },
      {
        token: 'brackethighlighter.square',
        foreground: '768390',
      },
      {
        token: 'brackethighlighter.angle',
        foreground: '768390',
      },
      {
        token: 'brackethighlighter.quote',
        foreground: '768390',
      },
      {
        token: 'brackethighlighter.unmatched',
        foreground: 'FF938A',
      },
      {
        token: 'constant.other.reference.link',
        foreground: '96D0FF',
      },
      {
        token: 'string.other.link',
        foreground: '96D0FF',
      },
    ],
    colors: {
      focusBorder: '#316DCA',
      foreground: '#ADBAC7',
      descriptionForeground: '#768390',
      errorForeground: '#E5534B',
      'textLink.foreground': '#539BF5',
      'textLink.activeForeground': '#539BF5',
      'textBlockQuote.background': '#1C2128',
      'textBlockQuote.border': '#444C56',
      'textCodeBlock.background': '#636E7B66',
      'textPreformat.foreground': '#768390',
      'textSeparator.foreground': '#373E47',
      'button.background': '#347D39',
      'button.foreground': '#FFFFFF',
      'button.hoverBackground': '#46954A',
      'dropdown.background': '#2D333B',
      'dropdown.border': '#444C56',
      'dropdown.foreground': '#ADBAC7',
      'input.background': '#22272E',
      'input.border': '#444C56',
      'input.foreground': '#ADBAC7',
      'input.placeholderForeground': '#636E7B',
      'badge.foreground': '#CDD9E5',
      'badge.background': '#316DCA',
      'progressBar.background': '#316DCA',
      'list.hoverForeground': '#ADBAC7',
      'list.inactiveSelectionForeground': '#ADBAC7',
      'list.activeSelectionForeground': '#ADBAC7',
      'list.hoverBackground': '#636E7B1A',
      'list.inactiveSelectionBackground': '#636E7B66',
      'list.activeSelectionBackground': '#636E7B66',
      'list.focusForeground': '#ADBAC7',
      'list.focusBackground': '#4184E426',
      'list.highlightForeground': '#539BF5',
      'pickerGroup.border': '#444C56',
      'pickerGroup.foreground': '#768390',
      'editor.foreground': '#ADBAC7',
      'editor.background': '#22272E',
      'editorWidget.background': '#2D333B',
      'editor.lineHighlightBackground': '#636E7B1A',
      'editorLineNumber.foreground': '#636E7B',
      'editorLineNumber.activeForeground': '#ADBAC7',
      'editorIndentGuide.background': '#ADBAC71F',
      'editorWhitespace.foreground': '#545D68',
      'editorCursor.foreground': '#539BF5',
      'editor.findMatchBackground': '#966600',
      'editor.findMatchHighlightBackground': '#EAC55F80',
      'editor.selectionHighlightBackground': '#57AB5A40',
      'editor.wordHighlightBackground': '#636E7B80',
      'editor.wordHighlightStrongBackground': '#636E7B4D',
      'editorBracketMatch.background': '#57AB5A40',
      'editorBracketMatch.border': '#57AB5A99',
      'editorInlayHint.background': '#76839033',
      'editorInlayHint.foreground': '#768390',
      'diffEditor.insertedTextBackground': '#57AB5A4D',
      'diffEditor.removedTextBackground': '#F470674D',
      'scrollbar.shadow': '#545D6833',
      'scrollbarSlider.background': '#76839033',
      'scrollbarSlider.hoverBackground': '#7683903D',
      'scrollbarSlider.activeBackground': '#76839047',
      'editorOverviewRuler.border': '#1C2128',
      'peekViewEditor.matchHighlightBackground': '#AE7C1466',
      'peekViewResult.matchHighlightBackground': '#AE7C1466',
      'peekViewEditor.background': '#636E7B1A',
      'peekViewResult.background': '#22272E',
    },
  },
  'github-dark': {
    base: 'vs-dark',
    inherit: true,
    rules: [
      {
        token: 'comment',
        foreground: '8B949E',
      },
      {
        token: 'punctuation.definition.comment',
        foreground: '8B949E',
      },
      {
        token: 'string.comment',
        foreground: '8B949E',
      },
      {
        token: 'constant.other.placeholder',
        foreground: 'FF7B72',
      },
      {
        token: 'constant.character',
        foreground: 'FF7B72',
      },
      {
        token: 'constant',
        foreground: '79C0FF',
      },
      {
        token: 'entity.name.constant',
        foreground: '79C0FF',
      },
      {
        token: 'variable.other.constant',
        foreground: '79C0FF',
      },
      {
        token: 'variable.other.enummember',
        foreground: '79C0FF',
      },
      {
        token: 'variable.language',
        foreground: '79C0FF',
      },
      {
        token: 'entity',
        foreground: '79C0FF',
      },
      {
        token: 'entity.name',
        foreground: 'FFA657',
      },
      {
        token: 'meta.export.default',
        foreground: 'FFA657',
      },
      {
        token: 'meta.definition.variable',
        foreground: 'FFA657',
      },
      {
        token: 'variable.parameter.function',
        foreground: 'E6EDF3',
      },
      {
        token: 'meta.jsx.children',
        foreground: 'E6EDF3',
      },
      {
        token: 'meta.block',
        foreground: 'E6EDF3',
      },
      {
        token: 'meta.tag.attributes',
        foreground: 'E6EDF3',
      },
      {
        token: 'entity.name.constant',
        foreground: 'E6EDF3',
      },
      {
        token: 'meta.object.member',
        foreground: 'E6EDF3',
      },
      {
        token: 'meta.embedded.expression',
        foreground: 'E6EDF3',
      },
      {
        token: 'entity.name.function',
        foreground: 'D2A8FF',
      },
      {
        token: 'entity.name.tag',
        foreground: '7EE787',
      },
      {
        token: 'support.class.component',
        foreground: '7EE787',
      },
      {
        token: 'keyword',
        foreground: 'FF7B72',
      },
      {
        token: 'storage',
        foreground: 'FF7B72',
      },
      {
        token: 'storage.type',
        foreground: 'FF7B72',
      },
      {
        token: 'storage.modifier.package',
        foreground: 'E6EDF3',
      },
      {
        token: 'storage.modifier.import',
        foreground: 'E6EDF3',
      },
      {
        token: 'storage.type.java',
        foreground: 'E6EDF3',
      },
      {
        token: 'string',
        foreground: 'A5D6FF',
      },
      {
        token: 'string punctuation.section.embedded source',
        foreground: 'A5D6FF',
      },
      {
        token: 'support',
        foreground: '79C0FF',
      },
      {
        token: 'meta.property-name',
        foreground: '79C0FF',
      },
      {
        token: 'variable',
        foreground: 'FFA657',
      },
      {
        token: 'variable.other',
        foreground: 'E6EDF3',
      },
      {
        token: 'invalid.broken',
        foreground: 'FFA198',
        fontStyle: 'italic',
      },
      {
        token: 'invalid.deprecated',
        foreground: 'FFA198',
        fontStyle: 'italic',
      },
      {
        token: 'invalid.illegal',
        foreground: 'FFA198',
        fontStyle: 'italic',
      },
      {
        token: 'invalid.unimplemented',
        foreground: 'FFA198',
        fontStyle: 'italic',
      },
      {
        token: 'carriage-return',
        foreground: 'F0F6FC',
        fontStyle: 'italic underline',
      },
      {
        token: 'message.error',
        foreground: 'FFA198',
      },
      {
        token: 'string variable',
        foreground: '79C0FF',
      },
      {
        token: 'source.regexp',
        foreground: 'A5D6FF',
      },
      {
        token: 'string.regexp',
        foreground: 'A5D6FF',
      },
      {
        token: 'string.regexp.character-class',
        foreground: 'A5D6FF',
      },
      {
        token: 'string.regexp constant.character.escape',
        foreground: 'A5D6FF',
      },
      {
        token: 'string.regexp source.ruby.embedded',
        foreground: 'A5D6FF',
      },
      {
        token: 'string.regexp string.regexp.arbitrary-repitition',
        foreground: 'A5D6FF',
      },
      {
        token: 'string.regexp constant.character.escape',
        foreground: '7EE787',
        fontStyle: 'bold',
      },
      {
        token: 'support.constant',
        foreground: '79C0FF',
      },
      {
        token: 'support.variable',
        foreground: '79C0FF',
      },
      {
        token: 'support.type.property-name.json',
        foreground: '7EE787',
      },
      {
        token: 'meta.module-reference',
        foreground: '79C0FF',
      },
      {
        token: 'punctuation.definition.list.begin.markdown',
        foreground: 'FFA657',
      },
      {
        token: 'markup.heading',
        foreground: '79C0FF',
        fontStyle: 'bold',
      },
      {
        token: 'markup.heading entity.name',
        foreground: '79C0FF',
        fontStyle: 'bold',
      },
      {
        token: 'markup.quote',
        foreground: '7EE787',
      },
      {
        token: 'markup.italic',
        foreground: 'E6EDF3',
        fontStyle: 'italic',
      },
      {
        token: 'markup.bold',
        foreground: 'E6EDF3',
        fontStyle: 'bold',
      },
      {
        token: 'markup.underline',
        fontStyle: 'underline',
      },
      {
        token: 'markup.strikethrough',
        fontStyle: 'strikethrough',
      },
      {
        token: 'markup.inline.raw',
        foreground: '79C0FF',
      },
      {
        token: 'markup.deleted',
        foreground: 'FFA198',
      },
      {
        token: 'meta.diff.header.from-file',
        foreground: 'FFA198',
      },
      {
        token: 'punctuation.definition.deleted',
        foreground: 'FFA198',
      },
      {
        token: 'punctuation.section.embedded',
        foreground: 'FF7B72',
      },
      {
        token: 'markup.inserted',
        foreground: '7EE787',
      },
      {
        token: 'meta.diff.header.to-file',
        foreground: '7EE787',
      },
      {
        token: 'punctuation.definition.inserted',
        foreground: '7EE787',
      },
      {
        token: 'markup.changed',
        foreground: 'FFA657',
      },
      {
        token: 'punctuation.definition.changed',
        foreground: 'FFA657',
      },
      {
        token: 'markup.ignored',
        foreground: '161B22',
      },
      {
        token: 'markup.untracked',
        foreground: '161B22',
      },
      {
        token: 'meta.diff.range',
        foreground: 'D2A8FF',
        fontStyle: 'bold',
      },
      {
        token: 'meta.diff.header',
        foreground: '79C0FF',
      },
      {
        token: 'meta.separator',
        foreground: '79C0FF',
        fontStyle: 'bold',
      },
      {
        token: 'meta.output',
        foreground: '79C0FF',
      },
      {
        token: 'brackethighlighter.tag',
        foreground: '8B949E',
      },
      {
        token: 'brackethighlighter.curly',
        foreground: '8B949E',
      },
      {
        token: 'brackethighlighter.round',
        foreground: '8B949E',
      },
      {
        token: 'brackethighlighter.square',
        foreground: '8B949E',
      },
      {
        token: 'brackethighlighter.angle',
        foreground: '8B949E',
      },
      {
        token: 'brackethighlighter.quote',
        foreground: '8B949E',
      },
      {
        token: 'brackethighlighter.unmatched',
        foreground: 'FFA198',
      },
      {
        token: 'constant.other.reference.link',
        foreground: 'A5D6FF',
      },
      {
        token: 'string.other.link',
        foreground: 'A5D6FF',
      },
    ],
    colors: {
      focusBorder: '#1F6FEB',
      foreground: '#E6EDF3',
      descriptionForeground: '#7D8590',
      errorForeground: '#F85149',
      'textLink.foreground': '#2F81F7',
      'textLink.activeForeground': '#2F81F7',
      'textBlockQuote.background': '#010409',
      'textBlockQuote.border': '#30363D',
      'textCodeBlock.background': '#6E768166',
      'textPreformat.foreground': '#7D8590',
      'textSeparator.foreground': '#21262D',
      'button.background': '#238636',
      'button.foreground': '#FFFFFF',
      'button.hoverBackground': '#2EA043',
      'dropdown.background': '#161B22',
      'dropdown.border': '#30363D',
      'dropdown.foreground': '#E6EDF3',
      'input.background': '#0D1117',
      'input.border': '#30363D',
      'input.foreground': '#E6EDF3',
      'input.placeholderForeground': '#6E7681',
      'badge.foreground': '#FFFFFF',
      'badge.background': '#1F6FEB',
      'progressBar.background': '#1F6FEB',
      'list.hoverForeground': '#E6EDF3',
      'list.inactiveSelectionForeground': '#E6EDF3',
      'list.activeSelectionForeground': '#E6EDF3',
      'list.hoverBackground': '#6E76811A',
      'list.inactiveSelectionBackground': '#6E768166',
      'list.activeSelectionBackground': '#6E768166',
      'list.focusForeground': '#E6EDF3',
      'list.focusBackground': '#388BFD26',
      'list.highlightForeground': '#2F81F7',
      'pickerGroup.border': '#30363D',
      'pickerGroup.foreground': '#7D8590',
      'editor.foreground': '#E6EDF3',
      'editor.background': '#0D1117',
      'editorWidget.background': '#161B22',
      'editor.lineHighlightBackground': '#6E76811A',
      'editorLineNumber.foreground': '#6E7681',
      'editorLineNumber.activeForeground': '#E6EDF3',
      'editorIndentGuide.background': '#E6EDF31F',
      'editorWhitespace.foreground': '#484F58',
      'editorCursor.foreground': '#2F81F7',
      'editor.findMatchBackground': '#9E6A03',
      'editor.findMatchHighlightBackground': '#F2CC6080',
      'editor.selectionHighlightBackground': '#3FB95040',
      'editor.wordHighlightBackground': '#6E768180',
      'editor.wordHighlightStrongBackground': '#6E76814D',
      'editorBracketMatch.background': '#3FB95040',
      'editorBracketMatch.border': '#3FB95099',
      'editorInlayHint.background': '#8B949E33',
      'editorInlayHint.foreground': '#7D8590',
      'diffEditor.insertedTextBackground': '#3FB9504D',
      'diffEditor.removedTextBackground': '#FF7B724D',
      'scrollbar.shadow': '#484F5833',
      'scrollbarSlider.background': '#8B949E33',
      'scrollbarSlider.hoverBackground': '#8B949E3D',
      'scrollbarSlider.activeBackground': '#8B949E47',
      'editorOverviewRuler.border': '#010409',
      'peekViewEditor.matchHighlightBackground': '#BB800966',
      'peekViewResult.matchHighlightBackground': '#BB800966',
      'peekViewEditor.background': '#6E76811A',
      'peekViewResult.background': '#0D1117',
    },
  },
  'github-light': {
    base: 'vs',
    inherit: true,
    rules: [
      {
        token: 'comment',
        foreground: '6E7781',
      },
      {
        token: 'punctuation.definition.comment',
        foreground: '6E7781',
      },
      {
        token: 'string.comment',
        foreground: '6E7781',
      },
      {
        token: 'constant.other.placeholder',
        foreground: 'CF222E',
      },
      {
        token: 'constant.character',
        foreground: 'CF222E',
      },
      {
        token: 'constant',
        foreground: '0550AE',
      },
      {
        token: 'entity.name.constant',
        foreground: '0550AE',
      },
      {
        token: 'variable.other.constant',
        foreground: '0550AE',
      },
      {
        token: 'variable.other.enummember',
        foreground: '0550AE',
      },
      {
        token: 'variable.language',
        foreground: '0550AE',
      },
      {
        token: 'entity',
        foreground: '0550AE',
      },
      {
        token: 'entity.name',
        foreground: '953800',
      },
      {
        token: 'meta.export.default',
        foreground: '953800',
      },
      {
        token: 'meta.definition.variable',
        foreground: '953800',
      },
      {
        token: 'variable.parameter.function',
        foreground: '1F2328',
      },
      {
        token: 'meta.jsx.children',
        foreground: '1F2328',
      },
      {
        token: 'meta.block',
        foreground: '1F2328',
      },
      {
        token: 'meta.tag.attributes',
        foreground: '1F2328',
      },
      {
        token: 'entity.name.constant',
        foreground: '1F2328',
      },
      {
        token: 'meta.object.member',
        foreground: '1F2328',
      },
      {
        token: 'meta.embedded.expression',
        foreground: '1F2328',
      },
      {
        token: 'entity.name.function',
        foreground: '8250DF',
      },
      {
        token: 'entity.name.tag',
        foreground: '116329',
      },
      {
        token: 'support.class.component',
        foreground: '116329',
      },
      {
        token: 'keyword',
        foreground: 'CF222E',
      },
      {
        token: 'storage',
        foreground: 'CF222E',
      },
      {
        token: 'storage.type',
        foreground: 'CF222E',
      },
      {
        token: 'storage.modifier.package',
        foreground: '1F2328',
      },
      {
        token: 'storage.modifier.import',
        foreground: '1F2328',
      },
      {
        token: 'storage.type.java',
        foreground: '1F2328',
      },
      {
        token: 'string',
        foreground: '0A3069',
      },
      {
        token: 'string punctuation.section.embedded source',
        foreground: '0A3069',
      },
      {
        token: 'support',
        foreground: '0550AE',
      },
      {
        token: 'meta.property-name',
        foreground: '0550AE',
      },
      {
        token: 'variable',
        foreground: '953800',
      },
      {
        token: 'variable.other',
        foreground: '1F2328',
      },
      {
        token: 'invalid.broken',
        foreground: '82071E',
        fontStyle: 'italic',
      },
      {
        token: 'invalid.deprecated',
        foreground: '82071E',
        fontStyle: 'italic',
      },
      {
        token: 'invalid.illegal',
        foreground: '82071E',
        fontStyle: 'italic',
      },
      {
        token: 'invalid.unimplemented',
        foreground: '82071E',
        fontStyle: 'italic',
      },
      {
        token: 'carriage-return',
        foreground: 'F6F8FA',
        fontStyle: 'italic underline',
      },
      {
        token: 'message.error',
        foreground: '82071E',
      },
      {
        token: 'string variable',
        foreground: '0550AE',
      },
      {
        token: 'source.regexp',
        foreground: '0A3069',
      },
      {
        token: 'string.regexp',
        foreground: '0A3069',
      },
      {
        token: 'string.regexp.character-class',
        foreground: '0A3069',
      },
      {
        token: 'string.regexp constant.character.escape',
        foreground: '0A3069',
      },
      {
        token: 'string.regexp source.ruby.embedded',
        foreground: '0A3069',
      },
      {
        token: 'string.regexp string.regexp.arbitrary-repitition',
        foreground: '0A3069',
      },
      {
        token: 'string.regexp constant.character.escape',
        foreground: '116329',
        fontStyle: 'bold',
      },
      {
        token: 'support.constant',
        foreground: '0550AE',
      },
      {
        token: 'support.variable',
        foreground: '0550AE',
      },
      {
        token: 'support.type.property-name.json',
        foreground: '116329',
      },
      {
        token: 'meta.module-reference',
        foreground: '0550AE',
      },
      {
        token: 'punctuation.definition.list.begin.markdown',
        foreground: '953800',
      },
      {
        token: 'markup.heading',
        foreground: '0550AE',
        fontStyle: 'bold',
      },
      {
        token: 'markup.heading entity.name',
        foreground: '0550AE',
        fontStyle: 'bold',
      },
      {
        token: 'markup.quote',
        foreground: '116329',
      },
      {
        token: 'markup.italic',
        foreground: '1F2328',
        fontStyle: 'italic',
      },
      {
        token: 'markup.bold',
        foreground: '1F2328',
        fontStyle: 'bold',
      },
      {
        token: 'markup.underline',
        fontStyle: 'underline',
      },
      {
        token: 'markup.strikethrough',
        fontStyle: 'strikethrough',
      },
      {
        token: 'markup.inline.raw',
        foreground: '0550AE',
      },
      {
        token: 'markup.deleted',
        foreground: '82071E',
      },
      {
        token: 'meta.diff.header.from-file',
        foreground: '82071E',
      },
      {
        token: 'punctuation.definition.deleted',
        foreground: '82071E',
      },
      {
        token: 'punctuation.section.embedded',
        foreground: 'CF222E',
      },
      {
        token: 'markup.inserted',
        foreground: '116329',
      },
      {
        token: 'meta.diff.header.to-file',
        foreground: '116329',
      },
      {
        token: 'punctuation.definition.inserted',
        foreground: '116329',
      },
      {
        token: 'markup.changed',
        foreground: '953800',
      },
      {
        token: 'punctuation.definition.changed',
        foreground: '953800',
      },
      {
        token: 'markup.ignored',
        foreground: 'EAEEF2',
      },
      {
        token: 'markup.untracked',
        foreground: 'EAEEF2',
      },
      {
        token: 'meta.diff.range',
        foreground: '8250DF',
        fontStyle: 'bold',
      },
      {
        token: 'meta.diff.header',
        foreground: '0550AE',
      },
      {
        token: 'meta.separator',
        foreground: '0550AE',
        fontStyle: 'bold',
      },
      {
        token: 'meta.output',
        foreground: '0550AE',
      },
      {
        token: 'brackethighlighter.tag',
        foreground: '57606A',
      },
      {
        token: 'brackethighlighter.curly',
        foreground: '57606A',
      },
      {
        token: 'brackethighlighter.round',
        foreground: '57606A',
      },
      {
        token: 'brackethighlighter.square',
        foreground: '57606A',
      },
      {
        token: 'brackethighlighter.angle',
        foreground: '57606A',
      },
      {
        token: 'brackethighlighter.quote',
        foreground: '57606A',
      },
      {
        token: 'brackethighlighter.unmatched',
        foreground: '82071E',
      },
      {
        token: 'constant.other.reference.link',
        foreground: '0A3069',
      },
      {
        token: 'string.other.link',
        foreground: '0A3069',
      },
    ],
    colors: {
      focusBorder: '#0969DA',
      foreground: '#1F2328',
      descriptionForeground: '#656D76',
      errorForeground: '#CF222E',
      'textLink.foreground': '#0969DA',
      'textLink.activeForeground': '#0969DA',
      'textBlockQuote.background': '#F6F8FA',
      'textBlockQuote.border': '#D0D7DE',
      'textCodeBlock.background': '#AFB8C133',
      'textPreformat.foreground': '#656D76',
      'textSeparator.foreground': '#D8DEE4',
      'button.background': '#1F883D',
      'button.foreground': '#FFFFFF',
      'button.hoverBackground': '#1A7F37',
      'dropdown.background': '#FFFFFF',
      'dropdown.border': '#D0D7DE',
      'dropdown.foreground': '#1F2328',
      'input.background': '#FFFFFF',
      'input.border': '#D0D7DE',
      'input.foreground': '#1F2328',
      'input.placeholderForeground': '#6E7781',
      'badge.foreground': '#FFFFFF',
      'badge.background': '#0969DA',
      'progressBar.background': '#0969DA',
      'list.hoverForeground': '#1F2328',
      'list.inactiveSelectionForeground': '#1F2328',
      'list.activeSelectionForeground': '#1F2328',
      'list.hoverBackground': '#EAEEF280',
      'list.inactiveSelectionBackground': '#AFB8C133',
      'list.activeSelectionBackground': '#AFB8C133',
      'list.focusForeground': '#1F2328',
      'list.focusBackground': '#DDF4FF',
      'list.highlightForeground': '#0969DA',
      'pickerGroup.border': '#D0D7DE',
      'pickerGroup.foreground': '#656D76',
      'editor.foreground': '#1F2328',
      'editor.background': '#FFFFFF',
      'editorWidget.background': '#FFFFFF',
      'editor.lineHighlightBackground': '#EAEEF280',
      'editorLineNumber.foreground': '#8C959F',
      'editorLineNumber.activeForeground': '#1F2328',
      'editorIndentGuide.background': '#1F23281F',
      'editorWhitespace.foreground': '#AFB8C1',
      'editorCursor.foreground': '#0969DA',
      'editor.findMatchBackground': '#BF8700',
      'editor.findMatchHighlightBackground': '#FAE17D80',
      'editor.selectionHighlightBackground': '#4AC26B40',
      'editor.wordHighlightBackground': '#EAEEF280',
      'editor.wordHighlightStrongBackground': '#AFB8C14D',
      'editorBracketMatch.background': '#4AC26B40',
      'editorBracketMatch.border': '#4AC26B99',
      'editorInlayHint.background': '#AFB8C133',
      'editorInlayHint.foreground': '#656D76',
      'diffEditor.insertedTextBackground': '#6FDD8B80',
      'diffEditor.removedTextBackground': '#FF818266',
      'scrollbar.shadow': '#6E778133',
      'scrollbarSlider.background': '#8C959F33',
      'scrollbarSlider.hoverBackground': '#8C959F3D',
      'scrollbarSlider.activeBackground': '#8C959F47',
      'editorOverviewRuler.border': '#FFFFFF',
    },
  },
  monokai: {
    base: 'vs-dark',
    inherit: true,
    rules: [
      {
        token: 'meta.embedded',
        foreground: 'F8F8F2',
      },
      {
        token: 'source.groovy.embedded',
        foreground: 'F8F8F2',
      },
      {
        token: 'string meta.image.inline.markdown',
        foreground: 'F8F8F2',
      },
      {
        token: 'variable.legacy.builtin.python',
        foreground: 'F8F8F2',
      },
      {
        token: 'comment',
        foreground: '88846F',
      },
      {
        token: 'string',
        foreground: 'E6DB74',
      },
      {
        token: 'punctuation.definition.template-expression',
        foreground: 'F92672',
      },
      {
        token: 'punctuation.section.embedded',
        foreground: 'F92672',
      },
      {
        token: 'meta.template.expression',
        foreground: 'F8F8F2',
      },
      {
        token: 'constant.numeric',
        foreground: 'AE81FF',
      },
      {
        token: 'constant.language',
        foreground: 'AE81FF',
      },
      {
        token: 'constant.character, constant.other',
        foreground: 'AE81FF',
      },
      {
        token: 'variable',
        foreground: 'F8F8F2',
      },
      {
        token: 'keyword',
        foreground: 'F92672',
      },
      {
        token: 'storage',
        foreground: 'F92672',
      },
      {
        token: 'storage.type',
        foreground: '66D9EF',
        fontStyle: 'italic',
      },
      {
        token:
          'entity.name.type, entity.name.class, entity.name.namespace, entity.name.scope-resolution',
        foreground: 'A6E22E',
        fontStyle: 'underline',
      },
      {
        token: 'entity.other.inherited-class',
        foreground: 'A6E22E',
        fontStyle: 'italic underline',
      },
      {
        token: 'entity.name.function',
        foreground: 'A6E22E',
      },
      {
        token: 'variable.parameter',
        foreground: 'FD971F',
        fontStyle: 'italic',
      },
      {
        token: 'entity.name.tag',
        foreground: 'F92672',
      },
      {
        token: 'entity.other.attribute-name',
        foreground: 'A6E22E',
      },
      {
        token: 'support.function',
        foreground: '66D9EF',
      },
      {
        token: 'support.constant',
        foreground: '66D9EF',
      },
      {
        token: 'support.type, support.class',
        foreground: '66D9EF',
        fontStyle: 'italic',
      },
      {
        token: 'support.other.variable',
      },
      {
        token: 'invalid',
        foreground: 'F44747',
      },
      {
        token: 'invalid.deprecated',
        foreground: 'F44747',
      },
      {
        token: 'meta.structure.dictionary.json string.quoted.double.json',
        foreground: 'CFCFC2',
      },
      {
        token: 'meta.diff, meta.diff.header',
        foreground: '75715E',
      },
      {
        token: 'markup.deleted',
        foreground: 'F92672',
      },
      {
        token: 'markup.inserted',
        foreground: 'A6E22E',
      },
      {
        token: 'markup.changed',
        foreground: 'E6DB74',
      },
      {
        token: 'constant.numeric.line-number.find-in-files - match',
        foreground: 'AE81FFA0',
      },
      {
        token: 'entity.name.filename.find-in-files',
        foreground: 'E6DB74',
      },
      {
        token: 'markup.quote',
        foreground: 'F92672',
      },
      {
        token: 'markup.list',
        foreground: 'E6DB74',
      },
      {
        token: 'markup.bold, markup.italic',
        foreground: '66D9EF',
      },
      {
        token: 'markup.inline.raw',
        foreground: 'FD971F',
      },
      {
        token: 'markup.heading',
        foreground: 'A6E22E',
      },
      {
        token: 'markup.heading.setext',
        foreground: 'A6E22E',
        fontStyle: 'bold',
      },
      {
        token: 'markup.heading.markdown',
        fontStyle: 'bold',
      },
      {
        token: 'markup.quote.markdown',
        foreground: '75715E',
        fontStyle: 'italic',
      },
      {
        token: 'markup.bold.markdown',
        fontStyle: 'bold',
      },
      {
        token:
          'string.other.link.title.markdown,string.other.link.description.markdown',
        foreground: 'AE81FF',
      },
      {
        token:
          'markup.underline.link.markdown,markup.underline.link.image.markdown',
        foreground: 'E6DB74',
      },
      {
        token: 'markup.italic.markdown',
        fontStyle: 'italic',
      },
      {
        token: 'markup.strikethrough',
        fontStyle: 'strikethrough',
      },
      {
        token: 'markup.list.unnumbered.markdown, markup.list.numbered.markdown',
        foreground: 'F8F8F2',
      },
      {
        token: 'punctuation.definition.list.begin.markdown',
        foreground: 'A6E22E',
      },
      {
        token: 'token.info-token',
        foreground: '6796E6',
      },
      {
        token: 'token.warn-token',
        foreground: 'CD9731',
      },
      {
        token: 'token.error-token',
        foreground: 'F44747',
      },
      {
        token: 'token.debug-token',
        foreground: 'B267E6',
      },
      {
        token: 'variable.language',
        foreground: 'FD971F',
      },
    ],
    colors: {
      'dropdown.background': '#414339',
      'list.activeSelectionBackground': '#75715E',
      'list.inactiveSelectionBackground': '#414339',
      'list.hoverBackground': '#3E3D32',
      'list.dropBackground': '#414339',
      'list.highlightForeground': '#F8F8F2',
      'button.background': '#75715E',
      'editor.background': '#272822',
      'editor.foreground': '#F8F8F2',
      'selection.background': '#878B9180',
      'editor.selectionHighlightBackground': '#575B6180',
      'editor.selectionBackground': '#878B9180',
      'editor.wordHighlightBackground': '#4A4A7680',
      'editor.wordHighlightStrongBackground': '#6A6A9680',
      'editor.lineHighlightBackground': '#3E3D32',
      'editorLineNumber.activeForeground': '#C2C2BF',
      'editorCursor.foreground': '#F8F8F0',
      'editorWhitespace.foreground': '#464741',
      'editorIndentGuide.background': '#464741',
      'widget.shadow': '#00000098',
      'progressBar.background': '#75715E',
      'badge.background': '#75715E',
      'badge.foreground': '#F8F8F2',
      'editorLineNumber.foreground': '#90908A',
      'pickerGroup.foreground': '#75715E',
      'input.background': '#414339',
      'inputOption.activeBorder': '#75715E',
      focusBorder: '#99947C',
      'editorWidget.background': '#1E1F1C',
      'diffEditor.insertedTextBackground': '#4B661680',
      'diffEditor.removedTextBackground': '#90274A70',
      'inputValidation.errorBackground': '#90274A',
      'inputValidation.errorBorder': '#F92672',
      'inputValidation.warningBackground': '#848528',
      'inputValidation.warningBorder': '#E2E22E',
      'inputValidation.infoBackground': '#546190',
      'inputValidation.infoBorder': '#819AFF',
      'editorHoverWidget.background': '#414339',
      'editorHoverWidget.border': '#75715E',
      'editorSuggestWidget.background': '#272822',
      'editorSuggestWidget.border': '#75715E',
      'peekView.border': '#75715E',
      'peekViewEditor.background': '#272822',
      'peekViewResult.background': '#1E1F1C',
      'peekViewTitle.background': '#1E1F1C',
      'peekViewResult.selectionBackground': '#414339',
      'peekViewResult.matchHighlightBackground': '#75715E',
      'peekViewEditor.matchHighlightBackground': '#75715E',
    },
  },
} as const satisfies CustomThemeCollection;
