import * as monaco from 'monaco-editor';

export default {
  base: 'vs-dark',
  inherit: false,
  colors: {
    'activityBar.activeBorder': '#e6b450b3',
    'activityBar.background': '#0b0e14',
    'activityBar.border': '#0b0e14',
    'activityBar.foreground': '#565b66cc',
    'activityBar.inactiveForeground': '#565b6699',
    'activityBarBadge.background': '#e6b450',
    'activityBarBadge.foreground': '#0b0e14',
    'badge.background': '#e6b45033',
    'badge.foreground': '#e6b450',
    'button.background': '#e6b450',
    'button.foreground': '#0b0e14',
    'button.hoverBackground': '#e1af4b',
    'button.secondaryBackground': '#565b6633',
    'button.secondaryForeground': '#bfbdb6',
    'button.secondaryHoverBackground': '#565b6680',
    'debugConsoleInputIcon.foreground': '#e6b450',
    'debugExceptionWidget.background': '#0f131a',
    'debugExceptionWidget.border': '#11151c',
    'debugIcon.breakpointDisabledForeground': '#f2966880',
    'debugIcon.breakpointForeground': '#f29668',
    'debugToolBar.background': '#0f131a',
    descriptionForeground: '#565b66',
    'diffEditor.diagonalFill': '#11151c',
    'diffEditor.insertedTextBackground': '#7fd9621f',
    'diffEditor.removedTextBackground': '#f26d781f',
    'dropdown.background': '#0d1017',
    'dropdown.border': '#565b6645',
    'dropdown.foreground': '#565b66',
    'editor.background': '#0b0e14',
    'editor.findMatchBackground': '#6c5980',
    'editor.findMatchBorder': '#6c5980',
    'editor.findMatchHighlightBackground': '#6c598066',
    'editor.findMatchHighlightBorder': '#5f4c7266',
    'editor.findRangeHighlightBackground': '#6c598040',
    'editor.foreground': '#bfbdb6',
    'editor.inactiveSelectionBackground': '#409fff21',
    'editor.lineHighlightBackground': '#131721',
    'editor.rangeHighlightBackground': '#6c598033',
    'editor.selectionBackground': '#409fff4d',
    'editor.selectionHighlightBackground': '#7fd96226',
    'editor.selectionHighlightBorder': '#7fd96200',
    'editor.snippetTabstopHighlightBackground': '#7fd96233',
    'editor.wordHighlightBackground': '#73b8ff14',
    'editor.wordHighlightBorder': '#73b8ff80',
    'editor.wordHighlightStrongBackground': '#7fd96214',
    'editor.wordHighlightStrongBorder': '#7fd96280',
    'editorBracketMatch.background': '#6c73804d',
    'editorBracketMatch.border': '#6c73804d',
    'editorCodeLens.foreground': '#acb6bf8c',
    'editorCursor.foreground': '#e6b450',
    'editorError.foreground': '#d95757',
    'editorGroup.background': '#0f131a',
    'editorGroup.border': '#11151c',
    'editorGroupHeader.noTabsBackground': '#0b0e14',
    'editorGroupHeader.tabsBackground': '#0b0e14',
    'editorGroupHeader.tabsBorder': '#0b0e14',
    'editorGutter.addedBackground': '#7fd962cc',
    'editorGutter.deletedBackground': '#f26d78cc',
    'editorGutter.modifiedBackground': '#73b8ffcc',
    'editorHoverWidget.background': '#0f131a',
    'editorHoverWidget.border': '#11151c',
    'editorIndentGuide.activeBackground': '#6c738080',
    'editorIndentGuide.background': '#6c738033',
    'editorLineNumber.activeForeground': '#6c7380e6',
    'editorLineNumber.foreground': '#6c738099',
    'editorLink.activeForeground': '#e6b450',
    'editorMarkerNavigation.background': '#0f131a',
    'editorOverviewRuler.addedForeground': '#7fd962',
    'editorOverviewRuler.border': '#11151c',
    'editorOverviewRuler.bracketMatchForeground': '#6c7380b3',
    'editorOverviewRuler.deletedForeground': '#f26d78',
    'editorOverviewRuler.errorForeground': '#d95757',
    'editorOverviewRuler.findMatchForeground': '#6c5980',
    'editorOverviewRuler.modifiedForeground': '#73b8ff',
    'editorOverviewRuler.warningForeground': '#e6b450',
    'editorOverviewRuler.wordHighlightForeground': '#73b8ff66',
    'editorOverviewRuler.wordHighlightStrongForeground': '#7fd96266',
    'editorRuler.foreground': '#6c738033',
    'editorSuggestWidget.background': '#0f131a',
    'editorSuggestWidget.border': '#11151c',
    'editorSuggestWidget.highlightForeground': '#e6b450',
    'editorSuggestWidget.selectedBackground': '#47526640',
    'editorWarning.foreground': '#e6b450',
    'editorWhitespace.foreground': '#6c738099',
    'editorWidget.background': '#0f131a',
    'editorWidget.border': '#11151c',
    errorForeground: '#d95757',
    'extensionButton.prominentBackground': '#e6b450',
    'extensionButton.prominentForeground': '#0d1017',
    'extensionButton.prominentHoverBackground': '#e1af4b',
    focusBorder: '#e6b450b3',
    foreground: '#565b66',
    'gitDecoration.conflictingResourceForeground': '#',
    'gitDecoration.deletedResourceForeground': '#f26d78b3',
    'gitDecoration.ignoredResourceForeground': '#565b6680',
    'gitDecoration.modifiedResourceForeground': '#73b8ffb3',
    'gitDecoration.submoduleResourceForeground': '#d2a6ffb3',
    'gitDecoration.untrackedResourceForeground': '#7fd962b3',
    'icon.foreground': '#565b66',
    'input.background': '#0d1017',
    'input.border': '#565b6645',
    'input.foreground': '#bfbdb6',
    'input.placeholderForeground': '#565b6680',
    'inputOption.activeBackground': '#e6b45033',
    'inputOption.activeBorder': '#e6b4504d',
    'inputOption.activeForeground': '#e6b450',
    'inputValidation.errorBackground': '#0d1017',
    'inputValidation.errorBorder': '#d95757',
    'inputValidation.infoBackground': '#0b0e14',
    'inputValidation.infoBorder': '#39bae6',
    'inputValidation.warningBackground': '#0b0e14',
    'inputValidation.warningBorder': '#ffb454',
    'keybindingLabel.background': '#565b661a',
    'keybindingLabel.border': '#bfbdb61a',
    'keybindingLabel.bottomBorder': '#bfbdb61a',
    'keybindingLabel.foreground': '#bfbdb6',
    'list.activeSelectionBackground': '#47526640',
    'list.activeSelectionForeground': '#bfbdb6',
    'list.deemphasizedForeground': '#d95757',
    'list.errorForeground': '#d95757',
    'list.filterMatchBackground': '#5f4c7266',
    'list.filterMatchBorder': '#6c598066',
    'list.focusBackground': '#47526640',
    'list.focusForeground': '#bfbdb6',
    'list.focusOutline': '#47526640',
    'list.highlightForeground': '#e6b450',
    'list.hoverBackground': '#47526640',
    'list.inactiveSelectionBackground': '#47526633',
    'list.inactiveSelectionForeground': '#565b66',
    'list.invalidItemForeground': '#565b664d',
    'listFilterWidget.background': '#0f131a',
    'listFilterWidget.noMatchesOutline': '#d95757',
    'listFilterWidget.outline': '#e6b450',
    'minimap.background': '#0b0e14',
    'minimap.errorHighlight': '#d95757',
    'minimap.findMatchHighlight': '#6c5980',
    'minimap.selectionHighlight': '#409fff4d',
    'minimapGutter.addedBackground': '#7fd962',
    'minimapGutter.deletedBackground': '#f26d78',
    'minimapGutter.modifiedBackground': '#73b8ff',
    'panel.background': '#0b0e14',
    'panel.border': '#11151c',
    'panelTitle.activeBorder': '#e6b450',
    'panelTitle.activeForeground': '#bfbdb6',
    'panelTitle.inactiveForeground': '#565b66',
    'peekView.border': '#47526640',
    'peekViewEditor.background': '#0f131a',
    'peekViewEditor.matchHighlightBackground': '#6c598066',
    'peekViewEditor.matchHighlightBorder': '#5f4c7266',
    'peekViewResult.background': '#0f131a',
    'peekViewResult.fileForeground': '#bfbdb6',
    'peekViewResult.lineForeground': '#565b66',
    'peekViewResult.matchHighlightBackground': '#6c598066',
    'peekViewResult.selectionBackground': '#47526640',
    'peekViewTitle.background': '#47526640',
    'peekViewTitleDescription.foreground': '#565b66',
    'peekViewTitleLabel.foreground': '#bfbdb6',
    'pickerGroup.border': '#11151c',
    'pickerGroup.foreground': '#565b6680',
    'progressBar.background': '#e6b450',
    'scrollbar.shadow': '#11151c00',
    'scrollbarSlider.activeBackground': '#565b66b3',
    'scrollbarSlider.background': '#565b6666',
    'scrollbarSlider.hoverBackground': '#565b6699',
    'selection.background': '#409fff4d',
    'settings.headerForeground': '#bfbdb6',
    'settings.modifiedItemIndicator': '#73b8ff',
    'sideBar.background': '#0b0e14',
    'sideBar.border': '#0b0e14',
    'sideBarSectionHeader.background': '#0b0e14',
    'sideBarSectionHeader.border': '#0b0e14',
    'sideBarSectionHeader.foreground': '#565b66',
    'sideBarTitle.foreground': '#565b66',
    'statusBar.background': '#0b0e14',
    'statusBar.border': '#0b0e14',
    'statusBar.debuggingBackground': '#f29668',
    'statusBar.debuggingForeground': '#0d1017',
    'statusBar.foreground': '#565b66',
    'statusBar.noFolderBackground': '#0f131a',
    'statusBarItem.activeBackground': '#565b6633',
    'statusBarItem.hoverBackground': '#565b6633',
    'statusBarItem.prominentBackground': '#11151c',
    'statusBarItem.prominentHoverBackground': '#00000030',
    'statusBarItem.remoteBackground': '#e6b450',
    'statusBarItem.remoteForeground': '#0d1017',
    'tab.activeBackground': '#0b0e14',
    'tab.activeBorder': '#e6b450',
    'tab.activeForeground': '#bfbdb6',
    'tab.border': '#0b0e14',
    'tab.inactiveBackground': '#0b0e14',
    'tab.inactiveForeground': '#565b66',
    'tab.unfocusedActiveBorder': '#565b66',
    'tab.unfocusedActiveForeground': '#565b66',
    'tab.unfocusedInactiveForeground': '#565b66',
    'terminal.ansiBlack': '#11151c',
    'terminal.ansiBlue': '#53bdfa',
    'terminal.ansiBrightBlack': '#686868',
    'terminal.ansiBrightBlue': '#59c2ff',
    'terminal.ansiBrightCyan': '#95e6cb',
    'terminal.ansiBrightGreen': '#aad94c',
    'terminal.ansiBrightMagenta': '#d2a6ff',
    'terminal.ansiBrightRed': '#f07178',
    'terminal.ansiBrightWhite': '#ffffff',
    'terminal.ansiBrightYellow': '#ffb454',
    'terminal.ansiCyan': '#90e1c6',
    'terminal.ansiGreen': '#7fd962',
    'terminal.ansiMagenta': '#cda1fa',
    'terminal.ansiRed': '#ea6c73',
    'terminal.ansiWhite': '#c7c7c7',
    'terminal.ansiYellow': '#f9af4f',
    'terminal.background': '#0b0e14',
    'terminal.foreground': '#bfbdb6',
    'textBlockQuote.background': '#0f131a',
    'textLink.activeForeground': '#e6b450',
    'textLink.foreground': '#e6b450',
    'textPreformat.foreground': '#bfbdb6',
    'titleBar.activeBackground': '#0b0e14',
    'titleBar.activeForeground': '#bfbdb6',
    'titleBar.border': '#0b0e14',
    'titleBar.inactiveBackground': '#0b0e14',
    'titleBar.inactiveForeground': '#565b66',
    'tree.indentGuidesStroke': '#6c738080',
    'walkThrough.embeddedEditorBackground': '#0f131a',
    'welcomePage.buttonBackground': '#e6b45066',
    'welcomePage.progress.background': '#131721',
    'welcomePage.tileBackground': '#0b0e14',
    'welcomePage.tileShadow': '#00000080',
    'widget.shadow': '#00000080',
  },
  rules: [
    {
      token: 'comment',
      foreground: 'acb6bf8c',
    },
    {
      token: 'string',
      foreground: 'aad94c',
    },
    {
      token: 'constant.other.symbol',
      foreground: 'aad94c',
    },
    {
      token: 'string.regexp',
      foreground: '95e6cb',
    },
    {
      token: 'constant.character',
      foreground: '95e6cb',
    },
    {
      token: 'constant.other',
      foreground: '95e6cb',
    },
    {
      token: 'constant.numeric',
      foreground: 'd2a6ff',
    },
    {
      token: 'constant.language',
      foreground: 'd2a6ff',
    },
    {
      token: 'variable',
      foreground: 'bfbdb6',
    },
    {
      token: 'variable.parameter.function-call',
      foreground: 'bfbdb6',
    },
    {
      token: 'variable.member',
      foreground: 'f07178',
    },
    {
      token: 'variable.language',
      foreground: '39bae6',
    },
    {
      token: 'storage',
      foreground: 'ff8f40',
    },
    {
      token: 'keyword',
      foreground: 'ff8f40',
    },
    {
      token: 'keyword.operator',
      foreground: 'f29668',
    },
    {
      token: 'punctuation.separator',
      foreground: 'bfbdb6b3',
    },
    {
      token: 'punctuation.terminator',
      foreground: 'bfbdb6b3',
    },
    {
      token: 'punctuation.section',
      foreground: 'bfbdb6',
    },
    {
      token: 'punctuation.accessor',
      foreground: 'f29668',
    },
    {
      token: 'punctuation.definition.template-expression',
      foreground: 'ff8f40',
    },
    {
      token: 'punctuation.section.embedded',
      foreground: 'ff8f40',
    },
    {
      token: 'meta.embedded',
      foreground: 'bfbdb6',
    },
    {
      token: 'source.java storage.type',
      foreground: '59c2ff',
    },
    {
      token: 'source.haskell storage.type',
      foreground: '59c2ff',
    },
    {
      token: 'source.c storage.type',
      foreground: '59c2ff',
    },
    {
      token: 'entity.other.inherited-class',
      foreground: '39bae6',
    },
    {
      token: 'storage.type.function',
      foreground: 'ff8f40',
    },
    {
      token: 'source.java storage.type.primitive',
      foreground: '39bae6',
    },
    {
      token: 'entity.name.function',
      foreground: 'ffb454',
    },
    {
      token: 'variable.parameter',
      foreground: 'd2a6ff',
    },
    {
      token: 'meta.parameter',
      foreground: 'd2a6ff',
    },
    {
      token: 'variable.function',
      foreground: 'ffb454',
    },
    {
      token: 'variable.annotation',
      foreground: 'ffb454',
    },
    {
      token: 'meta.function-call.generic',
      foreground: 'ffb454',
    },
    {
      token: 'support.function.go',
      foreground: 'ffb454',
    },
    {
      token: 'support.function',
      foreground: 'f07178',
    },
    {
      token: 'support.macro',
      foreground: 'f07178',
    },
    {
      token: 'entity.name.import',
      foreground: 'aad94c',
    },
    {
      token: 'entity.name.package',
      foreground: 'aad94c',
    },
    {
      token: 'entity.name',
      foreground: '59c2ff',
    },
    {
      token: 'entity.name.tag',
      foreground: '39bae6',
    },
    {
      token: 'meta.tag.sgml',
      foreground: '39bae6',
    },
    {
      token: 'support.class.component',
      foreground: '59c2ff',
    },
    {
      token: 'punctuation.definition.tag.end',
      foreground: '39bae680',
    },
    {
      token: 'punctuation.definition.tag.begin',
      foreground: '39bae680',
    },
    {
      token: 'punctuation.definition.tag',
      foreground: '39bae680',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: 'ffb454',
    },
    {
      token: 'support.constant',
      foreground: 'f29668',
    },
    {
      token: 'support.type',
      foreground: '39bae6',
    },
    {
      token: 'support.class',
      foreground: '39bae6',
    },
    {
      token: 'source.go storage.type',
      foreground: '39bae6',
    },
    {
      token: 'meta.decorator variable.other',
      foreground: 'e6b673',
    },
    {
      token: 'meta.decorator punctuation.decorator',
      foreground: 'e6b673',
    },
    {
      token: 'storage.type.annotation',
      foreground: 'e6b673',
    },
    {
      token: 'invalid',
      foreground: 'd95757',
    },
    {
      token: 'meta.diff',
      foreground: 'c594c5',
    },
    {
      token: 'meta.diff.header',
      foreground: 'c594c5',
    },
    {
      token: 'source.ruby variable.other.readwrite',
      foreground: 'ffb454',
    },
    {
      token: 'source.css entity.name.tag',
      foreground: '59c2ff',
    },
    {
      token: 'source.sass entity.name.tag',
      foreground: '59c2ff',
    },
    {
      token: 'source.scss entity.name.tag',
      foreground: '59c2ff',
    },
    {
      token: 'source.less entity.name.tag',
      foreground: '59c2ff',
    },
    {
      token: 'source.stylus entity.name.tag',
      foreground: '59c2ff',
    },
    {
      token: 'source.css support.type',
      foreground: 'acb6bf8c',
    },
    {
      token: 'source.sass support.type',
      foreground: 'acb6bf8c',
    },
    {
      token: 'source.scss support.type',
      foreground: 'acb6bf8c',
    },
    {
      token: 'source.less support.type',
      foreground: 'acb6bf8c',
    },
    {
      token: 'source.stylus support.type',
      foreground: 'acb6bf8c',
    },
    {
      token: 'support.type.property-name',
      foreground: '39bae6',
    },
    {
      token: 'constant.numeric.line-number.find-in-files - match',
      foreground: 'acb6bf8c',
    },
    {
      token: 'constant.numeric.line-number.match',
      foreground: 'ff8f40',
    },
    {
      token: 'entity.name.filename.find-in-files',
      foreground: 'aad94c',
    },
    {
      token: 'message.error',
      foreground: 'd95757',
    },
    {
      token: 'markup.heading',
      foreground: 'aad94c',
    },
    {
      token: 'markup.heading entity.name',
      foreground: 'aad94c',
    },
    {
      token: 'markup.underline.link',
      foreground: '39bae6',
    },
    {
      token: 'string.other.link',
      foreground: '39bae6',
    },
    {
      token: 'markup.italic',
      foreground: 'f07178',
    },
    {
      token: 'markup.bold',
      foreground: 'f07178',
    },
    {
      token: 'meta.separator',
      foreground: 'acb6bf8c',
    },
    {
      token: 'markup.quote',
      foreground: '95e6cb',
    },
    {
      token: 'markup.list punctuation.definition.list.begin',
      foreground: 'ffb454',
    },
    {
      token: 'markup.inserted',
      foreground: '7fd962',
    },
    {
      token: 'markup.changed',
      foreground: '73b8ff',
    },
    {
      token: 'markup.deleted',
      foreground: 'f26d78',
    },
    {
      token: 'markup.strike',
      foreground: 'e6b673',
    },
    {
      token: 'markup.table',
      foreground: '39bae6',
    },
    {
      token: 'text.html.markdown markup.inline.raw',
      foreground: 'f29668',
    },
    {
      token: 'text.html.markdown meta.dummy.line-break',
      foreground: 'acb6bf8c',
    },
    {
      token: 'punctuation.definition.markdown',
      foreground: 'acb6bf8c',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
