import * as monaco from 'monaco-editor';

export default {
  base: 'vs',
  inherit: false,
  colors: {
    'activityBar.background': '#DDD6C1',
    'activityBar.foreground': '#584c27',
    'activityBarBadge.background': '#B58900',
    'badge.background': '#B58900AA',
    'button.background': '#AC9D57',
    'debugExceptionWidget.background': '#DDD6C1',
    'debugExceptionWidget.border': '#AB395B',
    'debugToolBar.background': '#DDD6C1',
    'dropdown.background': '#EEE8D5',
    'dropdown.border': '#D3AF86',
    'editor.background': '#FDF6E3',
    'editor.foreground': '#657B83',
    'editor.lineHighlightBackground': '#EEE8D5',
    'editor.selectionBackground': '#EEE8D5',
    'editorCursor.foreground': '#657B83',
    'editorGroup.border': '#DDD6C1',
    'editorGroup.dropBackground': '#DDD6C1AA',
    'editorGroupHeader.tabsBackground': '#D9D2C2',
    'editorHoverWidget.background': '#CCC4B0',
    'editorIndentGuide.activeBackground': '#081E2580',
    'editorIndentGuide.background': '#586E7580',
    'editorLineNumber.activeForeground': '#567983',
    'editorWhitespace.foreground': '#586E7580',
    'editorWidget.background': '#EEE8D5',
    'extensionButton.prominentBackground': '#b58900',
    'extensionButton.prominentHoverBackground': '#584c27aa',
    focusBorder: '#b49471',
    'input.background': '#DDD6C1',
    'input.foreground': '#586E75',
    'input.placeholderForeground': '#586E75AA',
    'inputOption.activeBorder': '#D3AF86',
    'list.activeSelectionBackground': '#DFCA88',
    'list.activeSelectionForeground': '#6C6C6C',
    'list.highlightForeground': '#B58900',
    'list.hoverBackground': '#DFCA8844',
    'list.inactiveSelectionBackground': '#D1CBB8',
    'minimap.selectionHighlight': '#EEE8D5',
    'notebook.cellEditorBackground': '#F7F0E0',
    'panel.border': '#DDD6C1',
    'peekView.border': '#B58900',
    'peekViewEditor.background': '#FFFBF2',
    'peekViewEditor.matchHighlightBackground': '#7744AA40',
    'peekViewResult.background': '#EEE8D5',
    'peekViewTitle.background': '#EEE8D5',
    'pickerGroup.border': '#2AA19899',
    'pickerGroup.foreground': '#2AA19899',
    'ports.iconRunningProcessForeground': '#2AA19899',
    'progressBar.background': '#B58900',
    'quickInputList.focusBackground': '#DFCA8866',
    'selection.background': '#878b9180',
    'sideBar.background': '#EEE8D5',
    'sideBarTitle.foreground': '#586E75',
    'statusBar.background': '#EEE8D5',
    'statusBar.debuggingBackground': '#EEE8D5',
    'statusBar.foreground': '#586E75',
    'statusBar.noFolderBackground': '#EEE8D5',
    'statusBarItem.prominentBackground': '#DDD6C1',
    'statusBarItem.prominentHoverBackground': '#DDD6C199',
    'statusBarItem.remoteBackground': '#AC9D57',
    'tab.activeBackground': '#FDF6E3',
    'tab.activeModifiedBorder': '#cb4b16',
    'tab.border': '#DDD6C1',
    'tab.inactiveBackground': '#D3CBB7',
    'tab.inactiveForeground': '#586E75',
    'tab.lastPinnedBorder': '#FDF6E3',
    'terminal.ansiBlack': '#073642',
    'terminal.ansiBlue': '#268bd2',
    'terminal.ansiBrightBlack': '#002b36',
    'terminal.ansiBrightBlue': '#839496',
    'terminal.ansiBrightCyan': '#93a1a1',
    'terminal.ansiBrightGreen': '#586e75',
    'terminal.ansiBrightMagenta': '#6c71c4',
    'terminal.ansiBrightRed': '#cb4b16',
    'terminal.ansiBrightWhite': '#fdf6e3',
    'terminal.ansiBrightYellow': '#657b83',
    'terminal.ansiCyan': '#2aa198',
    'terminal.ansiGreen': '#859900',
    'terminal.ansiMagenta': '#d33682',
    'terminal.ansiRed': '#dc322f',
    'terminal.ansiWhite': '#eee8d5',
    'terminal.ansiYellow': '#b58900',
    'terminal.background': '#FDF6E3',
    'titleBar.activeBackground': '#EEE8D5',
    'walkThrough.embeddedEditorBackground': '#00000014',
  },
  rules: [
    {
      token: 'meta.embedded',
      foreground: '657B83',
    },
    {
      token: 'source.groovy.embedded',
      foreground: '657B83',
    },
    {
      token: 'string meta.image.inline.markdown',
      foreground: '657B83',
    },
    {
      token: 'variable.legacy.builtin.python',
      foreground: '657B83',
    },
    {
      token: 'comment',
      foreground: '93A1A1',
    },
    {
      token: 'string',
      foreground: '2AA198',
    },
    {
      token: 'string.regexp',
      foreground: 'DC322F',
    },
    {
      token: 'constant.numeric',
      foreground: 'D33682',
    },
    {
      token: 'variable.language',
      foreground: '268BD2',
    },
    {
      token: 'variable.other',
      foreground: '268BD2',
    },
    {
      token: 'keyword',
      foreground: '859900',
    },
    {
      token: 'storage',
      foreground: '586E75',
    },
    {
      token: 'entity.name.class',
      foreground: 'CB4B16',
    },
    {
      token: 'entity.name.type',
      foreground: 'CB4B16',
    },
    {
      token: 'entity.name.namespace',
      foreground: 'CB4B16',
    },
    {
      token: 'entity.name.scope-resolution',
      foreground: 'CB4B16',
    },
    {
      token: 'entity.name.function',
      foreground: '268BD2',
    },
    {
      token: 'punctuation.definition.variable',
      foreground: '859900',
    },
    {
      token: 'punctuation.section.embedded.begin',
      foreground: 'DC322F',
    },
    {
      token: 'punctuation.section.embedded.end',
      foreground: 'DC322F',
    },
    {
      token: 'constant.language',
      foreground: 'B58900',
    },
    {
      token: 'meta.preprocessor',
      foreground: 'B58900',
    },
    {
      token: 'support.function.construct',
      foreground: 'CB4B16',
    },
    {
      token: 'keyword.other.new',
      foreground: 'CB4B16',
    },
    {
      token: 'constant.character',
      foreground: 'CB4B16',
    },
    {
      token: 'constant.other',
      foreground: 'CB4B16',
    },
    {
      token: 'entity.other.inherited-class',
      foreground: '6C71C4',
    },
    {
      token: 'entity.name.tag',
      foreground: '268BD2',
    },
    {
      token: 'punctuation.definition.tag',
      foreground: '93A1A1',
    },
    {
      token: 'entity.other.attribute-name',
      foreground: '93A1A1',
    },
    {
      token: 'support.function',
      foreground: '268BD2',
    },
    {
      token: 'punctuation.separator.continuation',
      foreground: 'DC322F',
    },
    {
      token: 'support.type',
      foreground: '859900',
    },
    {
      token: 'support.class',
      foreground: '859900',
    },
    {
      token: 'support.type.exception',
      foreground: 'CB4B16',
    },
    {
      token: 'invalid',
      foreground: 'DC322F',
    },
    {
      token: 'meta.diff',
      foreground: '268BD2',
    },
    {
      token: 'meta.diff.header',
      foreground: '268BD2',
    },
    {
      token: 'markup.deleted',
      foreground: 'DC322F',
    },
    {
      token: 'markup.changed',
      foreground: 'CB4B16',
    },
    {
      token: 'markup.inserted',
      foreground: '859900',
    },
    {
      token: 'markup.quote',
      foreground: '859900',
    },
    {
      token: 'markup.list',
      foreground: 'B58900',
    },
    {
      token: 'markup.bold',
      foreground: 'D33682',
    },
    {
      token: 'markup.italic',
      foreground: 'D33682',
    },
    {
      token: 'markup.inline.raw',
      foreground: '2AA198',
    },
    {
      token: 'markup.heading',
      foreground: '268BD2',
    },
    {
      token: 'markup.heading.setext',
      foreground: '268BD2',
    },
  ],
} as const satisfies monaco.editor.IStandaloneThemeData;
